### ISSUE TITLE
ShareX won't upload anything.

### ISSUE THREAD

**Issue by Nienhaus** [ShareX/ShareX#1001]
This is from the Debug Log

2015-09-19 10:42:32.399 - ShareX 10.2.5 Release build
2015-09-19 10:42:32.402 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-09-19 10:42:32.402 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2015-09-19 10:42:32.402 - Personal path: C:\Users\Lee\Documents\ShareX
2015-09-19 10:42:32.405 - ApplicationConfig load started: C:\Users\Lee\Documents\ShareX\ApplicationConfig.json
2015-09-19 10:42:32.791 - ApplicationConfig load finished: C:\Users\Lee\Documents\ShareX\ApplicationConfig.json
2015-09-19 10:42:32.793 - MainForm init started
2015-09-19 10:42:32.793 - UploadersConfig load started: C:\Users\Lee\Documents\ShareX\UploadersConfig.json
2015-09-19 10:42:32.910 - UploadersConfig load finished: C:\Users\Lee\Documents\ShareX\UploadersConfig.json
2015-09-19 10:42:32.910 - HotkeysConfig load started: C:\Users\Lee\Documents\ShareX\HotkeysConfig.json
2015-09-19 10:42:32.925 - HotkeysConfig load finished: C:\Users\Lee\Documents\ShareX\HotkeysConfig.json
2015-09-19 10:42:33.083 - MainForm init finished
2015-09-19 10:42:33.123 - Startup time: 746 ms
2015-09-19 10:42:33.138 - Hotkey registered: Hotkey: Multiply, Description: Capture active window, Job: ActiveWindow
2015-09-19 10:42:33.139 - HotkeyManager started
2015-09-19 10:42:33.141 - WatchFolderManager started
2015-09-19 10:42:41.967 - Task in queue. Job: Job, Type: Image, Host: Imgur
2015-09-19 10:42:41.975 - Task status: Preparing
2015-09-19 10:42:42.001 - Upload started. Filename: 2015-09-19_10-42-41.png
2015-09-19 10:42:42.012 - Upload failed. Retrying upload.
2015-09-19 10:42:42.066 - AddWebError(): Message:
Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section.

StackTrace:
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   at System.Net.WebRequest.get_InternalDefaultWebProxy()
   at System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
   at System.Net.HttpRequestCreator.Create(Uri Uri)
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at ShareX.UploadersLib.Uploader.PrepareDataWebRequest(String url, String boundary, Int64 length, String contentType, CookieCollection cookies, NameValueCollection headers, HttpMethod method)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2015-09-19 10:42:42.074 - Task failed. Filename: 2015-09-19_10-42-41.png, Errors:
Message:
Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section.

StackTrace:
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   at System.Net.WebRequest.get_InternalDefaultWebProxy()
   at System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
   at System.Net.HttpRequestCreator.Create(Uri Uri)
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at ShareX.UploadersLib.Uploader.PrepareDataWebRequest(String url, String boundary, Int64 length, String contentType, CookieCollection cookies, NameValueCollection headers, HttpMethod method)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by RockyTV** [comment]
Are you using a proxy?

**Comment by Nienhaus** [comment]
I was at one point but stopped.

**Comment by Jaex** [comment]
This error happens when creating WebRequest class of .NET which is nothing to do with ShareX. So in all .NET softwares your problem will happen but I'm not sure why it happens. There is nothing I can do about it because problem not to do with ShareX. It is with something to do in your computer.

**Comment by Nienhaus** [comment]
RIP. Thanks though.

**Comment by trdwll** [comment]
@Nienhaus With a simple google search I've came up with this.
"try running the command prompt with administrator privileges and typing "netsh winsock reset" then reboot"

Not sure if it'll work, but at least give it a try.
