### ISSUE TITLE
Exit Errors

### ISSUE THREAD

**Issue by philipkcraig** [ShareX/ShareX#1005]
System.UnauthorizedAccessException: Access to the path 'C:\Users\Philip\Documents\ShareX\Backup\ApplicationConfig-2015-09-W39.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.BackupFileWeekly(String filepath, String destinationFolder)
   at ShareX.Program.BackupSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

**Comment by Jaex** [comment]
Did you upgraded to Windows 10?

**Comment by philipkcraig** [comment]
Yes, I'm in the insider group, currently build 10547.
Thank you for very quick response,
Philip Craig

**Comment by Jaex** [comment]
Can you check this #884

**Comment by philipkcraig** [comment]
That folder is marked read only.
Thank you for trying,
Philip Craig

**Comment by Jaex** [comment]
So did it work?

**Comment by philipkcraig** [comment]
No, the folder was already marked read only, so I made no change,
Philip Craig

**Comment by Jaex** [comment]
If it is read only how ShareX can save settings?

**Comment by philipkcraig** [comment]
It is now unchecked, and I still get same error message;
System.UnauthorizedAccessException: Access to the path
'C:\Users\Philip\Documents\ShareX\Backup\ApplicationConfig-2015-09-W39.json'
is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String
destFileName, Boolean overwrite, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.BackupFileWeekly(String filepath, String
destinationFolder)
   at ShareX.Program.BackupSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

Philip Craig

**Comment by Jaex** [comment]
Well there is two reason why it can be happening first is folder or sub folders of it read only or those folders don't have proper permission. So problem not to do with ShareX because your Windows not allows reaching these path.

**Comment by philipkcraig** [comment]
I will look into permissions and also try to figure out error code.
Thank you,
Philip Craig
