### ISSUE TITLE
Error while uploading to FTP.

### ISSUE THREAD

**Issue by Rupurudu** [ShareX/ShareX#1006]
I'm having an error while trying to upload FTP.
```

2015-10-07 13:18:23.001 - Task in queue. Job: Job, Type: File, Host: FTP
2015-10-07 13:18:23.021 - Task status: Preparing
2015-10-07 13:18:23.161 - Image copied to clipboard.
2015-10-07 13:18:23.181 - Image saved to file: D:\Documents\ShareX\Screenshots\2015-10\2015-10-07_13-18-23.png
2015-10-07 13:18:23.191 - Upload started. Filename: 2015-10-07_13-18-23.png, Filepath: D:\Documents\ShareX\Screenshots\2015-10\2015-10-07_13-18-23.png
2015-10-07 13:18:27.751 - FTP directory created: /public_html
2015-10-07 13:18:29.141 - FTP directory created: /public_html/ss
2015-10-07 13:18:30.231 - FTP directory created: /public_html/ss/2015
2015-10-07 13:18:32.961 - FTP directory created: /public_html/ss/2015/10
2015-10-07 13:18:35.591 - Exception:
System.Net.FtpClient.FtpCommandException: Can't open that file: No such file or directory
   at System.Net.FtpClient.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenWrite(String path, FtpDataType type)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadFile(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2015-10-07 13:18:35.621 - Task failed. Filename: 2015-10-07_13-18-23.png, Errors:
System.Net.FtpClient.FtpCommandException: Can't open that file: No such file or directory
   at System.Net.FtpClient.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenWrite(String path, FtpDataType type)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadFile(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

```

**Comment by trdwll** [comment]
"Can't open that file: No such file or directory"

Looks like the directory that you're trying to upload to doesn't exist.

**Comment by Rupurudu** [comment]
The directory exist. Application created those directories itself when I pressed test on the FTP settings.

**Comment by Rupurudu** [comment]
I think I should put steps to reproduce here to remove "Cannot reproduce" tag.

1. Go to Destination > Destination Settings
2. Select FTP from the left.
3. Use the settings from the table:

FTP | Settings
--- | --------
Protocol|FTP
Name|Example.net
Host|127.0.0.1
Port|21
Username|username
Password|*************
SubFolderPath|public_html/ss/%y/%mo/
BrowserProtocol|http
HttpHomePath|example.net/ss/%y/%mo/
HttpHomePathAutoAddSubFolderPath|False
HttpHomePathNoExtension|False
IsActive|False
PreviewFtpPath|ftp://127.0.0.1:21/public_html/ss/2015/10/screenshot.jpg
PreviewHttpPath|http://elmaci.net/ss/2015/10/screenshot.jpg

Result of the Test button:
>Connected!
>Created folders:
>/public_html
>/public_html/ss
>/public_html/ss/2015
>/public_html/ss/2015/10

Folders are actually here (in /public_html/ss/2015/10/), I can see them with a FTP client.

However, when I try to upload an image to here I get the error I mentioned earlier.

**Comment by diamondo25** [comment]
I suggest you debug your FTP server if you can, as this sounds like a server-side issue.

**Comment by DreamPhreak** [comment]
I'm getting the same thing, even changed the chmod level to 777. Weird how it does create the folders on it's own in the server, but cant upload images.

**Comment by Jaex** [comment]
I'm closing this issue because this problem very high likely not to do with ShareX. Because everytime someone reports FTP issue it always to do with server, user configuration or FTP library we using which means not to do with ShareX.
