### ISSUE TITLE
Uploading to FTP error

### ISSUE THREAD

**Issue by ATVMc** [ShareX/ShareX#1017]
System.Net.FtpClient.FtpCommandException: Login authentication failed
   at System.Net.FtpClient.FtpClient.Authenticate()
   at System.Net.FtpClient.FtpClient.Connect()
   at ShareX.UploadersLib.FileUploaders.FTP.Connect()
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadFile(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

If you can help me fix this it'd be much appreciated!

**Comment by atillabyte** [comment]
That seems to be an error related to your configuration, rather than a bug within the application itself.

**Comment by trdwll** [comment]
"Login authentication failed"

I'd say you configured your details incorrectly.
