### ISSUE TITLE
ShareX throws an exception on startup after the most recent update

### ISSUE THREAD

**Issue by umgelurgel** [ShareX/ShareX#1050]
**Exception**:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

**Log**: 

2015-10-02 08:46:12.088 - ShareX 10.2.5 Release build
2015-10-02 08:46:12.088 - Operating system: Microsoft Windows NT 6.3.9600.0
2015-10-02 08:46:12.088 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2015-10-02 08:46:12.088 - Personal path: C:\Users\umgel_000\Documents\ShareX
2015-10-02 08:46:12.094 - ApplicationConfig load started: C:\Users\umgel_000\Documents\ShareX\ApplicationConfig.json
2015-10-02 08:46:12.953 - ApplicationConfig load finished: C:\Users\umgel_000\Documents\ShareX\ApplicationConfig.json
2015-10-02 08:46:12.962 - MainForm init started
2015-10-02 08:46:12.965 - UploadersConfig load started: C:\Users\umgel_000\Documents\ShareX\UploadersConfig.json
2015-10-02 08:46:13.134 - UploadersConfig load finished: C:\Users\umgel_000\Documents\ShareX\UploadersConfig.json
2015-10-02 08:46:13.135 - HotkeysConfig load started: C:\Users\umgel_000\Documents\ShareX\HotkeysConfig.json
2015-10-02 08:46:13.161 - HotkeysConfig load finished: C:\Users\umgel_000\Documents\ShareX\HotkeysConfig.json
2015-10-02 08:46:13.354 - MainForm init finished
2015-10-02 08:46:13.413 - Startup time: 1404 ms
2015-10-02 08:46:13.414 - CommandLine: silent
2015-10-02 08:46:13.429 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2015-10-02 08:46:13.429 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2015-10-02 08:46:13.429 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2015-10-02 08:46:13.429 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2015-10-02 08:46:13.430 - HotkeyManager started
2015-10-02 08:46:13.432 - WatchFolderManager started
2015-10-03 11:56:56.157 - ApplicationConfig save started: C:\Users\umgel_000\Documents\ShareX\ApplicationConfig.json
2015-10-03 11:56:56.463 - ApplicationConfig save successful: C:\Users\umgel_000\Documents\ShareX\ApplicationConfig.json
2015-10-03 11:56:56.463 - UploadersConfig save started: C:\Users\umgel_000\Documents\ShareX\UploadersConfig.json
2015-10-03 11:56:56.526 - UploadersConfig save successful: C:\Users\umgel_000\Documents\ShareX\UploadersConfig.json
2015-10-03 11:56:56.526 - HotkeysConfig save started: C:\Users\umgel_000\Documents\ShareX\HotkeysConfig.json
2015-10-03 11:56:56.615 - HotkeysConfig save successful: C:\Users\umgel_000\Documents\ShareX\HotkeysConfig.json
2015-10-03 11:56:56.622 - ShareX closing

**Comment by Jaex** [comment]
#1049
