### ISSUE TITLE
TargetInvocationException when loading ScrollingCaptureOptions

### ISSUE THREAD

**Issue by 0x1mason** [ShareX/ShareX#1063]
Windows 10 x64. Not certain what ShareX version (add this to your error modal?).

Expected: ShareX starts.

Actual: ShareX crashes on start with the following trace:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'ShareX.ScrollingCaptureOptions' from assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShareX.TaskSettingsCapture..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)
```

**Comment by 0x1mason** [comment]
I may have time to submit a fix for this if it has not been fixed already.

**Comment by Jaex** [comment]
This happens when library is corrupt I think. Good idea about writing ShareX version there.

**Comment by 0x1mason** [comment]
@Jaex Money. Reinstalling appears to have resolved the issue. Thanks for the help! And thanks for ShareX.
