### ISSUE TITLE
Authorisation URL do not open

### ISSUE THREAD

**Issue by jlahitte** [ShareX/ShareX#1085]
When trying to atcivate Google Drive account as a destination I click on "First step : Open authorisation page" and nothing happen. 

I check in log file and get this error : 
2015-10-27 10:35:14.170 - OpenURL(https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=XXXXXXX-XXXXXXXXXXXXXXXXXX.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive) failed:
System.ComponentModel.Win32Exception (0x80004005): Application introuvable
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.URLHelpers.<>c__DisplayClass0_0.<OpenURL>b__0()

I'm on windows XP

**Comment by Jaex** [comment]
Can you open Windows Run window and put any url there and see is it opens your browser. If URL not opens in your browser then that means your Windows not have proper configuration for default browser.

**Comment by jlahitte** [comment]
Ok thanks. That's the problem.

You can close the issue thank you for the tip.
