### ISSUE TITLE
Error on opening `Destination Settings`

### ISSUE THREAD

**Issue by jimmydorry** [ShareX/ShareX#1088]
Opened `Destination Settings` and got an error:

System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ListBox.set_SelectedIndex(Int32 value)
   at ShareX.UploadersLib.UploadersConfigForm.LoadSettings()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by Jaex** [comment]
Are you using ShareX 10.3?

**Comment by jimmydorry** [comment]
10.2. Disabled the automatic update due to it interfering with applications due to pop-over.
