### ISSUE TITLE
Lambda uploading issue

### ISSUE THREAD

**Issue by Frosttfire** [ShareX/ShareX#1089]
trying to upload anything comes up with this error

Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
Lambda API was updated in #1064 so problem could be to do with old API.

**Comment by Frosttfire** [comment]
looks like it was old api then, working well for me after a key change
