### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by danulas** [ShareX/ShareX#1103]
Rest of error message:

"Response:
{"data":{"error":"Invalid refresh token","request":"\/oauth2\/token","method":"POST"},"success":false,"status":400}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

Refresh access token failed."

Currently set to upload to own imgur album and save files to harddrive. Please help.

**Comment by Jaex** [comment]
Try re authenticate to Imgur.
