### ISSUE TITLE
Using "delete file localy" in the context menu on both local files and upload trigger a FileNotFound Exception

### ISSUE THREAD

**Issue by xrogaan** [ShareX/ShareX#1109]
As the title say, easy to reproduce. Just create a screenshot, upload it, then select both items in the list for deletion. It happened after I tried to remove a large number of items.

A good way to handle uploaded file deletion would be to allow sharex to delete the remote files if possible, otherwise ignore the entry.

```
System.IO.FileNotFoundException: Impossible de trouver le fichier 'C:\Users\xxx\Documents\ShareX\Screenshots\2015-11\2015-11-11_13-07-03.png'.
File name: 'C:\Users\xxx\Documents\ShareX\Screenshots\2015-11\2015-11-11_13-07-03.png'
   at Microsoft.VisualBasic.FileIO.FileSystem.DeleteFileInternal(String file, UIOptionInternal showUI, RecycleOption recycle, UICancelOption onUserCancel)
   at ShareX.UploadInfoManager.DeleteFiles()
   at ShareX.MainForm.tsmiDeleteSelectedFile_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Jaex** [comment]
How it works is when you right click ShareX checks selected items and their values and assigns is file exist or not so it can show proper menu items. So when deleting it using these already checked values instead of re checking and because you have 2x item with same file path it gives error in second one because it is already removed. So I must use real time check for it while looping instead of using already assigned value when deleting.
