### ISSUE TITLE
Capture rectangle region error

### ISSUE THREAD

**Issue by iwasaweeaboo** [ShareX/ShareX#1123]
Trying to  use the capture rectangle Region Feature gives me this error message: 

System.ArgumentException: Font 'Verdana' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at ShareX.ScreenCaptureLib.Surface..ctor()
   at ShareX.ScreenCaptureLib.RectangleRegion..ctor()
   at ShareX.MainForm.CaptureRegion(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

How do I fix this?

**Comment by Jaex** [comment]
Your Windows haven't Verdana font or it is corrupt. This very rarely happens in some peoples Windows I'm not sure why. So you must download that font.

**Comment by iwasaweeaboo** [comment]
Thank you so much. I works again just fine.
