### ISSUE TITLE
Exception has been thrown by the target of an invocation: Repetitive crash

### ISSUE THREAD

**Issue by ElleinadCZ** [ShareX/ShareX#1127]
So, I recently obtained Sharex to replace another screenshot program I had. This bug happened randomly, and when it did, I reinstalled Sharex. This fixed it. However, the same bug has come back. This is the error I get:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

Any assistance? And I do apologize if there is a section for this, I'm not very github savvy.

**Comment by Jaex** [comment]
#1049
