### ISSUE TITLE
Error after 10.4 update

### ISSUE THREAD

**Issue by bearhagen** [ShareX/ShareX#1135]
I got this error message after the latest update, on startup:

```
System.IO.FileNotFoundException: Could not load file or assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 10.4 Release
```

Reinstalling fixed it, but I couldn't use the hotkeys. I had to register them manually to make it work.

**Comment by Jaex** [comment]
If hotkey can't register reason for it is mainly hotkey conflict with another application. But then how you can manually register later I'm not sure. Maybe because conflicted application closed?
