### ISSUE TITLE
bug scroll capcher

### ISSUE THREAD

**Issue by pouya-0098** [ShareX/ShareX#1141]
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   at ShareX.HelpersLib.ImageHelpers.CombineImages(IEnumerable`1 images, Orientation orientation, Int32 space)
   at ShareX.ScreenCaptureLib.ScrollingCaptureForm.CombineImages()
   at ShareX.ScreenCaptureLib.ScrollingCaptureForm.CombineAndPreviewImages()
   at ShareX.ScreenCaptureLib.ScrollingCaptureForm.StopCapture()
   at ShareX.ScreenCaptureLib.ScrollingCaptureForm.captureTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.4 Relea

**Comment by Jaex** [comment]
Is there a way to reproduce this?

**Comment by Lemmmy** [comment]
what is a capcher

**Comment by mogufugi** [comment]
its google's new re-captcha system which forces you to put your dick in the RAM slot so it can proceed, dont forget the lube

Have a nice day

**Comment by Jaex** [comment]
Maybe this problem fixed with #1258 fix too.
