### ISSUE TITLE
Imgur authorization needs constant refresh to work again.

### ISSUE THREAD

**Issue by Mitsuma** [ShareX/ShareX#1143]
Not exactly sure how to describe it but almost every time I try to upload a picture after a restart or every few hours it greets me with this error message.

```
Message:
The remote server returned an error: (403) Forbidden.

Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

It won't upload anything unless I go into the destination settings and hit "Refresh authorization".
This started suddenly a few days ago where I also couldn't upload to imgur but that time I had to redo the whole authorization and since that day I have to hit refresh every now and then.

**Comment by Mitsuma** [comment]
Oh I just read this other post here. My bad.
https://github.com/ShareX/ShareX/issues/1138

Guess I have to wait for imgur to fix it.
