### ISSUE TITLE
Owncloud upload fails because of # character in webpage title

### ISSUE THREAD

**Issue by canihavesomecoffee** [ShareX/ShareX#1148]
Getting exact the same error as #739, namely:

```
`Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'ShareX.UploadersLib.FileUploaders.OwnCloud+OwnCloudShareResponseData' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'ocs.data', line 1, position 113.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.OwnCloud.ShareFile(String path)
   at ShareX.UploadersLib.FileUploaders.OwnCloud.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

This seems to be caused by the `#` character which is in the title of the page. It can be verified by trying to make a screenshot (using active window) with this html page open:

```
<html>
<head>
<title>Fail # Test</title>
</head>
<body>
<h1>This will fail to upload :(</h1>
</html> 
```
It should be a simple fix probably, if you need temporary access to an OwnCloud instance to test this, let me know.

**Comment by canihavesomecoffee** [comment]
I've done some digging on this, and the issue is that in order to upload the file to OwnCloud, the URL is formed including the # character, which makes it an invalid url.

OwnCloud is generating the file, no matter what, but without any fix, it chops off everything after the #.

Using `HttpUtility.UrlEncode` on the filename fixes that, but OwnCloud still returns an empty string.

I'll investigate this last issue further :)

**Comment by Jaex** [comment]
I can't test anything about OwnCloud.
