### ISSUE TITLE
it stopped working

### ISSUE THREAD

**Issue by kilemrah** [ShareX/ShareX#1150]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.ImageEffectsLib.DrawImage.Apply(Image img)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at ShareX.ImageEffectsLib.ImageEffectManager.ApplyEffects(Image img, List`1 imageEffects)
   at ShareX.ImageEffectsLib.ImageEffectsForm.UpdatePreview()
   at ShareX.TaskSettingsForm.btnImageEffects_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.4 Release

**Comment by kilemrah** [comment]
well i deleted all documents before i saved and reinstall it. now works for me....just for the info, problem had started once i uploaded an image from file..
![image](https://cloud.githubusercontent.com/assets/16045878/11443567/c374967a-9526-11e5-93ec-f07f9d03b046.png)

**Comment by Jaex** [comment]
I didn't understood how your problem happens. Because that image effects window can be opened from many places like tools or after capture etc. So without know how you reproduced it I can't fix it.
