### ISSUE TITLE
Error when uploading to imgur

### ISSUE THREAD

**Issue by Archenuh** [ShareX/ShareX#1151]
It's been like this for a few days now. I can upload to other websites though. Also, friends are reporting they are not having any issues uploading to imgur.

Message:
The remote server returned an error: (403) Forbidden.

Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Archenuh** [comment]
Fixed it by uninstalling and removing the "My Documents" ShareX folders containing the settings and stuff.

**Comment by Jaex** [comment]
#1138
