### ISSUE TITLE
Unable to Capture/Upload image to Imgur

### ISSUE THREAD

**Issue by NYPD** [ShareX/ShareX#1157]
I'm not really sure how to reproduce, but once in a while i get this stack trace when trying to capture and or upload an image:

```
2015-11-29 13:38:23.577 - Task failed. Filename: 2e796c2dca5d4839f9548dbd3e2dde1e.png, Errors:
Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

Then if i wait about 1-5min, in works perfectly fine. Perhaps it is an issue with imgur themselves, or maybe the image is too big.

**Comment by ValentinJesse** [comment]
I remember having similar issues with RightLoad. If you still encounter that issue, try to rename the file and retry the upload

**Comment by Jaex** [comment]
I don't think this can be to do with ShareX. Because if remote host closing connection then what ShareX can do about it.
