### ISSUE TITLE
Upload errors

### ISSUE THREAD

**Issue by ruuneabc** [ShareX/ShareX#1192]
Unable to upload > 
Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by ruuneabc** [comment]
I have also tried to link the upload to my own imgur account but after I go through the verification code bit and put it in the destination window when i try to complete auth it tells me there is a log in failure
This software was problem free up until a couple of days ago probably after an update
This is beyond annoying

**Comment by Jaex** [comment]
Nothing changed in Imgur codes for years... And entire Imgur problems was always not to do with ShareX.

**Comment by ruuneabc** [comment]
Thanks for the reply... I just dont know how to get it working I didnt
manually change any settings, really love Sharex so missing its great
functionality :(
