### ISSUE TITLE
Access is denied: recording screen as gif

### ISSUE THREAD

**Issue by mikeyjm145** [ShareX/ShareX#1193]
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at ShareX.ScreenRecordManager.StopRecording()
   at ShareX.ScreenRecordForm.OnStopRequested()
   at ShareX.ScreenRecordForm.btnStart_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jaex** [comment]
When you press stop button if FFmpeg not responding then ShareX tries to kill its process when clicked stop button again but then your OS not allowed ShareX to kill it. So permission issues not to do with ShareX. But still I'm not sure how your FFmpeg was not responding to stop request.

**Comment by elig0n** [comment]
I experience the same even when recording not as GIF
