### ISSUE TITLE
Wont let me upload pictures

### ISSUE THREAD

**Issue by Therealboy** [ShareX/ShareX#1205]
Whenever I try to upload a picture it just keeps loading to 100% then it gives me this error

"
Message:
The remote server returned an error: (403) Forbidden.

Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
"

**Comment by Scrxtchy** [comment]
Imgur destination?
Simple solution is to switch to a different destination to upload images
Otherwise imgur api needs to be reauthorised, unsure if you're using an account or anonymous

@Jaex knows a lot more about the issue, but he's not currently online

**Comment by Therealboy** [comment]
ty, just needed to reauthorise

**Comment by Jaex** [comment]
In next version when that error happen ShareX will try to automatically refresh it. Currently it was only refreshing when expired.
