### ISSUE TITLE
Error when uploading to Gfycat

### ISSUE THREAD

**Issue by Nikoskio2** [ShareX/ShareX#1219]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, Stream dataStream)

Error persists after a clean install of ShareX. GfyCat is working and I can upload files through the site.

**Comment by Jaex** [comment]
It works currently for me: https://gfycat.com/BeneficialFrigidAxisdeer
Can you try again?

**Comment by Nikoskio2** [comment]
It's been working intermittently since I posted this. I'm trying to figure out a pattern; best I can come up with right now is that uploading to Gfycat never fails when the gif's dimensions are small, irrespective of the length of the gif.
