### ISSUE TITLE
System.OutOfMemoryException: Out of memory. - When I'm trying to video record the entire screen.

### ISSUE THREAD

**Issue by techhelper1** [ShareX/ShareX#1224]
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawPath(Pen pen, GraphicsPath path)
   at ShareX.ScreenCaptureLib.RectangleRegion.Draw(Graphics g)
   at ShareX.ScreenCaptureLib.Surface.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.5 Release

I'm trying to do a recording of my screen, when I go to the top left corner to get the whole screen, I get prompted with what you see above. This is on a Dell XPS 15 9550 laptop with a 4K res screen.

Taskmgr screenshot (apologies for the image being big): http://rkhtech.org/screenshots/1452145342.png

**Comment by Jaex** [comment]
Did you checked is ShareX memory usage increasing alot when you start region selection? Is it filling memory?

**Comment by techhelper1** [comment]
Taskmgr doesn't show any signs of increasing ram or cpu.

**Comment by Jaex** [comment]
I don't think anyone can do anything about OutOfMemoryException. Especially when ShareX don't have memory leak in region selection.
