### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by sandmonkey** [ShareX/ShareX#1225]
Message:
Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
That mainly happens in two reason, either your firewall blocks ShareX or where you are trying to upload is down.

**Comment by sandmonkey** [comment]
I was messing around with proxy settings which i forgot to change back.
