### ISSUE TITLE
Imgur account: access token provided is invalid

### ISSUE THREAD

**Issue by BrianKhan** [ShareX/ShareX#1226]
it seems that i have to refresh my oauth certification, or else i get this error when uploading to imgur: 

Message:
The remote server returned an error: (403) Forbidden.

Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by mochawich** [comment]
Same here, it is not saving the verification code when closed.

**Comment by Jaex** [comment]
#1138

So I added workaround for it for next version.
