### ISSUE TITLE
Upload from clipboard broken: System.NullReferenceException

### ISSUE THREAD

**Issue by yutsuku** [ShareX/ShareX#1242]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.HelpersLib.MyPictureBox.LoadImage(Image img)
   at ShareX.HelpersLib.ClipboardContentViewer.ClipboardContentViewer_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.6 Release
```
Steps required to reproduce:

1. Copy any image into clipboard
2. Upload -> Upload from clipboard...

Running on Windows 7 (x64)

**Comment by Jaex** [comment]
#1237
