### ISSUE TITLE
Screenshot not Uploading to Any site

### ISSUE THREAD

**Issue by rafomac** [ShareX/ShareX#1246]
Hi Team,

Sharex not Uploading Screenshots to any cloud (we use Media Fire)

It shows an Error with following details.

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.MediaFire.DeserializeResponse[T](String s)
   at ShareX.UploadersLib.FileUploaders.MediaFire.GetSessionToken()
   at ShareX.UploadersLib.FileUploaders.MediaFire.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

Kindly Update me with Solution for this iisue.
Regards,
ABDUL RAFEEQUE

**Comment by rafomac** [comment]
Its working with some Pcs and Not with some. all are same configuration.

and these pcs are windows xp.

**Comment by Jaex** [comment]
How ShareX can't upload to any site. If that was the case then countless issues would be opened by users. Also tried MediaFire and I can upload without problem. So can't reproduce your problem.

**Comment by bialy77** [comment]
@rafomac check your firewall settings
