### ISSUE TITLE
Chevereto Upload Error

### ISSUE THREAD

**Issue by nixniz** [ShareX/ShareX#1250]
Its uploading but give this error and not pushup and clipboard copy img url... I have to go site and check manually. 

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Chevereto.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
I can't know what is wrong without see response. Something is wrong in response.

**Comment by nixniz** [comment]
Here is API key and site 
img.patifile.com/
8320784a9b044510e8c723fb778fe3b7

**Comment by Jaex** [comment]
That web site returns this:

```
<br />
<b>Warning</b>:  array_key_exists() expects parameter 2 to be array, null given in <b>D:\www\patifile.com\httpdocs\img\app\lib\classes\class.image.php</b> on line <b>930</b><br />
```

So it is not ShareX fault.

**Comment by nixniz** [comment]
Anyway Thank you for showing me the way... I check that line and change the code to this ;
if(!array_key_exists('title', $params)) 
to this:
if(is_array($params) && array_key_exists('title', $params)) 
And fixed.
