### ISSUE TITLE
Image upload breaks when pasting image from MightyText via clipboard

### ISSUE THREAD

**Issue by symmetryrtemmys** [ShareX/ShareX#1254]
This started breaking sometime within the last week or two. A reinstallation of both programs didn't fix the issue. I have double-checked that the image is being copied to the clipboard: in Paint.NET and Paint, the image pastes perfectly.

The bug I am experiencing occurs every time I copy an image from MightyText to my computer clipboard before editing and/or uploading with ShareX. When I attempt to upload the image via ShareX, I receive the following error: 

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.HelpersLib.MyPictureBox.LoadImage(Image img)
   at ShareX.HelpersLib.ClipboardContentViewer.ClipboardContentViewer_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.6 Release

Any help resolving this issue would be appreciated.

**Comment by Jaex** [comment]
#1237
