### ISSUE TITLE
Error after screen record

### ISSUE THREAD

**Issue by xnite** [ShareX/ShareX#1277]
I get this error after everytime I stop a screen recording. So it's been impossible for me to do a screen record at all.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.FileUploaders.Dropbox.GetPublicURL(String path)
   at ShareX.UploadersLib.FileUploaders.Dropbox.CheckEarlyURLCopy(String path, String fileName)
   at ShareX.UploadersLib.FileUploaders.Dropbox.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.FileUploaders.Dropbox.GetPublicURL(String path)
   at ShareX.UploadersLib.FileUploaders.Dropbox.CheckEarlyURLCopy(String path, String fileName)
   at ShareX.UploadersLib.FileUploaders.Dropbox.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

**Comment by Scrxtchy** [comment]
try toggling this
Looks like it's turned on
![](https://jii.moe/4keljH_ug.png)

It's an issue with the early url copier
See #1252
