### ISSUE TITLE
Chevereto Image uploading error

### ISSUE THREAD

**Issue by dhuw** [ShareX/ShareX#1290]
I uploaded my screenshots to [wi.to](url) until two months ago it didn't work anymore with the API Key there ([wi.to/page/api](url)).
I use still the settings but it doesn't work anymore. I contacted the hoster of wi.to and he found my image on his server. That means, ShareX Uploaded the image but didn't get any response (where the link for the Image URL is included).

Upload error:
> Message:
> The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF
> 
> StackTrace:
>    at System.Net.HttpWebRequest.GetResponse()
>    at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
> 

With "ShareX.UploadersLib" is this meant: [https://github.com/ShareX/ShareX/tree/master/ShareX.UploadersLib](url)

Log file (not more information):
```
2016-01-30 00:18:09.683 - Hotkey triggered: Hotkey: Ctrl + Y, Description: Capture region, Job: RectangleRegion
2016-01-30 00:18:12.692 - Task in queue. Job: Job, Type: Image, Host: Chevereto
2016-01-30 00:18:12.705 - Task status: Preparing
2016-01-30 00:18:12.737 - Image copied to clipboard.
2016-01-30 00:18:12.756 - Image saved to file: C:\Users\Nico\Documents\ShareX\Screenshots\2016-01\ShareX_2016-01-30_00-18-12.png
2016-01-30 00:18:12.770 - Upload started. Filename: ShareX_2016-01-30_00-18-12.png, Filepath: C:\Users\Nico\Documents\ShareX\Screenshots\2016-01\ShareX_2016-01-30_00-18-12.png
2016-01-30 00:18:15.373 - AddWebError(): Message:
The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2016-01-30 00:18:15.385 - Task failed. Filename: ShareX_2016-01-30_00-18-12.png, Errors:
Message:
The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

```
Additional Information: Any other uploader works fine.

**Comment by Jaex** [comment]
Problem to do with their server not ShareX. And even you telling it was working fine before and it not works anymore and nothing changed in ShareX.
