### ISSUE TITLE
System.Net.FtpClient.FtpCommandException: Disk full - please upload later

### ISSUE THREAD

**Issue by ParaPup** [ShareX/ShareX#1293]
System.Net.FtpClient.FtpCommandException: Disk full - please upload later
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

My FTP
Disk Space Usage	1.51 GB / 9.79 GB

**Comment by Jaex** [comment]
Because I didn't made that [FTP library](https://netftp.codeplex.com/) I can't know what is wrong. But probably developers of that library can't do anything about it too because it just shows what error server returns probably.
