### ISSUE TITLE
This request requires buffering data to succeed.

### ISSUE THREAD

**Issue by MarcProe** [ShareX/ShareX#1296]
Trying to upload to Owncloud, this error is thrown.
Complete Error Log:

```

Message:
This request requires buffering data to succeed.

Response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://xxx/webdav/Upload/yyyyy.dat">here</a>.</p>
</body></html>


StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

```

**Comment by Jaex** [comment]
Response shows problem not to do with ShareX: `<title>301 Moved Permanently</title>`

**Comment by wolfen351** [comment]
@MarcProe i'm encountering the same error, did you ever get it working?

**Comment by wolfen351** [comment]
aah changing the url worked, in my case https:// instead of http:// fixed it..
