### ISSUE TITLE
FTP upload issue

### ISSUE THREAD

**Issue by R0GGER** [ShareX/ShareX#1304]
I can not upload anything with FTP;

```
System.TimeoutException: Timed out trying to read data from the socket stream!
   at System.Net.FtpClient.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FtpClient.FtpSocketStream.ReadLine(Encoding encoding)
   at System.Net.FtpClient.FtpClient.GetReply()
   at System.Net.FtpClient.FtpClient.Execute(String command)
   at System.Net.FtpClient.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenWrite(String path, FtpDataType type)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

**Comment by R0GGER** [comment]
Solved!
Setting > Is active = False
