### ISSUE TITLE
Issue about uploading screencast (mp4)

### ISSUE THREAD

**Issue by anhlequoc** [ShareX/ShareX#1326]
Steps:
- use Work Flow > select screen recording > record a sample screencast (mp4)
- Right click on the sample video > choose Upload
-> App returns an error as below:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.FileUploaders.Dropbox.GetPublicURL(String path)
   at ShareX.UploadersLib.FileUploaders.Dropbox.CheckEarlyURLCopy(String path, String fileName)
   at ShareX.UploadersLib.FileUploaders.Dropbox.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.FileUploaders.Dropbox.GetPublicURL(String path)
   at ShareX.UploadersLib.FileUploaders.Dropbox.CheckEarlyURLCopy(String path, String fileName)
   at ShareX.UploadersLib.FileUploaders.Dropbox.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

**Comment by Jaex** [comment]
You can't upload to Dropbox without account info. Was fixed it to give proper error message.

**Comment by anhlequoc** [comment]
issue is found on ShareX 10.6.1, Windows Version

**Comment by anhlequoc** [comment]
ok, thank you :+1:
