### ISSUE TITLE
ShareX Activates Without Keypress

### ISSUE THREAD

**Issue by drguildo** [ShareX/ShareX#1339]
ShareX keeps activating without me doing anything that should activate it. For example, I'll just be moving my mouse across the screen and it'll decide to take a screenshot. I thought maybe this might be a problem with my keyboard or mouse or something but I've seen no other symptoms that would suggest this and it's only ShareX that I've been having problems with.

**Comment by Jaex** [comment]
Can you check debug log it can show is hotkey triggered.

**Comment by drguildo** [comment]
Is there anything I need to enable? I've found some log files but they aren't very detailed.

**Comment by Jaex** [comment]
Debug log window shows which hotkey pressed and which task started.

**Comment by drguildo** [comment]
```
2016-02-21 10:28:21.475 - Task in queue. Job: Job, Type: Image, Host: 
2016-02-21 10:28:21.484 - Task status: Preparing
2016-02-21 10:28:21.503 - Image copied to clipboard.
2016-02-21 10:28:21.515 - Image saved to file: C:\Users\Simon\Documents\ShareX\Screenshots\2016-02\explorer_2016-02-21_10-28-21.png
2016-02-21 10:28:21.527 - Task completed. Filename: explorer_2016-02-21_10-28-21.png, URL: , Duration: 28 ms
2016-02-21 10:28:24.013 - URL opened: C:\Users\Simon\Documents\ShareX\Screenshots\2016-02\explorer_2016-02-21_10-28-21.png
2016-02-21 11:22:16.049 - Exception:
System.InvalidCastException: Unable to cast COM object of type 'Shell32.ShellClass' to interface type 'Shell32.IShellDispatch6'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Shell32.ShellClass.NameSpace(Object vDir)
   at ShareX.HelpersLib.ShortcutHelpers.GetShortcutTargetPath(String shortcutPath)
2016-02-21 11:22:16.049 - Exception:
System.InvalidCastException: Unable to cast COM object of type 'Shell32.ShellClass' to interface type 'Shell32.IShellDispatch6'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Shell32.ShellClass.NameSpace(Object vDir)
   at ShareX.HelpersLib.ShortcutHelpers.GetShortcutTargetPath(String shortcutPath)
2016-02-21 11:22:35.711 - ApplicationConfig save started: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
2016-02-21 11:22:35.901 - ApplicationConfig save successful: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
```

**Comment by Jaex** [comment]
It not shows where Task started. There is no hotkey?

**Comment by drguildo** [comment]
The problem happened today and I pasted all the debug logs from today.

**Comment by Jaex** [comment]
I don't see how it can automatically start, nobody was reported such thing before.

**Comment by drguildo** [comment]
There has to be somebody who reports a bug for the first time. I still obviously can't say 100% it's a bug in ShareX but, like I say, I haven't had any other kind of weird behaviour that's consistent with a mouse/keyboard problem. I've been using ShareX for a while and it's only just started happening since the last update IIRC.

**Comment by Jaex** [comment]
I don't have any code which can execute itself. How am I supposed to find how it happened for you.

**Comment by drguildo** [comment]
> I don't have any code which can execute itself. How am I supposed to find how it happened for you.

I don't want to be pedantic but no code "executes itself" and I never said it did, I said it executes without me hitting a keyboard shortcut.

I don't expect you to reproduce it but I thought maybe you could help me track down the cause of it but instead you seem to want to just be defensive and argue.

> And reason why I told nobody reported it before because ShareX was released long years ago and someone would have reported if such bug exists.

Only if the bug had existed since then. It has been known for bugs to be added by code changes and not just removed.

Anyway, it just happened again.

```
2016-02-21 23:12:43.860 - Task in queue. Job: Job, Type: Image, Host: 
2016-02-21 23:12:43.860 - Task status: Preparing
2016-02-21 23:12:43.876 - Image copied to clipboard.
2016-02-21 23:12:43.904 - Image saved to file: C:\Users\Simon\Documents\ShareX\Screenshots\2016-02\2016-02-21_23-12-43.png
2016-02-21 23:12:43.914 - Task completed. Filename: 2016-02-21_23-12-43.png, URL: , Duration: 27 ms```

That's all there is in the debug log.

**Comment by Jaex** [comment]
What is that saved image, fullscreen?

**Comment by drguildo** [comment]
I think that one was the task bar and the one before that was the start menu button.

**Comment by Jaex** [comment]
If it was region capture then without show region selection how it can trigger that i'm not sure.

**Comment by drguildo** [comment]
The selection dialog does appear and I'm not sure whether it takes the screenshot itself or whether I'm in the middle of clicking the mouse but that's how it ends up taking the screenshot. I'll try to give you a definitive answer next time it happens.

**Comment by Jaex** [comment]
Is it possible you were clicked tray icon once which opens region capture. Or if you middle click tray icon then it takes fullscreen ss.

**Comment by drguildo** [comment]
I don't remember doing that but I suppose it's possible. I'll report back if it happens again.

**Comment by srnyx** [comment]
@Jaex this is happening to me
