### ISSUE TITLE
Cannot upload images

### ISSUE THREAD

**Issue by ze10** [ShareX/ShareX#1361]
I've been trying to upload images with sharex, but I can't seem to do it, no matter which host I choose

When I try uploading to imgur, I get:

`Message:
Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)`

When I try Tinypic, I get:

`Message:
Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, Stream dataStream)

Unable to get upload key.`

When I try Sendspace:

`URL is empty.`

Dropfile:

`Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)`

Is something wrong?

**Comment by Jaex** [comment]
Your firewall or something in your computer blocks internet connection I think.

**Comment by Dunky13** [comment]
I have this problem, tried disabling firewall - no succes.
