### ISSUE TITLE
Task Settings produces an exception and fails to open

### ISSUE THREAD

**Issue by Yuubari** [ShareX/ShareX#1367]
Error log:

```
2016-02-26 13:48:31.639 - Unhandled exception:
System.ArgumentOutOfRangeException: Value of '4096' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at ShareX.TaskSettingsForm..ctor(TaskSettings hotkeySetting, Boolean isDefault)
   at ShareX.MainForm.tsbTaskSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.7 Release

```

**Comment by Jaex** [comment]
#1350
