### ISSUE TITLE
Trying to access task setting gives error

### ISSUE THREAD

**Issue by SpyroZeppeli** [ShareX/ShareX#1372]
```
System.ArgumentOutOfRangeException: Value of '3000' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at ShareX.TaskSettingsForm..ctor(TaskSettings hotkeySetting, Boolean isDefault)
   at ShareX.MainForm.tsbTaskSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.7 Release
```

This appears just from clicking task settings, and task settings refuses to open. I can recreate it by just clicking task settings. No idea what the cause of it could be.

**Comment by Jaex** [comment]
#1350
