### ISSUE TITLE
Bug Report: UploaderLib not found after updating.

### ISSUE THREAD

**Issue by khoin** [ShareX/ShareX#1398]
This is the bug report I got:
```
System.IO.FileNotFoundException: Could not load file or assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 10.8 Release
```

**Comment by Jaex** [comment]
Reinstall ShareX.

**Comment by khoin** [comment]
@Jaex That was fast. Ok. I'll try.
