### ISSUE TITLE
Illegal characters in path.

### ISSUE THREAD

**Issue by drguildo** [ShareX/ShareX#1402]
I get this when starting ShareX:

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at ShareX.RecentTask.get_FileName()
   at ShareX.WorkerTask.CreateHistoryTask(RecentTask recentTask)
   at ShareX.TaskManager.AddRecentTasksToMainWindow()
   at ShareX.RecentTaskManager.UpdateMainWindowList()
   at ShareX.RecentTaskManager.InitItems()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

The full log looks like this:

```
2016-03-12 15:37:53.311 - ShareX 10.8 Release
2016-03-12 15:37:53.311 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2016-03-12 15:37:53.327 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2016-03-12 15:37:53.327 - Personal path: C:\Users\Simon\Documents\ShareX
2016-03-12 15:37:53.327 - ApplicationConfig load started: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
2016-03-12 15:37:53.857 - ApplicationConfig load finished: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
2016-03-12 15:37:53.857 - MainForm init started
2016-03-12 15:37:53.857 - UploadersConfig load started: C:\Users\Simon\Documents\ShareX\UploadersConfig.json
2016-03-12 15:37:54.060 - UploadersConfig load finished: C:\Users\Simon\Documents\ShareX\UploadersConfig.json
2016-03-12 15:37:54.060 - HotkeysConfig load started: C:\Users\Simon\Documents\ShareX\HotkeysConfig.json
2016-03-12 15:37:54.107 - HotkeysConfig load finished: C:\Users\Simon\Documents\ShareX\HotkeysConfig.json
2016-03-12 15:37:54.169 - MainForm init finished
2016-03-12 15:37:54.201 - Unhandled exception:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at ShareX.RecentTask.get_FileName()
   at ShareX.WorkerTask.CreateHistoryTask(RecentTask recentTask)
   at ShareX.TaskManager.AddRecentTasksToMainWindow()
   at ShareX.RecentTaskManager.UpdateMainWindowList()
   at ShareX.RecentTaskManager.InitItems()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.8 Release
2016-03-12 15:37:57.967 - ShareX closing. Reason: Unhandled exception
2016-03-12 15:37:57.998 - ApplicationConfig save started: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
2016-03-12 15:37:58.201 - ApplicationConfig save successful: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
2016-03-12 15:37:58.201 - UploadersConfig save started: C:\Users\Simon\Documents\ShareX\UploadersConfig.json
2016-03-12 15:37:58.294 - UploadersConfig save successful: C:\Users\Simon\Documents\ShareX\UploadersConfig.json
2016-03-12 15:37:58.294 - HotkeysConfig save started: C:\Users\Simon\Documents\ShareX\HotkeysConfig.json
2016-03-12 15:37:58.403 - HotkeysConfig save successful: C:\Users\Simon\Documents\ShareX\HotkeysConfig.json
2016-03-12 15:37:58.403 - ShareX closing
```

**Comment by Jaex** [comment]
I was fixed this yesterday. Until next version you can workaround this like this: Open Documents\ShareX\ApplicationConfig.json file when ShareX is not open, search for "RecentTasks" remove items inside it and save.

**Comment by Jaex** [comment]
6fbe9b591309c06daf48dabc4029297351441dfd
