### ISSUE TITLE
System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by OliverDatGuy** [ShareX/ShareX#1405]
Every time ShareX (10.8) launches, I get this error. But then it launches fine upon first inspection. However my hotkeys don't work whatsoever so I can't press things like prtscn to screencap etc.

Here's the error

`System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at ShareX.RecentTask.get_FileName()
   at ShareX.WorkerTask.CreateHistoryTask(RecentTask recentTask)
   at ShareX.TaskManager.AddRecentTasksToMainWindow()
   at ShareX.RecentTaskManager.UpdateMainWindowList()
   at ShareX.RecentTaskManager.InitItems()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.8 Release`

Sorry if this has already been posted, I didn't see it anywhere.

**Comment by OliverDatGuy** [comment]
Ah nvm, found the issue elsewhere. Sorry for the bother.
