### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by gui7vaz** [ShareX/ShareX#1409]
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at ShareX.RecentTask.get_FileName()
   at ShareX.WorkerTask.CreateHistoryTask(RecentTask recentTask)
   at ShareX.TaskManager.AddRecentTasksToMainWindow()
   at ShareX.RecentTaskManager.UpdateMainWindowList()
   at ShareX.RecentTaskManager.InitItems()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.8 Release

**Comment by campbeb** [comment]
Please see #1402 for how to fix prior to next release.
