### ISSUE TITLE
Error on portable ShareX install

### ISSUE THREAD

**Issue by stisev** [ShareX/ShareX#1422]
I get this 
Screenshot: http://i.imgur.com/E6ld5RN.png

Right click / Show Errors displays:

System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at ShareX.UploadersLib.FileUploaders.SendSpace.ParseUploadResponse(String response)
   at ShareX.UploadersLib.FileUploaders.SendSpace.Upload(Stream stream, String fileName, UploadInfo uploadInfo)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Log displays the same thing

**Comment by Jaex** [comment]
Your report not makes sense because your error log have nothing to do with portable or install.
But SendSpace gives error when you upload file with no extension and no data in it. But it allows uploading file with no extension or file with no data but have extension. So it is their fault.
