### ISSUE TITLE
Illegal characters in path on startup

### ISSUE THREAD

**Issue by rzumer** [ShareX/ShareX#1434]
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.GetFileName(String path)
   at ShareX.WorkerTask.CreateHistoryTask(RecentTask recentTask)
   at ShareX.TaskManager.AddRecentTasksToMainWindow()
   at ShareX.RecentTaskManager.InitItems()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.8 Release
```

Happens every time, already tried re-installing ShareX. Might be because the system language is in Japanese which uses ￥ instead of \ for file paths.

**Comment by Jaex** [comment]
#1402
