### ISSUE TITLE
i dunno,it was working now its not

### ISSUE THREAD

**Issue by random1167** [ShareX/ShareX#1495]
Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, AutoResetEvent wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.FlushWriteBuffer()
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Close()
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, AutoResetEvent wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.FlushWriteBuffer()
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Close()
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, AutoResetEvent wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.FlushWriteBuffer()
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Close()
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, AutoResetEvent wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.FlushWriteBuffer()
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Close()
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, AutoResetEvent wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.FlushWriteBuffer()
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Close()
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
If it was working before then how it can be fault of ShareX because nothing changed in ShareX.

**Comment by random1167** [comment]
i dont know im just reporting the error it spat at me, i dunno what i did because i really dont remember doing anything, even after i ran my domain thru cloudflare it was working, i will go back and run thru the steps again and try to sniff it out

**Comment by Jaex** [comment]
Because only error message is: `SshException: Failure` and because sftp library is not made by me it is not possible for me to figure out what is problem, sorry.

**Comment by random1167** [comment]
my vps was reading a full hardrive,rebooted and it works again
