### ISSUE TITLE
settings not saved. Problem with accented windows acount folder name and with NET Framework 4.0 installation.

### ISSUE THREAD

**Issue by pierv** [ShareX/ShareX#1496]
Hi all,
my problem has same symptom as: #934 and #702 
although I do not know if it is the same root cause, maybe not. That is why I created a new bug report.
I red through the issues and tried a few things around but not luck.
One constant: I always get in the debug log this error:

"System.IO.FileLoadException: not able to load the file or assembly 'System.Data.dll' or one of its dependecies. Access denied. File name: System.Data.dll'"   (It is actually in french and translated the error message).

I won't write more details and heredown my complete debug log when I start shareX and my settings folder screenshot. Note: I installed shareX as administrator under a Windows 7 / 64 bits (french).
Thanks for any suggestion :-)... anyway, this software looks exactly what I need ... great job, thanks !

---------- settings folder ---------
![ss 2016-04-12 at 08 34 35](https://cloud.githubusercontent.com/assets/18045037/14457569/b58c82e6-00ee-11e6-84c3-6ff0be274e80.jpg)
---------- Debug log ---------
2016-04-12 20:03:52.536 - ShareX 10.9.1 Release
2016-04-12 20:03:52.540 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2016-04-12 20:03:52.540 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2016-04-12 20:03:52.540 - Personal path: ShareX
2016-04-12 20:03:52.544 - ApplicationConfig load started: ShareX\ApplicationConfig.json
2016-04-12 20:03:52.544 - ApplicationConfig not found. Loading new instance.
2016-04-12 20:03:52.544 - ApplicationConfig load started: ShareX\ApplicationConfig.json.bak
2016-04-12 20:03:52.595 - MainForm init started
2016-04-12 20:03:52.595 - UploadersConfig not found. Loading new instance.
2016-04-12 20:03:52.595 - UploadersConfig load started: ShareX\UploadersConfig.json.bak
2016-04-12 20:03:52.596 - UploadersConfig load started: ShareX\UploadersConfig.json
2016-04-12 20:03:52.611 - HotkeysConfig load started: ShareX\HotkeysConfig.json
2016-04-12 20:03:52.612 - HotkeysConfig load started: ShareX\HotkeysConfig.json.bak
2016-04-12 20:03:52.612 - HotkeysConfig not found. Loading new instance.
2016-04-12 20:03:52.892 - MainForm init finished
2016-04-12 20:03:52.936 - Startup time: 434 ms
2016-04-12 20:03:52.968 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capturer une région, Job: RectangleRegion
2016-04-12 20:03:52.969 - Hotkey registered: Hotkey: Print Screen, Description: Capturer tout l'écran, Job: PrintScreen
2016-04-12 20:03:52.969 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capturer la fenêtre active, Job: ActiveWindow
2016-04-12 20:03:52.969 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Enregistrement d'écran, Job: ScreenRecorder
2016-04-12 20:03:52.969 - HotkeyManager started
2016-04-12 20:03:52.969 - WatchFolderManager started
2016-04-12 20:03:56.730 - GitHub update check failed:
System.IO.FileLoadException: Impossible de charger le fichier ou l'assembly 'System.Data.dll' ou une de ses dépendances. Accès refusé.
File name: 'System.Data.dll'
   at Newtonsoft.Json.Converters.BinaryConverter.CanConvert(Type objectType)
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()

**Comment by Jaex** [comment]
Why you storing your settings in program files. That will require ShareX to run as admin always to be able to save there.

**Comment by pierv** [comment]
Thanks Jaex for quick reply. Your comment suggested me additional inquiry.
I finally could solve my problem, was long to find out but I will explain here how so that can help others. Yeahhh !
I created another admin windows acount for understanding the problems, called "testacount".
I had, I think, three root causes for the problem:

1) My windows acount folder has an accented name: "Propriétaire". That is probably why by default shareX got confused and installed the user folder under the program file. Installing under my "testacount" confirmed that behaviour as shareX found easily the "testacount\Documents" folder under which to add the "shareX" settings folder. Probably this accented name (unluckilly created by my computer vendor) is the cause of various software installation issues I had in the past.
I believe it would be wise for me to change this folder name soon. I found the instructions but so far I do not need it for the purpose of installing shareX given that I solved that issue by selecting a new settings folder in "Application settings"/"paths". By the way, it would be wise in a future version of shareX, to propose to the user, during installation process, to manually select the "settings" folder, as an option. This would avoid users (say 1% ?) to get into that problem.
The instruction for renaming an account folder: [http://superuser.com/questions/570601/rename-profile-folder-on-windows-7-8](url)

2) My .Net framework 4.5 installation had a problem. That is why I got this "System.Data.dll" error. Installing in my new "testacount" did not solve that problem. So I had to uninstall NET framework 4.5. Then I reinstalled shareX, which warned about the needed Net Framework 4.0 and invited to automatically install it, which I did. After that shareX installed properly in my "testacount" and worked perfectly:
![ss 2016-04-14 at 10 45 49](https://cloud.githubusercontent.com/assets/18045037/14531651/8399ab10-02a1-11e6-963b-3f514d7ca176.png)
![ss 2016-04-14 at 11 02 38](https://cloud.githubusercontent.com/assets/18045037/14531743/e5a4d910-02a1-11e6-99cb-6816a16c055c.png)

3) Then I uninstalled shareX and reinstalled from my "Propriétaire" account as this is the regular account I am using. There shareX failed to start with the following error: "CLR 80004005"
![ss 2016-04-14 at 11 08 27](https://cloud.githubusercontent.com/assets/18045037/14531831/3b77fc28-02a2-11e6-9304-63d1425f297d.jpg)
Not sure what is the root cause but I believe my account user folder name may be the problem. Anyway, I "magically" solved that problem by running a tool called "Microsoft .NET Framework Repair Tool":
[https://www.microsoft.com/en-us/download/details.aspx?id=30135](url)
![ss 2016-04-14 at 11 09 51](https://cloud.githubusercontent.com/assets/18045037/14532056/f799032a-02a2-11e6-8066-8d9379dc5669.png)

Finally all working perfectly... at least I hope for a while, as I will have to upgrade my NET FW from 4.0 to 4.5 soon... let's see...

Thank you again to the developers. Beside the useful tool I learned something new today !
Regards
Pier
