### ISSUE TITLE
Cannot upload webm to gfycat

### ISSUE THREAD

**Issue by DyKrass** [ShareX/ShareX#1506]
I used to be able to record and upload webm videos to gfycat but all of a sudden I get an error now. The video file is successfully saved to my screenshots folder though.

> Newtonsoft.Json.JsonReaderException: Could not convert string to boolean: ShareX. Path 'isOk', line 1, position 16.
   at Newtonsoft.Json.JsonReader.ReadBooleanString(String s)
   at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadFile(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
I tried to upload webm to gfycat, it worked. There can be temporary issue in gfycat side.
