### ISSUE TITLE
Failed to create an IPC Port: access denied

### ISSUE THREAD

**Issue by marker1k** [ShareX/ShareX#1509]
System.Runtime.Remoting.RemotingException: Failed to create an IPC Port: Отказано в доступе.

   at System.Runtime.Remoting.Channels.Ipc.IpcServerChannel.StartListening(Object data)
   at ShareX.HelpersLib.ApplicationInstanceManager.RegisterRemoteType(String uri)
   at ShareX.HelpersLib.ApplicationInstanceManager.CreateFirstInstance(EventHandler`1 callback)
   at ShareX.Program.Main(String[] args)

ShareX 10.9.1 Release

**Comment by Jaex** [comment]
#1462
