### ISSUE TITLE
Can't upload webm to pomf.cat

### ISSUE THREAD

**Issue by CabbaLens** [ShareX/ShareX#1526]
System.IO.IOException: The process cannot access the file 'C:\Users\Admin\Documents\ShareX\Screenshots\2016-04\CabbaLens_2016-04-28_19-00-32.webm' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 10.9.1 Release

> help?

**Comment by MTadder** [comment]
it is being used by another process. Close other processes that might be using it.
