### ISSUE TITLE
An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by Lloydski246** [ShareX/ShareX#1541]
I've been a long time user of ShareX and it's been brilliant. However, after upgrading my pc from W7 to W10 I have been plagued by errors 90% of the time whilst trying to upload screenshots and other images.

Any help on what the cause/solution may be would be greatly appreciated.

Latest error log (as far as I can remember all the others were this error too).
http://pastebin.com/Yi3L6bra

**Comment by Lloydski246** [comment]
New error.

Message:
The underlying connection was closed: An unexpected error occurred on a receive.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
These problems not to do with ShareX.
