### ISSUE TITLE
Can't Save Edited Pictures

### ISSUE THREAD

**Issue by GinjaNinja018** [ShareX/ShareX#1593]
I have been trying to save an edited picture, but each time I press the save button, this comes up:

System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.<>c__DisplayClass6_2.<AnnotateImage>b__5()
   at ShareX.HelpersLib.Extensions.InvokeSafe(Control control, Action action)
   at Greenshot.ImageEditorForm.OnImageSaveRequested()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at Greenshot.Controls.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.9.1 Steam

**Comment by campbeb** [comment]
Can you verify that you have write permission to the directory the image is stored in? Sometimes that error can occur if the image can't be saved to the directory.

**Comment by Jaex** [comment]
This problem not to do with ShareX. But error message not gives enough info to know why it happens too. But if it were to do with ShareX then many people would have reported it. But saving works fine for everyone, so something in your end must be causing it.

**Comment by timelf123** [comment]
Reproduced in 11.2.1, it could be a perms issue.

Steps:
- Screenshot, upload to imgur
- Later, want to edit image which is conveniently in my clipboard as URL
- Tools -> Image editor -> File open window appears
- Paste imgur url (in windows, this saves the file to a tmp dir, which I believe is the root of the problem)
- Edit image, click save
- file picker never appears, following error is thrown


```
2016-09-28 10:52:24.232 - Unhandled exception:
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.<>c__DisplayClass7_2.<AnnotateImage>b__5()
   at ShareX.HelpersLib.Extensions.InvokeSafe(Control control, Action action)
   at Greenshot.ImageEditorForm.OnImageSaveRequested()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at Greenshot.Controls.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.2.1 (Release)
2016-09-28 10:52:26.615 - ShareX continue.
2016-09-28 10:52:28.958 - Unhandled exception:
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.<>c__DisplayClass7_2.<AnnotateImage>b__5()
   at ShareX.HelpersLib.Extensions.InvokeSafe(Control control, Action action)
   at Greenshot.ImageEditorForm.OnImageSaveRequested()
   at Greenshot.ImageEditorForm.ImageEditorFormFormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

ShareX 11.2.1 (Release)
```

![SCREENSHOT](http://i.imgur.com/OZ21YKK.png)
