### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ad1c** [ShareX/ShareX#1604]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadInfoParser.Parse(TaskInfo info, String pattern)
   at ShareX.TaskManager.task_TaskCompleted(WorkerTask task)
   at ShareX.WorkerTask.OnTaskCompleted()

ShareX 11.0 Release

**Comment by Jaex** [comment]
#1603

**Comment by ad1c** [comment]
Can't find a way to attach log file.  Here it is.

2016-06-06 19:55:09.653 - ShareX 10.9.1 Release
2016-06-06 19:55:09.662 - Personal path: C:\Users\jjrei\OneDrive\Documents\ShareX
2016-06-06 19:55:09.675 - Command line: "D:\ShareX\ShareX.exe" -silent
2016-06-06 19:55:09.687 - Operating system: Microsoft Windows NT 10.0.14352.0
2016-06-06 19:55:11.273 - ApplicationConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-06 19:55:12.694 - ApplicationConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-06 19:55:12.700 - UploadersConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-06 19:55:12.704 - MainForm init started
2016-06-06 19:55:13.359 - UploadersConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-06 19:55:13.363 - HotkeysConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-06 19:55:13.393 - HotkeysConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-06 19:55:13.540 - MainForm init finished
2016-06-06 19:55:13.621 - Startup time: 4158 ms
2016-06-06 19:55:13.625 - CommandLine: silent
2016-06-06 19:55:13.647 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2016-06-06 19:55:13.653 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2016-06-06 19:55:13.657 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2016-06-06 19:55:13.662 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2016-06-06 19:55:13.666 - HotkeyManager started
2016-06-06 19:55:13.671 - WatchFolderManager started
2016-06-07 08:50:22.400 - Executing: Capture region
2016-06-07 08:50:29.926 - Task in queue. Job: Job, Type: Image, Host: 
2016-06-07 08:50:29.931 - Task status: Preparing
2016-06-07 08:50:29.952 - Image saved to file: C:\Users\jjrei\OneDrive\Documents\ShareX\Screenshots\2016-06\QSO_Detail_-_Mozilla_Firefox_2016-06-07_08-50-29.png
2016-06-07 08:50:29.965 - Task completed. Filename: QSO_Detail_-_Mozilla_Firefox_2016-06-07_08-50-29.png, URL: , Duration: 23 ms
2016-06-07 08:51:36.825 - Executing: Capture region
2016-06-07 08:51:43.357 - Task in queue. Job: Job, Type: Image, Host: 
2016-06-07 08:51:43.362 - Task status: Preparing
2016-06-07 08:51:43.369 - Image saved to file: C:\Users\jjrei\OneDrive\Documents\ShareX\Screenshots\2016-06\ARRL_National_Parks_on_the_Air_-_Mozilla_Firefox_2016-06-07_08-51-43.png
2016-06-07 08:51:43.374 - Task completed. Filename: ARRL_National_Parks_on_the_Air_-_Mozilla_Firefox_2016-06-07_08-51-43.png, URL: , Duration: 4 ms
2016-06-08 07:01:26.546 - Executing: Capture region
2016-06-08 07:01:38.162 - Task in queue. Job: Job, Type: Image, Host: 
2016-06-08 07:01:38.167 - Task status: Preparing
2016-06-08 07:01:38.173 - Image saved to file: C:\Users\jjrei\OneDrive\Documents\ShareX\Screenshots\2016-06\HAMLOG_-_Online_LOG_for_any_HAM_(radioamateur)_-_b_2016-06-08_07-01-38.png
2016-06-08 07:01:38.178 - Task completed. Filename: HAMLOG_-_Online_LOG_for_any_HAM_(radioamateur)_-_b_2016-06-08_07-01-38.png, URL: , Duration: 13 ms
2016-06-08 18:55:21.977 - GitHub update check failed:
System.Net.WebException: The remote name could not be resolved: 'api.github.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()
2016-06-08 20:25:25.720 - Hotkey unregistered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2016-06-08 20:25:25.736 - Hotkey unregistered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2016-06-08 20:25:25.736 - Hotkey unregistered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2016-06-08 20:25:25.752 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2016-06-08 22:09:16.010 - Command line: "D:\ShareX\ShareX.exe" -silent
2016-06-08 22:09:16.017 - Operating system: Microsoft Windows NT 10.0.14361.0
2016-06-08 22:09:16.024 - Personal path: C:\Users\jjrei\OneDrive\Documents\ShareX
2016-06-08 22:09:16.031 - ShareX 10.9.1 Release
2016-06-08 22:09:17.636 - ApplicationConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-08 22:09:18.165 - ApplicationConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-08 22:09:18.371 - UploadersConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-08 22:09:18.377 - HotkeysConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-08 22:09:18.409 - HotkeysConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-08 22:09:18.500 - MainForm init finished
2016-06-08 22:09:18.562 - Startup time: 2786 ms
2016-06-08 22:09:18.567 - CommandLine: silent
2016-06-08 22:09:18.602 - Unable to register hotkey: Print Screen
2016-06-08 22:09:18.608 - Hotkey register failed: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2016-06-08 22:09:18.612 - Unable to register hotkey: Alt + Print Screen
2016-06-08 22:09:18.617 - Hotkey register failed: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2016-06-08 22:09:18.621 - Unable to register hotkey: Ctrl + Print Screen
2016-06-08 22:09:18.625 - Hotkey register failed: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2016-06-08 22:09:18.629 - Unable to register hotkey: Shift + Print Screen
2016-06-08 22:09:18.633 - Hotkey register failed: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2016-06-08 22:11:04.266 - HotkeyManager started
2016-06-08 22:11:04.282 - WatchFolderManager started
2016-06-09 08:02:37.562 - Operating system: Microsoft Windows NT 10.0.14361.0
2016-06-09 08:02:37.579 - Personal path: C:\Users\jjrei\OneDrive\Documents\ShareX
2016-06-09 08:02:37.589 - Command line: "D:\ShareX\ShareX.exe" -silent
2016-06-09 08:02:37.594 - ShareX 10.9.1 Release
2016-06-09 08:02:39.284 - ApplicationConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 08:02:40.961 - ApplicationConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 08:02:40.966 - MainForm init started
2016-06-09 08:02:40.976 - UploadersConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 08:02:41.401 - UploadersConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 08:02:41.406 - HotkeysConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 08:02:41.428 - HotkeysConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 08:02:41.788 - MainForm init finished
2016-06-09 08:02:41.867 - Startup time: 4483 ms
2016-06-09 08:02:41.872 - CommandLine: silent
2016-06-09 08:02:41.890 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2016-06-09 08:02:41.894 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2016-06-09 08:02:41.898 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2016-06-09 08:02:41.902 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2016-06-09 08:02:41.907 - HotkeyManager started
2016-06-09 08:02:41.911 - WatchFolderManager started
2016-06-09 20:03:40.646 - ApplicationConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:03:40.788 - ApplicationConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:03:40.793 - UploadersConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:03:40.850 - UploadersConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:03:40.856 - HotkeysConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:03:40.928 - HotkeysConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:03:40.941 - ShareX closing
2016-06-09 20:03:49.418 - Operating system: Microsoft Windows NT 10.0.14361.0
2016-06-09 20:03:49.425 - Personal path: C:\Users\jjrei\OneDrive\Documents\ShareX
2016-06-09 20:03:49.430 - Command line: "D:\ShareX\ShareX.exe"
2016-06-09 20:03:49.436 - ShareX 11.0 Release
2016-06-09 20:03:49.442 - ApplicationConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:03:49.841 - ApplicationConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:03:49.848 - UploadersConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:03:49.855 - MainForm init started
2016-06-09 20:03:49.998 - UploadersConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:03:50.004 - HotkeysConfig load started: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:03:50.026 - HotkeysConfig load finished: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:03:50.166 - MainForm init finished
2016-06-09 20:03:50.226 - Startup time: 876 ms
2016-06-09 20:03:50.249 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2016-06-09 20:03:50.254 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2016-06-09 20:03:50.258 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2016-06-09 20:03:50.262 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2016-06-09 20:03:50.266 - HotkeyManager started
2016-06-09 20:03:50.270 - WatchFolderManager started
2016-06-09 20:33:34.420 - ApplicationConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:33:34.420 - HotkeysConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:33:34.436 - UploadersConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:33:34.521 - UploadersConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:33:34.552 - HotkeysConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:33:34.588 - ApplicationConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:33:34.721 - Task in queue. Job: Job, Type: Image, Host: 
2016-06-09 20:33:34.721 - Task status: Preparing
2016-06-09 20:33:34.752 - Image saved to file: C:\Users\jjrei\OneDrive\Documents\ShareX\Screenshots\2016-06\2016-06-09_20-33-34.png
2016-06-09 20:33:34.768 - Task completed. Filename: 2016-06-09_20-33-34.png, Duration: 31 ms
2016-06-09 20:33:34.774 - UploadersConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:33:34.781 - ApplicationConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:33:34.787 - HotkeysConfig save started: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:33:34.792 - Unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadInfoParser.Parse(TaskInfo info, String pattern)
   at ShareX.TaskManager.task_TaskCompleted(WorkerTask task)
   at ShareX.WorkerTask.OnTaskCompleted()

ShareX 11.0 Release
2016-06-09 20:33:34.842 - UploadersConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\UploadersConfig.json
2016-06-09 20:33:34.873 - HotkeysConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\HotkeysConfig.json
2016-06-09 20:33:34.892 - ApplicationConfig save successful: C:\Users\jjrei\OneDrive\Documents\ShareX\ApplicationConfig.json
2016-06-09 20:33:40.515 - URL opened: https://github.com/ShareX/ShareX/issues
