### ISSUE TITLE
error after capture

### ISSUE THREAD

**Issue by Zivelz** [ShareX/ShareX#1605]
System.NullReferenceException: Object reference not set to an instance of an object.
 at ShareX.UploadInfoParser.Parse(TaskInfo info, String pattern)
 at ShareX.TaskManager.task_TaskCompleted(WorkerTask task)
 at ShareX.WorkerTask.OnTaskCompleted()

error with not uploaded options(just capture to clipboard)

when use Capture with upload, normally work.

using version Share X v11.0

**Comment by Jaex** [comment]
#1603
