### ISSUE TITLE
NullReferenceException on PrintScreen

### ISSUE THREAD

**Issue by kapitanov** [ShareX/ShareX#1611]
1. Press `Print Screen` key
2. An Error window pops up:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadInfoParser.Parse(TaskInfo info, String pattern)
   at ShareX.TaskManager.task_TaskCompleted(WorkerTask task)
   at ShareX.WorkerTask.OnTaskCompleted()

ShareX 11.0 Release
```
I've started to see this error right after updating to v11.0

Here are parameters that are passed into `UploadInfoParser.Parse()` (managed to capture it using debugger but I had no PDBs): 
```javascript

info = {
	"TaskSettings": {
		"Description": "",
		"Job": "ActiveWindow",
		"UseDefaultAfterCaptureJob": true,
		"AfterCaptureJob": 80,
		"UseDefaultAfterUploadJob": true,
		"AfterUploadJob": 8,
		"UseDefaultDestinations": true,
		"ImageDestination": 0,
		"ImageFileDestination": 0,
		"TextDestination": 0,
		"TextFileDestination": 0,
		"FileDestination": 0,
		"URLShortenerDestination": 0,
		"URLSharingServiceDestination": 1,
		"OverrideFTP": false,
		"FTPIndex": 0,
		"OverrideCustomUploader": false,
		"CustomUploaderIndex": 0,
		"UseDefaultGeneralSettings": true,
		"GeneralSettings": {
			"PlaySoundAfterCapture": true,
			"ShowAfterCaptureTasksForm": false,
			"ShowBeforeUploadForm": false,
			"PlaySoundAfterUpload": true,
			"PopUpNotification": 2,
			"ShowAfterUploadForm": false
		},
		"UseDefaultImageSettings": true,
		"ImageSettings": {
			"ImageFormat": 0,
			"ImageJPEGQuality": 90,
			"ImageGIFQuality": 0,
			"ImageSizeLimit": 1024,
			"ImageFormat2": 1,
			"FileExistAction": 0,
			"ImageEffects": [{
				"$type": "ShareX.ImageEffectsLib.Canvas, ShareX.ImageEffectsLib",
				"Margin": "0, 0, 0, 30",
				"Enabled": true
			},
			{
				"$type": "ShareX.ImageEffectsLib.DrawText, ShareX.ImageEffectsLib",
				"Placement": 1024,
				"Offset": "0, 0",
				"AutoHide": true,
				"Text": "getsharex.com",
				"TextFont": "Arial, 11.25pt",
				"TextColor": "White",
				"DrawTextShadow": true,
				"TextShadowColor": "Black",
				"TextShadowOffset": "-1, -1",
				"CornerRadius": 4,
				"BackgroundPadding": 5,
				"DrawBorder": true,
				"BorderColor": "Black",
				"DrawBackground": true,
				"BackgroundColor": "10, 110, 230",
				"UseGradient": true,
				"GradientType": 1,
				"BackgroundColor2": "0, 20, 40",
				"UseCustomGradient": true,
				"Gradient": {
					"Type": 1,
					"Colors": [{
						"Color": "68, 120, 194",
						"Location": 0.0
					},
					{
						"Color": "13, 58, 122",
						"Location": 50.0
					},
					{
						"Color": "6, 36, 78",
						"Location": 50.0
					},
					{
						"Color": "23, 89, 174",
						"Location": 100.0
					}],
					"IsValid": true
				},
				"Enabled": true
			}],
			"ShowImageEffectsWindowAfterCapture": false,
			"ImageEffectOnlyRegionCapture": false,
			"ThumbnailWidth": 200,
			"ThumbnailHeight": 0,
			"ThumbnailName": "-thumbnail",
			"ThumbnailCheckSize": false
		},
		"UseDefaultCaptureSettings": true,
		"CaptureSettings": {
			"ShowCursor": true,
			"CaptureTransparent": false,
			"CaptureShadow": true,
			"CaptureShadowOffset": 20,
			"CaptureClientArea": false,
			"IsDelayScreenshot": false,
			"DelayScreenshot": 2.0,
			"CaptureAutoHideTaskbar": false,
			"CaptureCustomRegion": "0, 0, 0, 0",
			"SurfaceOptions": {
				"ShowMenuTip": true,
				"AnnotationOptions": {
					"BorderColor": "Red",
					"BorderSize": 2,
					"FillColor": "0, 0, 0, 0",
					"RoundedRectangleRadius": 15,
					"TextOptions": {
						"Font": "Arial",
						"Size": 20,
						"Color": "White",
						"Bold": false,
						"Italic": false,
						"Underline": false,
						"AlignmentHorizontal": 1,
						"AlignmentVertical": 1,
						"Style": 0
					},
					"TextBorderColor": "White",
					"TextBorderSize": 0,
					"TextFillColor": "150, 0, 0, 0",
					"StepBorderColor": "White",
					"StepBorderSize": 2,
					"StepFillColor": "Red",
					"BlurRadius": 15,
					"PixelateSize": 7,
					"HighlightColor": "Yellow"
				},
				"QuickCrop": true,
				"AnnotationEnabled": true,
				"DetectWindows": true,
				"DetectControls": true,
				"ShowInfo": true,
				"UseCustomInfoText": false,
				"CustomInfoText": "X: $x, Y: $y\r\nR: $r, G: $g, B: $b\r\nHex: $hex",
				"ShowTips": false,
				"ShowMagnifier": true,
				"UseSquareMagnifier": false,
				"MagnifierPixelCount": 15,
				"MagnifierPixelSize": 10,
				"ShowCrosshair": true,
				"UseDimming": true,
				"ShowFPS": false,
				"MinMoveSpeed": 1,
				"MaxMoveSpeed": 5,
				"IsFixedSize": false,
				"FixedSize": "250, 250",
				"SnapDistance": 20,
				"SnapSizes": [{
					"Width": 426,
					"Height": 240
				},
				{
					"Width": 640,
					"Height": 360
				},
				{
					"Width": 854,
					"Height": 480
				},
				{
					"Width": 1280,
					"Height": 720
				},
				{
					"Width": 1920,
					"Height": 1080
				},
				{
					"Width": 2560,
					"Height": 1440
				},
				{
					"Width": 3840,
					"Height": 2160
				},
				{
					"Width": 800,
					"Height": 600
				},
				{
					"Width": 1024,
					"Height": 768
				},
				{
					"Width": 4096,
					"Height": 2160
				}]
			},
			"FFmpegOptions": {
				"OverrideCLIPath": false,
				"CLIPath": "ffmpeg.exe",
				"VideoSource": "GDI grab",
				"AudioSource": "None",
				"VideoCodec": 0,
				"AudioCodec": 0,
				"UserArgs": "",
				"UseCustomCommands": false,
				"CustomCommands": null,
				"ShowError": true,
				"x264_Preset": 2,
				"x264_CRF": 30,
				"VPx_bitrate": 1000,
				"XviD_qscale": 3,
				"GIFStatsMode": 0,
				"GIFDither": 5,
				"AAC_bitrate": 128,
				"Vorbis_qscale": 3,
				"MP3_qscale": 4,
				"FFmpegPath": "C:\\Program Files\\ShareX\\ffmpeg.exe",
				"Extension": "mp4",
				"IsSourceSelected": true,
				"IsVideoSourceSelected": true,
				"IsAudioSourceSelected": false
			},
			"ScreenRecordFPS": 20,
			"GIFFPS": 5,
			"GIFEncoding": 0,
			"ScreenRecordFixedDuration": false,
			"ScreenRecordDuration": 3.0,
			"ScreenRecordAutoStart": true,
			"ScreenRecordStartDelay": 0.5,
			"ScreenRecordShowCursor": true,
			"RunScreencastCLI": false,
			"VideoEncoderSelected": 0,
			"ScrollingCaptureOptions": {
				"TrimLeftEdge": 0,
				"TrimTopEdge": 0,
				"TrimRightEdge": 0,
				"TrimBottomEdge": 0,
				"CombineAdjustmentVertical": 0,
				"CombineAdjustmentLastVertical": 0,
				"IgnoreLast": 0,
				"ScrollMethod": 0,
				"StartDelay": 500,
				"ScrollDelay": 500,
				"MaximumScrollCount": 20,
				"StartSelectionAutomatically": true,
				"StartCaptureAutomatically": false,
				"ScrollTopMethodBeforeCapture": 0,
				"AutoDetectScrollEnd": true,
				"RemoveDuplicates": true,
				"AfterCaptureAutomaticallyCombine": true,
				"AutoUpload": false,
				"AutoClose": false
			}
		},
		"UseDefaultUploadSettings": true,
		"UploadSettings": {
			"UseCustomTimeZone": false,
			"CustomTimeZone": {
				"Id": "UTC",
				"DisplayName": "(UTC) Coordinated Universal Time",
				"StandardName": "Coordinated Universal Time",
				"DaylightName": "Coordinated Universal Time",
				"BaseUtcOffset": "00:00:00",
				"AdjustmentRules": null,
				"SupportsDaylightSavingTime": false
			},
			"NameFormatPattern": "%y-%mo-%d_%h-%mi-%s",
			"NameFormatPatternActiveWindow": "%pn_%y-%mo-%d_%h-%mi-%s",
			"RegionCaptureUseWindowPattern": true,
			"FileUploadUseNamePattern": false,
			"ClipboardUploadURLContents": false,
			"ClipboardUploadShortenURL": false,
			"ClipboardUploadShareURL": false,
			"ClipboardUploadAutoIndexFolder": false
		},
		"UseDefaultActions": true,
		"ExternalPrograms": [{
			"IsActive": false,
			"HiddenWindow": false,
			"Name": "Paint",
			"Path": "C:\\WINDOWS\\system32\\mspaint.exe",
			"Args": "%input",
			"Extensions": null,
			"OutputExtension": null
		}],
		"UseDefaultToolsSettings": true,
		"ToolsSettings": {
			"IndexerSettings": {
				"Output": 1,
				"SkipHiddenFolders": true,
				"SkipHiddenFiles": true,
				"MaxDepthLevel": 0,
				"ShowSizeInfo": true,
				"AddFooter": true,
				"IndentationText": "|___",
				"AddEmptyLineAfterFolders": false,
				"UseCustomCSSFile": false,
				"CustomCSSFilePath": "",
				"UseAttribute": true,
				"CreateParseableJson": true
			},
			"ImageCombinerOptions": {
				"Orientation": 1,
				"Space": 0
			},
			"VideoThumbnailOptions": {
				"DefaultOutputDirectory": null,
				"LastVideoPath": null,
				"OutputLocation": 0,
				"CustomOutputDirectory": "",
				"ImageFormat": 0,
				"ThumbnailCount": 9,
				"FilenameSuffix": "_Thumbnail",
				"RandomFrame": false,
				"UploadThumbnails": true,
				"KeepScreenshots": false,
				"OpenDirectory": false,
				"MaxThumbnailWidth": 512,
				"CombineScreenshots": true,
				"Padding": 10,
				"Spacing": 10,
				"ColumnCount": 3,
				"AddVideoInfo": true,
				"AddTimestamp": true,
				"DrawShadow": true,
				"DrawBorder": true
			}
		},
		"UseDefaultAdvancedSettings": true,
		"AdvancedSettings": {
			"ProcessImagesDuringFileUpload": false,
			"ProcessImagesDuringClipboardUpload": false,
			"UseAfterCaptureTasksDuringFileUpload": true,
			"TextTaskSaveAsFile": true,
			"AutoClearClipboard": false,
			"UseCustomCaptureSound": false,
			"CustomCaptureSoundPath": "",
			"SpeechCapture": "",
			"UseCustomTaskCompletedSound": false,
			"CustomTaskCompletedSoundPath": "",
			"SpeechTaskCompleted": "",
			"UseCustomErrorSound": false,
			"CustomErrorSoundPath": "",
			"CapturePath": null,
			"ImageExtensions": ["jpg",
			"jpeg",
			"png",
			"gif",
			"bmp",
			"ico",
			"tif",
			"tiff"],
			"EarlyCopyURL": false,
			"TextExtensions": ["txt",
			"log",
			"nfo",
			"c",
			"cpp",
			"cc",
			"cxx",
			"h",
			"hpp",
			"hxx",
			"cs",
			"vb",
			"html",
			"htm",
			"xhtml",
			"xht",
			"xml",
			"css",
			"js",
			"php",
			"bat",
			"java",
			"lua",
			"py",
			"pl",
			"cfg",
			"ini"],
			"ResultForceHTTPS": false,
			"ClipboardContentFormat": "$result",
			"BalloonTipContentFormat": "$result",
			"OpenURLFormat": "$result",
			"AutoShortenURLLength": 0,
			"ToastWindowDuration": 3.0,
			"ToastWindowFadeDuration": 1.0,
			"ToastWindowPlacement": 1024,
			"ToastWindowClickAction": 5,
			"ToastWindowSize": "400, 300",
			"AutoCloseAfterUploadForm": false,
			"DisableNotifications": false,
			"TextFileExtension": "txt",
			"TextFormat": "text",
			"TextCustom": "",
			"TextCustomEncodeInput": true,
			"NamePatternMaxLength": 100,
			"NamePatternMaxTitleLength": 50,
			"ScreenColorPickerFormat": "$r, $g, $b"
		},
		"WatchFolderEnabled": false,
		"WatchFolderList": [],
		"IsUsingDefaultSettings": true,
		"CaptureFolder": "C:\\Users\\Albert\\Documents\\ShareX\\Screenshots\\2016-06"
	},
	"Status": "Done",
	"Job": 0,
	"IsUploadJob": false,
	"Progress": null,
	"FilePath": "C:\\Users\\Albert\\Documents\\ShareX\\Screenshots\\2016-06\\ApplicationFrameHost_2016-06-10_12-39-01.png",
	"FileName": "ApplicationFrameHost_2016-06-10_12-39-01.png",
	"ThumbnailFilePath": null,
	"DataType": 2,
	"UploadDestination": 2,
	"UploaderHost": "",
	"TaskStartTime": "2016-06-10T09:39:01.9526232Z",
	"TaskEndTime": "2016-06-10T09:39:02.0616228Z",
	"TaskDuration": "00:00:00.1089996",
	"UploadDuration": null,
	"Result": {
		"URL": null,
		"ThumbnailURL": null,
		"DeletionURL": null,
		"ShortenedURL": null,
		"IsSuccess": false,
		"Response": null,
		"Errors": [],
		"IsURLExpected": false,
		"IsError": false
	}
}


pattern = "$result"
```

**Comment by Jaex** [comment]
#1603 please update ShareX.

**Comment by kapitanov** [comment]
Thanks!
