### ISSUE TITLE
Can't open new version (11.0)

### ISSUE THREAD

**Issue by jblanteigne** [ShareX/ShareX#1613]
Here's the message I got in the error box.

System.TypeLoadException: Could not load type 'ShareX.UploadersLib.OtherServices.OCRSpaceLanguages' from assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0 Release

===
and here's the log file (only the stuff from today):

2016-06-10 11:46:51.391 - Unhandled exception:
System.TypeLoadException: Could not load type 'ShareX.UploadersLib.OtherServices.OCRSpaceLanguages' from assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0 Release
2016-06-10 11:46:58.466 - ShareX closing. Reason: Unhandled exception
2016-06-10 13:32:32.926 - Unhandled exception:
System.TypeLoadException: Could not load type 'ShareX.UploadersLib.OtherServices.OCRSpaceLanguages' from assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0 Release
2016-06-10 13:32:34.554 - ShareX continue.
2016-06-10 13:32:40.457 - Unhandled exception:
System.TypeLoadException: Could not load type 'ShareX.UploadersLib.OtherServices.OCRSpaceLanguages' from assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0 Release
2016-06-10 13:32:42.483 - URL opened: https://github.com/ShareX/ShareX/issues
2016-06-10 13:32:52.042 - ShareX continue.
2016-06-10 13:33:06.512 - Unhandled exception:
System.TypeLoadException: Could not load type 'ShareX.UploadersLib.OtherServices.OCRSpaceLanguages' from assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0 Release

**Comment by campbeb** [comment]
Can you check and make sure there is not an old version of the UploadersLib on your computer? The file is named ShareX.UploadersLib.dll

Check in the folder path `C:\Windows\Microsoft.NET\assembly` and `c:\windows\assembly`

The only one should be the one in your ShareX folder.

**Comment by Jaex** [comment]
Try reinstalling ShareX.

**Comment by jblanteigne** [comment]
I ended up installing a previous version and now after suggesting it updates to the latest version it works with 11.0.1.

ShareX is an amazing tool btw.

Thanks.
