### ISSUE TITLE
ShareX version 11.0.1 launch crash

### ISSUE THREAD

**Issue by robflop** [ShareX/ShareX#1615]
I'm getting a crash when trying to open the latest ShareX. (Sadly it only outputs the error in german).

System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.BadImageFormatException: Die Datei oder Assembly "ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
   bei ShareX.TaskSettingsTools..ctor()
   bei ShareX.TaskSettings..ctor()
   bei ShareX.ApplicationConfig..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance[T]()
   bei ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   bei ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   bei ShareX.Program.LoadProgramSettings()
   bei ShareX.Program.Run()
   bei ShareX.Program.Main(String[] args)

ShareX 11.0.1 Release

**Comment by Jaex** [comment]
This happens when library is corrupt. Please reinstall ShareX.

**Comment by robflop** [comment]
That fixed it.

**Comment by Jaex** [comment]
I'm never gonna figure out how library can get corrupt randomly for few people :(

**Comment by progmars** [comment]
Yep, I too had the same issue - at first ShareX update came and installed ok. Then a Windows 10 update came and the pc rebooted. After that, I could not launch ShareX anymore, the same `The module was expected to contain an assembly manifest.` error.

**Comment by DBJDBJ** [comment]
### @Jaex  said: "I'm never gonna figure out how library can get corrupt randomly for few people :("
### Well ... what is "few", which library and can it be reproduced now? Different random libs? Same lib?
### I have/had the same issue. Few months after it was first reported.

**Comment by Jaex** [comment]
"few" means it is lesser than 0.01% I believe. Also it mainly happens to people when computer startup. So I suspect it happens after their PC shutdown non clean (blue screen, electricity issue etc.) which causing library to be corrupt. Library is random it not to do with library itself.

**Comment by Kane-Nexus** [comment]
More information to help diagnose this issue

Popup Dialog

`System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)`

ShareX-Log-2017-02.txt

`2017-02-01 15:12:37.268 - ShareX 11.5
2017-02-01 15:12:37.278 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-01 15:12:37.279 - Build: Steam
2017-02-01 15:12:37.280 - Operating system: Windows 10 Pro Insider Preview
2017-02-01 15:12:37.280 - Flags: SilentRun
2017-02-01 15:12:37.282 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-01 15:12:37.463 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-01 15:13:06.928 - ShareX continue.
2017-02-02 16:34:25.898 - ShareX 11.5
2017-02-02 16:34:25.958 - Flags: SilentRun
2017-02-02 16:34:25.959 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-02 16:34:25.960 - Operating system: Windows 10 Pro Insider Preview
2017-02-02 16:34:25.960 - Build: Steam
2017-02-02 16:34:25.961 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-02 16:34:26.069 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-02 16:34:29.479 - ShareX closing. Reason: Unhandled exception
2017-02-03 08:17:46.864 - ShareX 11.5
2017-02-03 08:17:47.047 - Build: Steam
2017-02-03 08:17:47.047 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-03 08:17:47.069 - Operating system: Windows 10 Pro Insider Preview
2017-02-03 08:17:47.073 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-03 08:17:47.103 - Flags: SilentRun
2017-02-03 08:17:47.306 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-03 08:17:57.186 - ShareX closing. Reason: Unhandled exception
2017-02-03 18:00:56.572 - ShareX 11.5
2017-02-03 18:00:56.573 - Flags: SilentRun
2017-02-03 18:00:56.573 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-03 18:00:56.574 - Build: Steam
2017-02-03 18:00:56.574 - Operating system: Windows 10 Pro Insider Preview
2017-02-03 18:00:56.575 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-03 18:00:56.712 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-03 18:01:58.631 - ShareX continue.
2017-02-03 19:10:02.475 - ShareX 11.5
2017-02-03 19:10:02.477 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-03 19:10:02.478 - Build: Steam
2017-02-03 19:10:02.479 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" 
2017-02-03 19:10:02.480 - Operating system: Windows 10 Pro Insider Preview
2017-02-03 19:10:02.621 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-03 19:10:06.162 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2017-02-03 19:10:29.442 - ShareX closing. Reason: Unhandled exception
2017-02-05 01:46:40.925 - ShareX 11.5
2017-02-05 01:46:41.386 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-05 01:46:41.387 - Build: Steam
2017-02-05 01:46:41.387 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-05 01:46:41.387 - Operating system: Windows 10 Pro Insider Preview
2017-02-05 01:46:41.388 - Flags: SilentRun
2017-02-05 01:46:41.388 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-05 01:46:52.651 - ShareX continue.
2017-02-05 20:14:03.336 - ShareX 11.5
2017-02-05 20:14:03.337 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" 
2017-02-05 20:14:03.337 - Operating system: Windows 10 Pro Insider Preview
2017-02-05 20:14:03.338 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-05 20:14:03.338 - Build: Steam
2017-02-05 20:14:03.458 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-05 20:14:06.326 - ShareX continue.
2017-02-06 01:53:17.858 - ShareX 11.5
2017-02-06 01:53:18.417 - Operating system: Windows 10 Pro Insider Preview
2017-02-06 01:53:18.417 - Flags: SilentRun
2017-02-06 01:53:18.418 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-06 01:53:18.418 - Build: Steam
2017-02-06 01:53:18.418 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-06 01:53:18.419 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-06 01:53:23.426 - ShareX closing. Reason: Unhandled exception
2017-02-06 07:14:11.108 - ShareX 11.5
2017-02-06 07:14:11.949 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-06 07:14:11.949 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-06 07:14:11.950 - Build: Steam
2017-02-06 07:14:11.951 - Operating system: Windows 10 Pro Insider Preview
2017-02-06 07:14:11.952 - Flags: SilentRun
2017-02-06 07:14:11.953 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-06 07:14:18.403 - ShareX closing. Reason: Unhandled exception
2017-02-06 07:47:28.385 - ShareX 11.5
2017-02-06 07:47:28.386 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-06 07:47:28.386 - Operating system: Windows 10 Pro Insider Preview
2017-02-06 07:47:28.387 - Build: Steam
2017-02-06 07:47:28.392 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" 
2017-02-06 07:47:28.536 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-06 07:47:31.109 - ShareX closing. Reason: Unhandled exception
2017-02-06 08:26:52.387 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-06 08:26:52.752 - Build: Steam
2017-02-06 08:26:52.752 - Operating system: Windows 10 Pro Insider Preview
2017-02-06 08:26:52.752 - ShareX 11.5
2017-02-06 08:26:52.753 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-06 08:26:52.753 - Flags: SilentRun
2017-02-06 08:26:52.754 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-06 08:27:24.563 - ShareX closing. Reason: Unhandled exception
2017-02-06 08:36:37.740 - ShareX 11.5
2017-02-06 08:36:38.363 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-06 08:36:38.363 - Build: Steam
2017-02-06 08:36:38.363 - Operating system: Windows 10 Pro Insider Preview
2017-02-06 08:36:38.364 - Flags: SilentRun
2017-02-06 08:36:38.364 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-06 08:36:38.364 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-06 08:36:44.208 - ShareX closing. Reason: Unhandled exception
2017-02-08 08:57:47.989 - ShareX 11.5
2017-02-08 08:57:47.990 - Operating system: Windows 10 Pro Insider Preview
2017-02-08 08:57:47.990 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" -silent
2017-02-08 08:57:47.991 - Flags: SilentRun
2017-02-08 08:57:47.991 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-08 08:57:47.992 - Build: Steam
2017-02-08 08:57:48.119 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-08 08:57:55.694 - ShareX closing. Reason: Unhandled exception
2017-02-08 09:26:04.722 - ShareX 11.5
2017-02-08 09:26:04.723 - Operating system: Windows 10 Pro Insider Preview
2017-02-08 09:26:04.723 - Personal path: C:\Users\Kane\Documents\ShareX
2017-02-08 09:26:04.724 - Command line: "E:\Steam\steamapps\common\ShareX\ShareX\ShareX.exe" 
2017-02-08 09:26:04.728 - Build: Steam
2017-02-08 09:26:04.924 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


ShareX 11.5 (Steam)
2017-02-08 09:28:55.186 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
`

**Comment by ArsenArsen** [comment]
Perhaps a bad installer checksum? 

I'd recommend to add an issue template to .github that tells the user to attempt reinstalling first. And some other common possible fixes.

**Comment by Jaex** [comment]
It is not about installer, it works after install but when people restart their pc once then they get this error. It even happens to Steam build which shows it is not about download or installer. So I have no clue whats going on.

**Comment by Scrxtchy** [comment]
it may only be fixed if we know how to replicate it without fail,
then hopefully it can be caught and prevented

**Comment by ArsenArsen** [comment]
That's what I am saying @Jaex, but telling people to attempt to fully reinstall as a common fix might be worth it. It is obviously related to post-install file corruption, so that would probably do the trick in alot of cases.
