### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by OMGasm** [ShareX/ShareX#1620]
Out of memory exception when using `capture region (light)` with a bounding box of approximately 1x1 px
[video of error reproduction](https://github.com/ShareX/ShareX/files/310147/video.zip)
Running Win10, also noticed it still does it in 11.0.1
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawRectangle(Pen pen, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.DrawRectangle(Pen pen, Rectangle rect)
   at ShareX.HelpersLib.GraphicsExtensions.DrawRectangleProper(Graphics g, Pen pen, Rectangle rect)
   at ShareX.ScreenCaptureLib.RectangleLight.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.9.1 Release
```

**Comment by Jaex** [comment]
Was this issue always exist? How nobody not reported it before.

**Comment by OMGasm** [comment]
Maybe no one had it before. I was also thinking about how long it might have existed, lol...

**Comment by Jaex** [comment]
I can't figure out why it gives this error because normally drawing rectangle with 1 width 1 height not gives any error. Also transparent rectangle capture using same drawing methods and pen style and not gives error in 1x1 so this is weird.
