### ISSUE TITLE
Exception "Could not load file or assembly ShareX.IndexerLib" during start

### ISSUE THREAD

**Issue by jeanspector** [ShareX/ShareX#1622]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0.1 Release
```
[ShareX-Log-2016-06.txt](https://github.com/ShareX/ShareX/files/310175/ShareX-Log-2016-06.txt)

**Comment by Jaex** [comment]
#1615

**Comment by jeanspector** [comment]
Ironically, I've searched for the exception before reporting the bug and couldn't find it.
That's because #1615 was reported in German :-(
