### ISSUE TITLE
Load sharex.screencapturelib.freehandregion

### ISSUE THREAD

**Issue by adr29truck** [ShareX/ShareX#1626]
```
System.TypeLoadException: Could not load type 'ShareX.ScreenCaptureLib.FreeHandRegion' from assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShareX.MainForm.CaptureRegion(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.MainForm.HandleHotkeys(HotkeySettings hotkeySetting)
   at ShareX.HotkeyManager.OnHotkeyTrigger(HotkeySettings hotkeySetting)
   at ShareX.HotkeyManager.hotkeyForm_HotkeyPress(UInt16 id, Keys key, Modifiers modifier)
   at ShareX.HotkeyForm.OnKeyPressed(UInt16 id, Keys key, Modifiers modifier)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.9.1 Release
```

Unable to install updates and take screen shots

**Comment by Jaex** [comment]
Downloaded latest version from web site.

**Comment by Jaex** [comment]
#1613
