### ISSUE TITLE
custom uploader fails with SSL

### ISSUE THREAD

**Issue by Phoenix09** [ShareX/ShareX#1636]
```Message:
The underlying connection was closed: An unexpected error occurred on a send.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

it works fine in ShareX without SSL, my firewall is disabled, and the server has a valid Let's Encrypt certificate and works fine in Firefox and Chrome

I am using v11.0.1 on Windows 8.1 64 bit

**Comment by Jaex** [comment]
Is it TLS 1.2? Are you using custom uploader?

**Comment by Phoenix09** [comment]
yes and yes

**Comment by Jaex** [comment]
.NET framework 4.0 not supports TLS 1.2 but if you have .NET 4.5 installed you can workaround like this:

http://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5/34009938#34009938

I tested this method in one custom uploader which was requiring TLS 1.2 and it worked.
