### ISSUE TITLE
ShareX not starting, throwing an error.

### ISSUE THREAD

**Issue by Jolo248** [ShareX/ShareX#1642]
Hello,
When I try to open ShareX I get the following error.
This error is recent, it never happened before:

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0.1 Release`

Thank You,
Jolo248

**Comment by Jaex** [comment]
#1615

**Comment by Jolo248** [comment]
Oh sorry for the duplicate! and thanks for the link to the thread!
Reinstalling fixed it!

Thank you!

**Comment by aniljadhavmca** [comment]
I was also getting the same error. And also found the solution for this issue!

Please refer following steps:
- Right click on sharX icon
- Click on Application settings menu - http://goo.gl/6ZOiE1
- Now click on proxy settings - http://goo.gl/ISmie7
- And select automatic proxy configuration
