### ISSUE TITLE
Fail to write to clipboard (at all)

### ISSUE THREAD

**Issue by PossiblyKris** [ShareX/ShareX#1660]
```System.Runtime.InteropServices.ExternalException (0x80004005): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyText(String text)```

Any attempt to write to clipboard (url, image, text) fails.

This started happening suddenly after switching destinations (imgur -> vgy.me), which I often do, so I don't see how this would have caused it. I have tried to switch back to imgur, but it still happens.
Other than tampering with settings *after* the error, I have not touched the settings in the last couple days. 
I screenshot a lot, and it was working fine earlier today.
Any help would be appreciated.

**Comment by Jaex** [comment]
Something in your computer must be causing this, not to do with ShareX.

**Comment by PossiblyKris** [comment]
Yikes. Any idea what it could be?

**Comment by Jaex** [comment]
No idea, nobody reported this issue before.

**Comment by PossiblyKris** [comment]
Whelp. I will try a reinstall then.

**Comment by PossiblyKris** [comment]
@Jaex before reinstalling I went ahead and rebooted. Seems like it was just windows being windows, and it works fine now. Thank you for your time, and sorry to bother.
