### ISSUE TITLE
Uploading image to SomeImage isn't working

### ISSUE THREAD

**Issue by PepinCZ** [ShareX/ShareX#1666]
Hello,
I'm getting this error message everytime I'm trying to upload image with SomeImage:

```
The remote server returned an error: (500) Internal Server Error.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

**Comment by Jaex** [comment]
`(500) Internal Server Error` means problem in their end. I tried uploading now it uploaded without problem.

**Comment by PepinCZ** [comment]
@Jaex I even tried the custom script, with the test button it works fine, but when I'm trying to upload with this script i get exact error.
I'm trying to upload 17 MB GIF, which should be ok because they have 25 MB limit.

**Comment by Jaex** [comment]
I'm not owner of that website. If they give error when big size gif uploaded what can I do?
