### ISSUE TITLE
Imgur upload fails frequently.

### ISSUE THREAD

**Issue by otaru1921** [ShareX/ShareX#1689]
2016-07-02 22:10:36.514 - Task in queue. Job: Job, Type: Image, Host: Imgur
2016-07-02 22:10:36.525 - Task status: Preparing
2016-07-02 22:10:36.537 - Upload started. Filename: 2016-07-02_22-10-36.png
2016-07-02 22:10:58.296 - AddWebError(): Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2016-07-02 22:10:58.304 - Upload failed. Retrying upload.
2016-07-02 22:11:19.008 - AddWebError(): Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2016-07-02 22:11:19.017 - Task failed. Filename: 2016-07-02_22-10-36.png, Errors:
Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2016-07-02 22:11:19.042 - ApplicationConfig save started: C:\Users\otaru\Documents\ShareX\ApplicationConfig.json
2016-07-02 22:11:19.054 - UploadersConfig save started: C:\Users\otaru\Documents\ShareX\UploadersConfig.json
2016-07-02 22:11:19.063 - HotkeysConfig save started: C:\Users\otaru\Documents\ShareX\HotkeysConfig.json
2016-07-02 22:11:19.138 - UploadersConfig save successful: C:\Users\otaru\Documents\ShareX\UploadersConfig.json
2016-07-02 22:11:19.200 - HotkeysConfig save successful: C:\Users\otaru\Documents\ShareX\HotkeysConfig.json
2016-07-02 22:11:19.234 - ApplicationConfig save successful: C:\Users\otaru\Documents\ShareX\ApplicationConfig.json
2016-07-02 22:11:49.508 - URL opened: https://github.com/ShareX/ShareX/graphs/contributors
2016-07-02 22:13:14.892 - Task in queue. Job: FileUpload, Type: Image, Host: Imgur
2016-07-02 22:13:14.956 - Task status: Preparing
2016-07-02 22:13:14.966 - Upload started. Filename: dota2_2016-07-02_22-10-35.png, Filepath: K:\Screenshots\Screenshots\2016-06\2016-07\dota2_2016-07-02_22-10-35.png
2016-07-02 22:13:34.300 - AddWebError(): Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2016-07-02 22:13:34.311 - Upload failed. Retrying upload.
2016-07-02 22:13:55.270 - AddWebError(): Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2016-07-02 22:13:55.288 - Task failed. Filename: dota2_2016-07-02_22-10-35.png, Errors:
Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2016-07-02 22:13:55.319 - ApplicationConfig save started: C:\Users\otaru\Documents\ShareX\ApplicationConfig.json
2016-07-02 22:13:55.344 - UploadersConfig save started: C:\Users\otaru\Documents\ShareX\UploadersConfig.json
2016-07-02 22:13:55.371 - HotkeysConfig save started: C:\Users\otaru\Documents\ShareX\HotkeysConfig.json
2016-07-02 22:13:55.433 - UploadersConfig save successful: C:\Users\otaru\Documents\ShareX\UploadersConfig.json
2016-07-02 22:13:55.447 - HotkeysConfig save successful: C:\Users\otaru\Documents\ShareX\HotkeysConfig.json
2016-07-02 22:13:55.475 - ApplicationConfig save successful: C:\Users\otaru\Documents\ShareX\ApplicationConfig.json

**Comment by LuqJensen** [comment]
Im getting exactly the same, very often...

Message:
Der kunne ikke skrives data til transportforbindelsen: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært.

StackTrace:
   ved System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   ved System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   ved System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   ved System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   ved System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   ved System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   ved ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   ved ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

Imgur is online as of writing this message yet after repeatedly trying a 100 times i still cannot upload

**Comment by Jaex** [comment]
Imgur returns:

`{"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":500}`
