### ISSUE TITLE
Exception has been thrown by the target of an invocation - argumentException

### ISSUE THREAD

**Issue by penous** [ShareX/ShareX#1695]
```
System.Reflection.TargetInvocationException:` Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Font 'Arial' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObject(Int32 pos)
   at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   at ShareX.HelpersLib.MyPictureBox..ctor()
   at ShareX.MainForm.InitializeComponent()
   at ShareX.MainForm.InitializeControls()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.0.1 Release
```

i get this everytime i try to launch ShareX. it just started happening one day. i've reinstalled 3 times already and it still happens.

Thanks

**Comment by Jaex** [comment]
#374

**Comment by penous** [comment]
i checked my fonts, i reset my fonts, i redownloaded my fonts. i still get the same error. so i'm inclined to believe the font is not whats causing this.

**Comment by Jaex** [comment]
Your error tells: `Font 'Arial' does not support style 'Regular'.`

So it is to do with font.
