### ISSUE TITLE
Uploading GIF - Unable to write data to the transport connection

### ISSUE THREAD

**Issue by NotTrying** [ShareX/ShareX#1706]
Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by NotTrying** [comment]
On close program and re-launch then re-attempt upload it always works..  But never straight after capturing the GIF will it allow upload.

**Comment by Jaex** [comment]
You don't write which destination you trying to upload. If it is Imgur then it was giving this error to me right now:

`{"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":500}`
