### ISSUE TITLE
Crash when opening release 11.1

### ISSUE THREAD

**Issue by ErikBleifield** [ShareX/ShareX#1715]
I am getting this exception when I open release 11.1 - which installed itself this morning:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)

How do I revert to a previous release?

**Comment by dannoe** [comment]
#1615

**Comment by ErikBleifield** [comment]
Uninstall and reinstall indeed fixed the issue.

**Comment by Jaex** [comment]
Is this issue happens right after update install?

**Comment by ErikBleifield** [comment]
Yes - right after the update install.

**Comment by Jaex** [comment]
Because few people reported that right after update ShareX was working but when they reopened it (like after Windows restart), it was giving error.

**Comment by ErikBleifield** [comment]
Now that you mention it, it was right after I had restarted windows.
