### ISSUE TITLE
Unable to open task settings.

### ISSUE THREAD

**Issue by Xayzel** [ShareX/ShareX#1724]
When attempting to open task settings, the following error box appears:

```
System.ArgumentOutOfRangeException: Value of '41' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at ShareX.TaskSettingsForm..ctor(TaskSettings hotkeySetting, Boolean isDefault)
   at ShareX.MainForm.tsbTaskSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.1 (Release)
```

**Comment by dannoe** [comment]
see #1350

**Comment by Xayzel** [comment]
Where do I find the config/json file? Sorry for the dumb question, just really can't find it.

**Comment by Jaex** [comment]
Documents\ShareX\ApplicationConfig.json
