### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by mitch619911** [ShareX/ShareX#1771]
`System.Net.FtpClient.FtpCommandException: Disk full - please upload later
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)`
Thats the error I get when I try to screenshot/upload anything to my server, and im sure there is space for stuff.
Any help?

**Comment by Jaex** [comment]
Your server returns "Disk full" message. So problem in your end.
