### ISSUE TITLE
Chevereto support broke..

### ISSUE THREAD

**Issue by ne0ark** [ShareX/ShareX#1813]
It seems like chevereto support broke in last version:

`
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Chevereto.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)`

**Comment by Jaex** [comment]
Nothing changed in Chevereto codes and it uploads in my test now.

**Comment by Jaex** [comment]
But if you gave your web site with api key I could test your web site and give more readable error from that invalid response.

**Comment by ne0ark** [comment]
This was resolved. There is a bug with chevereto that was causing this error.

**Comment by Jaex** [comment]
How you resolved it? Because this issue looks #1849 same too.

**Comment by ne0ark** [comment]
https://chevereto.com/community/threads/api-url-enable-consent-screen.7754/

It seems like when consent screen is enabled. It also shows up on api URL. Admin has to disable consent screen.
