### ISSUE TITLE
Just a bug report... thing

### ISSUE THREAD

**Issue by Nit-Pick** [ShareX/ShareX#1834]
I don't know if this will help or not but ShareX is working fine right now it just had an "Illigal character paths" thing.

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at ShareX.RecentTask.get_FileName()
   at ShareX.WorkerTask.CreateHistoryTask(RecentTask recentTask)
   at ShareX.TaskManager.AddRecentTasksToMainWindow()
   at ShareX.RecentTaskManager.UpdateMainWindowList()
   at ShareX.RecentTaskManager.InitItems()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 10.8 Release

I was going to launch the application to see if it needs an update. If this bug is the case of an older version then my problem _should_ be fixed right?

**Comment by Jaex** [comment]
WTF "ShareX 10.8 Release" ?
