### ISSUE TITLE
Exception when uploading to chevereto 3.8.3

### ISSUE THREAD

**Issue by thoaimedia** [ShareX/ShareX#1849]
I meet this error when uploading image to http://photos.toiyeucontrai.com
`2016-08-29 02:26:11.332 - Task failed. Filename: Baker Twins (0001).jpg, Errors:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Chevereto.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)`

**Comment by Jaex** [comment]
Your issue is this I think: https://chevereto.com/community/threads/api-url-enable-consent-screen.7754/
Which is not to do with ShareX.
