### ISSUE TITLE
ShareX: Cannot access a disposed object. Object name: 'MainForm'.

### ISSUE THREAD

**Issue by thezoggy** [ShareX/ShareX#1856]
app froze after recent upgrade, win7

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MainForm'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at ShareX.Program.SingleInstanceCallback(Object sender, InstanceCallbackEventArgs args)
   at ShareX.HelpersLib.ApplicationInstanceManager.WaitOrTimerCallback(Object state, Boolean timedOut)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

ShareX 11.1 (Release)
```

**Comment by thezoggy** [comment]
looks like the bug never allowed it to upgrade, see the workaround on the site. upgraded to 11.2.1.
