### ISSUE TITLE
The invoked member is not supported in a dynamic assembly 

### ISSUE THREAD

**Issue by Permik** [ShareX/ShareX#1860]
How to reproduce:
1. Open main window
2. Go to Debug -> Debug log....
3. Press "Loaded assemblies"
4. Profit!

Tested on: Win 7 (64-bit) & Win 10 (64-bit)

The produced error:

```
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at ShareX.HelpersLib.DebugForm.btnLoadedAssemblies_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.2.1 (Release)

```

Edit: After a while ShareX crashed and seemed to fix itself after restart.

**Comment by Jaex** [comment]
This is weird I can't reproduce it when I click "Loaded assemblies".

**Comment by TNTUP** [comment]
Happens to me too 
![ShareX](http://i.qcfb.ca/201609202065513.png)
