### ISSUE TITLE
Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Alpha4993** [ShareX/ShareX#1865]
2016-09-01 12:57:45.698 - ShareX 11.1
2016-09-01 12:57:45.726 - Personal path: C:\Users\Hugh\Documents\ShareX
2016-09-01 12:57:45.734 - Operating system: Windows 10 Pro N
2016-09-01 12:57:45.738 - Build: Release
2016-09-01 12:57:45.743 - Command line: "E:\Program Index\puush\ShareX\ShareX.exe" -silent
2016-09-01 12:57:45.749 - Flags: SilentRun, PuushMode
2016-09-01 12:57:45.803 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json
2016-09-01 12:57:46.241 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-01 12:57:46.252 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak
2016-09-01 12:57:46.261 - ApplicationConfig not found. Loading new instance.
2016-09-01 12:57:46.273 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-01 12:57:46.429 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)
2016-09-01 12:57:49.742 - ShareX continue.
2016-09-01 19:41:34.398 - ShareX 11.1
2016-09-01 19:41:34.415 - Build: Release
2016-09-01 19:41:34.421 - Command line: "E:\Program Index\puush\ShareX\ShareX.exe" -silent
2016-09-01 19:41:34.425 - Personal path: C:\Users\Hugh\Documents\ShareX
2016-09-01 19:41:34.429 - Operating system: Windows 10 Pro N
2016-09-01 19:41:34.433 - Flags: SilentRun, PuushMode
2016-09-01 19:41:34.599 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json
2016-09-01 19:41:35.264 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-01 19:41:35.268 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak
2016-09-01 19:41:35.275 - ApplicationConfig not found. Loading new instance.
2016-09-01 19:41:35.280 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-01 19:41:35.669 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)
2016-09-01 19:41:41.366 - ShareX continue.
2016-09-02 18:55:53.989 - Build: Release
2016-09-02 18:55:53.998 - Personal path: C:\Users\Hugh\Documents\ShareX
2016-09-02 18:55:54.003 - Command line: "E:\Program Index\puush\ShareX\ShareX.exe" -silent
2016-09-02 18:55:54.017 - Operating system: Windows 10 Pro N
2016-09-02 18:55:54.021 - ShareX 11.1
2016-09-02 18:55:54.025 - Flags: SilentRun, PuushMode
2016-09-02 18:55:54.102 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json
2016-09-02 18:55:54.636 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 18:55:54.642 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak
2016-09-02 18:55:54.647 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 18:55:54.651 - ApplicationConfig not found. Loading new instance.
2016-09-02 18:55:54.750 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)
2016-09-02 18:56:08.023 - ShareX continue.
2016-09-02 19:26:17.353 - Personal path: C:\Users\Hugh\Documents\ShareX
2016-09-02 19:26:17.358 - Build: Release
2016-09-02 19:26:17.364 - Command line: "E:\Program Index\puush\ShareX\ShareX.exe" "C:\Users\Hugh\Desktop\leftEye1.png"
2016-09-02 19:26:17.369 - ShareX 11.1
2016-09-02 19:26:17.373 - Operating system: Windows 10 Pro N
2016-09-02 19:26:17.377 - Flags: PuushMode
2016-09-02 19:26:17.382 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json
2016-09-02 19:26:17.500 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 19:26:17.505 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak
2016-09-02 19:26:17.511 - ApplicationConfig not found. Loading new instance.
2016-09-02 19:26:17.515 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 19:26:17.525 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)
2016-09-02 19:26:19.054 - ShareX continue.
2016-09-02 19:26:48.109 - ShareX 11.1
2016-09-02 19:26:48.113 - Build: Release
2016-09-02 19:26:48.117 - Command line: "E:\Program Index\puush\ShareX\ShareX.exe" "C:\Users\Hugh\Desktop\leftEye1.png"
2016-09-02 19:26:48.121 - Operating system: Windows 10 Pro N
2016-09-02 19:26:48.125 - Personal path: C:\Users\Hugh\Documents\ShareX
2016-09-02 19:26:48.129 - Flags: PuushMode
2016-09-02 19:26:48.133 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json
2016-09-02 19:26:48.245 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 19:26:48.249 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 19:26:48.254 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak
2016-09-02 19:26:48.257 - ApplicationConfig not found. Loading new instance.
2016-09-02 19:26:48.266 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)
2016-09-02 19:27:28.658 - ShareX continue.
2016-09-02 19:27:37.006 - ShareX 11.1
2016-09-02 19:27:37.011 - Build: Release
2016-09-02 19:27:37.015 - Personal path: C:\Users\Hugh\Documents\ShareX
2016-09-02 19:27:37.019 - Command line: "E:\Program Index\puush\ShareX\ShareX.exe" "C:\Users\Hugh\Desktop\leftEye1.png"
2016-09-02 19:27:37.023 - Operating system: Windows 10 Pro N
2016-09-02 19:27:37.026 - Flags: PuushMode
2016-09-02 19:27:37.030 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json
2016-09-02 19:27:37.143 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 19:27:37.147 - ApplicationConfig not found. Loading new instance.
2016-09-02 19:27:37.151 - ApplicationConfig load started: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak
2016-09-02 19:27:37.155 - ApplicationConfig load failed: C:\Users\Hugh\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-02 19:27:37.165 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.1 (Release)
2016-09-02 19:27:43.221 - URL opened: https://github.com/ShareX/ShareX/issues

**Comment by Jaex** [comment]
#1615
