### ISSUE TITLE
all settings lost

### ISSUE THREAD

**Issue by Rukenshia** [ShareX/ShareX#1881]
All of my settings have been reset. According to the logs, the settings were saved successfully, but on the next startup, it tells me

```
2016-09-05 23:10:13.539 - ApplicationConfig load started: C:\Users\Jan\Documents\ShareX\ApplicationConfig.json
2016-09-05 23:10:13.688 - ApplicationConfig load failed: C:\Users\Jan\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-05 23:10:13.692 - ApplicationConfig load started: C:\Users\Jan\Documents\ShareX\ApplicationConfig.json.bak
2016-09-05 23:10:13.695 - ApplicationConfig not found. Loading new instance.
2016-09-05 23:10:13.699 - ApplicationConfig load failed: C:\Users\Jan\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-05 23:10:13.758 - MainForm init started
2016-09-05 23:10:13.762 - UploadersConfig load started: C:\Users\Jan\Documents\ShareX\UploadersConfig.json
2016-09-05 23:10:13.788 - UploadersConfig load failed: C:\Users\Jan\Documents\ShareX\UploadersConfig.json:
System.Exception: UploadersConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-05 23:10:13.792 - UploadersConfig load failed: C:\Users\Jan\Documents\ShareX\UploadersConfig.json.bak:
System.Exception: UploadersConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-05 23:10:13.796 - UploadersConfig load started: C:\Users\Jan\Documents\ShareX\UploadersConfig.json.bak
2016-09-05 23:10:13.799 - UploadersConfig not found. Loading new instance.
2016-09-05 23:10:13.807 - HotkeysConfig load started: C:\Users\Jan\Documents\ShareX\HotkeysConfig.json
2016-09-05 23:10:13.812 - HotkeysConfig load failed: C:\Users\Jan\Documents\ShareX\HotkeysConfig.json:
System.Exception: HotkeysConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-05 23:10:13.816 - HotkeysConfig load failed: C:\Users\Jan\Documents\ShareX\HotkeysConfig.json.bak:
System.Exception: HotkeysConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-09-05 23:10:13.820 - HotkeysConfig load started: C:\Users\Jan\Documents\ShareX\HotkeysConfig.json.bak
2016-09-05 23:10:13.823 - HotkeysConfig not found. Loading new instance.
```

I see some .bak files in my user directory. Is there any way to recover my settings?

**Comment by Jaex** [comment]
2016-09-05 23:10:13.692 - ApplicationConfig load started: C:\Users\Jan\Documents\ShareX\ApplicationConfig.json.bak
2016-09-05 23:10:13.695 - ApplicationConfig not found. Loading new instance.

How even backup fails to load?

**Comment by Rukenshia** [comment]
Well, the file does exist. I didn't change anything. The backup file does not contain my previous settings, by the way. I updated my ShareX version to the latest one about a week ago, I think.

**Comment by Jaex** [comment]
Of course it won't contain because it already overwritten when new settings save. Every save previous save is backed up so if corruption happen still you can have one previous save.

**Comment by Rukenshia** [comment]
How did they corrupt, then? I didn't change my settings for a couple of months and the latest update worked fine, too. It just occurred today.

**Comment by Jaex** [comment]
How may I know? My settings never corrupts all these years and I keep using one previous version and debug version countless times everyday.
