### ISSUE TITLE
No way to send 

### ISSUE THREAD

**Issue by maxnaumov** [ShareX/ShareX#1909]
Message:
The remote server returned an error: (400) Bad Request.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Scrxtchy** [comment]
Lots of information missing from this issue post,
What are you uploading to, do if you are logged in to that destination etc.

Essentially, a brief steps of reproduction so we can be on the same page

**Comment by Jaex** [comment]
Probably Imgur was down temporarily.
