### ISSUE TITLE
No way to upload file :( 

### ISSUE THREAD

**Issue by maxnaumov** [ShareX/ShareX#1933]
Message:
Specified value has invalid Control characters.
Parameter name: value

StackTrace:
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.WebHeaderCollection.Add(String name, String value)
   at System.Collections.Specialized.NameValueCollection.Add(NameValueCollection c)
   at ShareX.UploadersLib.Uploader.PrepareWebRequest(HttpMethod method, String url, NameValueCollection headers, CookieCollection cookies, String contentType, Int64 contentLength)
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

**Comment by Jaex** [comment]
Where you uploading to?
