### ISSUE TITLE
failed uploading to gyfycat

### ISSUE THREAD

**Issue by Opzon** [ShareX/ShareX#1949]
Any idea why? Here is my log.

```
2016-09-28 16:29:06.442 - Hotkey triggered. Hotkey: Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2016-09-28 16:29:06.442 - Executing: Start/Stop screen recording (GIF)
2016-09-28 16:29:06.443 - Starting Animated GIF recording. GIF encoding: "FFmpeg", FPS: 30
2016-09-28 16:29:11.516 - CLI: "C:\Users\Riot\Documents\ShareX\Tools\ffmpeg.exe" -y -rtbufsize 100M -f gdigrab -framerate 30 -offset_x 297 -offset_y 144 -video_size 1294x672 -draw_mouse 0 -i desktop -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -qp 0 "C:\Users\Riot\Documents\ShareX\Screenshots\2016-09\2016-09-28_16-29-10.mp4"
2016-09-28 16:29:20.701 - CLI: "C:\Users\Riot\Documents\ShareX\Tools\ffmpeg.exe" -y -i "C:\Users\Riot\Documents\ShareX\Screenshots\2016-09\2016-09-28_16-29-10.mp4" -vf "palettegen=stats_mode=full" "C:\Users\Riot\Documents\ShareX\Tools\palette.png"
2016-09-28 16:29:31.825 - CLI: "C:\Users\Riot\Documents\ShareX\Tools\ffmpeg.exe" -y -i "C:\Users\Riot\Documents\ShareX\Screenshots\2016-09\2016-09-28_16-29-10.mp4" -i "C:\Users\Riot\Documents\ShareX\Tools\palette.png" -lavfi "paletteuse=dither=sierra2_4a" "C:\Users\Riot\Documents\ShareX\Screenshots\2016-09\2016-09-28_16-29-20.gif"
2016-09-28 16:30:13.795 - Task in queue. Job: Job, Type: Image, Host: Imgur
2016-09-28 16:30:13.796 - Task status: Working
2016-09-28 16:30:13.798 - Upload started. Filename: 2016-09-28_16-29-20.gif, Filepath: C:\Users\Riot\Documents\ShareX\Screenshots\2016-09\2016-09-28_16-29-20.gif
2016-09-28 16:31:06.745 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-09-28 16:31:06.745 - Upload failed. Retrying upload.
2016-09-28 16:31:59.611 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-09-28 16:32:29.470 - AddWebError(): Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-09-28 16:32:29.751 - AddWebError(): Message:
The remote server returned an error: (400) Bad Request.

Response:
{
  "error" : "invalid_grant"
}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
2016-09-28 16:32:29.753 - ImageShack configuration is invalid or missing. Please check "Destination settings" window to configure it.
2016-09-28 16:32:30.166 - Task failed. Filename: 2016-09-28_16-29-20.gif, Errors:
ImageShack configuration is invalid or missing. Please check "Destination settings" window to configure it.

Message:
The remote server returned an error: (400) Bad Request.

Response:
{
  "error" : "invalid_grant"
}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

Refresh access token failed.
```
I was able to manually upload the file itself successfully too.

**Comment by Jaex** [comment]
"Internal Server Error." mainly means problem in their side.

**Comment by Opzon** [comment]
@Jaex Huh... strange. thanks for that insanely fast response. I was able to successfully upload the same file to gyfycat literally a minute later. And yes the log contains some other info about uploading elsewhere but I didn't know exactly where to end my log.
