### ISSUE TITLE
ShareX won't start after 11.3 update

### ISSUE THREAD

**Issue by fahy** [ShareX/ShareX#1968]
Hi guys.

Updated ShareX to 11.3 and seem to be creating this error:
Clicking "Continue" doesn't actually ignore the warning and doesn't continue.

Re-installing ShareX seemed to fix this issue for me. But I don't know if anyone is getting the error similar to myself.

```
2016-10-01 02:21:49.864 - ShareX 11.3
2016-10-01 02:21:49.865 - Personal path: C:\Users\spitf\Documents\ShareX
2016-10-01 02:21:49.865 - Operating system: Windows 10 Pro
2016-10-01 02:21:49.865 - Flags: PuushMode
2016-10-01 02:21:49.865 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2016-10-01 02:21:49.866 - Build: Release
2016-10-01 02:21:49.874 - ApplicationConfig load started: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json
2016-10-01 02:21:50.086 - ApplicationConfig load failed: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-10-01 02:21:50.096 - ApplicationConfig load started: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json.bak
2016-10-01 02:21:50.098 - ApplicationConfig not found. Loading new instance.
2016-10-01 02:21:50.098 - ApplicationConfig load failed: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-10-01 02:21:50.147 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.3 (Release)
2016-10-01 02:21:54.160 - ShareX continue.
2016-10-02 15:49:30.550 - ShareX 11.3
2016-10-02 15:49:30.550 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2016-10-02 15:49:30.550 - Personal path: C:\Users\spitf\Documents\ShareX
2016-10-02 15:49:30.551 - Flags: PuushMode
2016-10-02 15:49:30.551 - Operating system: Windows 10 Pro
2016-10-02 15:49:30.551 - Build: Release
2016-10-02 15:49:30.558 - ApplicationConfig load started: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json
2016-10-02 15:49:30.732 - ApplicationConfig load failed: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-10-02 15:49:30.732 - ApplicationConfig load started: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json.bak
2016-10-02 15:49:30.735 - ApplicationConfig load failed: C:\Users\spitf\Documents\ShareX\ApplicationConfig.json.bak:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
2016-10-02 15:49:30.738 - ApplicationConfig not found. Loading new instance.
2016-10-02 15:49:30.786 - Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.3 (Release)
```

Kind regards,

**Comment by Jaex** [comment]
#1615
