### ISSUE TITLE
Parameter is not valid.

### ISSUE THREAD

**Issue by Coolazn132** [ShareX/ShareX#1979]
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Width()
   at ShareX.TaskHelpers.CreateThumbnail(Image img, String folder, String filename, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 11.3 (Release)

**Comment by campbeb** [comment]
@Coolazn132 
Do you have a copy of the image that was being processed?
What tasks were being performed on the image?

**Comment by Jaex** [comment]
Merging this issue with #596
