### ISSUE TITLE
ShareX will not attempt custom uploader

### ISSUE THREAD

**Issue by rekyuu** [ShareX/ShareX#1991]
Hiya,

For whatever reason ShareX refuses to `POST` to my own personal file uploader, `kyo.li`:

```
{
  "Name": "kyo.li",
  "RequestType": "POST",
  "RequestURL": "https://kyo.li/api/upload",
  "FileFormName": "files[]",
  "ResponseType": "Text",
  "URL": "https://kyo.li$json:urls[0]$"
}
```

I get the error:

```
Error: Message:
The underlying connection was closed: An unexpected error occurred on a send.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

This does not happen for other custom uploaders. I have verified that my cert is good, I can `POST` with `curl` and there are no problems otherwise. My `nginx` logs do not show any attempts to `POST` or access the site in any way either.

I've used custom settings for `fuwa.se` and it works fine:

```
{
  "Name": "fuwa.se",
  "RequestType": "POST",
  "RequestURL": "https://fuwa.se/api/upload",
  "FileFormName": "files[]",
  "ResponseType": "Text",
  "URL": "$json:files[0].url$"
}
```

**Comment by Jaex** [comment]
Is your web site only allows TLS 1.2?

**Comment by rekyuu** [comment]
Yea it does, does ShareX not work with TLS 1.2?

**Comment by Jaex** [comment]
#1868

**Comment by rekyuu** [comment]
Neat, that'll do it. Thank you very much!
