### ISSUE TITLE
Error uploading files on custom upload

### ISSUE THREAD

**Issue by Joaquin-V** [ShareX/ShareX#2002]
Error message:
```
Response parse failed.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at ShareX.HelpersLib.Helpers.ParseJSON(String text, String jsonPath)
   at ShareX.UploadersLib.CustomUploaderItem.ParseURL(String url)
   at ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, Boolean isShortenedURL)
   at ShareX.UploadersLib.FileUploaders.CustomFileUploader.Upload(Stream stream, String fileName)
```
Upload:
![](https://i.imgur.com/GPvbxpg.png)

Tried it with the built-in uploaders like Imgur and they work just fine. I also could upload stuff via the upload site's web uploader, so it's apparently not a server issue. It worked just fine before, only recently is it giving me these errors.

**Comment by Joaquin-V** [comment]
Nevermind, turns out the site recently updated their API and this was no longer a valid setup.
