### ISSUE TITLE
Modern SSL settings aren't supported?

### ISSUE THREAD

**Issue by shavitush** [ShareX/ShareX#2019]
I've configured my website to get all A+ and >=100s on [Mozilla Observatory](https://observatory.mozilla.org/analyze.html?host=shav.it).

Now ShareX doesn't let me upload files! I think ShareX doesn't support newer cipher suites, or just big RSA certificates?

Error:

```
Message:
The underlying connection was closed: An unexpected error occurred on a send.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

Edit: I think that actually ShareX just targets an old version of .NET Framework which doesn't support TLS v1.2. I'll try building locally while targeting .NET Framework 4.6.2 and will report back.

**Comment by Jaex** [comment]
#1868
