### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by scraxxy** [ShareX/ShareX#2022]
Message:
The server committed a protocol violation. Section=ResponseStatusLine

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by scraxxy** [comment]
Actually, I think it's an issue at imgur's end as I can't even resolve them at the moment.

**Comment by Artiiz0115** [comment]
I'm getting the same error message, is it Imgur's fault or Sharex?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/10/chrome_aXmBZRD2Tk.png)
