### ISSUE TITLE
Text can't be added (Greenshot Image Editor) if previously used font is missing

### ISSUE THREAD

**Issue by manicmario82** [ShareX/ShareX#2023]
System.ArgumentException: Font 'Verdana Pro SemiBold' cannot be found.
   at System.Drawing.FontFamily.CreateFontFamily(String name, FontCollection fontCollection)
   at Greenshot.Drawing.TextContainer.UpdateFormat()
   at Greenshot.Drawing.TextContainer.Init()
   at Greenshot.Drawing.Surface.CreateUndrawnElement()
   at Greenshot.ImageEditorForm.BtnTextClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at Greenshot.Controls.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.3 (Steam)

**Comment by STALKER2010** [comment]
The same on 11.5, official site distro, Roboto Condensed font.

**Comment by danne2** [comment]
This issue still affects the latest build. Would be nice to see a fix

**Comment by andrewpros** [comment]
Latest version 11.9.1, has still the same issue, should be really fixed @Jaex 

Temporary solution is to close sharex, go to config file GreenshotImageEditor.ini in %HOMEPATH%/Documents/ShareX and delete the whole line with problematic font

In my case i didn't even know how the font removed itself or was there in the first place.
