### ISSUE TITLE
Generic Error in GDI+

### ISSUE THREAD

**Issue by Scellow** [ShareX/ShareX#2060]
I have no idea what happened, my screen went black, then i got this message error  (i wasn't even capturing anything)

```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.SelectActiveFrame(FrameDimension dimension, Int32 frameIndex)
   at System.Drawing.ImageAnimator.ImageInfo.UpdateFrame()
   at System.Drawing.ImageAnimator.UpdateFrames(Image image)
   at System.Windows.Forms.PictureBox.OnPaint(PaintEventArgs pe)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.4.1 (Release)
```

Log: (removed it include imgur links..)

**Comment by Jaex** [comment]
If your screen become black when you were not even doing region capture then maybe it is not to do with ShareX. For example it could be to do with graphic card driver crashing and that effecting picture box rendering of ShareX somehow.

**Comment by Scellow** [comment]
Yeah after checking it was the game i was developing that caused the driver to crash :(
