### ISSUE TITLE
Imgur upload failed: (500) Could not process upload!

### ISSUE THREAD

**Issue by maxnaumov** [ShareX/ShareX#2070]
2016-11-11 08:28:23.477 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2016-11-11 08:28:23.496 - Executing: Capture region
2016-11-11 08:28:25.843 - Task in queue. Job: Job, Type: Image, Host: Imgur
2016-11-11 08:28:25.879 - Task status: Preparing
2016-11-11 08:28:25.921 - Image copied to clipboard.
2016-11-11 08:28:25.960 - Image saved to file: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-28-25.png
2016-11-11 08:28:25.972 - Upload started. Filename: chrome_2016-11-11_08-28-25.png, Filepath: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-28-25.png
2016-11-11 08:28:26.776 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:28:26.797 - Upload failed. Retrying upload.
2016-11-11 08:28:27.252 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2016-11-11 08:28:27.262 - Executing: Capture region
2016-11-11 08:28:28.187 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:28:28.199 - Task failed. Filename: chrome_2016-11-11_08-28-25.png, Errors:
Imgur upload failed: (500) Could not process upload!
2016-11-11 08:28:28.213 - HotkeysConfig save started: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:28:28.252 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:28:28.280 - ApplicationConfig save started: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:28:28.393 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:28:28.490 - HotkeysConfig save successful: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:28:28.544 - ApplicationConfig save successful: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:28:30.632 - Task in queue. Job: Job, Type: Image, Host: Imgur
2016-11-11 08:28:30.664 - Task status: Preparing
2016-11-11 08:28:30.746 - Image copied to clipboard.
2016-11-11 08:28:30.770 - Upload started. Filename: chrome_2016-11-11_08-28-30.png, Filepath: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-28-30.png
2016-11-11 08:28:30.784 - Image saved to file: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-28-30.png
2016-11-11 08:28:31.340 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:28:31.348 - Upload failed. Retrying upload.
2016-11-11 08:28:32.858 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:28:32.873 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:28:32.917 - HotkeysConfig save started: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:28:32.975 - Task failed. Filename: chrome_2016-11-11_08-28-30.png, Errors:
Imgur upload failed: (500) Could not process upload!
2016-11-11 08:28:33.025 - ApplicationConfig save started: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:28:33.095 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:28:33.139 - HotkeysConfig save successful: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:28:33.195 - ApplicationConfig save successful: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:44:47.482 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2016-11-11 08:44:47.509 - Executing: Capture region
2016-11-11 08:44:55.976 - Task in queue. Job: Job, Type: Image, Host: Imgur
2016-11-11 08:44:56.004 - Task status: Preparing
2016-11-11 08:44:56.027 - Image copied to clipboard.
2016-11-11 08:44:56.057 - Upload started. Filename: WINPROJ_2016-11-11_08-44-55.png, Filepath: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\WINPROJ_2016-11-11_08-44-55.png
2016-11-11 08:44:56.088 - Image saved to file: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\WINPROJ_2016-11-11_08-44-55.png
2016-11-11 08:44:56.605 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:44:56.614 - Upload failed. Retrying upload.
2016-11-11 08:44:58.141 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:44:58.156 - Task failed. Filename: WINPROJ_2016-11-11_08-44-55.png, Errors:
Imgur upload failed: (500) Could not process upload!
2016-11-11 08:44:58.206 - HotkeysConfig save started: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:44:58.220 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:44:58.242 - ApplicationConfig save started: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:44:58.387 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:44:58.425 - HotkeysConfig save successful: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:44:58.479 - ApplicationConfig save successful: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:45:28.264 - Task in queue. Job: FileUpload, Type: Image, Host: Imgur
2016-11-11 08:45:28.275 - Task status: Preparing
2016-11-11 08:45:28.286 - Upload started. Filename: WINPROJ_2016-11-11_08-44-55.png, Filepath: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\WINPROJ_2016-11-11_08-44-55.png
2016-11-11 08:45:28.799 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:45:28.808 - Upload failed. Retrying upload.
2016-11-11 08:45:30.373 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:45:30.385 - Task failed. Filename: WINPROJ_2016-11-11_08-44-55.png, Errors:
Imgur upload failed: (500) Could not process upload!
2016-11-11 08:45:30.426 - ApplicationConfig save started: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:45:30.447 - HotkeysConfig save started: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:45:30.462 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:45:30.589 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:45:30.608 - HotkeysConfig save successful: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:45:30.641 - ApplicationConfig save successful: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:45:36.681 - Task in queue. Job: FileUpload, Type: Image, Host: Imgur
2016-11-11 08:45:36.692 - Task status: Working
2016-11-11 08:45:36.704 - Upload started. Filename: chrome_2016-11-09_15-31-14.png, Filepath: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-09_15-31-14.png
2016-11-11 08:45:37.484 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:45:37.493 - Upload failed. Retrying upload.
2016-11-11 08:45:39.307 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:45:39.318 - Task failed. Filename: chrome_2016-11-09_15-31-14.png, Errors:
Imgur upload failed: (500) Could not process upload!
2016-11-11 08:45:39.379 - HotkeysConfig save started: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:45:39.393 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:45:39.419 - ApplicationConfig save started: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:45:39.545 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:45:39.557 - HotkeysConfig save successful: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:45:39.590 - ApplicationConfig save successful: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:46:19.978 - ImgurAuthOpen - Authorization URL is opened: https://api.imgur.com/oauth2/authorize?client_id=d297fd441566f99&response_type=pin
2016-11-11 08:46:19.991 - URL opened: https://api.imgur.com/oauth2/authorize?client_id=d297fd441566f99&response_type=pin
2016-11-11 08:46:58.850 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:46:58.996 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:46:59.694 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2016-11-11 08:46:59.703 - Executing: Capture region
2016-11-11 08:47:00.657 - Task in queue. Job: Job, Type: Image, Host: Imgur
2016-11-11 08:47:00.669 - Task status: Preparing
2016-11-11 08:47:00.721 - Image copied to clipboard.
2016-11-11 08:47:00.770 - Image saved to file: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-47-00.png
2016-11-11 08:47:00.796 - Upload started. Filename: chrome_2016-11-11_08-47-00.png, Filepath: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-47-00.png
2016-11-11 08:47:01.165 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:47:01.174 - Upload failed. Retrying upload.
2016-11-11 08:47:02.632 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:47:02.644 - Task failed. Filename: chrome_2016-11-11_08-47-00.png, Errors:
Imgur upload failed: (500) Could not process upload!
2016-11-11 08:47:02.694 - ApplicationConfig save started: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:47:02.722 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:47:02.748 - HotkeysConfig save started: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:47:02.858 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:47:02.871 - HotkeysConfig save successful: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:47:02.922 - ApplicationConfig save successful: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:48:55.865 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2016-11-11 08:48:55.882 - Executing: Capture region
2016-11-11 08:49:00.752 - Task in queue. Job: Job, Type: Image, Host: Imgur
2016-11-11 08:49:00.763 - Task status: Preparing
2016-11-11 08:49:00.826 - Image copied to clipboard.
2016-11-11 08:49:00.895 - Image saved to file: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-49-00.png
2016-11-11 08:49:00.906 - Upload started. Filename: chrome_2016-11-11_08-49-00.png, Filepath: C:\Users\mnaumo01\Documents\ShareX\Screenshots\2016-11\chrome_2016-11-11_08-49-00.png
2016-11-11 08:49:01.737 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:49:01.750 - Upload failed. Retrying upload.
2016-11-11 08:49:03.502 - AddWebError(): Message:
The remote server returned an error: (500) Internal Server Error.

Response:
{"data":{"error":"Could not process upload!","request":"\/3\/image","method":"POST"},"success":false,"status":500}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2016-11-11 08:49:03.513 - Task failed. Filename: chrome_2016-11-11_08-49-00.png, Errors:
Imgur upload failed: (500) Could not process upload!
2016-11-11 08:49:03.562 - HotkeysConfig save started: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:49:03.589 - ApplicationConfig save started: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:49:03.612 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:49:03.735 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:49:03.770 - HotkeysConfig save successful: C:\Users\mnaumo01\Documents\ShareX\HotkeysConfig.json
2016-11-11 08:49:03.845 - ApplicationConfig save successful: C:\Users\mnaumo01\Documents\ShareX\ApplicationConfig.json
2016-11-11 08:49:21.150 - UploadersConfig save started: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:49:21.314 - UploadersConfig save successful: C:\Users\mnaumo01\Documents\ShareX\UploadersConfig.json
2016-11-11 08:49:27.087 - URL opened: https://github.com/ShareX/ShareX/issues

**Comment by Jaex** [comment]
It is Imgur internal server error not to do with ShareX.

**Comment by maxnaumov** [comment]
But web version of site are working correctly :(

**Comment by Jaex** [comment]
Web version not using this API to upload.

**Comment by maxnaumov** [comment]
Did you by chance tested the imgur api?

**Comment by Jaex** [comment]
I can upload to Imgur currently using API.

**Comment by maxnaumov** [comment]
I'll check again.

**Comment by maxnaumov** [comment]
No way :( 

![image](https://cloud.githubusercontent.com/assets/17650919/20206896/b445a888-a7f4-11e6-822c-a6f6f5c2ea49.png)

**Comment by Jaex** [comment]
http://api.imgur.com/errorhandling

Status Code: 500
Unexpected internal error. What it says. We'll strive NOT to return these but your app should be prepared to see it. It basically means that something is broken with the Imgur service.

**Comment by maxnaumov** [comment]
Thanks for the detailed explanation, sorry for interrupting. I hope soon all will be restored. It is a pity that not Imgur page with the statuses of the servers.

**Comment by TestUser013** [comment]
Hi All,
I asked imgur support about this issue, and they answered me:

> Hi there,
>Thank you for reaching out to Imgur Help. Unfortunately we’re experiencing temporary errors in your region, which may result in access issues on some Imgur features. At this time, we’re investigating a long-term solution to this problem.
>I apologize for the inconvenience this has caused and appreciate your patience.
