### ISSUE TITLE
Upload error when uploading a picture from Android Studio

### ISSUE THREAD

**Issue by n0wbie** [ShareX/ShareX#2118]
Tried to upload from Android Studio many times but I am getting this error:

Message:
The remote server returned an error: (400) Bad Request.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
Are you still can't upload? When Imgur API have problem it tend to return "Bad request".

**Comment by n0wbie** [comment]
Alright it works now. Must be imgur's problem. Thanks for everything!
