### ISSUE TITLE
Random error upon trying to upload a capture.

### ISSUE THREAD

**Issue by Omen267901** [ShareX/ShareX#2136]
Gave me this error

Message:
The remote server returned an error: (400) Bad Request.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
#2118

**Comment by Jaex** [comment]
Got this in Imgur website:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/12/chrome_w8IU7NM4tT.png)
