### ISSUE TITLE
Dropbox uploader: The connection was closed unexpectedly

### ISSUE THREAD

**Issue by tekord** [ShareX/ShareX#2210]
Today I started to receive this error on image upload to my dropbox. Yesterday it worked fine, no updates or settings were changed.

```
2017-01-19 00:07:55.711 - Task failed. Filename: chrome_2017-01-19_00-04-05.png, Errors:
Message:
The underlying connection was closed: The connection was closed unexpectedly.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
```

Any ideas what's wrong?

**Comment by Jaex** [comment]
I also received this today:

```
The remote server returned an error: (502) Bad Gateway.

Response:
{"error": "Internal Server Error"}
```

But later it resolved.
