### ISSUE TITLE
Help? Soft-Reset Computer, Files may be messed up?

### ISSUE THREAD

**Issue by SteveEG158** [ShareX/ShareX#2211]
Soft reset, I tried to uninstall and reinstall as well.
Here is the log message: "
[ShareX-Log-2017-01.txt](https://github.com/ShareX/ShareX/files/715534/ShareX-Log-2017-01.txt)
Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)"

**Comment by Jaex** [comment]
That issue could be to do with lack of TLS 1.2 support in .NET Framework we using. I added workaround for it in latest ShareX version. But it also can be to do with problem in server where you uploading to.
