### ISSUE TITLE
The remote server returned an error: (500) Internal Server Error

### ISSUE THREAD

**Issue by GeoDoX** [ShareX/ShareX#2222]
Message:
The remote server returned an error: (500) Internal Server Error.

Response:
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
Where you uploading to?
