### ISSUE TITLE
ShareX doesn't save some settings

### ISSUE THREAD

**Issue by Kowgan** [ShareX/ShareX#2243]
ShareX won't memorize some of my choosen settings, like "Run ShareX when Windows starts" and "don't prompt me with updates again".
When I re-launch it, the previously deleted files on the list will return.
I've tried launching the application as admin, with no success. Video as follows:

[https://youtu.be/a5d6ofJafSM](https://youtu.be/a5d6ofJafSM)

Thanks.

**Comment by Jaex** [comment]
ShareX Windows startup option is actually not setting but shortcut file. So it just creates/checks this folder:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/explorer_1AQ6kJ2vwE.png)

If ShareX unable to create shortcut there then it is problem in your Windows which not lets ShareX do it.

Check ShareX debug log maybe it contains error message.

About main window list you can disable saving of them from here:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2017/01/ShareX_7CByeqTUdy.png)

**Comment by Kowgan** [comment]
Thanks for the quick response.

Weird. ShareX did create a shortcut on my startup folder ("Inicializar", as in brazilian portuguese); but the option remains unchecked. When I check and uncheck the option before closing the window, the shortcut is deleted, as expected. I'll check the the results after rebooting.
![ss firefox 2017-01-28 at 18-06-56](https://cloud.githubusercontent.com/assets/6265501/22399830/946d6212-e584-11e6-9875-95581511fc02.png)

Here's the debug log (in portuguese, even though the application language is set to english):
`> 2017-01-28 18:09:44.235 - ApplicationConfig save started: C:\Users\Adrian\Documents\ShareX\ApplicationConfig.json
2017-01-28 18:09:44.335 - UploadersConfig save started: C:\Users\Adrian\Documents\ShareX\UploadersConfig.json
2017-01-28 18:09:44.335 - HotkeysConfig save started: C:\Users\Adrian\Documents\ShareX\HotkeysConfig.json
2017-01-28 18:09:44.335 - Exception:
System.InvalidCastException: Não é possível converter o objeto COM do tipo 'Shell32.ShellClass' na interface tipo 'Shell32.IShellDispatch6'. Esta operação falhou porque a chamada de QueryInterface no componente COM para a interface com IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' falhou devido ao seguinte erro: Não há suporte para esta interface (Exceção de HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Shell32.ShellClass.NameSpace(Object vDir)
   at ShareX.HelpersLib.ShortcutHelpers.GetShortcutTargetPath(String shortcutPath)
2017-01-28 18:09:44.335 - Exception:
System.InvalidCastException: Não é possível converter o objeto COM do tipo 'Shell32.ShellClass' na interface tipo 'Shell32.IShellDispatch6'. Esta operação falhou porque a chamada de QueryInterface no componente COM para a interface com IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' falhou devido ao seguinte erro: Não há suporte para esta interface (Exceção de HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Shell32.ShellClass.NameSpace(Object vDir)
   at ShareX.HelpersLib.ShortcutHelpers.GetShortcutTargetPath(String shortcutPath)
2017-01-28 18:09:44.335 - UploadersConfig save successful: C:\Users\Adrian\Documents\ShareX\UploadersConfig.json
2017-01-28 18:09:44.345 - HotkeysConfig save successful: C:\Users\Adrian\Documents\ShareX\HotkeysConfig.json
2017-01-28 18:09:44.365 - ApplicationConfig save successful: C:\Users\Adrian\Documents\ShareX\ApplicationConfig.json
2017-01-28 18:09:50.548 - ApplicationConfig save started: C:\Users\Adrian\Documents\ShareX\ApplicationConfig.json
2017-01-28 18:09:50.668 - ApplicationConfig save successful: C:\Users\Adrian\Documents\ShareX\ApplicationConfig.json`

About the main window list, the recent tasks opton did the job, thanks!

**Comment by Jaex** [comment]
Because that error is not english I can't Google it :( But it not looks to do with ShareX.

**Comment by Kowgan** [comment]
No big. The shortcut set into the startup folder should fix the problem anyway. Thank you for the amazing support!
