### ISSUE TITLE
Can't login to puuush

### ISSUE THREAD

**Issue by Gektorian** [ShareX/ShareX#2258]
Had issues with uploading screenshots to puush. I uninstalled sharex and deleted data from user folder. Now I can't login after new installation to puush. First it take long time to create request and it says "not responding", after unfreez, as a response I get : "Authentication failure: Login failed."

![untitled](https://cloud.githubusercontent.com/assets/3693219/22510204/b3584170-e899-11e6-9741-418cc8fb1035.png)

In same time I can login via web to puush.me/login

**Comment by Jaex** [comment]
I can't reproduce your issue, is your issue still continue?

**Comment by Gektorian** [comment]
Yes, still the same:
![still_1](https://cloud.githubusercontent.com/assets/3693219/22518492/6d499af0-e8b5-11e6-9139-efc4a5c30b6b.png)
Also I tried to past directly API key from puush.me/account and this is error that I retrieved when try to upload:
```
Message:
Unable to connect to the remote server

Request URL:
https://puush.me/api/up

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

Maybe I'm missing something?

**Comment by Jaex** [comment]
Can you be able to upload other uploaders like Imgur?

**Comment by Gektorian** [comment]
Didn't have account there, I will create one now and will test. Will update you with info asap.

**Comment by Jaex** [comment]
Imgur not require account to upload.

**Comment by Gektorian** [comment]
Same issue:

```
Message:
Unable to connect to the remote server

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

**Comment by Jaex** [comment]
That means something in your computer blocks all ShareX connection. Did you check your firewall?

**Comment by Gektorian** [comment]
My w10 firewall is off and bitdefender seems also not blocking it. Just did checking. Is there any guide, how to clear up system with current installation? Uninstall from control panel (using windows 10) and delete Documents\ShareX ? That's it?

**Comment by Jaex** [comment]
Uninstalling ShareX never fix any issue other than corrupt installation.

**Comment by GamerzHell9137** [comment]
Is still happening. Reinstalled W10 and wanted to login to Puush but nothing happens when you press the login button.
