### ISSUE TITLE
Trying to upload images to Tinypic

### ISSUE THREAD

**Issue by teddybearharris89** [ShareX/ShareX#2286]
Message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
http://api.tinypic.com/api.php

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Have been getting this all day, I have been using TP for months and this is the first time it's glitched out on me. What's the crack?

**Comment by Jaex** [comment]
Their server have problem.
