### ISSUE TITLE
Gyfcat Upload Error

### ISSUE THREAD

**Issue by LBUlises** [ShareX/ShareX#2290]
I haven't toyed with any settings and Gyfcat uploading just stopped working today. I'm on ShareX 11.5 and have been since the update came out.

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
https://upload.gfycat.com/transcodeRelease/WIoxqSwZ68?noResize=true

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
2017-02-14 20:00:46.303 - UploadersConfig save successful: D:\LB\Documents\ShareX\UploadersConfig.json
2017-02-14 20:00:46.311 - UploadersConfig save started: D:\LB\Documents\ShareX\UploadersConfig.json
2017-02-14 20:00:46.322 - HotkeysConfig save started: D:\LB\Documents\ShareX\HotkeysConfig.json
2017-02-14 20:00:46.331 - HotkeysConfig save successful: D:\LB\Documents\ShareX\HotkeysConfig.json
2017-02-14 20:00:46.338 - ApplicationConfig save started: D:\LB\Documents\ShareX\ApplicationConfig.json
2017-02-14 20:00:46.344 - ApplicationConfig save successful: D:\LB\Documents\ShareX\ApplicationConfig.json
```

**Comment by Jaex** [comment]
>The remote server returned an error: (503) Server Unavailable.

This message explains situation.
