### ISSUE TITLE
FTPS seems to be broken?

### ISSUE THREAD

**Issue by digitalix** [ShareX/ShareX#2294]
Today I have installed ssl cert for my ftp server, after that uploading to ftp server is somehow broken.
ShareX do upload files but it results in "Upload Errors":

`System.Net.FtpClient.FtpCommandException: Failure reading network stream.
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

System.Net.FtpClient.FtpCommandException: Failure reading network stream.
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)`

How can I fix it?

**Comment by dannoe** [comment]
Can you still upload files with a normal ftp client? (e.g. FileZilla or WinSCP)
And did you change the protocol to FTPS?


![9y4h3dq](https://cloud.githubusercontent.com/assets/7450586/23093843/d9a6550e-f5ed-11e6-923f-39d96cd6f75d.png)

**Comment by digitalix** [comment]
Yes I can, even ShareX does it properly but after upload I get this error but file is successfully uploaded on my ftp server. 

http://i.imgur.com/JJltcNb.png
