### ISSUE TITLE
A generic error occured in GDI+

### ISSUE THREAD

**Issue by Wilbo007** [ShareX/ShareX#2337]
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.CreateThumbnail(Image img, String folder, String filename, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 11.6 (Release)
```

**Comment by Wilbo007** [comment]
happens any time I want to take a screenshot.

the greenshot editor pops up, I click green tick then crashes

**Comment by Wilbo007** [comment]
I reverted back to 11.5

issue is no longer happening

**Comment by Jaex** [comment]
Which after capture tasks must be selected to reproduce this issue?

**Comment by Wilbo007** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3623279/24581175/19ffc820-1749-11e7-9ccd-244774f3fc82.png)

**Comment by Jaex** [comment]
I still can't manage to reproduce it. After press green tick it uploads without problem :(
