### ISSUE TITLE
Issue with Gfycat upload

### ISSUE THREAD

**Issue by pock2793** [ShareX/ShareX#2340]
when i try to upload to gfycat its throwing this error 
```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
https://upload.gfycat.com/transcodeRelease/Wjis4ImO2E?noResize=true

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
https://upload.gfycat.com/transcodeRelease/gWtHlJzrSn?noResize=true

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
```

**Comment by Jaex** [comment]
I'm not sure why Gfycat returns `(503) Server Unavailable.`.

But this happened right after Amazon issues, so is it can be to do with it?

**Comment by Scrxtchy** [comment]
Getting a few references to The US West for amazon, which was not affected by the outage, but I'm not ruling it out, still possible. 
Gfycat works on my machine now though

**Comment by pock2793** [comment]
can confirm working now
