### ISSUE TITLE
Escape not work in "Capture region" mode

### ISSUE THREAD

**Issue by sm-g** [ShareX/ShareX#2356]
11.6, Windows 7 x64

1. Click Start button
2. Press sortcut for "capture region"
3. press esc - nothing

it works when cursor hovers Start button, after that ShareX crashes with 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.ScreenCaptureLib.ShapeManager.UpdateMenu()
   at ShareX.ScreenCaptureLib.ShapeManager.OnCurrentShapeChanged(BaseShape shape)
   at ShareX.ScreenCaptureLib.ShapeManager.DeselectShape(BaseShape shape)
   at ShareX.ScreenCaptureLib.ShapeManager.DeleteAllShapes()
   at ShareX.ScreenCaptureLib.RegionCaptureForm.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()

**Comment by Jaex** [comment]
When you press esc button which item in toolbar was selected?

**Comment by sm-g** [comment]
First, rectangle. After switch to other "esc" works

**Comment by Jaex** [comment]
Because I can't manage to reproduce your error.
