### ISSUE TITLE
Illegal characters in path.

### ISSUE THREAD

**Issue by notesplaymyheart** [ShareX/ShareX#2359]
``System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   at ShareX.ApplicationSettingsForm.UpdatePersonalFolderPathPreview()
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.6 (Release)``

**Comment by Jaex** [comment]
What is that path?

**Comment by NielsGregers** [comment]
I've got the same , the path is that point to where I like screen shots saved  @Jaex 

Pasted this one in "C:\Users\ngjoh\OneDrive - Nets\Root\ScreenShots"
