### ISSUE TITLE
Sharex Can't upload my image file

### ISSUE THREAD

**Issue by nishanthii2w** [ShareX/ShareX#2391]
The images uploaded in local folder and can't create a link for live upload its causing the anonymous uploading error

2017-03-28 11:01:24.148 - Image copied to clipboard.
2017-03-28 11:01:24.152 - Image saved to file: C:\Users\DELL\Documents\ShareX\Screenshots\2017-03\firefox_2017-03-28_11-01-24.png
2017-03-28 11:01:24.156 - Upload started. Filename: firefox_2017-03-28_11-01-24.png, Filepath: C:\Users\DELL\Documents\ShareX\Screenshots\2017-03\firefox_2017-03-28_11-01-24.png
2017-03-28 11:01:25.372 - AddWebError(): Message:
The remote server returned an error: (400) Bad Request.

Response:
{"data":{"error":"We're really sorry, but anonymous uploading in your country has been disabled. Please <a href=\"\/register\">register for an account<\/a> and try uploading again.","request":"\/3\/image","method":"POST"},"success":false,"status":400}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2017-03-28 11:01:25.374 - Upload failed. Retrying upload.
2017-03-28 11:01:27.263 - AddWebError(): Message:
The remote server returned an error: (400) Bad Request.

Response:
{"data":{"error":"We're really sorry, but anonymous uploading in your country has been disabled. Please <a href=\"\/register\">register for an account<\/a> and try uploading again.","request":"\/3\/image","method":"POST"},"success":false,"status":400}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2017-03-28 11:01:27.299 - Task failed. Filename: firefox_2017-03-28_11-01-24.png, Errors:
Imgur upload failed: (400) We're really sorry, but anonymous uploading in your country has been disabled. Please <a href="/register">register for an account</a> and try uploading again.
2017-03-28 11:01:27.432 - HotkeysConfig save started: C:\Users\DELL\Documents\ShareX\HotkeysConfig.json
2017-03-28 11:01:27.434 - UploadersConfig save started: C:\Users\DELL\Documents\ShareX\UploadersConfig.json
2017-03-28 11:01:27.435 - ApplicationConfig save started: C:\Users\DELL\Documents\ShareX\ApplicationConfig.json
2017-03-28 11:01:27.507 - UploadersConfig save successful: C:\Users\DELL\Documents\ShareX\UploadersConfig.json
2017-03-28 11:01:27.536 - HotkeysConfig save successful: C:\Users\DELL\Documents\ShareX\HotkeysConfig.json
2017-03-28 11:01:27.545 - ApplicationConfig save successful: C:\Users\DELL\Documents\ShareX\ApplicationConfig.json

**Comment by Jaex** [comment]
Error tells:

> We're really sorry, but anonymous uploading in your country has been disabled. Please register for an account and try uploading again.
