### ISSUE TITLE
A generic error occurred in GDI+

### ISSUE THREAD

**Issue by Wilbo007** [ShareX/ShareX#2401]
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.CreateThumbnail(Image img, String folder, String filename, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 11.6 (Release)
```

Windows 7, after I take a screenshot this happens

If I have Greenshot editing enabled it crashes when I click the green tick

**Comment by Jaex** [comment]
Few people was also reported that creating thumbnail gives error but I can't manage to reproduce it with these settings:

![](http://i.imgur.com/lgEAjHk.png)

**Comment by Jaex** [comment]
#2337

**Comment by Wilbo007** [comment]
Yep, it was the thumbnail thing, works fine without it
