### ISSUE TITLE
error on img upload

### ISSUE THREAD

**Issue by gaia** [ShareX/ShareX#2408]
on 11.6, been getting an error on img upload (imgur, already did reauth twice) since yesterday. 

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Cannot change album contents while in gallery","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Cannot change album contents while in gallery","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2017-04-04 16:18:48.648 - UploadersConfig save successful: C:\Program Files\ShareX\Settings\UploadersConfig.json
2017-04-04 16:18:48.662 - HotkeysConfig save successful: C:\Program Files\ShareX\Settings\HotkeysConfig.json
2017-04-04 16:18:48.685 - ApplicationConfig save successful: C:\Program Files\ShareX\Settings\ApplicationConfig.json

**Comment by Jaex** [comment]
I'm not sure what is this error means: "Cannot change album contents while in gallery".

**Comment by gaia** [comment]
i switched around the album and works again. sorry for the hassle and thank you for your efforts on this wonderful tool
