### ISSUE TITLE
Color pipette: Cross-thread exception

### ISSUE THREAD

**Issue by Fredrik-G** [ShareX/ShareX#2450]
I get a cross-thread exception when clicking the color picker pipette.

Steps to reproduce:
1. Open the image editor, click any color picker and its pipette. 
2. Close the editor and repeat step 1. 
3. Exception.

I downloaded the latest Greenshot and I cannot reproduce it there.
(It seems like 'MovableShowColorForm' is used like a singleton and never disposed between editors).

Callstack:
```
System.InvalidOperationException: Cross-thread operation not valid: Control 'Zoomer' accessed from a thread other than the thread it was created on.
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at Greenshot.Controls.Pipette.OnMouseCaptureChanged(EventArgs e) in C:\Users\Fredrik\Desktop\ShareX-master\Greenshot.ImageEditor\Controls\Pipette.cs:line 174
   at System.Windows.Forms.Control.WmCaptureChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by AKTheKnight** [comment]
Hey @Fredrik-G I am unable to reproduce this error. Are you still having it? What version of ShareX are you using?

**Comment by Fredrik-G** [comment]
@AKTheKnight  I looked into it more and I cannot reproduce it with a fresh install.
I can only reproduce it using an old setup with old settings made before #2438, in which the "Annotate Image" pops up after capturing an image. It will then crash with the mentioned error, 

But I guess it's not really relevant since you need an old setup to notice the issue.

**Comment by AKTheKnight** [comment]
Ahh okay, so something since then has fixed it in a recent release. That's awesome to hear.

I was just having a look through open issues and seeing if there is anything still needing fixing I can take a look at.
