### ISSUE TITLE
[Hastebin] UploadErrors

### ISSUE THREAD

**Issue by BlackSharp** [ShareX/ShareX#2466]
![default](https://cloud.githubusercontent.com/assets/16515416/25448999/076e2426-2ac3-11e7-9de2-3a49dc8cc2d3.png)
```
2017-04-26 20:57:08.528 - ShareX closing.
2017-04-26 20:57:08.528 - ShareX restarting.
2017-04-26 20:57:09.107 - ShareX 11.7
2017-04-26 20:57:09.108 - Command line: "D:\1_soft\ShareX\ShareX.exe" 
2017-04-26 20:57:09.109 - Build: Release
2017-04-26 20:57:09.109 - Personal path: D:\Maxim\Документы\ShareX
2017-04-26 20:57:09.109 - Operating system: Windows 10 Enterprise
2017-04-26 20:57:09.132 - ApplicationConfig load started: D:\Maxim\Документы\ShareX\ApplicationConfig.json
2017-04-26 20:57:10.528 - ApplicationConfig load finished: D:\Maxim\Документы\ShareX\ApplicationConfig.json
2017-04-26 20:57:10.531 - UploadersConfig load started: D:\Maxim\Документы\ShareX\UploadersConfig.json
2017-04-26 20:57:10.606 - Language changed to: English (United States)
2017-04-26 20:57:10.606 - MainForm init started.
2017-04-26 20:57:11.134 - UploadersConfig load finished: D:\Maxim\Документы\ShareX\UploadersConfig.json
2017-04-26 20:57:11.135 - HotkeysConfig load started: D:\Maxim\Документы\ShareX\HotkeysConfig.json
2017-04-26 20:57:11.210 - HotkeysConfig load finished: D:\Maxim\Документы\ShareX\HotkeysConfig.json
2017-04-26 20:57:11.395 - MainForm init finished.
2017-04-26 20:57:11.686 - Startup time: 2759 ms
2017-04-26 20:57:11.738 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-04-26 20:57:11.738 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-04-26 20:57:11.739 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-04-26 20:57:11.739 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2017-04-26 20:57:11.739 - Hotkey registered: Hotkey: Ctrl + Alt + Print Screen, Description: Text capture (OCR), Job: TextCapture
2017-04-26 20:57:11.740 - HotkeyManager started.
2017-04-26 20:57:11.740 - WatchFolderManager started.
2017-04-26 20:57:20.873 - CommandLine: D:\Maxim\Документы\Orbwalker.cs
2017-04-26 20:57:20.912 - Task in queue. Job: FileUpload, Type: Text, Host: Hastebin
2017-04-26 20:57:20.921 - Task status: Preparing
2017-04-26 20:57:20.934 - Upload started. Filename: Orbwalker.cs, Filepath: D:\Maxim\Документы\Orbwalker.cs
2017-04-26 20:57:21.955 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.TextUploaders.Hastebin.UploadText(String text, String fileName)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2017-04-26 20:57:21.956 - Upload failed. Retrying upload.
2017-04-26 20:57:22.956 - Exception:
System.ArgumentException: Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2017-04-26 20:57:22.964 - Task failed. Filename: Orbwalker.cs, Errors:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.TextUploaders.Hastebin.UploadText(String text, String fileName)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

System.ArgumentException: Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2017-04-26 20:57:23.214 - UploadersConfig save successful: D:\Maxim\Документы\ShareX\UploadersConfig.json
2017-04-26 20:57:23.214 - UploadersConfig save started: D:\Maxim\Документы\ShareX\UploadersConfig.json
2017-04-26 20:57:23.248 - ApplicationConfig save successful: D:\Maxim\Документы\ShareX\ApplicationConfig.json
2017-04-26 20:57:23.248 - ApplicationConfig save started: D:\Maxim\Документы\ShareX\ApplicationConfig.json
2017-04-26 20:57:23.248 - HotkeysConfig save started: D:\Maxim\Документы\ShareX\HotkeysConfig.json
2017-04-26 20:57:23.340 - HotkeysConfig save successful: D:\Maxim\Документы\ShareX\HotkeysConfig.json
2017-04-26 20:57:25.691 - URL opened: D:\Maxim\Документы\Orbwalker.cs
2017-04-26 20:57:31.788 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-04-26 20:57:31.792 - Executing: Capture region
2017-04-26 20:57:33.020 - Task in queue. Job: Job, Type: Image, Host: 
2017-04-26 20:57:33.029 - Task status: Preparing
2017-04-26 20:57:33.047 - Image copied to clipboard.
2017-04-26 20:57:33.093 - Image saved to file: D:\Maxim\Документы\ShareX\Screenshots\2017-04\ShareX_2017-04-26_20-57-33.png
2017-04-26 20:57:33.094 - Task completed. Filename: ShareX_2017-04-26_20-57-33.png, Duration: 72 ms
2017-04-26 20:57:33.686 - ApplicationConfig save successful: D:\Maxim\Документы\ShareX\ApplicationConfig.json
2017-04-26 20:57:33.687 - ApplicationConfig save started: D:\Maxim\Документы\ShareX\ApplicationConfig.json
2017-04-26 20:57:33.783 - UploadersConfig save successful: D:\Maxim\Документы\ShareX\UploadersConfig.json
2017-04-26 20:57:33.783 - UploadersConfig save started: D:\Maxim\Документы\ShareX\UploadersConfig.json
2017-04-26 20:57:33.783 - HotkeysConfig save started: D:\Maxim\Документы\ShareX\HotkeysConfig.json
2017-04-26 20:57:33.907 - HotkeysConfig save successful: D:\Maxim\Документы\ShareX\HotkeysConfig.json
```

**Comment by Jaex** [comment]
They disable http:// endpoint and it returns html response.

In here either change custom domain to use https:// or clear that textbox so ShareX will use default endpoint which using https://

![](https://jaex.getsharex.com/2017/04/ShareX_QMyjOJiBdF.png)

**Comment by Jaex** [comment]
#2185
