### ISSUE TITLE
Imgur Upload error

### ISSUE THREAD

**Issue by MN1JY** [ShareX/ShareX#2531]
Hello, I have been unable to send images to Imgur for a long time. 
If you selected "Account type": User> Error. 
If you selected "Account type": Anonymos> Ok (the image is sent).
What could be the problem? I'm enclosing the log. Tried "Refresh authorization".

> Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

>Message:
The remote server returned an error: (400) Bad Request.

>Request URL:
https://api.imgur.com/3/image

>Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

>Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Probably, similar problems already were, but on search has not found the answer (badly with English). Problems with sending were here https://github.com/ShareX/ShareX/issues/2519, but here is another problem.

**Comment by Jaex** [comment]
Did you tried re doing authorization instead of refresh auth button?

**Comment by MN1JY** [comment]
Yes
1. Step:  Open authorize page
1.1 Copy and paste the PIN number below into the application that sent you here. 
2. Complete authorization
2.1. Login successful > ok

Now I tried again. The error is the same.
> The remote server returned an error: (400) Bad Request.
> Response:
> {"Data": {"error": {"code": 403, "message": "Forbidden", "type": "ImgurException", "exception": []}, "request": "\ / 3 \ / Image "," method ":" POST "}," success ": false," status ": 400}

**Comment by Jaex** [comment]
Did  you tried uploading with your account in imgur website?

**Comment by MN1JY** [comment]
OU. It turns out I'm watching the problem when downloading through the site. Thanks for the help. I'll try to write in support of Imgur, most likely the problem is on their side.
Http://i.imgur.com/W7dyMPr.png
