### ISSUE TITLE
The value of argument 'value' (1) is invalid for Enum type 'ColumnHeaderStyle'.

### ISSUE THREAD

**Issue by PazerOP** [ShareX/ShareX#2601]
```
System.ComponentModel.InvalidEnumArgumentException: The value of argument 'value' (1) is invalid for Enum type 'ColumnHeaderStyle'.
Parameter name: value
   at System.Windows.Forms.ListView.set_HeaderStyle(ColumnHeaderStyle value)
   at ShareX.MainForm.InitializeComponent()
   at ShareX.MainForm.InitializeControls()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.7 (Release)
```
Error occurs on every launch.

**Comment by Jaex** [comment]
This is very weird problem because this line causing error:

```this.lvUploads.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.Nonclickable;```

And value 1 (Nonclickable) is valid in this enum.
