### ISSUE TITLE
ShareX error - can't open anymore

### ISSUE THREAD

**Issue by roovyshapiro** [ShareX/ShareX#2608]
ShareX is the best screenshot software and it was working really well for a long time. Today, I get the following error:
"Exception has been thrown by the target of an invocation."
I received the same error after uninstalling and reinstalling.
http://imgur.com/a/DJ4zf

If I click on "continue," a popup says ShareX has stopped working. A problem caused the program to stop working correctly.  Please close the program. Then I have the options to Close the program or Debug the program.

Note: I am using Windows 7 currently.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Font 'Arial' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObject(Int32 pos)
   at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   at ShareX.HelpersLib.MyPictureBox..ctor()
   at ShareX.MainForm.InitializeComponent()
   at ShareX.MainForm.InitializeControls()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.7 (Release)

**Comment by Jaex** [comment]
#374

**Comment by roovyshapiro** [comment]
stumbled onto this link and it fixed the problem, https://www.microsoft.com/en-us/download/details.aspx?id=16083 thanks for pointing me in the right direction.
