### ISSUE TITLE
Could not load file or assembly ShareX.UploadersLib

### ISSUE THREAD

**Issue by Kronkleberry** [ShareX/ShareX#2625]
```
ShareX 11.8 (Release)
2017-07-10 16:06:03.082 - ShareX closing. Reason: Unhandled exception.
2017-07-10 16:06:35.752 - Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ShareX.UploadersLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

Happened shortly after updating to the newest version.

**Comment by Jaex** [comment]
#1615
