### ISSUE TITLE
Unable to change ShareX folder from redirected Documents to local drive.

### ISSUE THREAD

**Issue by ctahok** [ShareX/ShareX#2640]
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\ShareX\ShareX\PersonalPath.cfg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ShareX.Program.WritePersonalPathConfig(String path)
   at ShareX.ApplicationSettingsForm.SettingsForm_FormClosed(Object sender, FormClosedEventArgs e)
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

ShareX 11.8 (Release)

**Comment by Jaex** [comment]
Writing to program files requires admin access. So you must not put ShareX personal folder to program files.
