### ISSUE TITLE
"Run ShareX when Windows starts" not updated properly

### ISSUE THREAD

**Issue by josegeraldo1** [ShareX/ShareX#2659]
Hello,

Application Settings -> Integration -> checkbox "Run ShareX when Windows starts" shows always disabled even with this option turned ON.

Thanks!

**Comment by Jaex** [comment]
<kbd>Windows + R</kbd> shell:startup

In here is ShareX shortcut created? Checkbox checking is shortcut exists there when application settings window opening.

**Comment by josegeraldo1** [comment]
OS is Windows 7 Professional
ShareX Version is 11.8

Yes, ShareX shortcut is created in startup.
![s1](https://user-images.githubusercontent.com/20847642/28841403-7f1a81c8-76d0-11e7-956c-cdbf4d63f81a.png)

I hope GIF below shows what I mean.
![2017-08-01_15-54-45](https://user-images.githubusercontent.com/20847642/28841875-fd37cbdc-76d1-11e7-8943-95b365333f0d.gif)

**Comment by phantx** [comment]
OS is Windows 7 Professional
ShareX Version is 12.0 portable

On my PC, after click 'Run ShareX when Windows starts', I can find shortcut created on Startup folder. But the checkbox is still uncheck. 

The checkbox keep unchecked whether how many times click on it.

**Comment by merinoffff** [comment]
Same for me. The option remains unchecked, even though the link is in place. Maybe something to do with antivirus (e.g. Kaspersky).

**Comment by Jaex** [comment]
It works for me:

![](https://jaex.getsharex.com/2018/03/bP7IvAYBfV.gif)

Is your ShareX run as admin?

**Comment by w-w-y** [comment]
I have this problem in Windows 7, ShareX version 12.1.1. Clicking the "Run ShareX when Windows starts" checkbox does not update the checkbox. It remains unchecked at all times. Clicking the control does not update the shortcut in the Startup folder. Running with Admin privileges makes no difference.

**Comment by Jaex** [comment]
I ran Windows 7 virtual machine and indeed I can reproduce your issue now. It is weird how not many people reported this too. If you check debug log you can see error message there.

**Comment by phantx** [comment]
2018-04-08 14:48:59.842 - ShareX 12.0 Portable
2018-04-08 14:48:59.843 - Build: Release
2018-04-08 14:48:59.843 - Command line: "E:\software\ShareX-portable\ShareX.exe" 
2018-04-08 14:48:59.844 - Personal path: E:\software\ShareX-portable\ShareX
2018-04-08 14:48:59.845 - Operating system: Windows 7 Professional
2018-04-08 14:48:59.847 - Flags: Portable
2018-04-08 14:48:59.918 - ApplicationConfig load started: E:\software\ShareX-portable\ShareX\ApplicationConfig.json
2018-04-08 14:49:00.723 - ApplicationConfig load finished: E:\software\ShareX-portable\ShareX\ApplicationConfig.json
2018-04-08 14:49:00.726 - UploadersConfig load started: E:\software\ShareX-portable\ShareX\UploadersConfig.json
2018-04-08 14:49:00.729 - MainForm init started.
2018-04-08 14:49:00.943 - UploadersConfig load finished: E:\software\ShareX-portable\ShareX\UploadersConfig.json
2018-04-08 14:49:00.946 - HotkeysConfig load started: E:\software\ShareX-portable\ShareX\HotkeysConfig.json
2018-04-08 14:49:01.000 - HotkeysConfig load finished: E:\software\ShareX-portable\ShareX\HotkeysConfig.json
2018-04-08 14:49:01.492 - MainForm init finished.
2018-04-08 14:49:01.638 - Startup time: 1940 ms
2018-04-08 14:49:01.669 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2018-04-08 14:49:01.669 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2018-04-08 14:49:01.669 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2018-04-08 14:49:01.669 - Hotkey registered: Hotkey: Ctrl + Alt + Print Screen, Description: Capture last region, Job: LastRegion
2018-04-08 14:49:01.671 - HotkeyManager started.
2018-04-08 14:49:01.672 - WatchFolderManager started.
2018-04-08 14:49:08.356 - Exception:
System.InvalidCastException: Unable to cast COM object of type 'Shell32.ShellClass' to interface type 'Shell32.IShellDispatch6'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Shell32.ShellClass.NameSpace(Object vDir)
   at ShareX.HelpersLib.ShortcutHelpers.GetShortcutTargetPath(String shortcutPath)

---

Is this log helpful?

**Comment by stuntguy3000** [comment]
Yes, the error down the bottom will help us resolve this.

**Comment by Jaex** [comment]
Fixed it now you can test it if you want: https://getsharex.com/docs/dev-builds
