### ISSUE TITLE
i have a problem with uploading images

### ISSUE THREAD

**Issue by CoolGoga** [ShareX/ShareX#2737]
Hello. Today i downloaded ShareX and try to upload image but ShareX gave error:
```
Message:
Unable to connect to the remote server

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```
What should i do?

**Comment by campbeb** [comment]
If you try to go that webpage (https://api.imgur.com/3/image) what do you see?

**Comment by CoolGoga** [comment]
{"data":{"error":"Authentication required","request":"\/3\/image","method":"GET"},"success":false,"status":401}

**Comment by campbeb** [comment]
And you still can't upload to imgur?

**Comment by Scrxtchy** [comment]
Are you uploading to imgur as a user or anonymous?
if the former, relogin
