### ISSUE TITLE
Crash: Font "Arial monospaced for SAP" cannot be found

### ISSUE THREAD

**Issue by Ric0la** [ShareX/ShareX#2796]
When I want to add some text using greenshot, this happens:

```
System.ArgumentException: Font 'Arial monospaced for SAP' cannot be found.
   at System.Drawing.FontFamily.CreateFontFamily(String name, FontCollection fontCollection)
   at Greenshot.Drawing.TextContainer.UpdateFormat()
   at Greenshot.Drawing.TextContainer.Init()
   at Greenshot.Drawing.Surface.CreateUndrawnElement()
   at Greenshot.ImageEditorForm.BtnTextClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at Greenshot.Controls.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 11.9.1 (Release)
```

I had the same issue on my previous machine and had the impression it would be a setup issue. Now I have a new notebook, freshly set up, and it's still happening. Note: I don't have SAP installed, I never had! 😃 

Anything I can do about this?

**Comment by campbeb** [comment]
- Go to your ShareX settings folder (usually C:\Users\username\Documents\ShareX)
 - Open the file `GreenshotImageEditor.ini`
 - Look for the line with `LastFieldValue.TextContainer.FONT_FAMILY`
 - Delete that entire line

Alternately, you could set the font name at the end of the line to one you know you have installed.
Mine is:
```
LastFieldValue.TextContainer.FONT_FAMILY=System.String,mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089:Roboto
```

**Comment by Ric0la** [comment]
Awesome, thanks!

**Comment by campbeb** [comment]
If your problem is solved, please close the issue.
