### ISSUE TITLE
ShareX won't start. - System.BadImageFormatException

### ISSUE THREAD

**Issue by spajo** [ShareX/ShareX#2837]
Hi,

I have ShareX in autostart, today when I booted up my PC I was shown this stack trace. Reinstallation doesn't fix the problem, neither does removing the ShareX folder from documents.

Logs after removing all config files:
```
2017-10-09 18:39:13.973 - ShareX 11.9.1
2017-10-09 18:39:13.974 - Build: Release
2017-10-09 18:39:13.974 - Personal path: C:\Users\spaj\Documents\ShareX
2017-10-09 18:39:13.975 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2017-10-09 18:39:13.975 - Operating system: Windows 10 Pro N
2017-10-09 18:39:13.981 - ApplicationConfig load started: C:\Users\spaj\Documents\ShareX\ApplicationConfig.json
2017-10-09 18:39:13.982 - ApplicationConfig load started: C:\Users\spaj\Documents\ShareX\ApplicationConfig.json.bak
2017-10-09 18:39:13.982 - ApplicationConfig not found. Loading new instance.
2017-10-09 18:39:14.015 - UploadersConfig load started: C:\Users\spaj\Documents\ShareX\UploadersConfig.json
2017-10-09 18:39:14.016 - UploadersConfig load started: C:\Users\spaj\Documents\ShareX\UploadersConfig.json.bak
2017-10-09 18:39:14.017 - MainForm init started.
2017-10-09 18:39:14.017 - UploadersConfig not found. Loading new instance.
2017-10-09 18:39:14.031 - HotkeysConfig load started: C:\Users\spaj\Documents\ShareX\HotkeysConfig.json
2017-10-09 18:39:14.032 - HotkeysConfig not found. Loading new instance.
2017-10-09 18:39:14.033 - HotkeysConfig load started: C:\Users\spaj\Documents\ShareX\HotkeysConfig.json.bak
2017-10-09 18:39:14.084 - Unhandled exception:
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at System.Reflection.MetadataImport._GetParentToken(IntPtr scope, Int32 mdToken, Int32& tkParent)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Runtime.Serialization.SerializationEvents.GetMethodsWithAttribute(Type attribute, Type t)
   at System.Runtime.Serialization.SerializationEvents..ctor(Type t)
   at System.Runtime.Serialization.SerializationEventsCache.GetSerializationEventsForType(Type t)
   at System.Runtime.Serialization.ObjectManager.RaiseOnDeserializedEvent(Object obj)
   at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at ShareX.HelpersLib.Properties.Resources.get_Loading()
   at ShareX.HelpersLib.MyPictureBox..ctor()
   at ShareX.MainForm.InitializeComponent()
   at ShareX.MainForm.InitializeControls()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.9.1 (Release)
2017-10-09 18:39:16.851 - ShareX closing. Reason: Unhandled exception.
```

**Comment by Jaex** [comment]
I wonder is your .NET Framework become corrupt.

**Comment by spajo** [comment]
Haven't thought of that. Forced Windows Update to reinstall .NET solved this issue.

Thanks!
