### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by rambling1** [ShareX/ShareX#2903]
Hello, I'm getting this error daily now since the Fall Creators Update. Re-starting ShareX solves it temporarily. How do I get rid of this error?

System.IO.FileNotFoundException: Could not find file 'C:\Users\XXX\Documents\ShareX\Backup\ApplicationConfig-2017-11-W45.json'.
File name: 'C:\Users\XXX\Documents\ShareX\Backup\ApplicationConfig-2017-11-W45.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.BackupFileWeekly(String filepath, String destinationFolder)
   at ShareX.SettingManager.BackupSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 11.9.1 (Release)

**Comment by SWBennett06** [comment]
I'm also seeing this error and was not seeing it before the Creators Update, though that may be coincidental. Full debug log:

2017-12-28 12:37:57.546 - ShareX 12.0
2017-12-28 12:37:57.548 - Build: Release
2017-12-28 12:37:57.548 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2017-12-28 12:37:57.549 - Personal path: C:\Users\[NAME]\Documents\ShareX
2017-12-28 12:37:57.552 - Operating system: Windows 10 Pro
2017-12-28 12:37:57.608 - ApplicationConfig load started: C:\Users\[NAME]\Documents\ShareX\ApplicationConfig.json
2017-12-28 12:37:58.965 - ApplicationConfig load finished: C:\Users\[NAME]\Documents\ShareX\ApplicationConfig.json
2017-12-28 12:37:58.968 - UploadersConfig load started: C:\Users\[NAME]\Documents\ShareX\UploadersConfig.json
2017-12-28 12:37:58.971 - MainForm init started.
2017-12-28 12:37:59.446 - UploadersConfig load finished: C:\Users\[NAME]\Documents\ShareX\UploadersConfig.json
2017-12-28 12:37:59.449 - HotkeysConfig load started: C:\Users\[NAME]\Documents\ShareX\HotkeysConfig.json
2017-12-28 12:37:59.499 - HotkeysConfig load finished: C:\Users\[NAME]\Documents\ShareX\HotkeysConfig.json
2017-12-28 12:37:59.725 - MainForm init finished.
2017-12-28 12:38:01.431 - Startup time: 4170 ms
2017-12-28 12:38:01.751 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-12-28 12:38:01.751 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-12-28 12:38:01.751 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-12-28 12:38:01.752 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-12-28 12:38:01.755 - HotkeyManager started.
2017-12-28 12:38:01.756 - WatchFolderManager started.
2017-12-28 12:38:18.004 - Starting screen recording. Video encoder: "x264 (mp4)", Audio encoder: "AAC", FPS: 20
2017-12-28 12:38:40.812 - Exception:
System.IO.FileNotFoundException: Could not find file 'C:\Users\[NAME]\Documents\ShareX\Screenshots\2017-12'.
File name: 'C:\Users\[NAME]\Documents\ShareX\Screenshots\2017-12'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String path)
2017-12-28 12:38:51.477 - CLI: "C:\Users\[NAME]\Documents\ShareX\Tools\ffmpeg.exe" -y -rtbufsize 100M -f gdigrab -framerate 20 -offset_x 2879 -offset_y 487 -video_size 1920x1088 -draw_mouse 1 -i desktop -c:v libx264 -r 20 -preset ultrafast -tune zerolatency -crf 30 -pix_fmt yuv420p -movflags +faststart "C:\Users\[NAME]\Documents\ShareX\Screenshots\2017-12\2017-12-28_12-38-39.mp4"

**Comment by Jaex** [comment]
Now both Windows 10 and anti virus apps have protected folder feature which can block ShareX from creating files in Documents folder. Maybe your issue is to do with it.
