### ISSUE TITLE
Crash when capturing webpage

### ISSUE THREAD

**Issue by SanderBouwhuis** [ShareX/ShareX#2904]
**I get this crash when capturing a webpage https://bookofbadarguments.com/?view=allpages**

`System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.SaveImageAsPNGStream(Image img, Stream stream, PNGBitDepth bitDepth)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   at ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 11.9.1 Portable (Release)`

**This is in the log file:**

`2017-11-01 07:43:11.611 - Build: Release
2017-11-01 07:43:11.624 - Personal path: C:\Utilities\ShareX\ShareX
2017-11-01 07:43:11.687 - Command line: "C:\Utilities\ShareX\ShareX.exe" -silent
2017-11-01 07:43:11.709 - ShareX 11.9.1 Portable
2017-11-01 07:43:11.723 - Operating system: Windows 10 Pro
2017-11-01 07:43:11.742 - Flags: Portable, SilentRun
2017-11-01 07:43:11.749 - ApplicationConfig load started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 07:43:13.433 - ApplicationConfig load finished: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 07:43:13.461 - UploadersConfig load started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 07:43:13.510 - MainForm init started.
2017-11-01 07:43:13.925 - UploadersConfig load finished: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 07:43:13.949 - HotkeysConfig load started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 07:43:14.002 - HotkeysConfig load finished: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 07:43:14.094 - MainForm init finished.
2017-11-01 07:43:14.494 - Startup time: 3195 ms
2017-11-01 07:43:14.526 - CommandLine: silent
2017-11-01 07:43:14.864 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 07:43:14.899 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 07:43:14.947 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-01 07:43:14.981 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-01 07:43:15.014 - HotkeyManager started.
2017-11-01 07:43:15.058 - WatchFolderManager started.
2017-11-01 08:31:49.634 - ShareX 11.9.1 Portable
2017-11-01 08:31:49.665 - Build: Release
2017-11-01 08:31:49.728 - Personal path: C:\Utilities\ShareX\ShareX
2017-11-01 08:31:49.759 - Command line: "C:\Utilities\ShareX\ShareX.exe" -silent
2017-11-01 08:31:49.806 - Operating system: Windows 10 Pro
2017-11-01 08:31:49.915 - Flags: Portable, SilentRun
2017-11-01 08:31:49.947 - ApplicationConfig load started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 08:31:50.634 - ApplicationConfig load finished: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 08:31:50.665 - MainForm init started.
2017-11-01 08:31:50.681 - UploadersConfig load started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 08:31:51.009 - UploadersConfig load finished: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 08:31:51.056 - HotkeysConfig load started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 08:31:51.087 - HotkeysConfig load finished: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 08:31:51.165 - MainForm init finished.
2017-11-01 08:31:51.402 - Startup time: 2161 ms
2017-11-01 08:31:51.449 - CommandLine: silent
2017-11-01 08:31:53.308 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 08:31:53.324 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 08:31:53.355 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-01 08:31:53.386 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-01 08:31:53.418 - HotkeyManager started.
2017-11-01 08:31:53.449 - WatchFolderManager started.
2017-11-01 09:14:07.514 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 09:15:52.120 - Build: Release
2017-11-01 09:15:52.151 - Command line: "C:\Utilities\ShareX\ShareX.exe" -silent
2017-11-01 09:15:52.237 - ShareX 11.9.1 Portable
2017-11-01 09:15:52.256 - Personal path: C:\Utilities\ShareX\ShareX
2017-11-01 09:15:52.280 - Operating system: Windows 10 Pro
2017-11-01 09:15:52.321 - Flags: Portable, SilentRun
2017-11-01 09:15:52.352 - ApplicationConfig load started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 09:15:53.235 - ApplicationConfig load finished: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 09:15:53.256 - UploadersConfig load started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 09:15:53.290 - MainForm init started.
2017-11-01 09:15:53.562 - UploadersConfig load finished: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 09:15:53.617 - HotkeysConfig load started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 09:15:53.658 - HotkeysConfig load finished: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 09:15:53.694 - MainForm init finished.
2017-11-01 09:15:53.869 - Startup time: 1965 ms
2017-11-01 09:15:53.892 - CommandLine: silent
2017-11-01 09:15:54.220 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 09:15:54.257 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 09:15:54.275 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-01 09:15:54.304 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-01 09:15:54.335 - HotkeyManager started.
2017-11-01 09:15:54.365 - WatchFolderManager started.
2017-11-01 15:12:18.658 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 15:13:50.363 - ShareX 11.9.1 Portable
2017-11-01 15:13:50.410 - Personal path: C:\Utilities\ShareX\ShareX
2017-11-01 15:13:50.472 - Build: Release
2017-11-01 15:13:50.504 - Command line: "C:\Utilities\ShareX\ShareX.exe" -silent
2017-11-01 15:13:50.535 - Operating system: Windows 10 Pro
2017-11-01 15:13:50.566 - Flags: Portable, SilentRun
2017-11-01 15:13:50.597 - ApplicationConfig load started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 15:13:51.397 - ApplicationConfig load finished: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 15:13:51.412 - UploadersConfig load started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 15:13:51.459 - MainForm init started.
2017-11-01 15:13:51.819 - UploadersConfig load finished: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 15:13:51.850 - HotkeysConfig load started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 15:13:51.928 - HotkeysConfig load finished: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 15:13:52.209 - MainForm init finished.
2017-11-01 15:13:52.412 - Startup time: 2326 ms
2017-11-01 15:13:52.428 - CommandLine: silent
2017-11-01 15:13:54.303 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 15:13:54.319 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 15:13:54.350 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-01 15:13:54.397 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-01 15:13:54.428 - HotkeyManager started.
2017-11-01 15:13:54.490 - WatchFolderManager started.
2017-11-01 16:35:57.224 - Hotkey unregistered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 16:37:41.606 - Build: Release
2017-11-01 16:37:41.615 - Personal path: C:\Utilities\ShareX\ShareX
2017-11-01 16:37:41.657 - Command line: "C:\Utilities\ShareX\ShareX.exe" -silent
2017-11-01 16:37:41.667 - ShareX 11.9.1 Portable
2017-11-01 16:37:41.677 - Operating system: Windows 10 Pro
2017-11-01 16:37:41.684 - ApplicationConfig load started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 16:37:41.692 - Flags: Portable, SilentRun
2017-11-01 16:37:42.469 - ApplicationConfig load finished: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 16:37:42.482 - MainForm init started.
2017-11-01 16:37:42.493 - UploadersConfig load started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 16:37:42.763 - UploadersConfig load finished: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 16:37:42.773 - HotkeysConfig load started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 16:37:42.807 - HotkeysConfig load finished: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 16:37:42.889 - MainForm init finished.
2017-11-01 16:37:43.153 - Startup time: 1735 ms
2017-11-01 16:37:43.168 - CommandLine: silent
2017-11-01 16:37:43.474 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 16:37:43.480 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 16:37:43.491 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-01 16:37:43.504 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-01 16:37:43.512 - HotkeyManager started.
2017-11-01 16:37:43.526 - WatchFolderManager started.
2017-11-01 19:11:16.739 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 19:11:16.774 - Hotkey unregistered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-01 19:11:16.780 - Hotkey unregistered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-01 19:11:16.794 - Hotkey unregistered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 21:20:10.661 - Build: Release
2017-11-01 21:20:10.726 - ShareX 11.9.1 Portable
2017-11-01 21:20:10.746 - Personal path: C:\Utilities\ShareX\ShareX
2017-11-01 21:20:10.779 - Command line: "C:\Utilities\ShareX\ShareX.exe" -silent
2017-11-01 21:20:10.799 - Operating system: Windows 10 Pro
2017-11-01 21:20:10.853 - Flags: Portable, SilentRun
2017-11-01 21:20:10.888 - ApplicationConfig load started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 21:20:11.733 - ApplicationConfig load finished: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-01 21:20:11.771 - UploadersConfig load started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 21:20:11.780 - MainForm init started.
2017-11-01 21:20:12.085 - UploadersConfig load finished: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-01 21:20:12.109 - HotkeysConfig load started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 21:20:12.138 - HotkeysConfig load finished: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-01 21:20:12.233 - MainForm init finished.
2017-11-01 21:20:12.380 - Startup time: 1997 ms
2017-11-01 21:20:12.414 - CommandLine: silent
2017-11-01 21:20:12.729 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-01 21:20:12.758 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-01 21:20:12.785 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-01 21:20:12.792 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-01 21:20:12.798 - HotkeyManager started.
2017-11-01 21:20:12.819 - WatchFolderManager started.
2017-11-02 02:01:55.164 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-02 07:42:33.060 - Build: Release
2017-11-02 07:42:33.120 - Command line: "C:\Utilities\ShareX\ShareX.exe" -silent
2017-11-02 07:42:33.216 - ShareX 11.9.1 Portable
2017-11-02 07:42:33.247 - Personal path: C:\Utilities\ShareX\ShareX
2017-11-02 07:42:33.271 - Operating system: Windows 10 Pro
2017-11-02 07:42:33.302 - Flags: Portable, SilentRun
2017-11-02 07:42:33.335 - ApplicationConfig load started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 07:42:34.470 - ApplicationConfig load finished: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 07:42:34.492 - UploadersConfig load started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 07:42:34.516 - MainForm init started.
2017-11-02 07:42:34.782 - UploadersConfig load finished: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 07:42:34.806 - HotkeysConfig load started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 07:42:34.843 - HotkeysConfig load finished: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 07:42:34.946 - MainForm init finished.
2017-11-02 07:42:35.121 - Startup time: 2328 ms
2017-11-02 07:42:35.144 - CommandLine: silent
2017-11-02 07:42:35.459 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-02 07:42:35.483 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-11-02 07:42:35.497 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-11-02 07:42:35.504 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
2017-11-02 07:42:35.529 - HotkeyManager started.
2017-11-02 07:42:35.536 - WatchFolderManager started.
2017-11-02 08:34:30.992 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-02 08:34:31.026 - Executing: Capture region
2017-11-02 08:34:51.822 - Task in queue. Job: Job, Type: Image, Host: 
2017-11-02 08:34:51.831 - Task status: Preparing
2017-11-02 08:34:51.854 - Image saved to file: Z:\waterfox_2017-11-02_08-34-51.png
2017-11-02 08:34:51.863 - Running C:\Utilities\XnView\Addon\pngout.exe with arguments: "Z:\waterfox_2017-11-02_08-34-51.png"
2017-11-02 08:35:13.197 - Task completed. Filename: waterfox_2017-11-02_08-34-51.png, Duration: 21368 ms
2017-11-02 08:35:13.360 - UploadersConfig save successful: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 08:35:13.377 - UploadersConfig save started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 08:35:13.384 - HotkeysConfig save started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 08:35:13.399 - ApplicationConfig save started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 08:35:13.407 - HotkeysConfig save successful: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 08:35:13.431 - ApplicationConfig save successful: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 10:29:41.325 - Executing: Capture region
2017-11-02 10:29:41.332 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2017-11-02 10:29:56.723 - ApplicationConfig save started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 10:29:56.741 - UploadersConfig save started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 10:29:56.748 - HotkeysConfig save started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 10:29:56.837 - UploadersConfig save successful: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 10:29:56.854 - HotkeysConfig save successful: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 10:29:56.863 - ApplicationConfig save successful: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 10:31:10.425 - ApplicationConfig save started: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 10:31:10.444 - HotkeysConfig save started: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 10:31:10.476 - UploadersConfig save started: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 10:31:10.504 - UploadersConfig save successful: C:\Utilities\ShareX\ShareX\UploadersConfig.json
2017-11-02 10:31:10.521 - HotkeysConfig save successful: C:\Utilities\ShareX\ShareX\HotkeysConfig.json
2017-11-02 10:31:10.558 - ApplicationConfig save successful: C:\Utilities\ShareX\ShareX\ApplicationConfig.json
2017-11-02 10:36:34.319 - Task in queue. Job: Job, Type: Image, Host: 
2017-11-02 10:36:34.328 - Task status: Preparing
2017-11-02 10:36:34.351 - Unhandled exception:
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.SaveImageAsPNGStream(Image img, Stream stream, PNGBitDepth bitDepth)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   at ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 11.9.1 Portable (Release)
2017-11-02 10:36:49.751 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
`

**Comment by campbeb** [comment]
That error usually indicates that the image was too large to be processed.

**Comment by SanderBouwhuis** [comment]
Too large? I run the 64-bit version of ShareX and have 32GB RAM. So, it seems strange that an image can be too large. Is there some arbitrary limit in ShareX? If so, why?
