### ISSUE TITLE
Google Drive API Outdated

### ISSUE THREAD

**Issue by thebigben** [ShareX/ShareX#301]
Message:
The remote server returned an error: (400) Bad Request.

Response:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notUpload",
    "message": "Not an upload request. Re-send request to: https://www.googleapis.com/drive/v2/files"
   }
  ],
  "code": 400,
  "message": "Not an upload request. Re-send request to: https://www.googleapis.com/drive/v2/files"
 }
}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)

**Comment by Jaex** [comment]
Pull request of Kesmy #586 fixed this problem I think.
