### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'ShareX.UploadersLib.UploaderFactory' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

### ISSUE THREAD

**Issue by allday1** [ShareX/ShareX#3013]
System.TypeInitializationException: The type initializer for 'ShareX.UploadersLib.UploaderFactory' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ShareX.HelpersLib.Helpers.GetInstances[T]()
   at ShareX.UploadersLib.UploaderFactory.CacheServices[T,T2]()
   at ShareX.UploadersLib.UploaderFactory..cctor()
   --- End of inner exception stack trace ---
   at ShareX.UploadersLib.UploadersConfigValidator.Validate(ImageDestination destination, UploadersConfig config)
   at ShareX.MainForm.EnableDisableToolStripMenuItems[T](ToolStripDropDownItem[] parents)
   at ShareX.MainForm.UpdateDestinationStates()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HelpersLib.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.0 (Release)

**Comment by Jaex** [comment]
Library file could be corrupted. Can you try reinstalling ShareX.

**Comment by allday1** [comment]
Yes, a few times now

I've used ShareX for a few years now without any issues. Then all of the sudden I keep getting this on newest editions. Some of the features still work but most do not. Have to go to the very oldest versions for more capabilities (which of course don't have all of the features as 12.0)

**Comment by DogeAmazed** [comment]
Try to update .NET-Framework. If this also doesn't work, I would suggest to get every version and check where the error began.
