### ISSUE TITLE
Uploading content with apostrophes to text uploaders causes a JSON error

### ISSUE THREAD

**Issue by ic3w0lf22** [ShareX/ShareX#3042]
If you try uploading content with apostrophes in them, this error is thrown

```
Response parse failed.
Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: Y. Path '', line 1, position 58.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at ShareX.HelpersLib.Helpers.ParseJSON(String text, String jsonPath)
   at ShareX.UploadersLib.CustomUploaderItem.ParseSyntax(String syntax, Boolean output)
   at ShareX.UploadersLib.CustomUploaderItem.ParseURL(String url, Boolean output)
   at ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, Boolean isShortenedURL)
   at ShareX.UploadersLib.TextUploaders.CustomTextUploader.UploadText(String text, String fileName)

System.ArgumentException: Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

This is the error I get when I try uploading something with an apostrophe; here's an example of what I'm uploading.
print'Hello World!'

**Comment by v0l** [comment]
Where are you uploading this to?

**Comment by ic3w0lf22** [comment]
My custom site which gets the input from $_POST["source"]; since ShareX doesn't send php://input
