### ISSUE TITLE
Bitlocker activated - cannot take pictures

### ISSUE THREAD

**Issue by Imadlekal** [ShareX/ShareX#3068]
The folder where pictures are stored is on a Disk encrypted with Bitlocker. As soon as I run my computer (ShareX run on Startup), I receive an error message from ShareX. (It's understandable as It cannot access the encrypted disk).

However, even after I Unlock the disk and try to take pictures, I receive the following errors (sorry for not taking pictures as shareX is the only thing I use):

```
 --------------------------
 ShareX
 ---------------------------
 Could not create directory.
 
 
 
 System.UnauthorizedAccessException: Access to the path 'ShareX\Screenshots\2018-01' is denied.
 
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
 
    at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
 
    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
 
    at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String path)
 ---------------------------
 OK   
 ---------------------------
```

If I click OK, a new window shows with the following error:

```
---------------------------
ShareX
---------------------------
Could not write image to path ShareX\Screenshots\2018-01\ShareX_2018-01-09_13-53-45.png.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\ShareX\ShareX\Screenshots\2018-01\ShareX_2018-01-09_13-53-45.png'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

   at ShareX.HelpersLib.StreamExtensions.WriteToFile(Stream stream, String filePath)

   at ShareX.ImageData.Write(String filePath)
---------------------------
OK   
---------------------------
```
Finally, If I click OK again, I receive a message asking me If I want to upload it.

I also noticed that Its trying to write images on C:/ disk while the encrypted disk (where I'm storing the pictures) is D:

**Comment by Fyers** [comment]
I tried reproducing it. After an automatic startup I dont get an error, I get an error when I try to make a Screenshot (good so far).
When I then unlock the disk everything works normal, images are being saved on the encrypted disk.

As far as I tried to reproduce it should get the Folder from the Program.ScreenshotsFolder, as far as a AdvancedSettings CapturePath is not given.

So it should get the path you setup in the application settings... I dindt find anything that overwrites the Screenshot FolderPath on the startup or anything linke that.

What error message do you get on startup?

**Comment by Imadlekal** [comment]
Apparently, It can't create the folder "ShareX" (which is already created but ShareX can't check because the drive D is locked).

```
---------------------------
ShareX - Error
---------------------------
Unable to create folder: "ShareX"



System.UnauthorizedAccessException: Access to the path 'ShareX' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)

   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)

   at ShareX.Program.UpdatePersonalPath()
---------------------------
OK   
---------------------------
```

After clicking OK, another message shows:

```
---------------------------
ShareX
---------------------------
Could not create directory.



System.UnauthorizedAccessException: Access to the path 'ShareX\Logs' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)

   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)

   at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String path)
---------------------------
OK   
---------------------------
```

It's worth mentioning that ShareX is installed in **C:\Program Files\ShareX** (Drive is not locked) while Pictures are in ShareX folder in "Documents" which is on C by default in Windows but I changed it to D:

**Comment by Thepenguin9** [comment]
Could it be that the temp files etc are in the User folders, and they are protected by Bitlocker? Do you potentially have the anti-cryptolocker feature enabled
