### ISSUE TITLE
Upload errors

### ISSUE THREAD

**Issue by rakeshr** [ShareX/ShareX#3088]
Message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://picasaweb.google.com/data/feed/api/user/default/albumid/default

Response:
Internal error, try again later

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

**Comment by Niflxeim** [comment]
yep, i still have the same problem. I used Google Photos, updated Authentification, but anyway, have this issue.

**Comment by darkufo** [comment]
Yep same here.

**Comment by Jaex** [comment]
#3087

**Comment by thedanioner** [comment]
I also have the same error, any solution?
