### ISSUE TITLE
cant use OCR

### ISSUE THREAD

**Issue by bertelu** [ShareX/ShareX#3151]
OCR seems not working. the OCR window is opening but nothing happen
in the log i found:
Request URL:
https://apipro1.ocr.space/parse/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2018-02-16 13:51:52.465 - Error:
Message:
This request requires buffering data to succeed.

any suggestion?

thanks

**Comment by Jaex** [comment]
It works currently for me. Maybe it was temporary down.

**Comment by bertelu** [comment]
just tried. is not working. but if i go to the OCR website i can paste my screenshot and get the text. it should be something in my PC setting. does the log mean anything?

**Comment by stuntguy3000** [comment]
@bertelu Are you still having issues?

**Comment by Williamye88** [comment]
have the issue while trying to do screenshot. error appears - this request requires buffering data
