### ISSUE TITLE
Unable to upload to Gfycat

### ISSUE THREAD

**Issue by Firefox4312** [ShareX/ShareX#3154]
I've searched a bit, and haven't been able to get a good answer on it (that's fixed it I should say). Up until a couple days ago (might've happened longer than that, I rarely upload to gfycat through sharex), I've no longer been able to upload to gfycat.

Le error:

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (503) Server Unavailable.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, Stream dataStream, String contentType)

**Comment by Jaex** [comment]
It returns: `(503) Server Unavailable.`

So not to do with ShareX.
