### ISSUE TITLE
Can't download ffmpeg for GIF s

### ISSUE THREAD

**Issue by dannyss6** [ShareX/ShareX#3189]
I'd have made a gif out of that bug but i can't.
![ef25a30ba0 1](https://user-images.githubusercontent.com/6634309/37259233-0b849210-255a-11e8-95ab-3846fa99c5c9.png)

log : 

System.IO.IOException: The process cannot access the file 'C:\Users\f-rog\AppData\Local\Temp\ShareX\ffmpeg.7z' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ShareX.HelpersLib.DownloaderForm.StartDownload()
   at ShareX.HelpersLib.DownloaderForm.DownloaderForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

ShareX 12.0 (Release)

**Comment by dannyss6** [comment]
Looks like the 7z version is no longer hosted. Need a fast patch pls.

**Comment by dannyss6** [comment]
Downloading the file and putting it myself into the tools folder fixed it for now. I also had to change my username in my config files because i recently reinstalled windows. The issue is still there tho.

**Comment by Scrxtchy** [comment]
This has been fixed, but the update has not been published
https://github.com/ShareX/ShareX/blob/71c357ed489d8b0a69720cacf73d5428b3c097a1/ShareX.MediaLib/FFmpegDownloader.cs

If you are using the generic desktop version, you can download a working build from appveyor
https://ci.appveyor.com/project/ShareX/sharex/build/job/sxkc6pjlm6iqjcgx/artifacts

**Comment by Jaex** [comment]
https://getsharex.com/docs/dev-builds

**Comment by PeterWxin** [comment]
Thanks!
It should download a ZIP file instead of .7z now.

**Comment by seocliffdev** [comment]
I had comodo Firewall installed. Unblockin ffmpeg seems solved the problem.
