### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by GingeyBook** [ShareX/ShareX#3219]
Nothing will upload

[ShareX-Log-2018-03.txt](https://github.com/ShareX/ShareX/files/1840111/ShareX-Log-2018-03.txt)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/oauth2/token

Response:
{"data":{"error":"Invalid refresh token","request":"\/oauth2\/token","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)

Refresh access token failed.

**Comment by Jaex** [comment]
Re authenticate Imgur from destination settings window. Somehow refresh token become invalid.
