### ISSUE TITLE
Get error every time I take a screenshot

### ISSUE THREAD

**Issue by USAPaulQ** [ShareX/ShareX#3275]
I get two errors about inability to access directories every time I take a screenshot. I have tried uninstall, reinstall. Still happens. Any way around it? Thanks!

Windows 10 Pro.

This is the report it generations:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\ShareX\Backup\ApplicationConfig-2018-04-W13.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.BackupFileWeekly(String filepath, String destinationFolder)
   at ShareX.SettingManager.BackupSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 12.1.1 (Release)

**Comment by Jaex** [comment]
Did you change personal path option? It is set to program files folder which ShareX can't write to.

**Comment by USAPaulQ** [comment]
It's working now. I had uninstall and reinstall twice.... I used Revo to
clear it out. Not sure what was wrong. I didn't have it changed to any
locked folders.

Thanks!

Paul
