### ISSUE TITLE
Upload Error with .mp4

### ISSUE THREAD

**Issue by Elmuti** [ShareX/ShareX#3299]
**Uploading any .mp4 file to any of the available default services (streamable, gfycat, etc.)
results in an upload error.**

**Here are the logs:**
https://gist.github.com/Elmuti/6adea7fc02b124cd1980d419b190e35e

**Here is the full error:**

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Request URL:
https://api.streamable.com/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary 2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by matthewburnett** [comment]
Is this on your home network?
Do you have antivirus that may be scanning secure traffic?
Have you tried reinstalling sharex?
Can you directly upload the video through the website?

**Comment by Elmuti** [comment]
Yes its on my home network
I tried disabling my antivirus due to your suggestion, did not fix it
Yes actually that log was on an older version, I just installed the newest stable version and its still happening
Yes I can upload directly via their website, just not through ShareX
