### ISSUE TITLE
sftp upload fails if `URL path` option contains non-ascii characters

### ISSUE THREAD

**Issue by bl1nk** [ShareX/ShareX#3331]
When using non-ascii characters in the `URL path` field in FTP/FTPS/SFTP settings uploads will fail with

```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.UriBuilder.get_Uri()
   at ShareX.UploadersLib.FTPAccount.GetUriPath(String filename, String subFolderPath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.UriBuilder.get_Uri()
   at ShareX.UploadersLib.FTPAccount.GetUriPath(String filename, String subFolderPath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

**Comment by KSib** [comment]
Do you have an example of the URL path? It sounds more like there's a space or something between the http:// and the hostname or something, but there's not enough info here.

**Comment by bl1nk** [comment]
You can try any non-ascii character in the url, for example `bücher.example.com`. Browsers will translate it to punycode, in that case `xn--bcher-kva.example.com`.
