### ISSUE TITLE
GDI+ Generic Error while merging 92 images

### ISSUE THREAD

**Issue by Bluscream** [ShareX/ShareX#3367]
![](https://i.imgur.com/PcY7GJu.png)

```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.TaskHelpers.SaveImageAsPNGStream(Image img, Stream stream, PNGBitDepth bitDepth)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   at ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 12.1.1 (Release)
```

**Comment by campbeb** [comment]
See #1871
