### ISSUE TITLE
I'm sorry if this is a repeated submission. I tried searching for it, but couldn't find anything.

### ISSUE THREAD

**Issue by denismattos** [ShareX/ShareX#3379]
ShareX is crashing when initiated.
The error log displayed is:

    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.IndexerLib, Version=12.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
       at ShareX.TaskSettingsTools..ctor()
       at ShareX.TaskSettings..ctor()
       at ShareX.ApplicationConfig..ctor()
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
       at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance[T]()
       at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
       at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
       at ShareX.SettingManager.LoadApplicationConfig()
       at ShareX.SettingManager.LoadInitialSettings()
       at ShareX.Program.Run()
       at ShareX.Program.Main(String[] args)
    
    ShareX 12.1.1 (Steam)
Can anyone point me to a solution to this problem?

Much obliged.

**Comment by denismattos** [comment]
I had tried that before and it didn't work.
I did it again, this time making sure to delete every file besides captured items and logs.
Now it works! =)

Thanks for the quick and effective response.
Be well.
