### ISSUE TITLE
ShareX Issue (Cannot Upload to Google Photos)

### ISSUE THREAD

**Issue by MrCD1968** [ShareX/ShareX#3422]
Is this an issue with ShareX or Google?

-----

Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Request URL:
https://accounts.google.com/o/oauth2/token

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
2018-05-23 15:43:21.996 - GooglePhotosAuthOpen - Authorization URL is opened: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=810697162603-ag350u1fnmf3riubv91otme0v5fkk2d6.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https%3A%2F%2Fpicasaweb.google.com%2Fdata
2018-05-23 15:43:22.043 - URL opened: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=810697162603-ag350u1fnmf3riubv91otme0v5fkk2d6.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https%3A%2F%2Fpicasaweb.google.com%2Fdata
2018-05-23 15:44:29.466 - Error:
Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Request URL:
https://accounts.google.com/o/oauth2/token

**Comment by MrCD1968** [comment]
just an update... still not uploading.  Cannot login to Google Photos with credentials saved in ShareX- says login failed.

Request URL:
https://accounts.google.com/o/oauth2/token

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
2018-05-23 22:20:56.035 - UploadersConfig save started: C:\Users\user\Documents\ShareX\UploadersConfig.json
2018-05-23 22:20:56.098 - UploadersConfig save successful: C:\Users\user\Documents\ShareX\UploadersConfig.json
2018-05-23 22:26:07.119 - URL opened: https://accounts.google.com/o/oauth2/token
2018-05-23 22:33:37.299 - ApplicationConfig save started: C:\Users\user\Documents\ShareX\ApplicationConfig.json
2018-05-23 22:33:37.299 - UploadersConfig save started: C:\Users\user\Documents\ShareX\UploadersConfig.json
2018-05-23 22:33:37.299 - HotkeysConfig save started: C:\Users\user\Documents\ShareX\HotkeysConfig.json
2018-05-23 22:33:37.392 - UploadersConfig save successful: C:\Users\user\Documents\ShareX\UploadersConfig.json
2018-05-23 22:33:37.445 - HotkeysConfig save successful: C:\Users\user\Documents\ShareX\HotkeysConfig.json
2018-05-23 22:33:37.445 - ApplicationConfig save successful: C:\Users\user\Documents\ShareX\ApplicationConfig.json
2018-05-24 18:04:31.334 - Hotkey unregistered: Hotkey: Ctrl + Page Up, Description: Clipboard Upload, Job: ClipboardUpload
2018-05-24 18:06:40.187 - ShareX 12.1.1
2018-05-24 18:06:40.187 - Build: Release
2018-05-24 18:06:40.187 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2018-05-24 18:06:40.187 - Personal path: C:\Users\user\Documents\ShareX
2018-05-24 18:06:40.187 - Operating system: Windows 10 Pro
2018-05-24 18:06:40.187 - Flags: SilentRun
2018-05-24 18:06:40.234 - ApplicationConfig load started: C:\Users\user\Documents\ShareX\ApplicationConfig.json
2018-05-24 18:06:40.781 - ApplicationConfig load finished: C:\Users\user\Documents\ShareX\ApplicationConfig.json
2018-05-24 18:06:40.781 - UploadersConfig load started: C:\Users\user\Documents\ShareX\UploadersConfig.json
2018-05-24 18:06:40.781 - MainForm init started.
2018-05-24 18:06:40.953 - UploadersConfig load finished: C:\Users\user\Documents\ShareX\UploadersConfig.json
2018-05-24 18:06:40.953 - HotkeysConfig load started: C:\Users\user\Documents\ShareX\HotkeysConfig.json
2018-05-24 18:06:40.999 - HotkeysConfig load finished: C:\Users\user\Documents\ShareX\HotkeysConfig.json
2018-05-24 18:06:41.312 - MainForm init finished.
2018-05-24 18:06:41.484 - Startup time: 1338 ms
2018-05-24 18:06:41.484 - CommandLine: silent
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Ctrl + Page Up, Description: Clipboard Upload, Job: ClipboardUpload
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Shift + Page Up, Description: File Upload, Job: FileUpload
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Print Screen, Description: Fullscreen, Job: PrintScreen
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Active Window, Job: ActiveWindow
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Ctrl + Alt + Print Screen, Description: Active Monitor, Job: ActiveMonitor
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Window & Rectangle, Job: RectangleRegion
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Ctrl + Insert, Description: Rectangle Region, Job: RectangleRegion
2018-05-24 18:06:41.499 - Hotkey registered: Hotkey: Shift + F11, Description: Screen Recorder, Job: ScreenRecorder
2018-05-24 18:06:41.499 - HotkeyManager started.
2018-05-24 18:06:41.499 - WatchFolderManager started.
2018-05-24 18:06:44.280 - Exception:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.NewsManager.GetNews()
   at ShareX.NewsManager.UpdateNews()
2018-05-24 21:15:42.760 - URL opened: https://github.com/ShareX/ShareX
2018-05-24 21:22:58.581 - GooglePhotosAuthOpen - Authorization URL is opened: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=810697162603-ag350u1fnmf3riubv91otme0v5fkk2d6.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https%3A%2F%2Fpicasaweb.google.com%2Fdata
2018-05-24 21:22:58.604 - URL opened: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=810697162603-ag350u1fnmf3riubv91otme0v5fkk2d6.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=https%3A%2F%2Fpicasaweb.google.com%2Fdata
2018-05-24 21:24:06.796 - Error:
Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

**Comment by Jaex** [comment]
I can't reproduce your issue. Maybe try dev build: https://getsharex.com/docs/dev-builds

**Comment by MrCD1968** [comment]
**UPDATE:** I downloaded ShareX to another PC and was able to paste the Google Photos code and complete authorization and that logged me in and allowed ShareX rights.  I was also able to perform CTRL PRINT SCREEN to successfully upload a photo. Logically, this seems now to be an issue specific to my PC and not with SHAREX ON ANOTHER PC.  With that in fact what would you recommend?  I don't  want to lose all my settings. Do I need to reinstall? Does the SHAREX log offer any insight into what is going on?

**Comment by MrCD1968** [comment]
Dev Build 12.2 did not affect any change. I still cannot use Google Photos via ShareX .  Since Jaex says he cannot reproduce the issue and I was able to successfully use ShareX on another PC (both systems are Windows 10) I can no longer use ShareX on this PC.

**Comment by MrCD1968** [comment]
Issued resolved. Just don't know how.
