### ISSUE TITLE
Error when uploading a captured GIF.

### ISSUE THREAD

**Issue by wowweemip-fan** [ShareX/ShareX#3448]
Copy from the error panel:
https://pastebin.com/XcqfdFzb

**Comment by Jaex** [comment]
Pastebin is blocked in my country.

**Comment by bakapear** [comment]
Error log from pastebin:
```
Message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
http://api.tinypic.com/api.php

Response:

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Service Unavailable</title>
  </head>
  <body>
    <h1>Error 503 Service Unavailable</h1>
    <p>Service Unavailable</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 2277404869</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```
