### ISSUE TITLE
Pomf.me error??

### ISSUE THREAD

**Issue by wowweemip-fan** [ShareX/ShareX#3462]
Message:
Unable to connect to the remote server

Request URL:
https://pomf.pyonpyon.moe/upload.php

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by trollmad3** [comment]
![image](https://user-images.githubusercontent.com/7843719/41824102-3dde9fba-77c8-11e8-8d6c-fe920187fcae.png)
It works fine for me.

**Comment by wowweemip-fan** [comment]
Updating this topic to say it DOES work, but it's a malicious URL.
