### ISSUE TITLE
Access to the path 'C:\Users\(my name)\Documents\ShareX\Backup\ApplicationConfig-2018-06-W26.json' is denied

### ISSUE THREAD

**Issue by phantomelon** [ShareX/ShareX#3483]
System.UnauthorizedAccessException: Access to the path 'C:\Users\(my name)\Documents\ShareX\Backup\ApplicationConfig-2018-06-W26.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.BackupFileWeekly(String filepath, String destinationFolder)
   at ShareX.SettingManager.BackupSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 12.1.1 (Release)

**Comment by Kiwi-1995** [comment]
Check folder/file permissions.
Anti Virus?
Exception made for said anti-virus?
Tried running it as admin(dragons ahead not recommended) and see if it saves?(If so go back to 1)

**Comment by Jaex** [comment]
It is always anti virus.
