### ISSUE TITLE
Error When Opening ShareX - 12.2 (Release)

### ISSUE THREAD

**Issue by Wuff95** [ShareX/ShareX#3484]
Tried opening up ShareX after it updated earlier today, and got this error message pop up:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.MediaLib, Version=12.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 12.2 (Release)

have no clue where the problem lies.

**Comment by jasewatson** [comment]
Reverted to 12.1.1, no issues

**Comment by Kakeb141** [comment]
Same here

**Comment by ShiroHakane** [comment]
same issue here
