### ISSUE TITLE
can't start ShareX

### ISSUE THREAD

**Issue by MrSheldon** [ShareX/ShareX#3492]
System.Reflection.TargetInvocationException: יעד הפעלה התריע על חריג. ---> System.BadImageFormatException: לא היתה אפשרות לטעון קובץ או הרכבה 'ShareX.MediaLib, Version=12.2.0.0, Culture=neutral, PublicKeyToken=null' או אחת מהתלויות שלו. המערכת ציפתה שהמודול יכיל מניפסט הרכבה.
   ב-  ShareX.TaskSettingsTools..ctor()
   ב-  ShareX.TaskSettings..ctor()
   ב-  ShareX.ApplicationConfig..ctor()
   --- סוף רכיב מעקב אחר מחסנית של מצב חריג פנימי ---
   ב-  System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   ב-  System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   ב-  System.Activator.CreateInstance[T]()
   ב-  ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   ב-  ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   ב-  ShareX.SettingManager.LoadApplicationConfig()
   ב-  ShareX.SettingManager.LoadInitialSettings()
   ב-  ShareX.Program.Run()
   ב-  ShareX.Program.Main(String[] args)

ShareX 12.2 (Release)

**Comment by Ramlock** [comment]
Same here:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.MediaLib, Version=12.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsTools..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 12.2 (Release)
