### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Peposobhy** [ShareX/ShareX#3524]
Bad API request, maximum paste file size exceeded

System.ArgumentException: Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Any help, please?

**Comment by FurkanKambay** [comment]
[ShareX last line](https://github.com/ShareX/ShareX/blob/bd644a195078d6b10aa0debd51ad83420353482d/ShareX.UploadersLib/BaseUploaders/TextUploader.cs#L35)
[last line at System.IO.StreamReader](https://referencesource.microsoft.com/#mscorlib/system/io/streamreader.cs,167)

The exception was thrown by the clause `if (!stream.CanRead)`: The property `CanRead` of the `Stream` you passed was `false`.

From [Stream.CanRead docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canread?view=netframework-4.6.2):
>When overridden in a derived class, gets a value indicating whether the current stream supports reading.
