### ISSUE TITLE
imgur upload error

### ISSUE THREAD

**Issue by tilerthps** [ShareX/ShareX#3527]
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment]
Duplicate of #3526
