### ISSUE TITLE
Unable to upload to imgur

### ISSUE THREAD

**Issue by dotexev2** [ShareX/ShareX#3594]
Any image/gif i take shows this error:
Message:
Unable to connect to the remote server

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by trollmad3** [comment]
Link is working fine for me. 
![image](https://user-images.githubusercontent.com/7843719/44542816-25f22c00-a6cb-11e8-9dc8-ed4baf8b9626.png)
