### ISSUE TITLE
Clipboard Copy Image Failures over 50% of the time

### ISSUE THREAD

**Issue by bricep** [ShareX/ShareX#3606]
This has been an issue for me across several versions... half the time that I take a screenshot, the capture does not become available to the clipboard. I have no other screenshot programs running. I am on Windows 10 and have a custom screenshot key combination set (so no other programs are trying to take a screenshot at the same time)

From the debug log:

2018-08-29 12:26:06.509 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img)

**Comment by Hecker9** [comment]
I have the same problem and after a little testing what I found out is that this happens once after every start of ShareX.
This means it usually happens once after I boot my pc but if I restart ShareX it happens again.
Sometimes it happens twice. Once with simple copy and once when I try to edit before I copy
