### ISSUE TITLE
FTP/TLS Handshake fail

### ISSUE THREAD

**Issue by Zylon** [ShareX/ShareX#3635]
I'm getting an error trying to connect to my VSFTPD server with TLS 1.2 and 1.1
Connecting to the server goes fine on other clients like FileZilla. But when trying to test my connection with ShareX. I get the following error:
The handshake failed due to an unexpected packet format.

Turning off TLS 1.2 and turning on TLS 1.0 works just fine.

Log when failing to upload:
```
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.Disconnect()

System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect()
   at ShareX.UploadersLib.FileUploaders.FTP.Connect()
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

**Comment by tinybarks** [comment]
I've checked the version of FluentFTP in ShareX and it seems as though it's out of date and doesn't support TLS 1.2. I'll see what I can do about it.

**Comment by Zylon** [comment]
>           I've checked the version of FluentFTP in ShareX and it seems like the issue is related to that. I'll see what I can do about it.

Thanks, I wanted to add that TLS 1.2 works fine when I use a FileZilla server.
So the problem appears to be rather specific.

But thanks for the response!

**Comment by tinybarks** [comment]
Actually, it is most likely that the FileZilla server allows downgrading to TLS 1.0. 

Been testing TLS support in ShareX by running OpenSSL s_server with settings that only allow it to support one protocol at a time:

```
$ openssl s_server -port +1234 -key cert.key -cert cert.crt -tls1_2
- or - 
$ openssl s_server -port +1234 -key cert.key -cert cert.crt -tls1_1
- or - 
$ openssl s_server -port +1234 -key cert.key -cert cert.crt -tls1
- or - 
$ openssl s_server -port +1234 -key cert.key -cert cert.crt -no_tls1 -no_tls1_1 -no_tls1_2
```

and trying to connect to it with the FTP client in ShareX in implicit mode (which tries to establish a secure connection immediately). ShareX will only connect via TLS 1.0. Looking into the code, it would also connect via SSL 3.0, but FluentFTP uses native secure sockets and Windows 10 1607 and up appear to disable support for this.

I'm submitting a PR momentarily that will enable higher TLS versions and allow you to configure the acceptable range of TLS versions for a FTP account, defaulting to a minimum of TLS 1.2.

**Comment by tinybarks** [comment]
Still waiting on @Jaex for a merge.

**Comment by Zylon** [comment]
I see, I can also enable multiple TLS versions on VSFTPD, by turning all 3 of them on.
And the client will automatically use the version it can use (so filezilla indeed used 1.2, while sharex would default to 1.0).

Anyway, big thanks for clearing this up, AND even making a PR.
Couldn't have wanted more.
I'm sure I'm not the only one benefiting from TLS 1.2!

Again, thanks a lot!

**Comment by tinybarks** [comment]
Unfortunately, Jaex is now refusing to work with me or accept my contributions. Due to the fault of the chief maintainer, the PR went into a state that cannot be merged. The maintainers have shown refusal to collaborate with contributors and do not seem interested in solving issues that may hinder open source contributions, issues that include severely lacking communication. 

Sadly, this situation means that I cannot fix the PR or make any further contributions to ShareX. Contributions I made to this repository will remain licensed under GPLv3, and out of respect for the spirit of open source software, I do not and will not have any interest in granting further rights or relicensing that code.
