### ISSUE TITLE
Images won't upload

### ISSUE THREAD

**Issue by Whifph** [ShareX/ShareX#3683]
i just keep getting errors
`Message:
Unable to connect to the remote server`

`Request URL:
https://api.imgur.com/3/image`

`Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary(Grave accent)2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)`

**Comment by Whifph** [comment]
[ShareX-Log-2018-10.txt](https://github.com/ShareX/ShareX/files/2499346/ShareX-Log-2018-10.txt)

**Comment by stuntguy3000** [comment]
What happens if you visit [https://api.imgur.com/3/image](https://api.imgur.com/3/image) in your browser?

**Comment by trollmad3** [comment]
![screenshot 2018-10-24 at 10 33 16 am](https://user-images.githubusercontent.com/7843719/47446321-3af54500-d778-11e8-8aed-7590587def50.png)
@stuntguy3000 That URL appears to be down.

**Comment by Whifph** [comment]
> 
> 
> ![screenshot 2018-10-24 at 10 33 16 am](https://user-images.githubusercontent.com/7843719/47446321-3af54500-d778-11e8-8aed-7590587def50.png)
> @stuntguy3000 That URL appears to be down.

how do i change the url

**Comment by trollmad3** [comment]
@Whifph You cant. (to my knowledge)
