### ISSUE TITLE
Paste from screen capture sometimes fails

### ISSUE THREAD

**Issue by SimonKravis** [ShareX/ShareX#3700]
When capturing region with hotkey and pasting, paste sometimes fails on Clipboard copy as shown in log below. Repeating the Capture-Paste usually succeeds. Other screen capture tools have had the same problem. Running Win10 Pro. 

- Hotkey triggered. Hotkey: Ctrl + F10, Description: Capture region, Job: RectangleRegion
2018-10-31 16:22:51.278 - Executing: Capture region
2018-10-31 16:22:55.807 - Task in queue. Job: Job, Type: Image, Host: 
2018-10-31 16:22:55.807 - Task status: Preparing
2018-10-31 16:22:58.186 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img)
2018-10-31 16:22:58.186 - Image copied to clipboard.
2018-10-31 16:22:58.186 - Task completed. Filename: explorer_2018-10-31_16-22-55.bmp, Duration: 2379 ms
2018-10-31 16:22:58.186 - UploadersConfig save started: C:\Users\Simon\Documents\ShareX\UploadersConfig.json
2018-10-31 16:22:58.186 - ApplicationConfig save started: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
2018-10-31 16:22:58.503 - UploadersConfig save successful: C:\Users\Simon\Documents\ShareX\UploadersConfig.json
2018-10-31 16:22:58.542 - HotkeysConfig save started: C:\Users\Simon\Documents\ShareX\HotkeysConfig.json
2018-10-31 16:22:58.649 - ApplicationConfig save successful: C:\Users\Simon\Documents\ShareX\ApplicationConfig.json
2018-10-31 16:22:58.738 - HotkeysConfig save successful: C:\Users\Simon\Documents\ShareX\HotkeysConfig.json

**Comment by Jaex** [comment]
> Other screen capture tools have had the same problem.

How is it to do with ShareX then? Not to mention ShareX retries to set clipboard 20 times and even if it still fails then it means problem is not to do with ShareX.

**Comment by stuntguy3000** [comment]
No response from OP and mentioned as problem outside application, could probably be closed @Jaex
