### ISSUE TITLE
Font Arial does not support Regular style

### ISSUE THREAD

**Issue by ThatSava** [ShareX/ShareX#374]
I think that everything is said in the title.
The error appears after an image has been uploaded(to imgur in my case)
The error occurs when the tiny preview window tries to add text with the link to it.

```
System.ArgumentException: Font 'Arial' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at ShareX.NotificationForm..ctor(Int32 duration, ContentAlignment placement, Size size, NotificationFormConfig config)
   at ShareX.NotificationForm.Show(Int32 duration, ContentAlignment placement, Size size, NotificationFormConfig config)
   at ShareX.TaskManager.task_UploadCompleted(UploadTask task)
   at ShareX.UploadTask.OnUploadCompleted()
```

I have tried everything from custom builds to opening every single setting in ShareX and tweaking it.
QuickFix would also be appreciated ;)

**Comment by roovyshapiro** [comment]
I had the same issue with "Font 'Arial' does not support style 'Regular'."

If you go to the fonts section in windows control panel:
Control Panel\Appearance and Personalization\Fonts\Arial
You can see the font that is missing:
http://i.imgur.com/HaNqXee.png

I stumbled onto this link from microsoft to update my computer's fonts and it fixed the problem immediately. https://www.microsoft.com/en-us/download/details.aspx?id=16083

**Comment by madrbperu** [comment]
Wait a minute, I have the Arial font and I still get the error, OWN UP guys...!

![image](https://user-images.githubusercontent.com/49217274/82964269-aa519d00-9f8a-11ea-829c-8952520a874c.png)

**Comment by madrbperu** [comment]
Nevermind, it was exclusively the Arial Regular, ok.
