### ISSUE TITLE
Upload error to pomf based servers

### ISSUE THREAD

**Issue by colpocleisis** [ShareX/ShareX#3748]
Message:
The underlying connection was closed: An unexpected error occurred on a send.

Request URL:
https://pomf.cat/upload.php

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Machine: windows 10 x64
Uploading from browser works fine.
Upload to imgur works fine
getting this error trying to upload to any of the pomf based servers.

ShareX version: 12.3

**Comment by Jaex** [comment]
I tried uploading to pomf.cat it worked, but result URL not opens in my browser.
