### ISSUE TITLE
Error when uploading to GPhotos

### ISSUE THREAD

**Issue by panthersdude2001** [ShareX/ShareX#3900]
I have been recieving an error for the past several days, with the last photo being uploaded on the 12th of January, before GPhotos API shut down.
The message is below.
The Picasa API is deprecated. See https://developers.google.com/picasa-web/ for more details and the migration guide.

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
Is this going to be fixed? If not, I will NOT be using your program EVER again!

**Comment by TheZebstrike** [comment]
Lol i have the exact same problem, just posted a new issue without looking at others and found this...
