### ISSUE TITLE
Google Photos / Picasa API deprecated

### ISSUE THREAD

**Issue by mbukovac** [ShareX/ShareX#3906]
Hi, it seems that Picasaweb API has been deprecated by Google, so uploads to Google Photos stopped working. Any idea when we can expect an update to current Google Photos API? Thanks.

`
2019-01-23 14:42:17.127 - Task failed. Filename: ApplicationFrameHost_2019-01-23_14-42-12.png, Errors:
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://picasaweb.google.com/data/feed/api/user/default/albumid/6400746052733302785

Response:
The Picasa API is deprecated. See https://developers.google.com/picasa-web/ for more details and the migration guide.

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
`

**Comment by Jaex** [comment]
Duplicate of #3884
