### ISSUE TITLE
Error 500 When Uploading to GPhotos

### ISSUE THREAD

**Issue by ghost** [ShareX/ShareX#3911]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate

Response:
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate

Response:

After the 400 error being fixed, now its giving me a 500 Error.
Please fix right away.

**Comment by panthersdude2001** [comment]
https://lh3.googleusercontent.com/mGdRbG-c4xUVMIfrRePnkfa_xHhKVJycJzAlejXhY0h1pYdHCvhXXsmbKydHJy2aH4kzHVE41HyTx9E3lXzoYibH7D9Gsqh53FLo4uIpS58x2tpE6RmK9rfvIIxvVP0n8BjJsrIharkCsrIIMzeYWrrkJS2L6BTdvI8Ln_w-1aCdn727Hb0hSqekQzIQA3qlxKv-DXel9dA0hvd_Z8WQVeJ8FWmHJubLtifyM74FcEkSDOGj4m6BYFm8NfmcxNUQ1UsVYnj2BKeQyKGvKmQvSGHqQVkNQGhxZrJA0G6TlhwlVK_nXbIuo2WZrgonF-GCstg6HAxDNdWONd6r_DdtS8iiEHzSJeClLuTxGggOFyXra4o6P4hECNP-cWFanDS4Ojvg-EakTP_Mi9DlaCopV5_kJP4yzjxSqc9Ww1HThdYxGKnc8Zm41ykg4QuX-VCHLZA-MJVQd3NKtrs7zfVg-EbJ9LqFbMJzA2_5d_GyhERKG2ZNXG81EVEKIjWfW1owLlxxZbPL2XnZ6A6ko0gKO3M7NI5LjKegUkJFnzaSIz9277rs8UD70fXE3WUOZpPjYwYma0MWIITJzMdXu7Iit0P1KtDc9l9EwEEOB4Gw2Pz_LoVLhKRTWDNUBzom9cjB3AWYhyl0gSbo4OAmMA_92x0DTywijZt5MktmJjD2FL60kGXUXmpYgMUg7irwpjOmXuSZdgenbec4VRtBV8njWN_nSz_y3R7YKaViv5LxdYuZwVmGqaHdAraPTCuKfbGb9Twq4yuhE4FO52mhVqr5GniZEgyGb5nMQeTX9KrmJwLmSBwYGw=s256-no
Can you see this?
