### ISSUE TITLE
Error uploading to Youtube

### ISSUE THREAD

**Issue by vRobM** [ShareX/ShareX#3918]
Added Youtube as destination. Requested key, pasted key, logged in.

Uploading to Youtube failed with an unauthorized message.

Debug log:
Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2019-01-28 21:17:51.711 - Upload failed. Retrying upload.
2019-01-28 21:17:55.422 - Error:
Message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://www.googleapis.com/upload/youtube/v3/videos

Response:
{
 "error": {
  "errors": [
   {
    "domain": "youtube.header",
    "reason": "youtubeSignupRequired",
    "message": "Unauthorized",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Unauthorized"
 }
}

**Comment by vRobM** [comment]
is anyone going to comment or take a look?

**Comment by TheDemystifier** [comment]
Had this happen multiple times. Uploading small videos is okay, but over 100MB is a no-no.
Not only that, Whenever I go about re-authorizing, Youtube asks me to verify my account with phone number because of 'unusual activity'.

```
Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://www.googleapis.com/upload/youtube/v3/videos?part=id,snippet,status

Status code:
(401) Unauthorized

Headers:
X-GUploader-UploadID: 
Vary: Origin,X-Origin
Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
Content-Length: 249
Content-Type: application/json; charset=UTF-8
Date: Wed, 18 Sep 2019 14:22:08 GMT
Server: UploadServer
WWW-Authenticate: Bearer realm="https://accounts.google.com/", error=invalid_token

Response text:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```
