### ISSUE TITLE
I can't check the "Run ShareX when Windows starts" option

### ISSUE THREAD

**Issue by LOuroboros** [ShareX/ShareX#3983]
Long story short, I want to make ShareX run whenever Windows boots, but as soon as I try to check the "Run ShareX when Windows starts" box in Application Settings > Integration, it unchecks itself right away.
![2019-02-27_20-15-25](https://user-images.githubusercontent.com/4485172/53529854-c424db80-3acc-11e9-93df-489c04428a06.gif)

I'm using ShareX Portable v12.4.1 on Windows 8.1 _(64 Bits)_.

**Comment by HazyHills** [comment]
I am having the same issue.

Win 10 
ShareX 12.4.1

It will no longer start with Windows and the option can not be ticked.

https://puu.sh/CYtrI/c6ad492e02.mp4

**Comment by Jaex** [comment]
If you open "Debug -> Debug log" from main window, is there any error log?

**Comment by HazyHills** [comment]
No, nothing, the program doesn't start on bootup, but if you start ShareX from the shortcut after, it opens then.  Here is the debug log, but I don't see any errors. 

https://pastebin.com/7QeRy7i2

**Comment by Jaex** [comment]
Pastebin is blocked in my country. I meant check debug log after try enabling it from application settings.

**Comment by HazyHills** [comment]
Oh, my bad.  Is this any better?

https://i.imgur.com/n8yMfE3.png

System.UnauthorizedAccessException: Access to the path 'C:\Program Files\ShareX\ShareX.lnk' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at ShareX.HelpersLib.ShortcutHelpers.Delete(String shortcutPath)
   at ShareX.HelpersLib.ShortcutHelpers.Create(String shortcutPath, String targetPath, String arguments)
   at ShareX.HelpersLib.ShortcutHelpers.SetShortcut(Boolean create, String shortcutPath, String targetPath, String arguments)
2019-03-13 15:21:14.310 - ApplicationConfig save started: C:\Users\Hazy\Documents\ShareX\ApplicationConfig.json
2019-03-13 15:21:14.444 - ApplicationConfig save successful: C:\Users\Hazy\Documents\ShareX\ApplicationConfig.json
2019-03-13 15:21:20.577 - File opened: C:\Users\Hazy\Documents\ShareX\Logs\ShareX-Log-2019-03.txt

**Comment by BTSpaniel** [comment]
This just started today for me too. https://pastebin.com/LZM0CX4n I WILL MAKE A WORKAROUND!

**Comment by BTSpaniel** [comment]
Running as admin following https://github.com/ShareX/ShareX/issues/1454 Fixed the issue. Just Admin Problems

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/issues/3983#issuecomment-471974968
