### ISSUE TITLE
Image history unavailable

### ISSUE THREAD

**Issue by oldmud0** [ShareX/ShareX#4]
When I press the "Image History..." button, an exception is thrown instead of the window that should have opened instead. Here it is:

```
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "HistoryLib.ImageHistoryForm.resources" was correctly embedded or linked into assembly "HistoryLib" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at HistoryLib.ImageHistoryForm.InitializeComponent()
   at HistoryLib.ImageHistoryForm..ctor(String historyPath, Int32 viewMode, Size thumbnailSize, Int32 maxItemCount)
   at ShareX.MainForm.tsbImageHistory_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by shaunroselt** [comment]
@Jaex  Hasn't this issue already been solved?
