### ISSUE TITLE
ShareX not opening 

### ISSUE THREAD

**Issue by Axellious** [ShareX/ShareX#4001]
ShareX simply decided not to open anymore
I tried installing both old and new versions

-------------------------------------- LOG ---------------------------------------------

2019-03-01 00:05:24.969 - ShareX starting.
2019-03-01 00:05:24.971 - Version: 12.3.1
2019-03-01 00:05:24.971 - Build: Release
2019-03-01 00:05:24.971 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-01 00:05:24.971 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-01 00:05:24.972 - Operating system: Windows 10 Pro (64-bit)
2019-03-01 00:05:24.972 - Running as elevated process: False
2019-03-01 00:05:24.977 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-01 00:05:26.007 - Exception:
System.Runtime.Remoting.RemotingException: Failed to read from an IPC Port: The pipe has been ended.

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at ShareX.HelpersLib.InstanceProxy.SetCommandLineArgs(String[] commandLineArgs)
   at ShareX.HelpersLib.ApplicationInstanceManager.UpdateRemoteObject(String uri)
   at ShareX.HelpersLib.ApplicationInstanceManager.CreateMultipleInstance(String[] args)
2019-03-01 00:05:48.884 - ShareX starting.
2019-03-01 00:05:48.885 - Version: 12.3.1
2019-03-01 00:05:48.885 - Build: Release
2019-03-01 00:05:48.885 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-01 00:05:48.885 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-01 00:05:48.886 - Operating system: Windows 10 Pro (64-bit)
2019-03-01 00:05:48.886 - Running as elevated process: False
2019-03-01 00:05:48.891 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-01 16:23:40.293 - ShareX starting.
2019-03-01 16:23:40.293 - Version: 12.3.1
2019-03-01 16:23:40.293 - Build: Release
2019-03-01 16:23:40.293 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2019-03-01 16:23:40.293 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-01 16:23:40.293 - Operating system: Windows 10 Pro (64-bit)
2019-03-01 16:23:40.293 - Running as elevated process: False
2019-03-01 16:23:40.293 - Flags: SilentRun
2019-03-01 16:23:40.324 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-01 16:25:31.708 - ShareX starting.
2019-03-01 16:25:31.710 - Version: 12.3.1
2019-03-01 16:25:31.710 - Build: Release
2019-03-01 16:25:31.710 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-01 16:25:31.710 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-01 16:25:31.710 - Operating system: Windows 10 Pro (64-bit)
2019-03-01 16:25:31.710 - Running as elevated process: False
2019-03-01 16:25:31.716 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:09:38.008 - ShareX starting.
2019-03-02 17:09:38.010 - Version: 12.3.1
2019-03-02 17:09:38.010 - Build: Release
2019-03-02 17:09:38.010 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2019-03-02 17:09:38.010 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:09:38.010 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:09:38.010 - Running as elevated process: False
2019-03-02 17:09:38.011 - Flags: SilentRun
2019-03-02 17:09:38.037 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:15:26.719 - ShareX starting.
2019-03-02 17:15:26.721 - Version: 12.4.1
2019-03-02 17:15:26.721 - Build: Release
2019-03-02 17:15:26.721 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2019-03-02 17:15:26.721 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:15:26.722 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:15:26.722 - Running as elevated process: False
2019-03-02 17:15:26.743 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:15:35.267 - ShareX starting.
2019-03-02 17:15:35.268 - Version: 12.4.1
2019-03-02 17:15:35.268 - Build: Release
2019-03-02 17:15:35.269 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:15:35.269 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:15:35.269 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:15:35.269 - Running as elevated process: False
2019-03-02 17:15:35.275 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:15:57.053 - ShareX starting.
2019-03-02 17:15:57.055 - Version: 12.4.1
2019-03-02 17:15:57.055 - Build: Release
2019-03-02 17:15:57.055 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:15:57.055 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:15:57.056 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:15:57.056 - Running as elevated process: False
2019-03-02 17:15:57.061 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:17:50.827 - ShareX starting.
2019-03-02 17:17:50.828 - Version: 12.4.1
2019-03-02 17:17:50.828 - Build: Release
2019-03-02 17:17:50.828 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:17:50.828 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:17:50.829 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:17:50.829 - Running as elevated process: False
2019-03-02 17:17:50.834 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:18:57.230 - ShareX starting.
2019-03-02 17:18:57.232 - Version: 12.4.1
2019-03-02 17:18:57.232 - Build: Release
2019-03-02 17:18:57.232 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:18:57.232 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:18:57.233 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:18:57.233 - Running as elevated process: False
2019-03-02 17:18:57.238 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:20:47.727 - ShareX starting.
2019-03-02 17:20:47.729 - Version: 12.4.1
2019-03-02 17:20:47.729 - Build: Release
2019-03-02 17:20:47.729 - Command line: "C:\Program Files\ShareX\ShareX.exe" "C:\Program Files\ShareX\ShareX.exe"
2019-03-02 17:20:47.729 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:20:47.729 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:20:47.729 - Running as elevated process: False
2019-03-02 17:20:47.735 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:20:54.734 - ShareX starting.
2019-03-02 17:20:54.736 - Version: 12.4.1
2019-03-02 17:20:54.736 - Build: Release
2019-03-02 17:20:54.736 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:20:54.736 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:20:54.736 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:20:54.736 - Running as elevated process: True
2019-03-02 17:20:54.742 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:34:15.387 - ShareX starting.
2019-03-02 17:34:15.389 - Version: 12.4.1
2019-03-02 17:34:15.389 - Build: Release
2019-03-02 17:34:15.389 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:34:15.389 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:34:15.389 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:34:15.389 - Running as elevated process: False
2019-03-02 17:34:15.395 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:36:16.906 - ShareX starting.
2019-03-02 17:36:16.908 - Version: 12.3.1
2019-03-02 17:36:16.908 - Build: Release
2019-03-02 17:36:16.908 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2019-03-02 17:36:16.908 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:36:16.908 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:36:16.909 - Running as elevated process: False
2019-03-02 17:36:16.932 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:36:22.480 - ShareX starting.
2019-03-02 17:36:22.481 - Version: 12.3.1
2019-03-02 17:36:22.481 - Build: Release
2019-03-02 17:36:22.481 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:36:22.481 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:36:22.482 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:36:22.482 - Running as elevated process: False
2019-03-02 17:36:22.488 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:39:52.790 - ShareX starting.
2019-03-02 17:39:52.791 - Version: 12.3.1
2019-03-02 17:39:52.791 - Build: Release
2019-03-02 17:39:52.791 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:39:52.791 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:39:52.792 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:39:52.792 - Running as elevated process: False
2019-03-02 17:39:52.798 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-02 17:54:35.681 - ShareX starting.
2019-03-02 17:54:35.682 - Version: 12.3.1
2019-03-02 17:54:35.683 - Build: Release
2019-03-02 17:54:35.683 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-02 17:54:35.683 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-02 17:54:35.683 - Operating system: Windows 10 Pro (64-bit)
2019-03-02 17:54:35.683 - Running as elevated process: False
2019-03-02 17:54:35.689 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-03 11:25:03.241 - ShareX starting.
2019-03-03 11:25:03.243 - Version: 12.3.1
2019-03-03 11:25:03.243 - Build: Release
2019-03-03 11:25:03.243 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2019-03-03 11:25:03.243 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-03 11:25:03.244 - Operating system: Windows 10 Pro (64-bit)
2019-03-03 11:25:03.244 - Running as elevated process: False
2019-03-03 11:25:03.244 - Flags: SilentRun
2019-03-03 11:25:03.298 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-03 11:34:41.397 - ShareX starting.
2019-03-03 11:34:41.399 - Version: 12.4.1
2019-03-03 11:34:41.399 - Build: Release
2019-03-03 11:34:41.399 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2019-03-03 11:34:41.399 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-03 11:34:41.399 - Operating system: Windows 10 Pro (64-bit)
2019-03-03 11:34:41.399 - Running as elevated process: False
2019-03-03 11:34:41.421 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-03 11:34:50.496 - ShareX starting.
2019-03-03 11:34:50.498 - Version: 12.4.1
2019-03-03 11:34:50.498 - Build: Release
2019-03-03 11:34:50.498 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-03 11:34:50.498 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-03 11:34:50.499 - Operating system: Windows 10 Pro (64-bit)
2019-03-03 11:34:50.499 - Running as elevated process: False
2019-03-03 11:34:50.504 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-03 11:34:51.973 - ShareX starting.
2019-03-03 11:34:51.975 - Version: 12.4.1
2019-03-03 11:34:51.975 - Build: Release
2019-03-03 11:34:51.975 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-03 11:34:51.975 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-03 11:34:51.975 - Operating system: Windows 10 Pro (64-bit)
2019-03-03 11:34:51.975 - Running as elevated process: False
2019-03-03 11:34:51.981 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json
2019-03-03 11:34:53.081 - ShareX starting.
2019-03-03 11:34:53.083 - Version: 12.4.1
2019-03-03 11:34:53.083 - Build: Release
2019-03-03 11:34:53.083 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-03-03 11:34:53.083 - Personal path: C:\Users\Axellious\Documents\ShareX
2019-03-03 11:34:53.083 - Operating system: Windows 10 Pro (64-bit)
2019-03-03 11:34:53.084 - Running as elevated process: False
2019-03-03 11:34:53.089 - ApplicationConfig load started: C:\Users\Axellious\Documents\ShareX\ApplicationConfig.json

**Comment by Jaex** [comment]
He resolved the issue.
