### ISSUE TITLE
Unable to create album for Google Photos in destination settings

### ISSUE THREAD

**Issue by loganrp** [ShareX/ShareX#4021]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.CreateAlbum(String albumName)
   at ShareX.UploadersLib.UploadersConfigForm.GooglePhotosCreateAlbum(String albumName)
   at ShareX.UploadersLib.UploadersConfigForm.btnGooglePhotosCreateAlbum_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.4.1 (Release)

**Comment by lucario** [comment]
What are you naming the album?
