### ISSUE TITLE
OutOfMemoryException when uploading from clipboard after CTRL+X in Paint.NET

### ISSUE THREAD

**Issue by robotboy655** [ShareX/ShareX#4034]
Error
----
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at ShareX.TaskHelpers.SaveImageAsPNGStream(Image img, Stream stream, PNGBitDepth bitDepth)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   at ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 12.4.1 (Release)
```
The app still is responsive while the error message is displayed. Pressing continue crashes ShareX, pressing Quit freezes ShareX, including the Error message window.

This didn't use to happen on older versions (12.0.x? )
Saving the image as PNG in Paint.NET and uploading that via clipboard does work properly.

Steps to reproduce:
----
1. Get Paint.NET
2. Made/Open an image (Default 800x600 white image still causes the problem, even 1x1 white pixel crashes)
3. CTRL+A (select all) and CTRL+X (cut) the image 
4. Use your ShareX hotkey for "Upload from Clipboard"

**Comment by Jaex** [comment]
1. I opened new 800x600 image in PDN: https://jaex.getsharex.com/2019/03/PaintDotNet_OGR6GugY4m.png
2. Pressed Ctrl+A and Ctrl+X to copy image to clipboard: https://jaex.getsharex.com/2019/03/PaintDotNet_ZhPosB2qnp.png
3. Then used my "Upload from clipboard" hotkey and it uploaded fine: https://jaex.getsharex.com/2019/03/LaVXQiPNCU.png

These are my image options: https://jaex.getsharex.com/2019/03/ShareX_mSLDlErf0y.png
I also tried selecting automatic bit depth yet still works fine.

Is this option "True" in your ShareX: https://jaex.getsharex.com/2019/03/ShareX_HhZKIGMZqC.png

**Comment by robotboy655** [comment]
Yep, setting that option to true fixes the problem. Still either the option shouldn't exist, or it shouldn't crash.

**Comment by Jaex** [comment]
Default value changed long time ago and it not overrides user settings: https://github.com/ShareX/ShareX/commit/e4c1435cf0ee27cdd10cd95a6228641ae02507a3

I can't figure out why bitmap clone method fails with OutOfMemoryException when png image supplied from clipboard, so I will remove that clipboard option instead.
