### ISSUE TITLE
Share X not working still

### ISSUE THREAD

**Issue by ExReyth** [ShareX/ShareX#4046]
Just got new a computer with windows 10 pro  and upon re-downloading this i get slammed with this error, I've uninstall and reinstalled already a few times

System.TypeInitializationException: The type initializer for 'ShareX.UploadersLib.UploaderFactory' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ShareX.HelpersLib.Helpers.GetInstances[T]()
   at ShareX.UploadersLib.UploaderFactory.CacheServices[T,T2]()
   at ShareX.UploadersLib.UploaderFactory..cctor()
   --- End of inner exception stack trace ---
   at ShareX.UploadersLib.UploadersConfigValidator.Validate(ImageDestination destination, UploadersConfig config)
   at ShareX.MainForm.EnableDisableToolStripMenuItems[T](ToolStripDropDownItem[] parents)
   at ShareX.MainForm.UpdateDestinationStates()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HelpersLib.HotkeyForm.WndProc(Message& m)
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.4.1 (Release)

My Current Computer Cuild
Operating System
    Windows 10 Pro 64-bit
CPU
    AMD Ryzen 5    83 °C
    14nm Technology
RAM
    16.0GB Dual-Channel Unknown @ 1064MHz (15-15-15-36)
Motherboard
    Gigabyte Technology Co. Ltd. B450M DS3H-CF (AM4)    34 °C
Graphics
    SyncMaster (1920x1200@59Hz)
    2047MB NVIDIA GeForce GTX 1060 6GB (ASUStek Computer Inc)    38 °C
Storage
    3726GB Western Digital WDC WD40EFRX-68N32N0 (SATA )    29 °C
    465GB Samsung SSD 860 EVO 500GB (SATA (SSD))    36 °C
Optical Drives
    No optical disk drives detected
Audio
    NVIDIA Virtual Audio Device (Wave Extensible) (WDM)

**Comment by Jaex** [comment]
Your .NET Framework could be corrupted. So reinstalling it can fix the problem.

**Comment by ExReyth** [comment]
> Your .NET Framework could be corrupted. So reinstalling it can fix the problem.

Ok i gave it a shot and no dice

**Comment by ExReyth** [comment]
Bumping to hopeful get a fix to this issue i don't know what else to it still save s images but won't let me link them imgur when i try to select the destinations the tab this error  pops up stopping me

System.TypeInitializationException: The type initializer for 'ShareX.UploadersLib.UploaderFactory' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ShareX.HelpersLib.Helpers.GetInstances[T]()
   at ShareX.UploadersLib.UploaderFactory.CacheServices[T,T2]()
   at ShareX.UploadersLib.UploaderFactory..cctor()
   --- End of inner exception stack trace ---
   at ShareX.UploadersLib.UploadersConfigValidator.Validate(ImageDestination destination, UploadersConfig config)
   at ShareX.MainForm.EnableDisableToolStripMenuItems[T](ToolStripDropDownItem[] parents)
   at ShareX.MainForm.UpdateDestinationStates()
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripMenuItem.OnMenuAutoExpand()
   at System.Windows.Forms.MenuTimer.OnTick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.4.1 (Release)
