### ISSUE TITLE
ShareX 12.4.1 (Release) failure to open

### ISSUE THREAD

**Issue by Roozle** [ShareX/ShareX#4082]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.SettingManager.ApplicationConfigBackwardCompatibilityTasks()
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

**Comment by Jaex** [comment]
Duplicate of #3976
