### ISSUE TITLE
I cannot upload anything to imgur.

### ISSUE THREAD

**Issue by devonzimmi** [ShareX/ShareX#4149]
This only started off and on today. I'm able to connect to the site just fine, I refreshed my authentication successfully, and I have no problems with my internet. This is the first time I've been having an issue like this.

Error message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
https://api.imgur.com/3/image

Status code:
503 ServiceUnavailable

Headers:
Connection: Close
Content-Length: 0

Response text:

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by NielTaylor** [comment]
The same for me..

**Comment by NielTaylor** [comment]
It's working again!
