### ISSUE TITLE
ShareX lacks TLS v1.3 support

### ISSUE THREAD

**Issue by inabahare** [ShareX/ShareX#4210]
Using ShareX 12.4.1 on Windows 10 Enterprice LTSC 1809

Using TLS Version 1.3 with the following [nginx config](https://ssl-config.mozilla.org/#server=nginx&server-version=1.17.0&config=modern) will produce the following error:

```
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://lewd.se/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by Jaex** [comment]
.NET Framework not supports TLS 1.3

**Comment by inabahare** [comment]
It'll be implemented in .NET 4.8 iirc
