### ISSUE TITLE
After capture task doesn't work

### ISSUE THREAD

**Issue by pinomarcelo** [ShareX/ShareX#4301]
When "Copy to clipboard" is enabled in the "after capture tasks" menu (Open image editor enabled also) the captured image doesn't copy to clipboard (even after closing the image editor) automatically. I must clic on "copy" icon. Any suggestions?

**Comment by mfrsousa** [comment]
I also have the same issue, some times images are copied to the clipboard and sometimes are not. Without changing anything. I can see this error on log
`
2019-09-23 11:46:55.851 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img)
2019-09-23 11:46:55.852 - Image copied to clipboard.
`
or another one
`
2019-09-23 11:49:31.693 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img)
2019-09-23 11:49:31.693 - Image copied to clipboard.
`

**Comment by samuelaguilera** [comment]
Same issue here when using "Copy to clipboard" + "Perform actions" on the "After capture tasks":

![Image201910009](https://user-images.githubusercontent.com/1039772/66866289-46e5a280-ef99-11e9-8169-ee7a4e26fe90.png)

If I change it to "Save image to file" + "Perform actions" instead, with this combination the configured actions are triggered as expected.
