### ISSUE TITLE
BadImageFormat exception after update to 13.0.1

### ISSUE THREAD

**Issue by affifun** [ShareX/ShareX#4317]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=13.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsCapture..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath, String backupFolder, Boolean createBackup, Boolean createWeeklyBackup)
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.0.1 (Release)

**Comment by affifun** [comment]
Reinstalled from scratch, seems to be fine
