### ISSUE TITLE
429 on upload to imgur

### ISSUE THREAD

**Issue by link2110** [ShareX/ShareX#4335]
I've tried resetting upload hosts, restarting sharex, and re-authorising imgur. Is there anything else i should try? 

```
Date: Mon, 02 Sep 2019 05:16:19 GMT
Server: nginx/1.13.5

Response text:
{"errors":[{"id":"","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://api.imgur.com/3/upload

Status code:
(429) Too Many Requests

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 2000
X-Ratelimit-Userremaining: -801
X-Ratelimit-Userreset: 3600
Strict-Transport-Security: max-age=15724800; includeSubDomains;
Content-Length: 94
Content-Type: application/vnd.imgur.v1+json
Date: Mon, 02 Sep 2019 05:16:20 GMT
Server: nginx/1.13.5

Response text:
{"errors":[{"id":"","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2019-09-01 22:16:21.940 - ApplicationConfig save started: H:\Dropbox\ShareX\ApplicationConfig.json
2019-09-01 22:16:21.941 - UploadersConfig save started: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:21.950 - HotkeysConfig save started: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:22.060 - UploadersConfig save successful: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:22.124 - HotkeysConfig save successful: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:22.130 - ApplicationConfig save successful: H:\Dropbox\ShareX\ApplicationConfig.json
2019-09-01 22:16:25.135 - Task in queue. Job: Job, Type: Image, Host: 
2019-09-01 22:16:25.140 - Task status: Preparing
2019-09-01 22:16:25.153 - Image copied to clipboard.
2019-09-01 22:16:25.157 - Task completed. Filename: 2019-09-01_22-16-25.bmp, Duration: 17 ms
2019-09-01 22:16:25.157 - ApplicationConfig save started: H:\Dropbox\ShareX\ApplicationConfig.json
2019-09-01 22:16:25.158 - UploadersConfig save started: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:25.160 - HotkeysConfig save started: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:25.243 - UploadersConfig save successful: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:25.271 - HotkeysConfig save successful: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:25.289 - ApplicationConfig save successful: H:\Dropbox\ShareX\ApplicationConfig.json
2019-09-01 22:16:41.596 - ApplicationConfig save started: H:\Dropbox\ShareX\ApplicationConfig.json
2019-09-01 22:16:41.597 - UploadersConfig save started: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:41.598 - HotkeysConfig save started: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:41.695 - UploadersConfig save successful: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:41.714 - HotkeysConfig save successful: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:41.735 - ApplicationConfig save successful: H:\Dropbox\ShareX\ApplicationConfig.json
2019-09-01 22:16:59.019 - ApplicationConfig save started: H:\Dropbox\ShareX\ApplicationConfig.json
2019-09-01 22:16:59.020 - UploadersConfig save started: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:59.020 - HotkeysConfig save started: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:59.106 - UploadersConfig save successful: H:\Dropbox\ShareX\UploadersConfig.json
2019-09-01 22:16:59.134 - HotkeysConfig save successful: H:\Dropbox\ShareX\HotkeysConfig.json
2019-09-01 22:16:59.154 - ApplicationConfig save successful: H:\Dropbox\ShareX\ApplicationConfig.json
```

**Comment by link2110** [comment]
Also it's not like I'm spamming Imgur with uploads, this happens every time i try to clip anything, no matter how long it's been since the last time I tried to upload

**Comment by link2110** [comment]
Downgraded to 12.4.1, issue fixed with no changes.

**Comment by rohit0201** [comment]
@link2110 what did you downgrade here to 12.4.1 . I am getting the same issue . can you please help me

**Comment by Martin-HZK** [comment]
same question? Have you finished?
