### ISSUE TITLE
can't link/upload to imgur or anything else

### ISSUE THREAD

**Issue by ExReyth** [ShareX/ShareX#4338]
I've already tried reinstalling both ShareX and .NET 

System.TypeInitializationException: The type initializer for 'ShareX.UploadersLib.UploaderFactory' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ShareX.HelpersLib.Helpers.GetInstances[T]()
   at ShareX.UploadersLib.UploaderFactory.CacheServices[T,T2]()
   at ShareX.UploadersLib.UploaderFactory..cctor()
   --- End of inner exception stack trace ---
   at ShareX.UploadersLib.UploadersConfigValidator.Validate(ImageDestination destination, UploadersConfig config)
   at ShareX.MainForm.EnableDisableToolStripMenuItems[T](ToolStripDropDownItem[] parents)
   at ShareX.MainForm.UpdateDestinationStates()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HelpersLib.HotkeyForm.WndProc(Message& m)
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.0.1 (Release)
2019-09-03 10:14:11.902 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2019-09-03 10:19:27.294 - File opened: C:\Users\dark_\Documents\ShareX\Logs\ShareX-Log-2019-09.txt

**Comment by TODO4EVER** [comment]
yea same problem, revert back to 12.4.1

**Comment by ExReyth** [comment]
> yea same problem, revert back to 12.4.1

didn't work for me still the same error i really miss using this :(
