### ISSUE TITLE
Renci SSH Net Library error

### ISSUE THREAD

**Issue by Aida-Enna** [ShareX/ShareX#4341]
I've begun getting this error out of nowhere every time I try to upload to my website (which nothing has changed on) - I use the destinations menu to test it (I'm using SFTP, I haven't modified the destination in months) and it works fine, but uploading gives me the following error (and doesn't even seem to save the picture?):

> Renci.SshNet.Common.SshException: Failure
>    at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 serverOffset, Byte[] data, Int32 offset, Int32 length, AutoResetEvent wait, Action`1 writeCompleted)
>    at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
>    at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath, Boolean autoCreateDirectory)
>    at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 
> Renci.SshNet.Common.SshException: Failure
>    at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 serverOffset, Byte[] data, Int32 offset, Int32 length, AutoResetEvent wait, Action`1 writeCompleted)
>    at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
>    at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath, Boolean autoCreateDirectory)
>    at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 
> Renci.SshNet.Common.SshException: Failure
>    at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 serverOffset, Byte[] data, Int32 offset, Int32 length, AutoResetEvent wait, Action`1 writeCompleted)
>    at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
>    at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath, Boolean autoCreateDirectory)
>    at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)
> 
> Renci.SshNet.Common.SshException: Failure
>    at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 serverOffset, Byte[] data, Int32 offset, Int32 length, AutoResetEvent wait, Action`1 writeCompleted)
>    at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
>    at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath, Boolean autoCreateDirectory)
>    at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
>    at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
>    at ShareX.WorkerTask.DoUpload(Int32 retry)

**Comment by Aida-Enna** [comment]
Duplicate of #1495 - My remote server's hard drive was full. Sorry for the trouble!
