### ISSUE TITLE
OCR is not working

### ISSUE THREAD

**Issue by andrewklajman** [ShareX/ShareX#4466]
Hi All,

Apologies if this is not the proper forum to log this.  I was not able to find an existing solution on the internet.

I was not able to get the OCR to work in ShareX.  When I tried to do so i was able to get the following from the debug log.

2019-10-31 08:23:53.864 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.OtherServices.OCRSpace.DoOCR(Stream stream, String fileName)
   at ShareX.UploadersLib.OtherServices.OCRSpace.DoOCR(OCRSpaceLanguages language, Stream stream, String fileName)

I am working from my Work computer (I'm unsure if firewalls / VPN's / ... allow me to access something that is required from the internet).

If there is anything anyone could suggest it would be appreciated.

Kind regards

Andrew

**Comment by canpolat** [comment]
Looks like ShareX is using an external (online) service to perform the OCR (https://ocr.space/). It is difficult for me to say something definitive before seeing the actual network traffic, but it looks like the API used by ShareX returns non-JSON data (probably an error page with HTML content) and the application is therefore throwing an exception. (This is just a guess).

I think, in any case, it would be good to handle this exception in the application and display a proper error message so that it would be easier for the user to understand the problem.

I just tried doing an OCR, and it seems to work, so if you are still having problems, it could be due to a network restriction (firewall, VPN, etc.). Do you have the possibility to try it on another PC that is on another network (home vs. work)?

**Comment by andrewklajman** [comment]
Thanks, i just confirmed that i cannot access https://ocr.space/ on my work machine so Im requesting an exception.

Ill update when I get a response

Thanks again

Andrew
