### ISSUE TITLE
Generic GDI+ exception while updating tray icon

### ISSUE THREAD

**Issue by ernestgn** [ShareX/ShareX#4478]
ShareX crashes about once every two days, log snippet below.

System:
OS - Windows 10 Pro
Processor - Intel Core i7-8559U CPU @ 2.70 GHz, 2.71 GHz
RAM - 16.0 GB
System type - 64 bit

---
2019-11-05 11:42:52.615 - Task in queue. Job: Job, Type: File, Host: Amazon S3
2019-11-05 11:42:53.585 - Task status: Preparing
2019-11-05 11:42:53.607 - Image copied to clipboard.
2019-11-05 11:42:53.621 - Image saved to file: C:\Users\[username]2\Documents\ShareX\Screenshots\2019-11\2019-11-05_11-42-52.png
2019-11-05 11:42:53.638 - Upload started. Filename: 2019-11-05_11-42-52.png, Filepath: C:\Users\[username]2\Documents\ShareX\Screenshots\2019-11\2019-11-05_11-42-52.png
2019-11-05 11:42:54.112 - Exception:
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at ShareX.TaskHelpers.GetProgressIcon(Int32 percentage)
   at ShareX.TaskManager.UpdateTrayIcon(Int32 progress)
2019-11-05 11:42:54.700 - Upload completed. URL: https://s3.eu-central-1.amazonaws.com/[username]/[bucket]/2019/11/2019-11-05_11-42-52.png, Duration: 1063 ms
2019-11-05 11:42:54.703 - Task completed. Filename: 2019-11-05_11-42-52.png, Duration: 1117 ms
2019-11-05 11:43:52.616 - Task in queue. Job: Job, Type: File, Host: Amazon S3
2019-11-05 15:56:38.393 - ShareX starting.

**Comment by ernestgn** [comment]
These seem related:
https://github.com/ShareX/ShareX/issues/298
https://social.msdn.microsoft.com/Forums/en-US/3dd02621-4d7c-470d-b16b-610b11f8213c/creating-cursor-from-bitmap-causes-memory-leak-and-eventual?forum=winforms
https://stackoverflow.com/questions/12026664/a-generic-error-occurred-in-gdi-when-calling-bitmap-gethicon
https://stackoverflow.com/questions/10557474/generic-gdi-exception-while-drawing-cursor-3322-times/31536930

**Comment by Jaex** [comment]
I already use `DestroyIcon` like suggested in those stackoverflow links.

**Comment by Jaex** [comment]
I also handle that error in try catch so it couldn't be crashing ShareX at all?

**Comment by ernestgn** [comment]
Execution continues after that exception, so it might not be causing the crash by itself. However, when the next upload event happens (a minute later -- I've set ShareX to upload every minute), it crashes as soon as it queues up the upload, before the actual upload happens. This sequence happens reliably.

---
2019-11-05 11:42:54.700 - Upload completed. URL: https://s3.eu-central-1.amazonaws.com/[username]/[bucket]/2019/11/2019-11-05_11-42-52.png, Duration: 1063 ms
2019-11-05 11:42:54.703 - Task completed. Filename: 2019-11-05_11-42-52.png, Duration: 1117 ms
2019-11-05 11:43:52.616 - Task in queue. Job: Job, Type: File, Host: Amazon S3
2019-11-05 15:56:38.393 - ShareX starting.
