### ISSUE TITLE
Chrome extension's "Upload with ShareX" context menu option not work

### ISSUE THREAD

**Issue by rixinsc** [ShareX/ShareX#4482]
The "Enable Chrome extension support" checkbox in `Application Settings` -> `Integration` remains unchecked when I reopen the panel even after I checked it and reopen.

If I run ShareX as an elevated process, the boxes will appear as checked and no error occurs when I change their states. However the context menu button in the browser still doesn't work. (no response and nothing logged)

#### Log (for the first scene):
```
2019-11-10 19:20:06.980 - ShareX starting.
2019-11-10 19:20:07.046 - Version: 13.0.1
2019-11-10 19:20:07.046 - Build: Release
2019-11-10 19:20:07.046 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2019-11-10 19:20:07.046 - Personal path: C:\Users\User\Documents\ShareX
2019-11-10 19:20:07.047 - Operating system: Windows 10 Home Single Language (64-bit)
2019-11-10 19:20:07.057 - Running as elevated process: False
...
2019-11-10 19:20:14.027 - Startup time: 9353 ms
...
2019-11-10 19:20:15.200 - Executing: Open main window
2019-11-10 19:20:24.270 - Exception:
System.Security.SecurityException: Requested registry access is not allowed.
   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at ShareX.HelpersLib.RegistryHelpers.GetRegistryValue(String path, String name, RegistryHive root)
   at ShareX.IntegrationHelpers.CheckChromeExtensionSupport()
The Zone of the assembly that failed was:
MyComputer
2019-11-10 19:20:24.271 - Exception:
System.Security.SecurityException: Requested registry access is not allowed.
   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at ShareX.HelpersLib.RegistryHelpers.GetRegistryValue(String path, String name, RegistryHive root)
   at ShareX.IntegrationHelpers.CheckFirefoxAddonSupport()
The Zone of the assembly that failed was:
MyComputer
2019-11-10 19:20:27.510 - Exception:
System.UnauthorizedAccessException: Access to the registry key 'HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.getsharex.sharex' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at ShareX.HelpersLib.RegistryHelpers.CreateRegistry(String path, String name, String value, RegistryHive root)
   at ShareX.IntegrationHelpers.RegisterChromeExtensionSupport()
   at ShareX.IntegrationHelpers.CreateChromeExtensionSupport(Boolean create)
2019-11-10 19:20:30.059 - ApplicationConfig save started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2019-11-10 19:20:30.290 - ApplicationConfig save successful: C:\Users\User\Documents\ShareX\ApplicationConfig.json
```

Any idea what is the cause and on how to make it work?
PS: It works before but not recently.

**Comment by rixinsc** [comment]
Issue fixed after an update.

**Comment by Souchikjoardar1** [comment]
shareX is the best screenshot app out there but since I use firefox I honestly don't need anything else to take screenshots inside the browser window anything outside that window is shareX's job , honestly the scrolling screenshots feature is kinda buggy sometimes !
