### ISSUE TITLE
Thumbnail previews not updating

### ISSUE THREAD

**Issue by vSwifty** [ShareX/ShareX#4510]
`2019-12-04 21:16:03.321 - Exception:
System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.Image.get_Width()
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(Image img, Int32 width, Int32 height, Boolean allowEnlarge, Boolean centerImage, Color backColor)
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(Image img, Size size, Boolean allowEnlarge, Boolean centerImage)
   at ShareX.TaskThumbnailPanel.UpdateThumbnail(Image image)`

![image](https://user-images.githubusercontent.com/8891586/70206173-76807380-16db-11ea-89a8-52808647e55f.png)

I've tried reinstalling it but that didn't seem to fix it, I'm not too sure what I did in the settings to cause this to happen. Other than having my personal folder on my SSD and my bulk screenshot storage on my HDD

EDIT: Seems having the ShareX window unminimized from taskbar fixes it but closing it and having it sit in the taskbar/tray area causes it at least from what I've tested so far

**Comment by Jaex** [comment]
I'm unable to reproduce this issue. What is your after capture tasks?

**Comment by vSwifty** [comment]
> I'm unable to reproduce this issue. What is your after capture tasks?

![image](https://user-images.githubusercontent.com/8891586/70208316-13460f80-16e2-11ea-8e58-bd7868a6e3e8.png)

https://pastebin.com/ZdpGyhNx - Here's the debug log after a fresh restart and repeating the steps, Minimize to icon tray, Taking a screenshot via active window or region select and then checking the main window for results

Closing out ShareX completely and reopening it seems to regenerate the missing thumbnails

**Comment by Jaex** [comment]
Pastebin is blocked in my country so can't see it.

**Comment by vSwifty** [comment]
> Pastebin is blocked in my country so can't see it.
Oops, Was just using the upload logs button in the debug window how about gist?

https://gist.github.com/vSwifty/8cefa8a1f2dd39312628795a9f8f7818

**Comment by Zaczero** [comment]
Same problem here,
![](https://i.imgur.com/c191ehj.png)
It doesn't happen every time though. However from time to time it even crashes the ShareX application.

Crash log (from windows Event Viewer):
```
Application: ShareX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Drawing.SafeNativeMethods+Gdip.GdipGetImageWidth(System.Runtime.InteropServices.HandleRef, Int32 ByRef)
   at System.Drawing.Image.get_Width()
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(System.Drawing.Image, Int32, Int32, Boolean, Boolean, System.Drawing.Color)
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(System.Drawing.Image, System.Drawing.Size, Boolean, Boolean)
   at ShareX.TaskThumbnailPanel.UpdateThumbnail(System.Drawing.Image)
   at ShareX.TaskManager.Task_ImageReady(ShareX.WorkerTask)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at ShareX.Program.Run()
   at ShareX.Program.Main(System.String[])
```

and from the ShareX log file I got those exceptions (different than the crash):
```
2019-12-16 23:13:11.467 - Task in queue. Job: Job, Type: Image, Host: 
2019-12-16 23:13:11.470 - Task status: Preparing
2019-12-16 23:13:11.498 - Image copied to clipboard.
2019-12-16 23:13:11.517 - Image saved to file: C:\Users\-\Documents\ShareX\Screenshots\2019-12\191216_231311_gimp-2.10.png
2019-12-16 23:13:11.519 - Exception:
System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.Image.get_Width()
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(Image img, Int32 width, Int32 height, Boolean allowEnlarge, Boolean centerImage, Color backColor)
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(Image img, Size size, Boolean allowEnlarge, Boolean centerImage)
   at ShareX.TaskThumbnailPanel.UpdateThumbnail(Image image)
2019-12-16 23:13:11.519 - Task completed. Filename: 191216_231311_gimp-2.10.png, Duration: 49 ms
```
```
2019-12-16 23:09:59.631 - Task in queue. Job: Job, Type: Image, Host: 
2019-12-16 23:09:59.633 - Task status: Preparing
2019-12-16 23:09:59.647 - Image copied to clipboard.
2019-12-16 23:09:59.658 - Image saved to file: C:\Users\-\Documents\ShareX\Screenshots\2019-12\191216_230959_gimp-2.10.png
2019-12-16 23:09:59.658 - Exception:
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Width()
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(Image img, Int32 width, Int32 height, Boolean allowEnlarge, Boolean centerImage, Color backColor)
   at ShareX.HelpersLib.ImageHelpers.ResizeImage(Image img, Size size, Boolean allowEnlarge, Boolean centerImage)
   at ShareX.TaskThumbnailPanel.UpdateThumbnail(Image image)
2019-12-16 23:09:59.658 - Task completed. Filename: 191216_230959_gimp-2.10.png, Duration: 25 ms
```

---

![](https://i.imgur.com/FrZwxrQ.png)

**Comment by Jaex** [comment]
@Zaczero thanks for detailed report, now I figured why it happens.

**Comment by Jaex** [comment]
Hopefully it should be fixed now.

**Comment by chrisjj** [comment]
> Hopefully it should be fixed now.

Trying now I find the similar (possibly identical) [issue ](https://github.com/ShareX/ShareX/issues/4576)persists now on 13.0.1 which says "up-to-date".

I too find missing previews are restored by restarting.

**Comment by Zaczero** [comment]
> > Hopefully it should be fixed now.
> 
> Trying now I find the similar (possibly identical) [issue ](https://github.com/ShareX/ShareX/issues/4576)persists now on 13.0.1 which says "up-to-date".
> 
> I too find missing previews are restored by restarting.

Please install the dev build. The fix isn't contained in the latest release yet.

![image](https://user-images.githubusercontent.com/10835147/72558128-61822d00-38a2-11ea-966e-3ebbd2084400.png)

**Comment by chrisjj** [comment]
> Please install the dev build.

Sure. Happy to help!

I've done that and will watch for recurrence.

Do you know what triggered an occurrence?
