### ISSUE TITLE
More crashing with custom SFTP destinations:

### ISSUE THREAD

**Issue by ArghArgh200** [ShareX/ShareX#455]
Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, EventWaitHandle wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, EventWaitHandle wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, EventWaitHandle wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, EventWaitHandle wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, EventWaitHandle wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Renci.SshNet.Common.SshException: Failure
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, EventWaitHandle wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

**Comment by ArghArgh200** [comment]
Happens when I try and upload anything.

**Comment by Jaex** [comment]
Unfortunately but I can't help you about it because it is external library. And SFTP works in many people so  something can be wrong in your config or server not supported by SFTP library or maybe bug in library etc.

So either way I can't help about these because I never used SFTP and not wrote library.

**Comment by SpinahVieh** [comment]
This might be late, but I had this issue. Turns out my SFTP server didn't have any space available.
