### ISSUE TITLE
ShareX doesn't launch out of a cloud sync folder after upgrading to 13.1

### ISSUE THREAD

**Issue by naoey** [ShareX/ShareX#4657]
I use iCloud for Windows to sync my ShareX folder to the cloud by putting my ShareX folder inside the iCloud Drive folder. This has worked quite well all these years but after upgrading to 13.1 just now the application fails to start with the error:

```
System.IO.IOException: The operation is not supported by the cloud sync provider.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite)
   at ShareX.SettingManager.MigrateHistoryFile()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
```

Here's the log file:
[ShareX-Log-2020-03.txt](https://github.com/ShareX/ShareX/files/4316596/ShareX-Log-2020-03.txt)

**Comment by naoey** [comment]
Unsure if this was addressed or something else changed that resolved it, but it isn't occurring right now after updating to 12.3.1. Closing the issue until and unless it resurfaces.
