### ISSUE TITLE
"Access to the path is denied." and Will Not Run After Update to 13.1

### ISSUE THREAD

**Issue by DarkShiftMusic** [ShareX/ShareX#4658]
Regardless of whether I enable compatibility and/or run as admin this comes up and the program fails to start. The error message follows.
```
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite)
   at ShareX.SettingManager.MigrateHistoryFile()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
```

**Comment by Ncage1974** [comment]
I'm getting this same error after the upgrade. I thought it might have been my AV but its not i checked.

**Comment by haydenslee** [comment]
Same Error:

System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite)
   at ShareX.SettingManager.MigrateHistoryFile()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
