### ISSUE TITLE
System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.    at ShareX.TaskSettingsCapture..ctor()    at ShareX.TaskSettings..ctor()    at ShareX.ApplicationConfig..ctor()

### ISSUE THREAD

**Issue by trentet** [ShareX/ShareX#4664]
Attempting to launch ShareX via system tray or start menu gets me the following error (1 day after updating to v13.1.0.0)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=13.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettingsCapture..ctor()
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath, String backupFolder, Boolean createBackup, Boolean createWeeklyBackup)
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
[ShareX-Log-2020-03.txt](https://github.com/ShareX/ShareX/files/4322593/ShareX-Log-2020-03.txt)

**Comment by Heroesflorian** [comment]
Just had the same issue
