### ISSUE TITLE
When performing"Full screen Capture", an error appears.

### ISSUE THREAD

**Issue by dozyawa** [ShareX/ShareX#4685]
System.BadImageFormatException: Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 800703e6 Неверная попытка доступа к адресу памяти. (Exception from HRESULT: 0x800703E6).
   at ShareX.HelpersLib.TaskbarManager.get_TaskbarList()
   at ShareX.HelpersLib.TaskbarManager.SetProgressState(IntPtr hwnd, TaskbarProgressBarStatus state)
   at ShareX.HelpersLib.Extensions.InvokeSafe(Control control, Action action)
   at ShareX.TaskManager.UpdateProgressUI()
   at ShareX.TaskManager.Task_StatusChanged(WorkerTask task)

ShareX 13.1 (Release)

[ShareX-Log-2020-03.txt](https://github.com/ShareX/ShareX/files/4353224/ShareX-Log-2020-03.txt)
![Screenshot_11](https://user-images.githubusercontent.com/43491765/77043478-cfa0b880-69e7-11ea-99d4-efd4c0bb6fa8.png)

**Comment by barbiehunter** [comment]
I have the Issue too what he have right now, also the dozywa idk how to fix it
