### ISSUE TITLE
Google Photos API limit exhausted (Unable to upload to Google Photos)

### ISSUE THREAD

**Issue by Christbru** [ShareX/ShareX#4689]
When attempting to upload an image I get an error 429 quota exceeded. This quota is for project ID 810697162603 which I've verified is not a project associated to my gmail account. I assume your program uses your own project for accessing the google photos API but that project is currently exceeding the global limits meaning (assumedly) all users attempting to use ShareX with Google Photos as the upload location are unable to do so until the limit is reset or the project is changed (as this has been going on for days I assume it won't be resetting very soon)

Error log:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.CreateAlbum(String albumName)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://photoslibrary.googleapis.com/v1/albums?fields=id

Status code:
(429) Too Many Requests

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Fri, 20 Mar 2020 22:30:52 GMT
Server: ESF

Response text:
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/810697162603/apiui/credential"
          }
        ]
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.CreateAlbum(String albumName)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://photoslibrary.googleapis.com/v1/albums?fields=id

Status code:
(429) Too Many Requests

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Fri, 20 Mar 2020 22:30:53 GMT
Server: ESF

Response text:
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/810697162603/apiui/credential"
          }
        ]
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
```

**Comment by Jaex** [comment]
I sent Google Photos API quota increase request to Google and we are waiting now.

**Comment by emmaly** [comment]
I had this occur today.
