### ISSUE TITLE
Upload not working for ShareX versions above 11.0.1

### ISSUE THREAD

**Issue by aftery142** [ShareX/ShareX#4745]
Hello, ShareX versions newer than 11.0.1 won't upload to any uploaders for me. I have no antivirus installed and firewall is off.
Note: I can access the URL, also tried setting proxy to None/Automatic.

```
Error message:
Unable to connect to the remote server

Request URL:
https://api.imgur.com/3/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)```

**Comment by stephen147** [comment]
If like me you made the mistake of logging in to use the API but not selecting the album on the right shown in the image below.

This caused my upload to fail.

![image](https://user-images.githubusercontent.com/14054664/79473585-4045ef80-7ffd-11ea-87b3-0bdda1fee93a.png)

**Comment by aftery142** [comment]
> 
> 
> If like me you made the mistake of logging in to use the API but not selecting the album on the right shown in the image below.
> 
> This caused my upload to fail.

I'm using anonymous, and I can't connect to any host.

**Comment by aftery142** [comment]
reinstalled windows and it's working now
