### ISSUE TITLE
Google Team Drive/Shared drive support?  

### ISSUE THREAD

**Issue by iGerman00** [ShareX/ShareX#4787]
Some of us get a shared drive on our accounts, either from our university or company, and it is basically unlimited storage Google drive. 
It would be great if ShareX had it implemented as an uploader, since it already has Google Cloud Storage and regular Drive

**Comment by lucario** [comment]
Are you not able to select your university Google account when authenticating in ShareX?

**Comment by iGerman00** [comment]
> Are you not able to select your university Google account when authenticating in ShareX?

That’s not really how it works for me. The team drive shows up in my personal account, along with my regular google drive. There’s no way to select it in sharex and I don’t have any other account, my account just has access to a team drive

**Comment by lucario** [comment]
Here is the relevant API documentation: 
https://developers.google.com/drive/api/v3/enable-shareddrives

I can possibly look at supporting this myself soon, however, if anyone else wants to make an attempt, it shouldn't be too difficult.

**Comment by iGerman00** [comment]
All I tried was custom uploaders but I couldn’t figure it out. If you do make it a thing, please lmk

**Comment by lucario** [comment]
It's impossible to do as a custom uploader due to the nature of the API.

**Comment by thegreatestminer** [comment]
+1 for this. Attempting to upload to a shared drive folder ID gives this error:

```
Error message:
The remote server returned an error: (404) Not Found.

Request URL:
https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink,webContentLink

Status code:
(404) Not Found

Headers:
X-GUploader-UploadID: [REDACTED]
Vary: Origin,X-Origin
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 306
Content-Type: application/json; charset=UTF-8
Date: Tue, 26 May 2020 00:55:04 GMT
Server: UploadServer

Response text:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: [SHARED DRIVE ID].",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: [SHARED DRIVE ID]."
 }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by lucario** [comment]
@SupSuper Could you take a look at this issue?

**Comment by SupSuper** [comment]
> Note: After June 1, 2020, the includeItemsFromAllDrives parameter will be ignored and shared drive items will be returned in the results.

@lucario Might as well wait a week and see if that fixes it.

**Comment by thegreatestminer** [comment]
It is now June 3rd, and it still seems to not work.

```
Error message:
The remote server returned an error: (404) Not Found.

Request URL:
https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink,webContentLink

Status code:
(404) Not Found

Headers:
X-GUploader-UploadID: [REDACTED]
Vary: Origin,X-Origin
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 306
Content-Type: application/json; charset=UTF-8
Date: Wed, 03 Jun 2020 12:06:43 GMT
Server: UploadServer

Response text:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: [Shared drive ID].",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: [Shared drive ID]."
 }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by iGerman00** [comment]
> June 3rd

June 4th, also doesn't work.
```
Error message:
The remote server returned an error: (404) Not Found.

Request URL:
https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink,webContentLink

Status code:
(404) Not Found

Headers:
X-GUploader-UploadID: [REDACTED]
Vary: Origin,X-Origin
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 306
Content-Type: application/json; charset=UTF-8
Date: Thu, 04 Jun 2020 09:59:53 GMT
Server: UploadServer

Response text:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: [Folder in shared drive].",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: [Folder in shared drive]."
 }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by SupSuper** [comment]
Looks like drive IDs don't work as a parent, you need to explicitly pass both a drive ID and a folder ID.

I'll work on a PR for this.

**Comment by SupSuper** [comment]
Should be sorted now (note you still need to select the correct drive, even if you manually put in the folder ID).

> P.S. I have a ton of folders in my shared drive since I use it for backup. It makes refreshing the folder list hard to navigate and very slow to actually refresh. It would be great to have the folders open-able to show more folders, and not just show every single folder in the entire drive :/

The problem is Google Drive doesn't make this easy. It's not actually hierarchical, a single file can belong to multiple folders (they're more like "tags"), which would be a recursive mess. And the API is designed for quickly finding contents in your drive, rather than figuring out its structure.
