### ISSUE TITLE
Settings/history lost (?)

### ISSUE THREAD

**Issue by Xymanek** [ShareX/ShareX#4839]
Facing a rather bizarre issue here... Today ShareX was working perfectly fine (as it did over the last ~year with the same setup). Then I switched my laptop off, later back on and now it appears that ShareX has lost its history and settings. To be precise:

* Hotkey settings were reset to defaults
* After capture tasks were reset to defaults
* More settings reset to defaults? I can't recall if I changed something else...
* The screenshot folder itself is fine
* History as shown on the main screen is "lost"
* History as shown when clicking on the "History" button on the left is fine (still there)

Version is 13.1

I do not believe there were any updates during the shutdown/boot to either sharex or windows. Install is standalone (not from windows store)

**Comment by Xymanek** [comment]
I was looking at the `C:\Users\xyman\Documents\ShareX` folder (thanks to Cisien and PtrToStructure on C# discord for pointer) and found an interesting thing in logs:

Last image taken before shutdown:
```
2020-05-29 14:16:59.873 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2020-05-29 14:16:59.874 - Executing: Capture region
2020-05-29 14:17:02.246 - Task in queue. Job: Job, Type: Image, Host: 
2020-05-29 14:17:02.247 - Task status: Preparing
2020-05-29 14:17:02.388 - Image copied to clipboard.
2020-05-29 14:17:02.388 - Task completed. Filename: Cities_2020-05-29_14-17-02.bmp, Duration: 140 ms
2020-05-29 14:17:02.389 - ApplicationConfig save started: C:\Users\xyman\Documents\ShareX\ApplicationConfig.json
2020-05-29 14:17:02.389 - UploadersConfig save started: C:\Users\xyman\Documents\ShareX\UploadersConfig.json
2020-05-29 14:17:02.390 - HotkeysConfig save started: C:\Users\xyman\Documents\ShareX\HotkeysConfig.json
2020-05-29 14:17:02.510 - UploadersConfig save successful: C:\Users\xyman\Documents\ShareX\UploadersConfig.json
2020-05-29 14:17:02.551 - HotkeysConfig save successful: C:\Users\xyman\Documents\ShareX\HotkeysConfig.json
2020-05-29 14:17:02.592 - ApplicationConfig save successful: C:\Users\xyman\Documents\ShareX\ApplicationConfig.json
```
And then...
![image](https://user-images.githubusercontent.com/2865341/83321171-685c7b80-a256-11ea-9902-e1b71fbe5fa1.png)
That line ends with `2020-05-30 00:31:58.459 - ShareX starting.`

Afterwards:

```
2020-05-30 00:31:58.465 - Version: 13.1
2020-05-30 00:31:58.465 - Build: Release
2020-05-30 00:31:58.465 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2020-05-30 00:31:58.465 - Personal path: C:\Users\xyman\Documents\ShareX
2020-05-30 00:31:58.467 - Operating system: Windows 10 Education (64-bit)
2020-05-30 00:31:58.468 - Running as elevated process: False
2020-05-30 00:31:58.470 - Flags: SilentRun
2020-05-30 00:31:58.608 - ApplicationConfig load started: C:\Users\xyman\Documents\ShareX\ApplicationConfig.json
2020-05-30 00:31:59.405 - ApplicationConfig load failed: C:\Users\xyman\Documents\ShareX\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
2020-05-30 00:31:59.405 - ApplicationConfig load started: C:\Users\xyman\Documents\ShareX\Backup\ApplicationConfig.json
2020-05-30 00:31:59.412 - ApplicationConfig load failed: C:\Users\xyman\Documents\ShareX\Backup\ApplicationConfig.json:
System.Exception: ApplicationConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
2020-05-30 00:31:59.412 - Loading new ApplicationConfig instance.
2020-05-30 00:31:59.917 - UploadersConfig load started: C:\Users\xyman\Documents\ShareX\UploadersConfig.json
2020-05-30 00:31:59.926 - MainForm init started.
2020-05-30 00:32:00.016 - UploadersConfig load failed: C:\Users\xyman\Documents\ShareX\UploadersConfig.json:
System.Exception: UploadersConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
2020-05-30 00:32:00.018 - UploadersConfig load started: C:\Users\xyman\Documents\ShareX\Backup\UploadersConfig.json
2020-05-30 00:32:00.029 - UploadersConfig load failed: C:\Users\xyman\Documents\ShareX\Backup\UploadersConfig.json:
System.Exception: UploadersConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
2020-05-30 00:32:00.029 - Loading new UploadersConfig instance.
2020-05-30 00:32:00.337 - HotkeysConfig load started: C:\Users\xyman\Documents\ShareX\HotkeysConfig.json
2020-05-30 00:32:00.345 - HotkeysConfig load failed: C:\Users\xyman\Documents\ShareX\HotkeysConfig.json:
System.Exception: HotkeysConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
2020-05-30 00:32:00.345 - HotkeysConfig load started: C:\Users\xyman\Documents\ShareX\Backup\HotkeysConfig.json
2020-05-30 00:32:00.349 - HotkeysConfig load failed: C:\Users\xyman\Documents\ShareX\Backup\HotkeysConfig.json:
System.Exception: HotkeysConfig object is null.
   at ShareX.HelpersLib.SettingsBase`1.LoadInternal(String filePath, String backupFolder)
2020-05-30 00:32:00.349 - Loading new HotkeysConfig instance.
2020-05-30 00:32:03.141 - MainForm init finished.
2020-05-30 00:32:03.812 - Startup time: 6028 ms
2020-05-30 00:32:03.815 - CommandLine: silent
2020-05-30 00:32:03.862 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
```
Looking like a dirty shutdown or something? Although I'm sure I didn't use the "force shutdown" option and neither I used a hard reset/pull power

In any case, I made a copy of the `ShareX` folder as it is now, in case of any future questions/investigations

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/issues/702#issuecomment-630541152

**Comment by Xymanek** [comment]
Well, to be honest I could not really foresee the "solution" being in a comment to a closed 5 year old issue 😂 

That said, I'm glad the problem was found (even if my "investigation" was wasted) and looking forward to the next update 👍
