### ISSUE TITLE
The remote name could not be resolved

### ISSUE THREAD

**Issue by IndigoSypnopsis** [ShareX/ShareX#4859]
Error message:
The remote name could not be resolved: 'spheu.ca'

Request URL:
https://spheu.ca/ss/upload.php

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

I've been getting this error for around an hour now, any ideas?

**Comment by IndigoSypnopsis** [comment]
Nevermind issue resolved, though I'm getting "URL: File upload failed - CHMOD/Folder doesn't exist?" error now..
