### ISSUE TITLE
Temporary "Could not create SSL/TLS secure channel" when uploading to pomf.se

### ISSUE THREAD

**Issue by Moter8** [ShareX/ShareX#486]
```
Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)
```

Manually trying to upload again everything worked. Maybe include some "retry thrice" functionality?

**Comment by Jaex** [comment]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/01/ShareX_ndwKPlJffA.png)

**Comment by akiraaisha** [comment]
Using this method works for me after months of trying to find a fix. I can now upload and Auto Update.
`Go to this Registry:`
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols`

Then I set the value of `Enabled` into **1** from TLS 1.1 to TLS 1.2
If it doesn't exist, create one in DWORD.
