### ISSUE TITLE
Could not find a part of the path 'C:\Program Files\ShareX\ShareX\PersonalPath.cfg'.

### ISSUE THREAD

**Issue by YouAreWrongAgain** [ShareX/ShareX#4879]
I've formatted and reinstalled from scratch twice and (non-portable) ShareX 13.1.0 consistently attempts to wrongly access nonexistent files and directories ("C:\Program Files\ShareX\ShareX" does not exist.), create and modify folders and files in the application's directory instead of the user's home directory, and cannot be altered to use a folder in the user's home directory.

Method used to exhibit and replicate error: 
Format hard drive.
Install Windows 10 Home (64-bit).
Download and install
    https://github.com/ShareX/ShareX/releases/download/v13.1.0/ShareX-13.1.0-setup.exe
(NOT ShareX-portable.zip)

Run ShareX. Receive modal(?) un-copy-pasteable

    Unable to create folder: "ShareX"
    
    System.UnauthorizedAccessException: Access to the path 'ShareX' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.Program.UpdatePersonalPath()

(It is impossible to determine if the window is application modal since there are no other windows associated with this application to prevent recceiving focus.)
OK.  Receive modal(?) un-copy-pasteable

    Could not create directory.
    
    System.UnauthorizedAccessException: Access to the path 'ShareX\Logs' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String directory Path)     

OK.
ShareX window opens.
Application settings... | Paths 
Set ShareX personal folder: Browse.
New folder:  "(username)\ShareX"
Navigate to "(username)".  Select "ShareX".  Click "Select".
ShareX personal folder changes to "%UserProfile%\ShareX".
Click "Apply".  Receive modal un-copy-pasteable

    Could not create directory.

    System.UnauthorizedAccessException: Access to the path 'ShareX' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String directory Path)

OK.  Receive modal copy-pasteable ShareX debug log

    2020-06-13 15:03:08.785 - ShareX starting.
    2020-06-13 15:03:08.785 - Version: 13.1
    2020-06-13 15:03:08.785 - Build: Release
    2020-06-13 15:03:08.785 - Command line: "C:\Program Files\ShareX\ShareX.exe"
    2020-06-13 15:03:08.785 - Personal path: ShareX
    2020-06-13 15:03:08.785 - Operating system: Windows 10 Home (64-bit)
    2020-06-13 15:03:08.785 - Running as elevated process: False
    2020-06-13 15:03:08.801 - ApplicationConfig file does not exist: ShareX\ApplicationConfig.json
    2020-06-13 15:03:08.801 - ApplicationConfig file does not exist: ShareX\Backup\ApplicationConfig.json
    2020-06-13 15:03:08.801 - Loading new ApplicationConfig instance.
    2020-06-13 15:03:09.017 - UploadersConfig file does not exist: ShareX\UploadersConfig.json
    2020-06-13 15:03:09.017 - UploadersConfig file does not exist: ShareX\Backup\UploadersConfig.json
    2020-06-13 15:03:09.017 - Loading new UploadersConfig instance.
    2020-06-13 15:03:09.017 - MainForm init started.
    2020-06-13 15:03:09.033 - HotkeysConfig file does not exist: ShareX\HotkeysConfig.json
    2020-06-13 15:03:09.033 - HotkeysConfig file does not exist: ShareX\Backup\HotkeysConfig.json
    2020-06-13 15:03:09.033 - Loading new HotkeysConfig instance.
    2020-06-13 15:03:09.433 - MainForm init finished.
    2020-06-13 15:03:09.703 - Startup time: 487210 ms
    2020-06-13 15:03:09.750 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
    2020-06-13 15:03:09.750 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
    2020-06-13 15:03:09.750 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
    2020-06-13 15:03:09.750 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording using custom region, Job: ScreenRecorder
    2020-06-13 15:03:09.750 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF) using custom region, Job: ScreenRecorderGIF
    2020-06-13 15:03:09.750 - HotkeyManager started.
    2020-06-13 15:03:09.750 - WatchFolderManager started.
    2020-06-13 15:06:30.525 - Exception:
    System.UnauthorizedAccessException: Access to the path 'ShareX' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String directoryPath)
    2020-06-13 15:07:56.901 - Unhandled exception:
    System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\ShareX\ShareX\PersonalPath.cfg'.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
      at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
      at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
      at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
      at ShareX.Program.WritePersonalPathConfig(String path)
      at ShareX.ApplicationSettingsForm.btnPersonalFolderPathApply_Click(Object sender, EventArgs e)
      at System.Windows.Forms.Control.OnClick(EventArgs e)
      at System.Windows.Forms.Button.OnClick(EventArgs e)
      at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
      at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
      at System.Windows.Forms.Control.WndProc(Message& m)
      at System.Windows.Forms.ButtonBase.WndProc(Message& m)
      at System.Windows.Forms.Button.WndProc(Message& m)
      at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
    
    ShareX 13.1 (Release)

Continue.
Check in File Explorer:  "C:\Program Files\ShareX\ShareX" does not exist.  The only subdirectories of "C:\Program Files\ShareX" are "Languages", "Licenses", and "Stickers".
Check in File Explorer:  There is no file named "PersonalPath.cfg" on any disk attached to this computer.
Check in File Explorer:  text files (not in Licenses): "ShareX.exe.config" does not contain evidence of a method to fix ShareX.
Check in RegEdit: "PersonalPath.cfg" does not appear as a substring of a Key, Value, or Data element in the registry.
Back on the paths (sub-)window, the Sub-folder pattern example continues to be the prefix nonexistent (and non-copy-pasteable) path "C:\Program Files\ShareX\ShareX\Screenshots\2020-06".
Close application settings.  Receive non-modal non-copy-pasteable

    Could not create directory.

    System.UnauthorizedAccessException: Access to the path 'ShareX' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String directory Path)

Receive non-copy-pasteable system notification followed by ShareX debug log addendum.

    [continues from above]
    2020-06-13 15:21:08.593 - ShareX continue.
    2020-06-13 15:23:45.155 - Exception:
    System.UnauthorizedAccessException: Access to the path 'ShareX' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String directoryPath)
    2020-06-13 15:23:47.843 - Unhandled exception:
    System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\ShareX\ShareX\PersonalPath.cfg'.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
      at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
      at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
      at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
      at ShareX.Program.WritePersonalPathConfig(String path)
      at ShareX.ApplicationSettingsForm.btnPersonalFolderPathApply_Click(Object sender, EventArgs e)
      at System.Windows.Forms.Control.OnClick(EventArgs e)
      at System.Windows.Forms.Button.OnClick(EventArgs e)
      at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
      at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
      at System.Windows.Forms.Control.WndProc(Message& m)
      at System.Windows.Forms.ButtonBase.WndProc(Message& m)
      at System.Windows.Forms.Button.WndProc(Message& m)
      at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

    ShareX 13.1 (Release)
    2020-06-13 15:23:50.766 - ShareX continue.
    2020-06-13 15:23:54.122 - ApplicationConfig save started: ShareX\ApplicationConfig.json
    2020-06-13 15:23:54.122 - Exception:
    System.UnauthorizedAccessException: Access to the path 'ShareX' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String directoryPath)
    2020-06-13 15:24:59.723 - Exception:
    System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\ShareX\ShareX\ApplicationConfig.json.temp'.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
      at ShareX.HelpersLib.SettingsBase`1.SaveInternal(String filePath)
    2020-06-13 15:24:59.746 - ApplicationConfig save failed: ShareX\ApplicationConfig.json

Check in File Explorer:  There is no file named "ApplicationConfig.json" on any disk attached to this computer.
Exit ShareX.  Receive three copies of apparently identical non-modal non-copy-pasteable

    Could not create directory.

    System.UnauthorizedAccessException: Access to the path 'ShareX\Logs' is denied.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
      at ShareX.HelpersLib.Helpers.CreateDirectoryFromDirectoryPath(String directory Path)     

OK.  OK.  OK.

Restart ShareX.  Receive the same two potentially modal non-copy-pasteable error dialogs.
Check the Application Settings... | Paths and verify that this software is still unusable.

**Comment by Jaex** [comment]
https://getsharex.com/docs/command-line-arguments#personal-path

There I listed how ShareX decides about personal path. So one of them must be causing default personal path of ShareX to be changed.

**Comment by YouAreWrongAgain** [comment]
There are several launchers.

Startup applications | Share X : 'C:\Program Files\ShareX'
1. No flags specified.
2. 'C:\Program Files\ShareX\Portable' does not exist.
3. 'C:\Program Files\ShareX\PortableApps' does not exist.
4. '%LocalAppData\ShareX' is 'C:\Users\(username)\AppData\Local\ShareX' and does not exist.
5. 'C:\Program Files\ShareX\PersonalPath.cfg' does not exist.
6. 'Documents' is 'C:\Users\(username)\OneDrive\Documents' and does not exist.  (OneDrive has been uninstalled at user request.)  'C:\Users\(username)\Documents' exists (and is empty), but is not to what the special name 'Documents' resolves.
7. 'Documents' is 'C:\Users\(username)\OneDrive\Documents' and does not exist.

The desktop icon starts in 'C:\Program Files\ShareX', so the above applies exactly.
The start menu icon is mute as to how it launches the application.

No aspect of the above explains the fragment 'ShareX\ShareX' in the path at which ShareX is incorrectly attempting to modify files.  Nor does any aspect of the above explain why ShareX refuses to be configured to use a folder that actually exists.

**Comment by Jaex** [comment]
> No aspect of the above explains the fragment 'ShareX\ShareX' in the path at which ShareX is incorrectly attempting to modify files. Nor does any aspect of the above explain why ShareX refuses to be configured to use a folder that actually exists.

It explains. You even found the issue yourself there. You told:

> 'C:\Users(username)\Documents' exists (and is empty), but is not to what the special name 'Documents' resolves.

So ShareX code:

```cs
public static readonly string DefaultPersonalFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), Name);
```

tries to get Documents folder which returns empty string and empty string is combined with ShareX and end result becomes just "ShareX".

I don't even know how you managed to break Documents path but that is the issue looks like.

**Comment by YouAreWrongAgain** [comment]
Excellent.  You have identified wrong code.

However, you have mischaracterized its behaviour in this case.  GetFolderPath() returns "the path to the specified system special folder, if that folder physically exists on your computer; otherwise, an empty string ("")."  ( https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=netcore-3.1 )  Since the Documents folder does not exist, the code you quote is equivalent to 

    public static readonly string DefaultPersonalFolder = Path.Combine("", Name);

Since Name is not a rooted path, Path.Combine() returns whatever is in Name, which you write is "ShareX".  It is not documented to return the wrong absolute path you write, any absolute path, or any relative path.  It is documented to return "ShareX".

The issueis *not* that the Documents system special folder references a nonexistent folder.  *ANY* file system reference can reference a nonexistent folder.  The issueis that ShareX fails to detect this perfectly reasonable condition, consequently attempts permissions violating actions, and CANNOT BE FIXED by setting the folder in the software settings.

And additional issue is that it is easy to find years of equivalent reports of inadequate handling of configuration folders in ShareX with a consistent plan of blaming users for the deficiencies of ShareX's code.  You have just duplicated that error.

**Comment by Jaex** [comment]
ShareX works as intended, there is no problem in code.

**Comment by YouAreWrongAgain** [comment]
ShareX fails on install.  >90% of users will immediately uninstall it and think "these guys are too stupid to write working code."  They will move on to code that works when it is installed and you will never know about ShareX's failure.  Of the few percent who are willing to report that ShareX falls flat on its face immediately after install, more than 90% will see the GitHub account creation requirement and decide "this barrier to entry exceed my tolerance for fuckwits whose code doesn't even work."  You won;t ever hear of ShareX;s deficiencies from those users either.  Of the few percent of that less than 1% who persist, the majority will find that the ShareX code has made wrong assumptions about the filesystem for years, those errors have been reported, and Jaex has persistently claimed that obviously broken is actually correct as you have done here.  So ShareX fails more than ten thousand times for every time you choose to blame the users for broken code.

You have described that ShareX accepts user supplied data, the location of the Documents directly, and uses it without validation.  Input validation is a basic requirement for code that works.  ShareX does not perform input validation, so it exposes a bug, by being code that does not work.  No amount of blaming the user or blaming the OneDrive uninstall, or claiming that it works for other people overcomes that the ShareX code fails input validation.  That is a defect in ShareX's code.  Claiming that the code has no problem is wrong, unambiguously wrong, repeatedly demonstrated to be wrong, and indicative of deep incompetence.

My only hope at this point is that your bungling of every aspect of this issue report stands as a warning to the future less than 1% of potential bug reporters that trusting ShareX to work is trusting incompetence to succeed., something only a fool would do.

**Comment by AnotherNeko** [comment]
anyone want to propose/contribute a fix for this?

**Comment by CoreyCole** [comment]
FWIW I reproduced something like this when I clean installed windows today.
![image](https://github.com/ShareX/ShareX/assets/4467106/7bce5413-8f53-4e4a-996d-137ecae051ad)

Repro:
- Install windows 11 pro
- Uninstall onedrive
- Install sharex
- Open sharex
- Take screenshot
