### ISSUE TITLE
 at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

### ISSUE THREAD

**Issue by teguh77** [ShareX/ShareX#4881]
System.IO.IOException: The file cannot be accessed by the system.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite)
   at ShareX.SettingManager.MigrateHistoryFile()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)

**Comment by tsalagi** [comment]
Same:

System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ShareX.Program.ReadPersonalPathConfig()
   at ShareX.Program.UpdatePersonalPath()
   at ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
