### ISSUE TITLE
Custom Uploader Not Working

### ISSUE THREAD

**Issue by cupiditys** [ShareX/ShareX#4882]
It's been working fine for the past few months but now its started giving this error:
`Response parse failed.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: F. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntaxJson(String syntaxJsonPath)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntax(String syntax, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderParser.Parse(String text, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, ResponseInfo responseInfo, CustomUploaderInput input, Boolean isShortenedURL)
   at ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)
`

**Comment by Aholicknight** [comment]
What is the URL For your custom uploader?
