### ISSUE TITLE
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by shivam2100** [ShareX/ShareX#4893]
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.ExternalCLIManager.Open(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.Run(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.GetDirectShowDevices()
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<>c__DisplayClass11_0.<RefreshSourcesAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<RefreshSourcesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<SettingsLoad>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<FFmpegOptionsForm_Load>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.1 (Release)

**Comment by UserBL9999** [comment]
Hi, I am not a programmer whatsoever, but, if anyone figured out what this message may be I would appreciate and explanation. I am getting the same "error" on my ShareX and cannot seem to solve this

System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.ExternalCLIManager.Open(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.Run(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.GetDirectShowDevices()
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<>c__DisplayClass11_0.<RefreshSourcesAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<RefreshSourcesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<btnInstallHelperDevices_Click>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
