### ISSUE TITLE
Random crashes when taking full display screenshots

### ISSUE THREAD

**Issue by ReleaseOverflow** [ShareX/ShareX#4902]
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at ShareX.HelpersLib.Extensions.CreateEmptyBitmap(Image img, Int32 widthOffset, Int32 heightOffset, PixelFormat pixelFormat)
   at ShareX.HelpersLib.ImageHelpers.FillBackground(Image img, Brush brush)
   at ShareX.HelpersLib.ImageHelpers.FillBackground(Image img, Color color)
   at ShareX.TaskHelpers.SaveImageAsJPEGStream(Image img, Stream stream, Int32 jpegQuality)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   at ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.1 (Release)

LOG END:  https://pastebin.com/LYCkayMK

**Comment by Redirts** [comment]
I dont drink it makes sense for this one to be closed. It will just be reopened by someone else who will eventually hit this issue again....
