### ISSUE TITLE
The parameter is incorrect.

### ISSUE THREAD

**Issue by robinhood2014** [ShareX/ShareX#4905]
Trying to start ShareX causes the program to crash with this error:

```
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite)
   at ShareX.SettingManager.MigrateHistoryFile()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.1.1 Dev (Release)
```

Additionally, when I attempt to debug the program in Visual Studio 2019 Community Edition, I get this garglemesh which I can make neither head nor tail of:

```
System.IO.IOException
  HResult=0x80070057
  Message=The parameter is incorrect.

  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.MoveFile(String filePath, String destinationFolder, Boolean overwrite) in C:\Users\donni\Source\Repos\ShareX\ShareX.HelpersLib\Helpers\Helpers.cs:line 995
   at ShareX.SettingManager.MigrateHistoryFile() in C:\Users\donni\Source\Repos\ShareX\ShareX\SettingManager.cs:line 246
   at ShareX.SettingManager.LoadApplicationConfig() in C:\Users\donni\Source\Repos\ShareX\ShareX\SettingManager.cs:line 152
   at ShareX.SettingManager.LoadInitialSettings() in C:\Users\donni\Source\Repos\ShareX\ShareX\SettingManager.cs:line 116
   at ShareX.Program.Run() in C:\Users\donni\Source\Repos\ShareX\ShareX\Program.cs:line 325
   at ShareX.Program.Main(String[] args) in C:\Users\donni\Source\Repos\ShareX\ShareX\Program.cs:line 281
```

**Comment by robinhood2014** [comment]
Issue is fixed with latest commit.
