### ISSUE TITLE
Unable to load one or more of the requested types.

### ISSUE THREAD

**Issue by harkaj33** [ShareX/ShareX#4972]
I tried reinstalling it both on the Microsoft Store and the installer from the website, but I'm keep getting this error and I don't know how to fix it. It doesn't upload to Imgur anymore and I can't use the printscreen button on my keyboard.

```
System.TypeInitializationException: The type initializer for 'ShareX.UploadersLib.UploaderFactory' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ShareX.HelpersLib.Helpers.GetInstances[T]()
   at ShareX.UploadersLib.UploaderFactory.CacheServices[T,T2]()
   at ShareX.UploadersLib.UploaderFactory..cctor()
   --- End of inner exception stack trace ---
   at ShareX.UploadersLib.UploadersConfigValidator.Validate(ImageDestination destination, UploadersConfig config)
   at ShareX.MainForm.EnableDisableToolStripMenuItems[T](ToolStripDropDownItem[] parents)
   at ShareX.MainForm.UpdateDestinationStates()
   at ShareX.MainForm.UpdateControls()
   at ShareX.MainForm.MainForm_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at ShareX.HelpersLib.HotkeyForm.WndProc(Message& m)
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.1 (Release)
```

**Comment by harkaj33** [comment]
It was a bug in a Windows 10 version that got fixed after an update, even the patchnotes said it fixed an error where windows couldn't find files...
