### ISSUE TITLE
Gfycat upload error

### ISSUE THREAD

**Issue by Long-Horse** [ShareX/ShareX#499]
I got this error text when I tried uploading a gfycat mp4. Also my hotkey for recording a gfycat mp4 doesn't work and I can't make a new one.

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, Stream dataStream)

**Comment by Jaex** [comment]
I tried mp4 gfycat upload with hotkey and it worked: https://gfycat.com/AnxiousSparseBluejay

**Comment by Long-Horse** [comment]
Ok I got it. Idk why but no shortcut will work for Print Screen or Shift Print Screen. This is a new discovery for me since they both used to work fine.

**Comment by Jaex** [comment]
That means another software in your computer registered that hotkeys so ShareX can't register them again.

**Comment by Long-Horse** [comment]
Idk what it could be though. Nothing happens when I do Shift PrntScrn and I didn't install anything new that would use the hotkey.

**Comment by Jaex** [comment]
Is anything show up in debug log?

**Comment by Long-Horse** [comment]
No it just says I changed the hotkey. Also the little square stays green insted of turning red so I don't think therre is a conflicting hotkey :/
