### ISSUE TITLE
MediaCrush upload error

### ISSUE THREAD

**Issue by westor7** [ShareX/ShareX#502]
Hello,

I am trying to upload a file via MediaCrush but return me this error:

System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)
   at ShareX.UploadersLib.FileUploaders.MediaCrushUploader.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
You need to use email for username section maybe it caused it?

**Comment by Jaex** [comment]
I tried uploading to MediaCrush now and it worked. Is it possible your login info wrong? Or it can be server related issue too.
