### ISSUE TITLE
Error while importing custom uploader

### ISSUE THREAD

**Issue by skull** [ShareX/ShareX#5023]
System.BadImageFormatException: Could not load file or assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ShareX.HelpersLib.URLHelpers.ParseQueryString(String url)
   at ShareX.UploadersLib.CustomUploaderItem.CheckRequestURL()
   at ShareX.UploadersLib.CustomUploaderItem.CheckBackwardCompatibility()
   at ShareX.UploadersLib.CustomUploaderSettingsForm.eiCustomUploaders_ImportRequested(Object obj)
   at ShareX.HelpersLib.ExportImportControl.OnImportRequested(String json)
   at ShareX.HelpersLib.ExportImportControl.tsmiImportFile_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

ShareX 13.2 (Release)

**Comment by Jaex** [comment]
Most likely your .NET Framework become corrupt.
