### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by SarahTab** [ShareX/ShareX#5081]
I have just downloaded ShareX and receive this error every time I use the software to capture a screen. I have tried uninstalling, deleting the files from My Documents and then reinstalling but same issue. I have also tried doing the same on another PC under my login and received the same error. 

Error message:
The underlying connection was closed: An unexpected error occurred on a send.

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by wangliandong** [comment]
I met similar issue when I tried to upload my gif:
Error message:
The underlying connection was closed: An unexpected error occurred on a send.

Request URL:
https://api.imgur.com/3/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
