### ISSUE TITLE
Seafile is  broken in 13.2.1

### ISSUE THREAD

**Issue by gerroon** [ShareX/ShareX#5094]
Hi,

I have been using Seafile with 13.1 successfully for a bit. I just upgraded to 13.2.1 and now I am getting permission problems wit it. I check the Seafile setup from destionations and everything validates perfectly. I can even see the folder listing fine.

This is my api url `https://xxxx.org/api2/`

I am on Windows 10

```
Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2020-10-02 23:52:51.428 - Upload failed. Retrying upload.
2020-10-02 23:52:53.269 - Error:
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://xxxx.org/seafhttp/upload-api/7883310a-835a-4ddd-89c0-4d32b74a65dc

Status code:
(403) Forbidden

Headers:
Connection: keep-alive
Access-Control-Allow-Headers: x-requested-with, content-type, content-range, content-disposition, accept, origin, authorization
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 31
Content-Type: application/json; charset=utf-8
Date: Sat, 03 Oct 2020 04:52:17 GMT
Server: nginx/1.17.8

Response text:
{"error": "Permission denied."}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2020-10-02 23:52:53.274 - Task failed. Filename: ShareX_FK7FzYcLHn.jpg, Errors:
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://xxxx.org/seafhttp/upload-api/7883310a-835a-4ddd-89c0-4d32b74a65dc

Status code:
(403) Forbidden

Headers:
Connection: keep-alive
Access-Control-Allow-Headers: x-requested-with, content-type, content-range, content-disposition, accept, origin, authorization
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 31
Content-Type: application/json; charset=utf-8
Date: Sat, 03 Oct 2020 04:52:17 GMT
Server: nginx/1.17.8

Response text:
{"error": "Permission denied."}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)



```

**Comment by gerroon** [comment]
Hmm this seems to be tied to the subfolders, which was working in 13.1

**Comment by angelfor3v3r** [comment]
I just set up Seafile today and ShareX seems to fail if "Path:" is set to anything other than "/" (i.e, "/Share. Am I not understanding something here?

Curious if anyone else is still having this problem.

ShareX 14.1 Portable
Windows 11 (22H2 - 22621.674)

```
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://[REDACTED]/seafhttp/upload-api/5ad5bf8e-4d6b-485f-90a2-3db469f0abd3

Status code:
(403) Forbidden

Headers:
Access-Control-Allow-Headers: x-requested-with, content-type, content-range, content-disposition, accept, origin, authorization
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Content-Length: 31
Content-Type: application/json; charset=utf-8
Date: Fri, 21 Oct 2022 14:23:23 GMT

Response text:
{"error": "Permission denied."}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```
