### ISSUE TITLE
Trying to save an edited indexed resource breaks ShareX

### ISSUE THREAD

**Issue by brezanac** [ShareX/ShareX#5095]
Trying to save an edited indexed pixel format image, i.e. an 8-bit PNG, with added annotations, breaks ShareX consistently.

How to reproduce.

1) Load any indexed pixel format into the ShareX editor (i.e. an 8-bit PNG). Examples attached below.

![minions-8bit](https://user-images.githubusercontent.com/389770/95012338-0a8ed480-0638-11eb-93ca-1456ce239f19.png)
**PNG, 8 bit**

![minions-8bit](https://user-images.githubusercontent.com/389770/95012340-14183c80-0638-11eb-9941-fcce83dae08b.gif)
**GIF, 8 bit**

2) Make annotations (i.e. use the Rectangle tool, add some text etc.)

3) Try to save the image.

4) BOOM.

**Tested in Windows Sandbox too**
![shot](https://user-images.githubusercontent.com/389770/95012344-1aa6b400-0638-11eb-9d82-81cea97293e5.png)

The issue is reproducable accross all platforms and hardware I've tested it on.

```
[See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: A Graphics object cannot be created from an image that has an indexed pixel format.
   at System.Drawing.Graphics.FromImage(Image image)
   at ShareX.ScreenCaptureLib.ShapeManager.RenderOutputImage(Bitmap bmp, Point offset)
   at ShareX.ScreenCaptureLib.RegionCaptureForm.GetResultImage()
   at ShareX.ScreenCaptureLib.RegionCaptureForm.ReceiveImageForTask()
   at ShareX.ScreenCaptureLib.RegionCaptureForm.OnSaveImageAsRequested()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at ShareX.HelpersLib.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ShareX
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.exe
----------------------------------------
ShareX.HelpersLib
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.HelpersLib.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ShareX.UploadersLib
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.UploadersLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Program%20Files/ShareX/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ShareX.HistoryLib
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.HistoryLib.DLL
----------------------------------------
ShareX.ImageEffectsLib
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.ImageEffectsLib.DLL
----------------------------------------
ShareX.ScreenCaptureLib
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.ScreenCaptureLib.DLL
----------------------------------------
ShareX.IndexerLib
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.IndexerLib.DLL
----------------------------------------
ShareX.MediaLib
    Assembly Version: 13.2.1.0
    Win32 Version: 13.2.1
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.MediaLib.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
MegaApiClient
    Assembly Version: 1.8.2.0
    Win32 Version: 1.8.2.0
    CodeBase: file:///C:/Program%20Files/ShareX/MegaApiClient.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.](url)
```

**Comment by Jaex** [comment]
Can you give example image file.

**Comment by brezanac** [comment]
> Can you give example image file.

Of course. 

I've added a couple of example files (PNG and GIF, both 8bit) and a screenshot from Windows Sanbox, which should eliminate external influence and provide results in an isolated environment.

The exception message does sound pretty self-explanatory though.

> A Graphics object cannot be created from an image that has an indexed pixel format.

which, without going into the code, probably means whatever library is used to merge the 8-bit images themselves with added annotations, it is not capable of exporting the final image to the same depth (8 bit) of the original image.

This effectively eliminates the ability to use GIF images at all for adding annotations but PNG file limitation could be circumvented by simply defaulting all PNG saves from the editor to 24-bit PNG.

**Comment by worldsdream** [comment]
I do have the same and I am happy that you fixed it @Jaex. Will you publish a beta anytime soon, so we can install that version or do we need to wait to the next release?

**Comment by Jaex** [comment]
You can download it: https://getsharex.com/docs/dev-builds
