### ISSUE TITLE
Trouble uploading to Google photos

### ISSUE THREAD

**Issue by xchuey** [ShareX/ShareX#5097]
It was working fine like 2 days ago, no changes or anything made, just cant seem to upload to Google photos anymore.
Heres the log:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(429) Too Many Requests

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Oct 2020 05:35:55 GMT
Server: ESF

Response text:
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/810697162603/apiui/credential"
          }
        ]
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(429) Too Many Requests

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Oct 2020 05:35:57 GMT
Server: ESF

Response text:
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/810697162603/apiui/credential"
          }
        ]
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
```

**Comment by JoFo-IT** [comment]
I have the same problem.
I tryed it with my own Google key.
