### ISSUE TITLE
API upload error to Google Photos

### ISSUE THREAD

**Issue by rolltidehero** [ShareX/ShareX#5128]
I've been getting this A LOT lately. I may be wrong but it looks like it's exceeded API limit. Maybe you can add a setting to allow us to enter own API key? This is the first screenshot I've tried today.

**_"message": "Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'_**

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.CheckUploadFilters(Stream stream, String filename)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(429) Too Many Requests

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Thu, 15 Oct 2020 22:13:47 GMT
Server: ESF

Response text:
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/810697162603/apiui/credential"
          }
        ]
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.CheckUploadFilters(Stream stream, String filename)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(429) Too Many Requests

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Thu, 15 Oct 2020 22:13:49 GMT
Server: ESF

Response text:
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:810697162603'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/810697162603/apiui/credential"
          }
        ]
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
```

**Comment by Pedrilkov** [comment]
This is because google is spying on us
