### ISSUE TITLE
Error when uploading with FTP

### ISSUE THREAD

**Issue by ParaPup** [ShareX/ShareX#518]
Hi there,
After updating to 9.7.0, I am experiencing an issue with FTP.

I am trying to upload with FTP, when testing it responds Connected, however it is failing with the error:
```
2015-02-18 20:14:15.143 - Task in queue. Job: Job, Type: File, Host: FTP
2015-02-18 20:14:15.146 - Task status: Preparing
2015-02-18 20:14:15.152 - Upload started. Filename: 2015-02-18_20-14-15.png
2015-02-18 20:14:32.656 - Exception:
System.TimeoutException: Timed out trying to read data from the socket stream!
   at System.Net.FtpClient.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FtpClient.FtpSocketStream.ReadLine(Encoding encoding)
   at System.Net.FtpClient.FtpClient.GetReply()
   at System.Net.FtpClient.FtpClient.Execute(String command)
   at System.Net.FtpClient.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenWrite(String path, FtpDataType type)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)
2015-02-18 20:14:32.659 - Task failed. Filename: 2015-02-18_20-14-15.png, Errors:
System.TimeoutException: Timed out trying to read data from the socket stream!
   at System.Net.FtpClient.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FtpClient.FtpSocketStream.ReadLine(Encoding encoding)
   at System.Net.FtpClient.FtpClient.GetReply()
   at System.Net.FtpClient.FtpClient.Execute(String command)
   at System.Net.FtpClient.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenWrite(String path, FtpDataType type)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)
```
Loaded assemblies:
```ShareX.exe
ShareX.HelpersLib.dll
ShareX.UploadersLib.dll
Newtonsoft.Json.dll
ShareX.IndexerLib.dll
ShareX.ImageEffectsLib.dll
ShareX.ScreenCaptureLib.dll
MegaApiClient.dll
Renci.SshNet.dll
System.Net.FtpClient.dll
Greenshot.ImageEditor.dll
ShareX.HistoryLib.dll
```

I have uninstalled and reinstalled, and the issue still persists.

Any ideas?

Thanks.

**Comment by Jaex** [comment]
Time out issues mainly not to do with ShareX.

**Comment by ParaPup** [comment]
Like I mentioned before, this only happened after updating to 9.7.0 and not previous versions.

Time out was caused by ShareX using Active FTP.

Issue fixed by setting IsActive to false (passive) on the FTP Destination.

**Comment by Jaex** [comment]
Nothing changed in 9.7.0 to do with FTP. And nothing sets IsActive to true in codes.
