### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by HypoCheese** [ShareX/ShareX#5186]
Cannot seem to screenshot anything anymore. It was working no more than 5 minutes ago, and it's stopped working. Here are the error logs:

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
Content-Length: 102
Content-Type: application/vnd.imgur.v1+json
Date: Wed, 11 Nov 2020 09:20:08 GMT

Response text:
{"errors":[{"id":"","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
Content-Length: 102
Content-Type: application/vnd.imgur.v1+json
Date: Wed, 11 Nov 2020 09:20:11 GMT

Response text:
{"errors":[{"id":"","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

Thanks!

**Comment by jdroo** [comment]
Getting this as well. bump

**Comment by Jaex** [comment]
Imgur have problem.

**Comment by Dankbooru** [comment]
Same here. Jaex is probably right

**Comment by HypoCheese** [comment]
Yeah it's working now, seems to have been an Imgur issue.

**Comment by uncodable** [comment]
Ongoing issue @Jaex 

```
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1243
X-Post-Rate-Limit-Reset: 3310
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12499
X-Ratelimit-Clientreset: 27889
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Thu, 12 Nov 2020 13:32:12 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

Looking like Imgur's API is having a bad week.
