### ISSUE TITLE
gfycat upload error

### ISSUE THREAD

**Issue by tice1** [ShareX/ShareX#523]
All of sudden im only getting errors when i try to do a screen recording.
example: http://i.imgur.com/PYAtf3g.png

Errors are always the same:

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.TranscodeFile(String key, UploadResult result)
   at ShareX.UploadersLib.FileUploaders.GfycatUploader.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, Stream dataStream)

looks like someone didnt do a good job at the gfycat implementation...

**Comment by Jaex** [comment]
How you know implementation have problem instead it is server side or computer side problem?
If implementation was bad then how it worked for years and suddenly not works...

**Comment by WebFreak001** [comment]
Either it cant connect using SSL or the server sent a bad formatted response

**Comment by tice1** [comment]
@Jaex Because uploading a mp4 on www.gfycat.com works perfectly fine.

**Comment by WebFreak001** [comment]
can you view and send us the response? 
![](http://i.imgur.com/TI4XcJn.png)

**Comment by tice1** [comment]
Failed uploads do not have the option to view the response(?)
(also yeah, im using the latest sharex version)
http://i.imgur.com/Sm7o05s.png

**Comment by Jaex** [comment]
@tice1 are you using Bitdefender? Because Cloudflare ssl was causing problems with it.

**Comment by Rhedox** [comment]
I am able to fully reproduce the issue so it's most likely a bug.

http://i.imgur.com/lEciDQP.png

**Comment by Jaex** [comment]
I tried their web site and it not completes too:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/02/GqQKFOomsw.png)

It stucks like that never completes.

**Comment by Dinnerbone** [comment]
Definitely a bug on gfycat's side, I can't upload an mp4 on their website (same error as Jeax shows). I'll email them and ask what's up.
