### ISSUE TITLE
When opening Task Settings in 13.3

### ISSUE THREAD

**Issue by Arsenalist** [ShareX/ShareX#5248]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.TaskSettingsForm.WatchFolderAdd(WatchFolderSettings watchFolderSetting)
   at ShareX.TaskSettingsForm..ctor(TaskSettings hotkeySetting, Boolean isDefault)
   at ShareX.MainForm.tsbTaskSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.3 (Release)

**Comment by Jaex** [comment]
Is it happens always when you open task settings?

**Comment by Arsenalist** [comment]
> Is it happens always when you open task settings?

Yes. And my watch folder exists.
