### ISSUE TITLE
Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by indians0201** [ShareX/ShareX#5271]
Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: {. Path '', line 2, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://api.imgur.com/3/upload

Status code:
(429) Too Many Requests

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1200
X-Post-Rate-Limit-Reset: 2191
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 606
Content-Type: application/vnd.imgur.v1+json
Date: Thu, 17 Dec 2020 07:24:59 GMT

Response text:
{"errors":[{"id":"","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}
{"status":200,"success":true,"data":{"id":"TaRAw6a","deletehash":"3u1VB2jLsDwTBVE","account_id":null,"account_url":null,"ad_type":null,"ad_url":null,"title":null,"description":null,"name":"","type":"image/png","width":1106,"height":127,"size":35567,"views":0,"section":null,"vote":null,"bandwidth":0,"animated":false,"favorite":false,"in_gallery":false,"in_most_viral":false,"has_sound":false,"is_ad":false,"nsfw":null,"link":"https://i.imgur.com/TaRAw6a.png","tags":[],"datetime":1608189899,"mp4":"","hls":""}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: {. Path '', line 2, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://api.imgur.com/3/upload

Status code:
(429) Too Many Requests

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1199
X-Post-Rate-Limit-Reset: 2189
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 606
Content-Type: application/vnd.imgur.v1+json
Date: Thu, 17 Dec 2020 07:25:01 GMT

Response text:
{"errors":[{"id":"","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}
{"status":200,"success":true,"data":{"id":"xnKC5ZF","deletehash":"xsNCRHAlkEi6OgK","account_id":null,"account_url":null,"ad_type":null,"ad_url":null,"title":null,"description":null,"name":"","type":"image/png","width":1106,"height":127,"size":35567,"views":0,"section":null,"vote":null,"bandwidth":0,"animated":false,"favorite":false,"in_gallery":false,"in_most_viral":false,"has_sound":false,"is_ad":false,"nsfw":null,"link":"https://i.imgur.com/xnKC5ZF.png","tags":[],"datetime":1608189901,"mp4":"","hls":""}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by Smileynator** [comment]
I had this same issue right after ShareX somehow tried to upload 100 screenshots of my entire screen.
The return value still contains the link to your file usually, but the too many requests return makes it throw this error, and your paste is not the intended URL.

**Comment by Smileynator** [comment]
Good show.
