### ISSUE TITLE
Upgraded - now can't save image captures to folder

### ISSUE THREAD

**Issue by MrZizzy** [ShareX/ShareX#5292]
Recently upgraded and now I get an error when the app attempts to save the image to destination folder I had specified previously:

Exception:
System.UnauthorizedAccessException: Access to the path '[specified path]\firefox_1Cor7POFO2.png' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ShareX.HelpersLib.StreamExtensions.WriteToFile(Stream stream, String filePath)
   at ShareX.ImageData.Write(String filePath)

**Comment by Jaex** [comment]
Your anti virus software most likely blocking ShareX.

**Comment by MrZizzy** [comment]
That was it. Thanks!
