### ISSUE TITLE
ShareX doens't want to take screenshot and return me this error:

### ISSUE THREAD

**Issue by Imperiator** [ShareX/ShareX#5293]
System.Exception: "Request URL" must be configured.
   at ShareX.UploadersLib.CustomUploaderItem.GetRequestURL(CustomUploaderInput input)
   at ShareX.UploadersLib.FileUploaders.CustomFileUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.CheckUploadFilters(Stream stream, String filename)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

System.Exception: "Request URL" must be configured.
   at ShareX.UploadersLib.CustomUploaderItem.GetRequestURL(CustomUploaderInput input)
   at ShareX.UploadersLib.FileUploaders.CustomFileUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.CheckUploadFilters(Stream stream, String filename)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

The connection to the server is OK, works with certains pages but not all ...

**Comment by Imperiator** [comment]
![image](https://user-images.githubusercontent.com/47658318/103277592-b3e02f00-49c9-11eb-9a41-abbeaa5977ef.png)

also every time the error
