### ISSUE TITLE
Trying to upload gifs causes an error

### ISSUE THREAD

**Issue by Karolinskis** [ShareX/ShareX#5328]
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1247
X-Post-Rate-Limit-Reset: 3270
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12498
X-Ratelimit-Clientreset: 14654
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Jan 2021 14:14:12 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by Jaex** [comment]
Your GIF size could be bigger than allowed size.

**Comment by Neoony** [comment]
Pretty sure I got the same problem.
Imgur is supposed to accept gifs up to 200MB

I have no problem uploading some small gif with shareX to imgur.
But with a bigger one, it almost always fails.

I simply have to upload it manually and that works fine.

It has been like that for few versions at least (I guess I had this ever since I started uploading big gifs to imgur)

This was a 150MB Gif:
![](https://i.imgur.com/847tFpF.png)
While manual upload worked fine, see here https://imgur.com/a/rCqRkRX

Perhaps there are some API limitations?

First uploaded small few KB sized GIF just fine.
And then I tried that 150MB one

`
2021-01-13 18:49:32.043 - ShareX starting.
2021-01-13 18:49:32.046 - Version: 13.4
2021-01-13 18:49:32.046 - Build: Release
2021-01-13 18:49:32.046 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2021-01-13 18:49:32.046 - Personal path: C:\Users\Neoony\Documents\ShareX
2021-01-13 18:49:32.047 - Operating system: Windows 10 Pro (64-bit)
2021-01-13 18:49:32.047 - Running as elevated process: True
2021-01-13 18:49:32.060 - Flags: SilentRun
2021-01-13 18:49:32.083 - ApplicationConfig load started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-13 18:49:32.345 - ApplicationConfig load finished: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-13 18:49:32.350 - MainForm init started.
2021-01-13 18:49:32.363 - UploadersConfig load started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-13 18:49:32.492 - UploadersConfig load finished: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-13 18:49:32.509 - HotkeysConfig load started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-13 18:49:32.665 - HotkeysConfig load finished: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-13 18:49:32.891 - MainForm init finished.
2021-01-13 18:49:33.593 - Startup time: 1582 ms
2021-01-13 18:49:33.596 - CommandLine: -silent
2021-01-13 18:49:33.607 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2021-01-13 18:49:33.608 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2021-01-13 18:49:33.608 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2021-01-13 18:49:33.608 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2021-01-13 18:49:33.608 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2021-01-13 18:49:33.610 - HotkeyManager started.
2021-01-13 18:49:33.610 - WatchFolderManager started.
2021-01-14 18:50:36.032 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:50:36.032 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:50:36.032 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:50:36.044 - Starting screen recording. Video encoder: "GIF", Audio encoder: "AAC", FPS: 20
2021-01-14 18:50:36.143 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:50:36.186 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:50:36.222 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:50:40.095 - CLI: "C:\Users\Neoony\Documents\ShareX\Tools\ffmpeg.exe" -rtbufsize 150M -f dshow -framerate 20 -i video="screen-capture-recorder" -c:v libx264 -r 20 -preset ultrafast -tune zerolatency -qp 0 -y "C:\ScreenShots\2021-01\2021-01-14_18-50-37.mp4"
2021-01-14 18:50:52.063 - CLI: "C:\Users\Neoony\Documents\ShareX\Tools\ffmpeg.exe" -i "C:\ScreenShots\2021-01\2021-01-14_18-50-37.mp4" -lavfi "palettegen=stats_mode=full[palette],[0:v][palette]paletteuse=dither=sierra2_4a" -y "C:\ScreenShots\2021-01\2021-01-14_18-50-52.gif"
2021-01-14 18:51:04.135 - Task in queue. Job: Job, Type: Image, Host: Imgur
2021-01-14 18:51:04.178 - Task status: Preparing
2021-01-14 18:51:04.229 - Upload started. Filename: 2021-01-14_18-50-52.gif, Filepath: C:\ScreenShots\2021-01\2021-01-14_18-50-52.gif
2021-01-14 18:51:07.140 - Upload completed. URL: https://i.imgur.com/OwNh3u3.gif, Duration: 2905 ms
2021-01-14 18:51:07.160 - Task completed. Filename: 2021-01-14_18-50-52.gif, Duration: 2979 ms
2021-01-14 18:51:07.228 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:51:07.228 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:51:07.228 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:51:07.334 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:51:07.373 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:51:07.408 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:51:07.498 - URL opened: https://i.imgur.com/OwNh3u3.gif
2021-01-14 18:51:41.528 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:51:41.528 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:51:41.528 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:51:41.538 - Starting screen recording. Video encoder: "GIF", Audio encoder: "AAC", FPS: 20
2021-01-14 18:51:41.624 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:51:41.661 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:51:41.699 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:51:45.837 - CLI: "C:\Users\Neoony\Documents\ShareX\Tools\ffmpeg.exe" -rtbufsize 150M -f dshow -framerate 20 -i video="screen-capture-recorder" -c:v libx264 -r 20 -preset ultrafast -tune zerolatency -qp 0 -y "C:\ScreenShots\2021-01\2021-01-14_18-51-44.mp4"
2021-01-14 18:52:01.946 - CLI: "C:\Users\Neoony\Documents\ShareX\Tools\ffmpeg.exe" -i "C:\ScreenShots\2021-01\2021-01-14_18-51-44.mp4" -lavfi "palettegen=stats_mode=full[palette],[0:v][palette]paletteuse=dither=sierra2_4a" -y "C:\ScreenShots\2021-01\2021-01-14_18-52-01.gif"
2021-01-14 18:52:26.409 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:52:26.409 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:52:26.409 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:52:26.518 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:52:26.558 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:52:26.592 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:52:38.331 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:52:38.331 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:52:38.331 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:52:38.390 - Folder opened: C:\ScreenShots\2021-01\
2021-01-14 18:52:38.428 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:52:38.466 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:52:38.497 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:53:04.502 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:53:04.502 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:53:04.502 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:53:04.535 - Folder opened: C:\ScreenShots\2021-01\
2021-01-14 18:53:04.603 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:53:04.639 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:53:04.693 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:54:26.769 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:54:26.769 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:54:26.770 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:54:26.778 - Starting screen recording. Video encoder: "GIF", Audio encoder: "AAC", FPS: 20
2021-01-14 18:54:26.870 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:54:26.907 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:54:26.942 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:54:30.172 - CLI: "C:\Users\Neoony\Documents\ShareX\Tools\ffmpeg.exe" -rtbufsize 150M -f dshow -framerate 20 -i video="screen-capture-recorder" -c:v libx264 -r 20 -preset ultrafast -tune zerolatency -qp 0 -y "C:\ScreenShots\2021-01\2021-01-14_18-54-28.mp4"
2021-01-14 18:54:40.583 - CLI: "C:\Users\Neoony\Documents\ShareX\Tools\ffmpeg.exe" -i "C:\ScreenShots\2021-01\2021-01-14_18-54-28.mp4" -lavfi "palettegen=stats_mode=full[palette],[0:v][palette]paletteuse=dither=sierra2_4a" -y "C:\ScreenShots\2021-01\2021-01-14_18-54-40.gif"
2021-01-14 18:55:44.909 - Task in queue. Job: Job, Type: Image, Host: Imgur
2021-01-14 18:55:45.108 - Task status: Preparing
2021-01-14 18:55:48.089 - Upload started. Filename: 2021-01-14_18-54-40.gif, Filepath: C:\ScreenShots\2021-01\2021-01-14_18-54-40.gif
2021-01-14 18:56:39.480 - Error:
Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1249
X-Post-Rate-Limit-Reset: 3316
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12498
X-Ratelimit-Clientreset: 1351
X-Ratelimit-Userlimit: 2000
X-Ratelimit-Userremaining: 2000
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Jan 2021 17:56:39 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2021-01-14 18:56:39.482 - Upload failed. Retrying upload.
2021-01-14 18:57:32.949 - Error:
Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1248
X-Post-Rate-Limit-Reset: 3266
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12498
X-Ratelimit-Clientreset: 1301
X-Ratelimit-Userlimit: 2000
X-Ratelimit-Userremaining: 2000
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Jan 2021 17:57:33 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2021-01-14 18:57:32.949 - Upload failed. Retrying upload.
2021-01-14 18:57:44.004 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:57:44.004 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:57:44.004 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:57:44.107 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:57:44.149 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:57:44.189 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:58:19.523 - Upload failed. Retrying upload.
2021-01-14 18:58:19.523 - Flickr configuration is invalid or missing. Please check "Destination settings" window to configure it.
2021-01-14 18:58:20.507 - Task failed. Filename: 2021-01-14_18-54-40.gif, Errors:
Flickr configuration is invalid or missing. Please check "Destination settings" window to configure it.

Error message: Uploading into a free account is not allowed
Error code: 0
2021-01-14 18:58:20.596 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:58:20.596 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:58:20.596 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:58:20.712 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:58:20.748 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:58:20.782 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:58:26.471 - ApplicationConfig save started: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
2021-01-14 18:58:26.471 - HotkeysConfig save started: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:58:26.471 - UploadersConfig save started: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:58:26.566 - UploadersConfig save successful: C:\Users\Neoony\Documents\ShareX\UploadersConfig.json
2021-01-14 18:58:26.604 - HotkeysConfig save successful: C:\Users\Neoony\Documents\ShareX\HotkeysConfig.json
2021-01-14 18:58:26.637 - ApplicationConfig save successful: C:\Users\Neoony\Documents\ShareX\ApplicationConfig.json
`

**Comment by Neoony** [comment]
Just closed the issue??

**Comment by Jaex** [comment]
Yes.

**Comment by TheHDCrafter** [comment]
Adding to the now closed pr, i have the same issue and my gif is only 848 KB. 
![image](https://user-images.githubusercontent.com/29355595/104753431-4289d580-5758-11eb-8896-da9fb6a89919.png)

```
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1236
X-Post-Rate-Limit-Reset: 2276
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 2000
X-Ratelimit-Userremaining: 2000
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Fri, 15 Jan 2021 16:24:56 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)```
