### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by YT4LYFE** [ShareX/ShareX#533]
Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)

I'm not a programmer and I have no idea what any of this means. Please help.

**Comment by Jaex** [comment]
Which host?

**Comment by blackawps** [comment]
Seems to be imgur

**Comment by Jaex** [comment]
It is server side problem and probably it is working for him too now.

**Comment by Cyph3r** [comment]
Confirmed in Windows 10 with ShareX to imgur. Does not error on small images, but on larger ones, gives 405 error.

http://bit.ly/1IAkzsQ

Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
Everybody using their API have this problem. People keep emailing their api support email but got no response yet.

**Comment by Cyph3r** [comment]
@Jaex I figured as much. Just upgraded from Windows 7 where this issue is not present - at least for me. But in Windows 10, it is. Is the API different for Imgur in 10?

**Comment by Jaex** [comment]
No API not different.
