### ISSUE TITLE
Uploading failed

### ISSUE THREAD

**Issue by skeith** [ShareX/ShareX#536]
I have sharex set to upload on my server using SFTP. Images, files and texts all goes to their own subdirectory. Uploading up to 3 mB file has no issue, but when I try to upload 9mB file (e.g. Pidgin installer) it produce an error like this

    Renci.SshNet.Common.SftpPermissionDeniedException: Permission denied
       at Renci.SshNet.Sftp.SftpSession.RequestOpen(String path, Flags flags, Boolean nullOnError)
       at Renci.SshNet.Sftp.SftpFileStream..ctor(SftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize, Boolean useAsync)
       at Renci.SshNet.Sftp.SftpFileStream..ctor(SftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize)
       at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
       at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
       at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
       at ShareX.UploadTask.DoUpload(Int32 retry)

What did I do wrong?

**Comment by Jaex** [comment]
Server denies permission so can't be to do with ShareX I think.

**Comment by skeith** [comment]
Uploading to the same folder with different files do work. Permission was right

**Comment by Hetynne** [comment]
I've had this problem before and after update where screenshots fail to upload:
```
Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)
```

**Comment by Kesmy** [comment]
@skeith This probably has to do with a resumed upload and not having permissions on the server to modify the existing file. If that's the case, the client can't do anything about it. Try interrupting an upload and resuming on the same server, with an actual FTP client, using the same credentials, and see if you get the same result.

**Comment by skeith** [comment]
@Kesmy
I'll try that. Sorry for not being able to reply soon, been busy with work
