### ISSUE TITLE
send bug report!

### ISSUE THREAD

**Issue by Sangkeet** [ShareX/ShareX#5445]
2021-03-01 09:07:59.342 - ShareX starting.
2021-03-01 09:07:59.417 - Version: 13.4
2021-03-01 09:07:59.418 - Build: Release
2021-03-01 09:07:59.418 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2021-03-01 09:07:59.418 - Personal path: C:\Users\Sangkeat\Documents\ShareX
2021-03-01 09:07:59.421 - Operating system: Windows 10 Education (64-bit)
2021-03-01 09:07:59.422 - Running as elevated process: False
2021-03-01 09:07:59.512 - Temp files cleaned: C:\Users\Sangkeat\AppData\Local\Temp\ShareX
2021-03-01 09:07:59.730 - ApplicationConfig load started: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-01 09:08:02.220 - ApplicationConfig load finished: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-01 09:08:02.227 - UploadersConfig load started: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-01 09:08:02.397 - MainForm init started.
2021-03-01 09:08:02.732 - UploadersConfig load finished: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-01 09:08:02.791 - HotkeysConfig load started: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-01 09:08:03.110 - HotkeysConfig load finished: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-01 09:08:04.772 - MainForm init finished.
2021-03-01 09:08:05.571 - Startup time: 6941 ms
2021-03-01 09:08:05.677 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2021-03-01 09:08:05.677 - Unable to register hotkey: Print Screen
2021-03-01 09:08:05.678 - Hotkey register failed: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2021-03-01 09:08:05.678 - Unable to register hotkey: Alt + Print Screen
2021-03-01 09:08:05.678 - Hotkey register failed: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2021-03-01 09:08:05.678 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2021-03-01 09:08:05.678 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2021-03-01 09:08:08.793 - HotkeyManager started.
2021-03-01 09:08:08.799 - WatchFolderManager started.
2021-03-01 09:08:17.642 - CLI: "C:\Users\Sangkeat\Documents\ShareX\Tools\ffmpeg.exe" -list_devices true -f dshow -i dummy
2021-03-01 09:21:25.223 - CLI: "C:\Users\Sangkeat\Documents\ShareX\Tools\output.mp4" -list_devices true -f dshow -i dummy
2021-03-01 09:21:25.697 - Unhandled exception:
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.ExternalCLIManager.Open(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.Run(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.GetDirectShowDevices()
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<>c__DisplayClass11_0.<RefreshSourcesAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<RefreshSourcesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<buttonFFmpegBrowse_Click>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
2021-03-01 09:21:36.824 - ShareX closing. Reason: Unhandled exception.
2021-03-01 09:21:36.886 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2021-03-01 09:21:36.886 - Hotkey unregistered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2021-03-01 09:21:36.886 - Hotkey unregistered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2021-03-01 09:21:36.973 - ShareX closing.
2021-03-01 09:21:37.008 - ApplicationConfig save started: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-01 09:21:37.486 - ApplicationConfig save successful: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-01 09:21:37.501 - UploadersConfig save started: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-01 09:21:37.629 - UploadersConfig save successful: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-01 09:21:37.641 - HotkeysConfig save started: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-01 09:21:37.817 - HotkeysConfig save successful: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-01 09:21:37.833 - ShareX closed.
2021-03-07 11:05:16.370 - ShareX starting.
2021-03-07 11:05:16.386 - Version: 13.4
2021-03-07 11:05:16.386 - Build: Release
2021-03-07 11:05:16.386 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2021-03-07 11:05:16.386 - Personal path: C:\Users\Sangkeat\Documents\ShareX
2021-03-07 11:05:16.386 - Operating system: Windows 10 Education (64-bit)
2021-03-07 11:05:16.386 - Running as elevated process: False
2021-03-07 11:05:16.417 - ApplicationConfig load started: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-07 11:05:17.855 - ApplicationConfig load finished: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-07 11:05:17.855 - UploadersConfig load started: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-07 11:05:17.855 - MainForm init started.
2021-03-07 11:05:18.136 - UploadersConfig load finished: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-07 11:05:18.151 - HotkeysConfig load started: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-07 11:05:18.370 - HotkeysConfig load finished: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-07 11:05:18.604 - MainForm init finished.
2021-03-07 11:05:18.808 - Startup time: 2574 ms
2021-03-07 11:05:18.839 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2021-03-07 11:05:18.839 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2021-03-07 11:05:18.839 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2021-03-07 11:05:18.839 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2021-03-07 11:05:18.839 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2021-03-07 11:05:18.854 - HotkeyManager started.
2021-03-07 11:05:18.854 - WatchFolderManager started.
2021-03-07 11:05:28.729 - CLI: "C:\Users\Sangkeat\Documents\ShareX\Tools\output.mp4" -list_devices true -f dshow -i dummy
2021-03-07 11:05:29.073 - Unhandled exception:
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.ExternalCLIManager.Open(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.Run(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.GetDirectShowDevices()
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<>c__DisplayClass11_0.<RefreshSourcesAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<RefreshSourcesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<SettingsLoad>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<FFmpegOptionsForm_Load>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
2021-03-07 11:05:48.650 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2021-03-07 11:05:56.937 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2021-03-07 11:06:01.306 - ShareX continue.
2021-03-07 11:06:48.050 - ApplicationConfig save started: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-07 11:06:48.383 - ApplicationConfig save successful: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-07 11:06:49.686 - ApplicationConfig save started: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-07 11:06:49.687 - UploadersConfig save started: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-07 11:06:49.706 - HotkeysConfig save started: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-07 11:06:49.911 - UploadersConfig save successful: C:\Users\Sangkeat\Documents\ShareX\UploadersConfig.json
2021-03-07 11:06:50.001 - HotkeysConfig save successful: C:\Users\Sangkeat\Documents\ShareX\HotkeysConfig.json
2021-03-07 11:06:50.036 - ApplicationConfig save successful: C:\Users\Sangkeat\Documents\ShareX\ApplicationConfig.json
2021-03-07 11:07:07.081 - CLI: "C:\Users\Sangkeat\Documents\ShareX\Tools\output.mp4" -list_devices true -f dshow -i dummy
2021-03-07 11:07:07.097 - Unhandled exception:
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.ExternalCLIManager.Open(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.Run(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.GetDirectShowDevices()
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<>c__DisplayClass11_0.<RefreshSourcesAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<RefreshSourcesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<SettingsLoad>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<FFmpegOptionsForm_Load>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
2021-03-07 11:07:13.144 - File opened: C:\Users\Sangkeat\Documents\ShareX\Logs\ShareX-Log-2021-03.txt

**Comment by DasDunkel** [comment]
The FFmpeg executable (C:\Users\<You>\Documents\ShareX\Tools\ffmpeg.exe) is not valid for your OS, this will be beause you are using a 32 bit version of Windows. As far as I'm aware the official FFmpeg versions are only available for 64 bit systems. You may look around for a 32 bit version but I cannot ensure it will work.
