### ISSUE TITLE
System.IO.IOException͢→throwEx("The tag present in the reparse point buffer is invalid")

### ISSUE THREAD

**Issue by devopsmyth** [ShareX/ShareX#5459]
# [BUILD-INFO](#BUILD-INFO)
- build: `ShareX 13.4 (Release)`
- os-edition: `Windows 10 Enterprise`
- os-version: `1903`
- os-build: `18362.1256`

# [GIST OF IT](#GIST-OF-IT)
Getting the `error` below when trying to index my screenshots directory that ShareX dumps to. Found that ShareX creates a new directory for each screenshot that it takes, which may not be related—although the problem is when I select the root screenshot directory that contains all folders beneath it, that's when this occurs. When I select a single folder for indexing, the single file beneath is found and the index is generated. I did adjust the settings to use a max-depth of 5—way more than the 2 directories it would have to traverse—but it still throws the same error. Which is why I think it's something to do with nested directories within a root screenshot folder and zero pictures at the root level.

# [ERROR](#ERROR)
#4881 : may be related

```C#

021-03-12 16:04:32.989 - Unhandled exception:
System.IO.IOException: The tag present in the reparse point buffer is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.IndexerHtml.Index(String folderPath)
   at ShareX.IndexerLib.DirectoryIndexerForm.<>c__DisplayClass18_0.<IndexFolder>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<IndexFolder>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<BrowseFolder>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<DirectoryIndexerForm_Load>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
2021-03-12 16:04:47.672 - ShareX continue.
2021-03-12 16:06:09.687 - Unhandled exception:
System.IO.IOException: The tag present in the reparse point buffer is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.IndexerHtml.Index(String folderPath)
   at ShareX.IndexerLib.DirectoryIndexerForm.<>c__DisplayClass18_0.<IndexFolder>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<IndexFolder>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<BrowseFolder>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<btnBrowseFolder_Click>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
2021-03-12 16:06:13.228 - ShareX continue.
2021-03-12 16:07:12.504 - Unhandled exception:
System.IO.IOException: The tag present in the reparse point buffer is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.IndexerJson.Index(String folderPath)
   at ShareX.IndexerLib.DirectoryIndexerForm.<>c__DisplayClass18_0.<IndexFolder>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<IndexFolder>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<BrowseFolder>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<btnBrowseFolder_Click>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
2021-03-12 16:07:14.633 - ShareX continue.
2021-03-12 16:07:20.858 - Unhandled exception:
System.IO.IOException: The tag present in the reparse point buffer is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.IndexerJson.Index(String folderPath)
   at ShareX.IndexerLib.DirectoryIndexerForm.<>c__DisplayClass18_0.<IndexFolder>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<IndexFolder>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<BrowseFolder>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.IndexerLib.DirectoryIndexerForm.<btnBrowseFolder_Click>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)
2021-03-12 16:08:01.315 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2021-03-12 16:09:01.937 - File opened: C:\Users\PATH-TO-USERS-DOCUMENTS\Documents\ShareX\Logs\ShareX-Log-2021-03.txt
2021-03-12 16:09:39.072 - ShareX continue.

```

# [SUPPORTING SCREENSHOTS](#SUPPORTING-SCREENSHOTS)
### Root Folder View
> ![ShareX_6ic8wXkIM5](https://user-images.githubusercontent.com/8546107/111003516-4a7b8580-8355-11eb-850e-ce904573a576.png)

### ShareX Screenshot Folder(s) View (Inside Root Folder)
> ![PFAfQZtfA5](https://user-images.githubusercontent.com/8546107/111003583-6aab4480-8355-11eb-9eb0-ea318ecdc796.png)

### No Traversal Depth > 1 Level

***to reach image file(s) for indexing***

> ![ShareX_6ic8wXkIM5](https://user-images.githubusercontent.com/8546107/111003669-9a5a4c80-8355-11eb-849f-bb9ea078495a.png)

**Comment by devopsmyth** [comment]
**let me know if there's anything else I can do but I think I covered most of the necessary details.** 🆒
