### ISSUE TITLE
Issues with uploading gif.

### ISSUE THREAD

**Issue by alanlichen** [ShareX/ShareX#5465]
When I try to upload this specific gif (doesn't happen anywhere else) I get errors.
Here is what appears when I open up error logs:
```js
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1245
X-Post-Rate-Limit-Reset: 3533
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Mar 2021 23:42:05 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```
I am not sure if it is the code or imgur. Thanks :)

**Comment by Jaex** [comment]
Your GIF must be bigger than 10mb therefore upload is failing.

**Comment by alanlichen** [comment]
Thanks! Closing the issue since its stale now
