### ISSUE TITLE
Screen Recording Not Working

### ISSUE THREAD

**Issue by aclengen** [ShareX/ShareX#5466]
`System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at ShareX.HelpersLib.ExternalCLIManager.Open(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.Run(String path, String args)
   at ShareX.MediaLib.FFmpegCLIManager.GetDirectShowDevices()
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<>c__DisplayClass11_0.<RefreshSourcesAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<RefreshSourcesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<SettingsLoad>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.ScreenCaptureLib.FFmpegOptionsForm.<FFmpegOptionsForm_Load>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

ShareX 13.4 (Release)`

**Comment by botatooo** [comment]
> The requested operation requires elevation

Start ShareX as Admin and try again.
