### ISSUE TITLE
Sharex was working fine for me earlier but now get this error

### ISSUE THREAD

**Issue by NgXCyclone** [ShareX/ShareX#5488]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
Content-Length: 102
Content-Type: application/vnd.imgur.v1+json
Date: Sat, 27 Mar 2021 22:10:46 GMT

Response text:
{"errors":[{"id":"","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
Content-Length: 102
Content-Type: application/vnd.imgur.v1+json
Date: Sat, 27 Mar 2021 22:10:47 GMT

Response text:
{"errors":[{"id":"","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by MaraVitus** [comment]
I had the same issue as you. What I had to do was create a new album. I called it SECRET 2 and had to go into the setting of ShareX and tell it to save the screeshots to this album now. What I did was I went into the destination > destinations settings >

https://i.imgur.com/0gEUaUo.png

And then if you look at this screen shot... 

https://i.imgur.com/AJpNZZn.png

You need to click on refresh album list, and then make sure that the album shows up in the window there and click on it so that it's selected. And the make sure that there is a check mark in the box above saying "Upload images to selected album" and then you're good. Once I did this, and started taking screen shots of stuff again, then everything was fine. I'm wondering if there is a limit as to how many pictures you can have in an imgur album or any other album that you use for uploading images. I use Imgur right now. And it was when I was taking screen shots uploading them to imgur that started getting this error message. Hope this help. :)
