### ISSUE TITLE
Can't upload mp4 files to streamable for whatever reason

### ISSUE THREAD

**Issue by TearJoy** [ShareX/ShareX#5496]
```System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
Unable to connect to the remote server

Request URL:
https://api.streamable.com/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
Unable to connect to the remote server

Request URL:
https://api.streamable.com/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by ausername-1** [comment]
I think the error is pretty obvious the remote server credentials are wrong and you need to correct them.

**Comment by Jerrk** [comment]
I also have an issue where i cannot upload to streamable.

i can however upload from my browser directly

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.CheckUploadFilters(Stream stream, String filename)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://api.streamable.com/upload

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.CheckUploadFilters(Stream stream, String filename)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://api.streamable.com/upload

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by lindenkron** [comment]
Also getting the above issue. I believe Streamable has halted all API upload capabilities. Perhaps remove it from the options list?

October 7th, 2021:
> Please note that video uploading, clipping, or editing is not supported by the Streamable API at this time. You are required to go to Streamable.com to perform those functions.
https://support.streamable.com/article/46-streamable-api

**Comment by Jaex** [comment]
It works fine for me: https://streamable.com/3z3izi

**Comment by lindenkron** [comment]
Well strange.

I changed it to gfycat uguu and a few others to try and search for alternatives. Having changed nothing about this previously, I started getting error messages with The remote server returned an error: (404) Not Found.

I changed it back to Streamable just now after you reply and it's back to functioning.

Well.
