### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by stunspin** [ShareX/ShareX#5499]
Error message:
The remote server returned an error: (503) Server Unavailable.

Request URL:
https://stunspinnn.is-inside.me/upload

Status code:
(503) Service Unavailable

Headers:
Connection: keep-alive
X-DNS-Prefetch-Control: off
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-RateLimit-Limit: 50
X-RateLimit-Remaining: 38
X-RateLimit-Reset: 1617302282
Content-Length: 61
Content-Type: application/json; charset=utf-8
Date: Thu, 01 Apr 2021 17:38:01 GMT
Server: nginx/1.14.0 (Ubuntu)

Response text:
{"error":"Uploads are disabled while we upgrade our system."}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by stunspin** [comment]
didnt read the bottom
