### ISSUE TITLE
OneDrive  uploads stopped working today

### ISSUE THREAD

**Issue by tannaalok** [ShareX/ShareX#5553]
One Drive Uploads are not working? Are they working for any one else ? 

Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://graph.microsoft.com/v1.0/me/drive/items/01ASR3TTRAJPLXGK5OUFD2THOFOEIVDWBX/createLink

Status code:
(400) Bad Request

Headers:
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000
request-id: 84ff2b3c-3ade-1cb3156e9b72
client-request-id: 84ff2b3c-3ade-1cb3156e9b72
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Canada East","Slice":"E","Ring":"2","ScaleUnit":"002","RoleInstance":"QB1PEPF4400564300114F"}}
Cache-Control: no-cache
Content-Type: application/json
Date: Wed, 05 May 2021 21:10:02 GMT

Response text:
{"error":{"code":"invalidRequest","message":"The default link settings cannot be used to create a sharing link without a scope. Scope must be specified","innerError":{"date":"2021-05-05T21:10:02","request-id":"84ff2b3c-3ade-1cb3156e9b72","client-request-id":"84ff2b3c-1cb3156e9b72"}}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
2021-05-05 14:10:04.187 - Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.OneDrive.CreateShareableLink(String id, OneDriveLinkType linkType)
   at ShareX.UploadersLib.FileUploaders.OneDrive.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2021-05-05 14:10:04.188 - Upload failed. Retrying upload.
2021-05-05 14:10:04.955 - ApplicationConfig save started: C:\Users\Globalme\Documents\ShareX\ApplicationConfig.json
2021-05-05 14:10:04.957 - UploadersConfig save started: C:\Users\Globalme\Documents\ShareX\UploadersConfig.json
2021-05-05 14:10:04.958 - HotkeysConfig save started: C:\Users\Globalme\Documents\ShareX\HotkeysConfig.json
2021-05-05 14:10:05.474 - UploadersConfig save successful: C:\Users\Globalme\Documents\ShareX\UploadersConfig.json
2021-05-05 14:10:05.575 - HotkeysConfig save successful: C:\Users\Globalme\Documents\ShareX\HotkeysConfig.json
2021-05-05 14:10:05.781 - ApplicationConfig save successful: C:\Users\Globalme\Documents\ShareX\ApplicationConfig.json
2021-05-05 14:10:06.771 - Error:
Error message:
The remote server returned an error: (400) Bad Request.

**Comment by SupSuper** [comment]
Looks like something changed in the MS API, I'll investigate. In the meantime you can workaround the error by unchecking "Create sharable link" in the OneDrive Destination Settings. (you'll have to manually create it from the OneDrive website)

**Comment by tannaalok** [comment]
Thank you @SupSuper . Look forward to your finding and fixes. Hopefully its a minor change. 
"Create shareable link" part is the option most users are looking forward too.

**Comment by tannaalok** [comment]
@SupSuper just checking if you were able to find a fix for this issue.
