### ISSUE TITLE
Sharex Error 

### ISSUE THREAD

**Issue by slingring** [ShareX/ShareX#5613]
Error message:
The underlying connection was closed: An unexpected error occurred on a send.

Request URL:
https://api.imgur.com/3/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
   
   trying to upload a image, if i change where it uploads will it fix this?
   It says PR_CONNECT_RESET_ERROR
   if its valid, im on a school network, and school IT is always garbage at fixing things.

**Comment by phil330d** [comment]
same error on a private network
