### ISSUE TITLE
Error uploading to personal FTP server

### ISSUE THREAD

**Issue by ThePraeceps** [ShareX/ShareX#562]
Hey. I'm getting this error whenever I try to use my FTP server instead of imgur.
2015-03-17 17:57:24.050 - Task failed. Filename: 2015-03-17_17-57-06.png, Errors:
System.TimeoutException: Timed out trying to read data from the socket stream!
   at System.Net.FtpClient.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FtpClient.FtpSocketStream.ReadLine(Encoding encoding)
   at System.Net.FtpClient.FtpClient.GetReply()
   at System.Net.FtpClient.FtpClient.Execute(String command)
   at System.Net.FtpClient.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenWrite(String path, FtpDataType type)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

I have checked the login in credentials and I am able to upload the file and access it over http, but ShareX fails to upload them.

**Comment by Jaex** [comment]
Try changing FTP IsActive setting.

**Comment by ThePraeceps** [comment]
Yep! That worked. This means that my server needs to be configured to allow passive mode, right?

**Comment by Jaex** [comment]
I don't know, I don't have FTP server.

**Comment by ThePraeceps** [comment]
Thanks for your help!
