### ISSUE TITLE
Cant Copy URL

### ISSUE THREAD

**Issue by celestial1337** [ShareX/ShareX#5666]
I get this certain error everytime I take a picture with sharex

"Response parse failed.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntaxJson(String syntaxJsonPath)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntax(String syntax, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderParser.Parse(String text, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, ResponseInfo responseInfo, CustomUploaderInput input, Boolean isShortenedURL)
   at ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)"

can anyone help me please cus its quite annoying.

**Comment by Jaex** [comment]
It is problem to do with your host, not ShareX.
