### ISSUE TITLE
Entering an illegal path into video converter causes an error

### ISSUE THREAD

**Issue by JelNiSlaw** [ShareX/ShareX#5816]
Entering a file path with a `"` character into the video converter causes this error:
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at ShareX.MediaLib.VideoConverterOptions.get_OutputFilePath()
   at ShareX.MediaLib.VideoConverterOptions.GetFFmpegArgs()
   at ShareX.MediaLib.VideoConverterForm.UpdateOptions()
   at ShareX.MediaLib.VideoConverterForm..ctor(String ffmpegFilePath, VideoConverterOptions options)
   at ShareX.TaskHelpers.OpenVideoConverter(TaskSettings taskSettings)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.6.1 (Release, Admin)
```
Also because ShareX stores the last path, it will prevent the video converter from ever opening.

**Comment by crzytrane** [comment]
Thanks @JelNiSlaw. I've put up this pull request for this issue https://github.com/ShareX/ShareX/pull/5817
