### ISSUE TITLE
Screenshot doesn't copy to clipboard automatically

### ISSUE THREAD

**Issue by voltuz** [ShareX/ShareX#5819]
Even though i have it selected in the actions to do after the capture, what happens is:
It open the image editro (that's good) but it doesn't copy the image to the clipboard automatically (i need to enter ctrl+shift+c to copy it from the image editor)
![image](https://user-images.githubusercontent.com/68356371/133072189-900d94cc-8e67-47b0-8ae0-3276f60b21b2.png)

**Comment by maisyk** [comment]
I don't believe this is an issue with ShareX itself. It is likely to be an issue with something on your system. I have had this issue in the past both with ShareX and the built-in screenshot feature on Windows. 

I have tested it thoroughly just now and can't seem to replicate it in ShareX (13.6.2) - Windows 11.

According to the following article, it may be an issue with the cache not clearing properly on Windows. 

[Ability to paste screenshots suddenly not working in both Word and Outlook](https://answers.microsoft.com/en-us/msoffice/forum/all/ability-to-paste-screenshots-suddenly-not-working/d1b9c4f5-0b88-4712-931a-2e26da5a93a2) 

> It appears the cache/memory is not being cleared
>If you run disk cleanup, restart the PC then immediately use PrintScr & paste to a word doc?

Give this a go and see if it resolves the issue for you.

**Comment by Jay-Tarzan** [comment]
Snipping tool

**Comment by jtmackoy** [comment]
FYI - I had a similar problem, although my after capture settings were slightly different.  For my scenario, I found a workaround to this issue and documented it under #6069.

Referencing here, in case this is helpful to other users who run into this problem (or one like it), and find this issue while researching - as I did.

**Comment by git-tiger** [comment]
I have this problem too. 
Workaround, set "left click" tray icon to "Capture Last Region".
So, if the clipboard does not paste anything, recapture, and paste again.

**Comment by zb-creativeone** [comment]
@ragjoe the option is in the image editor menu.  Make sure you're on the latest version.

**Comment by the-Arioch** [comment]
If those tasks are soo sequential then maybe

* provide a way for users to reorder the menu
* mark the "modal" tasks

Currently nothing in GUI seems to hint at the tasts inter-dependency

**Comment by joeaki1983** [comment]
> 

You're very welcome! I'm glad I could help you! It indeed wasn't caused by ShareX; it was due to my other translation software! This issue has been bothering me for a long time. Thank you so much!w

> I don't believe this is an issue with ShareX itself. It is likely to be an issue with something on your system. I have had this issue in the past both with ShareX and the built-in screenshot feature on Windows.我不认为这是 ShareX 本身的问题。这可能是您系统上的某个问题。我过去在使用 ShareX 和 Windows 上的内置屏幕截图功能时都遇到过这个问题。
> 
> I have tested it thoroughly just now and can't seem to replicate it in ShareX (13.6.2) - Windows 11.我刚刚对其进行了彻底测试，似乎无法在 ShareX (13.6.2) - Windows 11 中复制它。
> 
> According to the following article, it may be an issue with the cache not clearing properly on Windows.根据以下文章，可能是 Windows 上的缓存未正确清除的问题。
> 
> [Ability to paste screenshots suddenly not working in both Word and Outlook 粘贴屏幕截图的功能突然在 Word 和 Outlook 中不起作用](https://answers.microsoft.com/en-us/msoffice/forum/all/ability-to-paste-screenshots-suddenly-not-working/d1b9c4f5-0b88-4712-931a-2e26da5a93a2)
> 
> > It appears the cache/memory is not being cleared看来缓存/内存没有被清除
> > If you run disk cleanup, restart the PC then immediately use PrintScr & paste to a word doc? 如果运行磁盘清理，重新启动电脑，然后立即使用 PrintScr 并粘贴到 Word 文档？
> 
> Give this a go and see if it resolves the issue for you.尝试一下，看看它是否可以解决您的问题。

**Comment by bertelu** [comment]
i have similar issue. the strange is that i do have within my Win10 PC a second virtual W10 PC running in VirtualBox. the 2 PC's have shared clipboard and both have ShareX installed. 
when i take a screenshot in the virtual PC is copie in the virtualPC clipboard and is propagated also in the host clipboard. however when i take a screenshot in the host PC, nothing happen. the clipboard is not filled, but the file is created and the thumbnail is created in history. 
in the log i can see the following

2024-07-10 16:39:06.614 - Hotkey triggered. Hotkey: Ctrl + Alt + P, Description: Capture region, Job: RectangleRegion
2024-07-10 16:39:06.614 - Executing: Capture region
2024-07-10 16:39:08.695 - Task in queue. Job: Job, Type: Image, Host: 
2024-07-10 16:39:08.708 - Task status: Preparing
2024-07-10 16:39:10.739 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageAlternative2(Image img, String fileName)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img, String fileName)
2024-07-10 16:39:10.739 - Image copied to clipboard.
2024-07-10 16:39:10.740 - Task completed. File name: dMFsn949V9.bmp, Duration: 2032 ms
2024-07-10 16:39:21.341 - File opened: C:\Users\100008576.HCAD\Documents\ShareX\Logs\ShareX-Log-2024-07.txt

**Comment by zb-creativeone** [comment]
@bertelu this is an entirely different issue, and is likely an issue with VirtualBox not ShareX.  I'm not too familiar with VirtualBox, but according to [this forum thread](https://forums.virtualbox.org/viewtopic.php?t=108301) the shared clipboard feature only works with images and `ASCII` text.  Based on the stack trace from your log, it looks like ShareX is using the `SetDataObject` method, not `SetImage`, so the clipboard would contain a .NET `Object` which wouldn't work with VirtualBox.

I'm not sure if this is the reason it failed, or possibly the guest VM was blocking the host VM's clipboard.  You can verify that this is a VirtualBox issue by disabling VirtualBox startup --> restarting your computer --> making sure no VirtualBox processes or services are running --> capturing a screenshot using ShareX.

**Comment by bertelu** [comment]
Sorry if I made some confusion. The sharex on virtualbox works perfectly. Is the one on the host that throw that error

**Comment by bertelu** [comment]
it should be something with my PC setting that ShareX doesnt like. i've tested Screenpresso, Flameshot, greenshot and all of them is working. i can screenshot and it will be copied to clipboard. while ShareX keep issuing the same error in the log
2024-07-12 13:52:44.872 - HotkeyManager started.
2024-07-12 13:52:44.873 - WatchFolderManager started.
2024-07-12 13:52:44.888 - Startup time: 1956 ms
2024-07-12 13:53:13.808 - Hotkey triggered. Hotkey: Ctrl + Alt + P, Description: Cattura Regione, Job: RectangleRegion
2024-07-12 13:53:13.812 - Executing: Cattura Regione
2024-07-12 13:53:16.483 - Task in queue. Job: Job, Type: Image, Host: 
2024-07-12 13:53:16.514 - Task status: Preparing
2024-07-12 13:53:18.550 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img, String fileName)

**Comment by the-Arioch** [comment]
Windows clipboard API sucks.
_Though personally I am mostly hit with languages-related troubles._

In your shows I would try to use task manager or process explorer or
anything to get full lists of the processes running on different machines,
and then try to find which processes exist only in the faulting machines.

Just a month ago I had to fix a bug with copying a text in a legacy app. It
was living there for many years, usually never causing a trouble. Until one
unlucky machine which run a (different, not ShareX) clipboard history
manager and screenshotter. That specific app was not coded correctly, and
when it's clipboard parsing hooks failed - it forgot to close the
clipboard, blocking all other applications to access clipboard ever again.

So, the shroedingbug was caused by TWO not very wide spread application,
and "malformed data" bug in one was triggering "block and never release"
bug in the other. And until this specific combination happened for years
nobody complained.

I see SetClipboardData failing in the exception log and I suspect a similar
scenario

**Comment by Lexiconmancer** [comment]
> ShareX executes tasks in order listed in after capture tasks and that order is not arbitrary. Some tasks depends on other tasks or in your case all image output options happens after image manipulations are finalized, that way end result can be copied. So reason for copy to clipboard is after image editor is, after modify image inside image editor then result image can be copied to clipboard instead of initial image. You will probably then suggest me to copy before image editor open and after image editor close but then in that case I need to do this after each image manipulation tasks and what about other output options? So it is more complicated than you think.
> 
> But I had one workaround idea now, I added this option to image editor:
> 
> ![](https://camo.githubusercontent.com/1b35f2c201f0810ec52eb2d566ce149486fb98d3ada207e00ee696806d77de6c/68747470733a2f2f6a6165782e6765747368617265782e636f6d2f323032312f31302f6578706c6f7265725f364d35733678417844552e706e67)
> 
> Which copies image to clipboard after each change. So if this option is enabled then I can copy initial image on image editor start too. Which should solve your problems I guess?

Thank you. Just now ran into the same issue and your explanation here got me where I wanted to be.
