### ISSUE TITLE
Error: "System.Net.ServicePointManager"

### ISSUE THREAD

**Issue by genesisx111** [ShareX/ShareX#5865]
System.TypeInitializationException: The type initializer for 'System.Net.ServicePointManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Net.ComNetOS' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section startup. (C:\Program Files\ShareX\ShareX.exe.Config line 3)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   at System.Diagnostics.TraceSource.Initialize()
   at System.Net.Logging.InitializeLogging()
   at System.Net.Logging.get_On()
   at System.Net.ComNetOS..cctor()
   --- End of inner exception stack trace ---
   at System.Net.ServicePointManager..cctor()
   --- End of inner exception stack trace ---
   at System.Net.ServicePointManager.set_InternalConnectionLimit(Int32 value)
   at System.Net.ServicePointManager.set_DefaultConnectionLimit(Int32 value)
   at ShareX.UploadersLib.Uploader.UpdateServicePointManager()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.6.1

**Comment by genesisx111** [comment]
how to fix this issue? cant open ShareX
