### ISSUE TITLE
[Crossover Linux] Win32 handle that was passed to Icon is not valid or is the wrong type.

### ISSUE THREAD

**Issue by JL102** [ShareX/ShareX#5943]
Hello,
I'm aware that ShareX is not intended to run on Linux, however Codeweavers' WINE-based "Crossover Linux" has made strides toward making more of ShareX's functionality work as expected. The .NET Framework is installable on Crossover, and I'm able to take screenshots and upload images just fine. (The screenshot creation "window" runs at an abysmal framerate, but at least it works.)
However, the "Copy Image" function does not work as expected. By searching for the error message, it seems to be something to do with shell32.dll? 

I can't tell if this error is something that can be fixed by ShareX, or if it's something that needs to be fixed by WINE or Codeweavers. Any help or additional insight in identifying & rectifying the issue would be greatly appreciated. I've been using ShareX for years, and it would be wonderful if I can keep using it on Linux. I couldn't find any alternatives that are actively maintained and yet have the same features that I use with ShareX. Thank you!

```
2021-11-15 11:49:12.130 - Exception:
System.ArgumentException: Win32 handle that was passed to Icon is not valid or is the wrong type.
   at System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   at System.Drawing.Icon..ctor(IntPtr handle)
   at System.Drawing.Icon.FromHandle(IntPtr handle)
   at ShareX.HelpersLib.NativeMethods.GetFileIcon(String filePath, Boolean isSmallIcon)
   at ShareX.HelpersLib.ImageFilesCache.GetFileIconAsImage(String filePath, Boolean isSmallIcon)
   at ShareX.MainForm.UpdateActionsMenu(String filePath)
2021-11-15 11:49:12.137 - Exception:
System.ArgumentException: Win32 handle that was passed to Icon is not valid or is the wrong type.
   at System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   at System.Drawing.Icon..ctor(IntPtr handle)
   at System.Drawing.Icon.FromHandle(IntPtr handle)
   at ShareX.HelpersLib.NativeMethods.GetFileIcon(String filePath, Boolean isSmallIcon)
   at ShareX.HelpersLib.ImageFilesCache.GetFileIconAsImage(String filePath, Boolean isSmallIcon)
   at ShareX.MainForm.UpdateActionsMenu(String filePath)
```

**Comment by tajetaje** [comment]
My bet is that ShareX is asking for a particular icon file included in windows.

**Comment by JL102** [comment]
From looking at the code for NativeMethods.GetFileIcon, it seems to me like it's asking a native system library to _turn_ the file into an "icon"? Not loading an _already existing_ particular icon file?
```
            Icon icon = (Icon)Icon.FromHandle(shfi.hIcon).Clone();
```

**Comment by tajetaje** [comment]
Win32 handle usually refers to a file, it is trying to turn a file into an icon, but the file doesn’t exist. hence invalid handle.
________________________________
