### ISSUE TITLE
Parameter is not valid - crash

### ISSUE THREAD

**Issue by Arthesian** [ShareX/ShareX#596]
When I tried to create thumbnails I got this error....

I have no idea how to configure thumbnail images for every image I upload? 

I get this error message as soon as I try to upload something new ::

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Width()
   at ShareX.TaskHelpers.CreateThumbnail(Image img, String folder, String filename, TaskSettings taskSettings)
   at ShareX.UploadTask.DoAfterCaptureJobs()
   at ShareX.UploadTask.DoThreadJob()
   at ShareX.UploadTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Jaex** [comment]
I keep trying but unable to manage to get your error with thumbnail creation. I wonder what you doing different.

**Comment by Jaex** [comment]
What is your after capture tasks and thumbnail settings?

**Comment by Arthesian** [comment]
it's kinda funny, but I can't seem to reproduce the crash myself anymore....( ShareX did update tho )

but I still can't get any thumbnail images/ thumbnail urls from the images I upload.... I always get these kind of results (empty source urls) ::

http://sharex.ennevanziel.nl/image/ShareX_-_2015-04-16_06-33-36.png

or it is greyed out like this: 

http://sharex.ennevanziel.nl/image/ShareX_-_2015-04-16_06-33-02.png

.....

I have tried several things, like customizing the thumbnails size, saving the thumbnail image to file etc.... but nothing seems to work

**Comment by Jaex** [comment]
It creates thumbnail image locally not uploads second image to host.

**Comment by canihavesomecoffee** [comment]
Please reopen this issue. I have exactly the same problem with the last (10.4) version.

```
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Width()
   at ShareX.TaskHelpers.CreateThumbnail(Image img, String folder, String filename, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 10.4 Release
```

I'm trying to make a rectangle capture and then generate a thumbnail for that rectangle capture. It does not produce an error when I capture the active window or the entire screen.

You know where to find me if you need more info :)
