### ISSUE TITLE
Crash when selecting "After capture tasks"

### ISSUE THREAD

**Issue by GuillaumeNury** [ShareX/ShareX#5961]
I tried to reinstall and reset my settings. But I still have the following issue :

![image](https://user-images.githubusercontent.com/12662533/143595725-d683e716-7e31-4f22-84b8-527bef4f2532.png)

I dont have any issue when selecting "After upload tasks"

Logs are:
```
2021-11-26 15:31:54.187 - ShareX starting.
2021-11-26 15:31:54.189 - Version: 13.6.1
2021-11-26 15:31:54.189 - Build: Release
2021-11-26 15:31:54.189 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2021-11-26 15:31:54.189 - Personal path: C:\Users\gnury\Documents\ShareX
2021-11-26 15:31:54.190 - Operating system: Windows 10 Pro (64-bit)
2021-11-26 15:31:54.190 - Running as elevated process: False
2021-11-26 15:31:54.212 - ApplicationConfig load started: C:\Users\gnury\Documents\ShareX\ApplicationConfig.json
2021-11-26 15:31:54.538 - ApplicationConfig load finished: C:\Users\gnury\Documents\ShareX\ApplicationConfig.json
2021-11-26 15:31:54.541 - UploadersConfig load started: C:\Users\gnury\Documents\ShareX\UploadersConfig.json
2021-11-26 15:31:54.543 - Language changed to: English (United States)
2021-11-26 15:31:54.544 - MainForm init started.
2021-11-26 15:31:54.641 - UploadersConfig load finished: C:\Users\gnury\Documents\ShareX\UploadersConfig.json
2021-11-26 15:31:54.643 - HotkeysConfig load started: C:\Users\gnury\Documents\ShareX\HotkeysConfig.json
2021-11-26 15:31:54.771 - HotkeysConfig load finished: C:\Users\gnury\Documents\ShareX\HotkeysConfig.json
2021-11-26 15:31:54.881 - MainForm init finished.
2021-11-26 15:31:55.121 - Startup time: 955 ms
2021-11-26 15:31:55.169 - Hotkey registered: Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2021-11-26 15:31:55.169 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture entire screen, Job: PrintScreen
2021-11-26 15:31:55.169 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2021-11-26 15:31:55.170 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2021-11-26 15:31:55.170 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2021-11-26 15:31:55.172 - HotkeyManager started.
2021-11-26 15:31:55.173 - WatchFolderManager started.
2021-11-26 15:31:57.664 - Unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.MainForm.UpdateImageEffectsMenu(ToolStripDropDownItem parent)
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownButton.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.6.1

```

**Comment by Jaex** [comment]
You can test it using: https://getsharex.com/docs/dev-builds

**Comment by GuillaumeNury** [comment]
Thank you for the quick reply and fix! Unfortunatly, I still have the same issue:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.MainForm.UpdateImageEffectsMenu(ToolStripDropDownItem parent)
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownButton.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.6.2 Dev
```

**Comment by Jaex** [comment]
Can you try again?

**Comment by GuillaumeNury** [comment]
Yeah! Thank you very much 🚀 

![image](https://user-images.githubusercontent.com/12662533/143613182-d94e74f3-bb7b-4dd4-aa5b-e8d619735440.png)
