### ISSUE TITLE
Watch folders disappeared, can't add them back

### ISSUE THREAD

**Issue by Arsenalist** [ShareX/ShareX#5963]
The watch folders I had configured are gone and when I try to add them, they don't show up. Instead I get this error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.TaskSettingsForm.cbWatchFolderEnabled_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.6.1
```

**Comment by Jaex** [comment]
It not looks like you trying to add them but enable watch folder option? But even then I check it and on task settings window startup it should have fixed that issue by re initiating watch folder list, so I'm not sure how you even lost your watch folders and it causing that now. Is re opening task settings window not works?
