### ISSUE TITLE
couldn't upload image

### ISSUE THREAD

**Issue by saraelbedeawi** [ShareX/ShareX#5964]
Error message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Request URL:
https://api.imgur.com/3/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by jjamesmartiin** [comment]
Could be related to issue #5945
