### ISSUE TITLE
ShareX not seeing my image effects after update to Dev

### ISSUE THREAD

**Issue by dcrme** [ShareX/ShareX#5976]
After I updated to the Dev release, my image effects got wiped out in the editor, but they were still present as options in the After capture tasks menu. I get an error when trying to automatically apply the effects because what's in the editor doesn't match what's in the menu.

Here's the error, though I think the issue is related to the menu reading and updating available image effects from the editor:

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Width()
   at ShareX.TaskHelpers.GetScreenshotsFolder(TaskSettings taskSettings, TaskMetadata metadata)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.6.2 Dev

**Comment by Jaex** [comment]
Your issue not looks like to do with image effects but also I can't reproduce the issue too.
Can you write step by step what are you doing?

**Comment by Jaex** [comment]
Managed to reproduce it now.

**Comment by Jaex** [comment]
You can update dev build to test it.

**Comment by dcrme** [comment]
Woohoo!! All fixed after update.
