### ISSUE TITLE
System Exception

### ISSUE THREAD

**Issue by SussyWussy1** [ShareX/ShareX#5982]
System.Exception: Unsupported request format: None
   at ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String filename, Int32 retry)
   
   this pops up

**Comment by Jaex** [comment]
Body of custom uploader request can't be "No body" for your uploader type.

**Comment by SussyWussy1** [comment]
where can i find it
