### ISSUE TITLE
Unable to upload image

### ISSUE THREAD

**Issue by alundil** [ShareX/ShareX#5986]
Attempted to upload a 594KB png file to imgur.

2021-12-15 17:11:33.916 - Task in queue. Job: FileUpload, Type: Image, Host: Imgur
2021-12-15 17:11:33.965 - Task status: Preparing
2021-12-15 17:11:33.978 - Upload started. Filename: firefox_KAanRgYXmK.png, Filepath: C:\Users\username\OneDrive - domain.org\Documents\ShareX\Screenshots\2021-12\firefox_KAanRgYXmK.png
2021-12-15 17:12:05.173 - Error:
Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1250
X-Post-Rate-Limit-Reset: 0
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Wed, 15 Dec 2021 23:12:05 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2021-12-15 17:12:05.188 - Upload failed. Retrying upload.
2021-12-15 17:12:15.572 - ApplicationConfig save started: C:\Users\username\OneDrive - domain.org\Documents\ShareX\ApplicationConfig.json
2021-12-15 17:12:15.573 - UploadersConfig save started: C:\Users\username\OneDrive - domain.org\Documents\ShareX\UploadersConfig.json
2021-12-15 17:12:15.573 - HotkeysConfig save started: C:\Users\username\OneDrive - domain.org\Documents\ShareX\HotkeysConfig.json
2021-12-15 17:12:15.727 - UploadersConfig save successful: C:\Users\username\OneDrive - domain.org\Documents\ShareX\UploadersConfig.json
2021-12-15 17:12:15.771 - HotkeysConfig save successful: C:\Users\username\OneDrive - domain.org\Documents\ShareX\HotkeysConfig.json
2021-12-15 17:12:15.813 - ApplicationConfig save successful: C:\Users\username\OneDrive - domain.org\Documents\ShareX\ApplicationConfig.json
2021-12-15 17:12:36.982 - Error:
Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1249
X-Post-Rate-Limit-Reset: 3568
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Wed, 15 Dec 2021 23:12:36 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2021-12-15 17:12:36.985 - Task failed. Filename: firefox_KAanRgYXmK.png, Errors:
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1249
X-Post-Rate-Limit-Reset: 3568
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Wed, 15 Dec 2021 23:12:36 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
2021-12-15 17:12:41.148 - Executing: Open main window
2021-12-15 17:12:57.353 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2021-12-15 17:13:21.252 - File opened: C:\Users\username\OneDrive - domain.org\Documents\ShareX\Logs\ShareX-Log-2021-12.txt

**Comment by Jaex** [comment]
Check: https://status.imgur.com/
