### ISSUE TITLE
Google meet recording - Saved recording not opening

### ISSUE THREAD

**Issue by Suryadreams** [ShareX/ShareX#6018]
I am trying to record the google meeting with voice using screen recorder option in shareX for 45 mins. Files gets saved but it is not opening. There was error with ffmpeg.

Windows Media Player cannot play the file. The Player might not support the file type or might not support the codec that was used to compress the file.
![ffmpeg issue](https://user-images.githubusercontent.com/97291682/148544810-d468c00a-5e97-4677-ba6a-8df9420d8474.png)

**Comment by Suryadreams** [comment]
ffmpeg[](url)
[ShareX-Log-2022-01.txt](https://github.com/ShareX/ShareX/files/7829038/ShareX-Log-2022-01.txt)

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at ShareX.ScreenRecordManager.StopRecording()
   at ShareX.ScreenCaptureLib.ScreenRecordForm.btnStart_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.7
