### ISSUE TITLE
Imgur Upload's not working

### ISSUE THREAD

**Issue by eeeBs** [ShareX/ShareX#604]
Trying to upload to Imgur:

Message:
Unable to connect to the remote server

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)

Probably on Imgur's end I suppose?

**Comment by Jaex** [comment]
It can be Imgur server is not reachable or your firewall blocking ShareX.
