### ISSUE TITLE
Capture doesn't appear to copy to clipboard after capture task

### ISSUE THREAD

**Issue by jtmackoy** [ShareX/ShareX#6069]
When taking a Region capture, the captured image will appear on the Toast notification near my system tray but will not be copied to the clipboard, even though I've configured that option as an "After capture task":
![image](https://user-images.githubusercontent.com/7025779/152227400-90b88f5f-4370-46d3-b026-23bdf2033e76.png)

If I then attempt to open the ShareX Clipboard Viewer an error is generated as shown below:
![image](https://user-images.githubusercontent.com/7025779/152224144-7e5613d2-7dad-4f74-b1e3-c98266578f37.png)

If I open the log file, I see the following (sensitive info \<snipped\>):
```
2022-02-02 09:47:28.180 - Task in queue. Job: Job, Type: Image, Host: 
2022-02-02 09:47:28.191 - Task status: Preparing
2022-02-02 09:47:28.210 - Image copied to clipboard.
2022-02-02 09:47:28.284 - Image saved to file: Z:\Temp\Screen Grabs\ShareX\2022-02\chrome_2022-02-02_09-47-28.png
2022-02-02 09:47:28.337 - Task completed. Filename: chrome_2022-02-02_09-47-28.png, Duration: 156 ms
2022-02-02 09:47:28.359 - UploadersConfig save started: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 09:47:28.360 - ApplicationConfig save started: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 09:47:28.373 - HotkeysConfig save started: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 09:47:28.495 - ApplicationConfig save successful: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 09:47:28.504 - UploadersConfig save successful: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 09:47:28.518 - HotkeysConfig save successful: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 13:23:08.541 - ApplicationConfig save started: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 13:23:08.543 - UploadersConfig save started: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 13:23:08.636 - UploadersConfig save successful: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 13:23:08.638 - HotkeysConfig save started: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 13:23:08.747 - ApplicationConfig save successful: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 13:23:08.797 - HotkeysConfig save successful: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 13:26:44.498 - Hotkey triggered. Hotkey: Shift + Print Screen, Description: Capture region, Job: RectangleRegion
2022-02-02 13:26:44.499 - Executing: Capture region
2022-02-02 13:26:51.135 - Task in queue. Job: Job, Type: Image, Host: 
2022-02-02 13:26:51.152 - Task status: Preparing
2022-02-02 13:26:53.352 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img, String fileName)
2022-02-02 13:26:53.353 - Image copied to clipboard.
2022-02-02 13:26:53.359 - Image saved to file: Z:\Temp\Screen Grabs\ShareX\2022-02\chrome_2022-02-02_13-26-51.png
2022-02-02 13:26:53.389 - Task completed. Filename: chrome_2022-02-02_13-26-51.png, Duration: 2246 ms
2022-02-02 13:26:53.450 - ApplicationConfig save started: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 13:26:53.450 - UploadersConfig save started: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 13:26:53.504 - HotkeysConfig save started: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 13:26:53.586 - UploadersConfig save successful: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 13:26:53.665 - ApplicationConfig save successful: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 13:26:53.744 - HotkeysConfig save successful: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 13:27:09.794 - ApplicationConfig save started: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 13:27:09.799 - UploadersConfig save started: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 13:27:09.799 - HotkeysConfig save started: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 13:27:09.931 - ApplicationConfig save successful: C:\Users\<snip>\Documents\ShareX\ApplicationConfig.json
2022-02-02 13:27:09.967 - HotkeysConfig save successful: C:\Users\<snip>\Documents\ShareX\HotkeysConfig.json
2022-02-02 13:27:10.017 - UploadersConfig save successful: C:\Users\<snip>\Documents\ShareX\UploadersConfig.json
2022-02-02 13:27:22.934 - Unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.ListView.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

The interesting thing here is that if I select to `Continue` in the Clipboard Viewer, then select to `Clear clipboard`, and then attempt *another* Region capture, it works (the region is captured to the clipboard as expected).  After learning this, I found the following Advanced option in Task Settings to `AutoClearClipboard` *before* the next capture task occurs - thus automatically doing what I just did manually to work around my original problem.  Here's the setting (set to True for the effect needed here):
![image](https://user-images.githubusercontent.com/7025779/152225937-69ed9c66-e80c-45a0-a070-fb8cddab9d2a.png)

I wanted to document this, as I've seen others with a similar problem but not a definitive way to mitigate the problem.

Also, I wanted to see if there was something that could be done to prevent the problem that leads to the errors above, without having to clear the clipboard before each capture.

**Comment by jtmackoy** [comment]
Similar issues, I've run across:
#5819 
#5107

Mentioning in case others who run across those issues find my work-around useful.
