### ISSUE TITLE
Bug report::System.NotSupportedException: The given path's format is not supported.

### ISSUE THREAD

**Issue by apsis0215** [ShareX/ShareX#6197]
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.7

**Comment by apsis0215** [comment]
2022-04-06 10:39:47.952 - ShareX continue.
2022-04-06 10:39:59.459 - ShareX starting.
2022-04-06 10:39:59.462 - Version: 13.7
2022-04-06 10:39:59.462 - Build: Release
2022-04-06 10:39:59.462 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2022-04-06 10:39:59.462 - Personal path: C:\Users\rallen\C_Documents\ShareX\Capture
2022-04-06 10:39:59.462 - Personal path detection method: PersonalPath.cfg file (C:\Users\rallen\OneDrive - Ware Malcomb\Documents\ShareX\PersonalPath.cfg)
2022-04-06 10:39:59.463 - Operating system: Windows 10 Pro (64-bit)
2022-04-06 10:39:59.463 - Running as elevated process: False
2022-04-06 10:39:59.481 - ApplicationConfig load started: C:\Users\rallen\C_Documents\ShareX\Capture\ApplicationConfig.json
2022-04-06 10:39:59.809 - ApplicationConfig load finished: C:\Users\rallen\C_Documents\ShareX\Capture\ApplicationConfig.json
2022-04-06 10:39:59.814 - UploadersConfig load started: C:\Users\rallen\C_Documents\ShareX\Capture\UploadersConfig.json
2022-04-06 10:39:59.815 - MainForm init started.
2022-04-06 10:39:59.898 - UploadersConfig load finished: C:\Users\rallen\C_Documents\ShareX\Capture\UploadersConfig.json
2022-04-06 10:39:59.900 - HotkeysConfig load started: C:\Users\rallen\C_Documents\ShareX\Capture\HotkeysConfig.json
2022-04-06 10:39:59.996 - HotkeysConfig load finished: C:\Users\rallen\C_Documents\ShareX\Capture\HotkeysConfig.json
2022-04-06 10:40:00.097 - MainForm init finished.
2022-04-06 10:40:00.482 - Startup time: 1051 ms
2022-04-06 10:40:00.546 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture Region, Job: RectangleRegion
2022-04-06 10:40:00.546 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2022-04-06 10:40:00.546 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2022-04-06 10:40:00.546 - Hotkey registered: Hotkey: Ctrl + F7, Description: Start/Stop screen recording, Job: ScreenRecorder
2022-04-06 10:40:00.546 - Hotkey registered: Hotkey: Ctrl + F6, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2022-04-06 10:40:00.546 - Hotkey registered: Hotkey: Ctrl + Shift + Alt + C, Description: Screen Color picker HEX, Job: ScreenColorPicker
2022-04-06 10:40:00.548 - HotkeyManager started.
2022-04-06 10:40:00.548 - WatchFolderManager started.
2022-04-06 10:40:10.589 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture Region, Job: RectangleRegion
2022-04-06 10:40:10.591 - Executing: Capture region
2022-04-06 10:40:18.110 - Task in queue. Job: Job, Type: Image, Host: 
2022-04-06 10:40:18.137 - Task status: Preparing
2022-04-06 10:40:19.108 - Image copied to clipboard.
2022-04-06 10:40:19.154 - Unhandled exception:
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.7
2022-04-06 10:40:21.303 - File opened: C:\Users\rallen\C_Documents\ShareX\Capture\Logs\ShareX-Log-2022-04.txt
