### ISSUE TITLE
Bug Report:: System.NotSupportedException: The given path's format is not supported.

### ISSUE THREAD

**Issue by apsis0215** [ShareX/ShareX#6199]
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.7

**Comment by apsis0215** [comment]
ShareX 13.7
2022-04-07 19:08:43.495 - ShareX continue.
2022-04-07 19:40:27.411 - ShareX starting.
2022-04-07 19:40:27.413 - Version: 13.7
2022-04-07 19:40:27.414 - Build: Release
2022-04-07 19:40:27.414 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2022-04-07 19:40:27.414 - Personal path: C:\Users\rallen\C_Documents\ShareX\Capture
2022-04-07 19:40:27.414 - Personal path detection method: PersonalPath.cfg file (C:\Users\rallen\OneDrive - Ware Malcomb\Documents\ShareX\PersonalPath.cfg)
2022-04-07 19:40:27.414 - Operating system: Windows 10 Pro (64-bit)
2022-04-07 19:40:27.414 - Running as elevated process: False
2022-04-07 19:40:27.433 - ApplicationConfig load started: C:\Users\rallen\C_Documents\ShareX\Capture\ApplicationConfig.json
2022-04-07 19:40:27.767 - ApplicationConfig load finished: C:\Users\rallen\C_Documents\ShareX\Capture\ApplicationConfig.json
2022-04-07 19:40:27.770 - UploadersConfig load started: C:\Users\rallen\C_Documents\ShareX\Capture\UploadersConfig.json
2022-04-07 19:40:27.770 - MainForm init started.
2022-04-07 19:40:27.864 - UploadersConfig load finished: C:\Users\rallen\C_Documents\ShareX\Capture\UploadersConfig.json
2022-04-07 19:40:27.867 - HotkeysConfig load started: C:\Users\rallen\C_Documents\ShareX\Capture\HotkeysConfig.json
2022-04-07 19:40:27.974 - HotkeysConfig load finished: C:\Users\rallen\C_Documents\ShareX\Capture\HotkeysConfig.json
2022-04-07 19:40:28.165 - MainForm init finished.
2022-04-07 19:40:28.460 - Startup time: 1077 ms
2022-04-07 19:40:28.543 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture Region, Job: RectangleRegion
2022-04-07 19:40:28.543 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2022-04-07 19:40:28.543 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2022-04-07 19:40:28.543 - Hotkey registered: Hotkey: Ctrl + F7, Description: Start/Stop screen recording, Job: ScreenRecorder
2022-04-07 19:40:28.543 - Hotkey registered: Hotkey: Ctrl + F6, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2022-04-07 19:40:28.543 - Hotkey registered: Hotkey: Ctrl + Shift + Alt + C, Description: Screen Color picker HEX, Job: ScreenColorPicker
2022-04-07 19:40:28.545 - HotkeyManager started.
2022-04-07 19:40:28.545 - WatchFolderManager started.
2022-04-07 19:40:30.783 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture Region, Job: RectangleRegion
2022-04-07 19:40:30.785 - Executing: Capture region
2022-04-07 19:40:36.964 - Task in queue. Job: Job, Type: Image, Host: 
2022-04-07 19:40:37.006 - Task status: Preparing
2022-04-07 19:40:37.771 - Image copied to clipboard.
2022-04-07 19:40:37.809 - Unhandled exception:
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.7
2022-04-07 19:41:19.542 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2022-04-07 19:41:41.101 - File opened: C:\Users\rallen\C_Documents\ShareX\Capture\Logs\ShareX-Log-2022-04.txt

**Comment by Jaex** [comment]
Where you trying to take screenshot from?

**Comment by Jaex** [comment]
Duplicate of #6197
