### ISSUE TITLE
Could not create SSL/TLS Channel secure channel

### ISSUE THREAD

**Issue by CupCacke** [ShareX/ShareX#6201]
Greetings,

I´m running the latest Version of ShareX and using the upload option to my nextcloud, OS Windows 10 Pro 21H1.

I´ve get the following issue:

2022-04-06 20:38:40.424 - Error:
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
*********.***** (censored for privacy reasons)

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
2022-04-06 20:38:40.424 - Upload failed. Retrying upload.

**Comment by Lightningblade** [comment]
#5635
