### ISSUE TITLE
Can't send video to streamable anymore

### ISSUE THREAD

**Issue by u9g** [ShareX/ShareX#6235]
Error:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://api.streamable.com/upload

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://api.streamable.com/upload

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
   ```

**Comment by ArtixAllMighty** [comment]
i second this

**Comment by Jaex** [comment]
I can't reproduce it: https://streamable.com/a3incr

**Comment by 0x0ACB** [comment]
I have the same issue. I am using the steam version if that is important

**Comment by ArtixAllMighty** [comment]
I'm also in anonymous. not from steam though

**Comment by ArtixAllMighty** [comment]
im guessing it must be something to do with the website ? It worked fine till a couple days ago, and I didn't update or downgrade or touch anything else on ShareX

**Comment by lindenkron** [comment]
Also getting same error.

**Comment by DennisSkov** [comment]
I think Streamable disabled anonymous uploads.
Logging in works just fine.

**Comment by lindenkron** [comment]
For anyone coming here looking for a solution.

**Issue:**
Streamable disabled anonymous upload

**Solution:**
1. https://streamable.com/ - Make an account.
2. Open ShareX Rightclick > Destination > Destination Settings.
3. Select Streamable, put in your login.

It should work now.

**Comment by ArtixAllMighty** [comment]
this solution works. Thanks !

**Comment by Jaex** [comment]
@lawlmart should we remove anonymous upload support?

**Comment by lawlmart** [comment]
Yes, it's no longer supported.
