### ISSUE TITLE
??? whats going on here ?

### ISSUE THREAD

**Issue by greentoe1109** [ShareX/ShareX#6258]
System.TypeInitializationException: The type initializer for 'System.Net.ServicePointManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Net.ComNetOS' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
   at System.Diagnostics.TraceSource.Initialize()
   at System.Net.Logging.InitializeLogging()
   at System.Net.Logging.get_On()
   at System.Net.ComNetOS..cctor()
   --- End of inner exception stack trace ---
   at System.Net.ServicePointManager..cctor()
   --- End of inner exception stack trace ---
   at System.Net.ServicePointManager.set_InternalConnectionLimit(Int32 value)
   at System.Net.ServicePointManager.set_DefaultConnectionLimit(Int32 value)
   at ShareX.UploadersLib.Uploader.UpdateServicePointManager()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 13.6.1

**Comment by Lucyfurnice** [comment]
Looks like it is calling some method or object from System.Xml around
`at System.Diagnostics.TraceSource.Initialize()`
and the actual error is 
`System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.`

looks like that could be missing from your .net installation.
