### ISSUE TITLE
The given path's format is not supported.

### ISSUE THREAD

**Issue by Mooshimi** [ShareX/ShareX#6270]
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at ShareX.HelpersLib.Helpers.GetAbsolutePath(String path)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.7

**Comment by Mooshimi** [comment]
2022-05-22 01:40:07.746 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2022-05-22 01:40:07.747 - Executing: Capture region
2022-05-22 01:40:10.127 - Task in queue. Job: Job, Type: Image, Host: 
2022-05-22 01:40:10.154 - Task status: Preparing
2022-05-22 01:40:10.217 - Image copied to clipboard.
2022-05-22 01:40:10.291 - Unhandled exception:
System.NotSupportedException: The given path's format is not supported.

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/169680768-37d42078-1051-4be6-9e4f-ad11f85a0c19.png)

I actually figured the cause of this error out, and it crashes the whole program. If you click the paths from the menu on the right that pops up only, the dashes aren't generated and thus the path is bogues somehow.

Basically no dashes means crash program.

**Comment by Jaex** [comment]
![ShareX_2MNT3l8U4d](https://user-images.githubusercontent.com/822090/169681359-d95158ab-53cc-4599-83c3-b1f9d7ed1cc0.png)

It works fine for me, what you mean dashes aren't generated? It must be something related to window title?

**Comment by Jaex** [comment]
Can you test it? https://getsharex.com/docs/dev-builds

**Comment by Mooshimi** [comment]
> Can you test it? https://getsharex.com/docs/dev-builds

Yes it's interesting, it works on the dev build just fine without explicitly adding the dashes.
