### ISSUE TITLE
Unhandled exception -- illegal characters in path - crash

### ISSUE THREAD

**Issue by SheikYahbouti** [ShareX/ShareX#6280]
I accidentally typed a ">" into the file name.  Love ShareX but seems this could be handled more gracefully.

2022-06-02 17:58:27.170 - Unhandled exception:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.ChangeExtension(String path, String extension)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 13.7

**Comment by Jaex** [comment]
You mean here?

![](https://jaex.getsharex.com/2022/06/ShareX_rtGPsIQiYG.png)
