### ISSUE TITLE
Error encounted in ShareX 14.0.1

### ISSUE THREAD

**Issue by EdCaneda** [ShareX/ShareX#6398]
2022-07-21 15:36:58.193 - ShareX starting.
2022-07-21 15:36:58.203 - Version: 14.0.1
2022-07-21 15:36:58.207 - Build: MicrosoftStore
2022-07-21 15:36:58.207 - Command line: "C:\Program Files\WindowsApps\19568ShareX.ShareX_14.0.1.0_x64__egrzcvs15399j\ShareX.exe" 
2022-07-21 15:36:58.207 - Personal path: C:\Users\320148197\Documents\ShareX
2022-07-21 15:36:58.208 - Operating system: Windows 10 Enterprise (64-bit)
2022-07-21 15:36:58.209 - Running as elevated process: False
2022-07-21 15:36:58.515 - Flags: SilentRun
2022-07-21 15:36:58.549 - ApplicationConfig load started: C:\Users\320148197\Documents\ShareX\ApplicationConfig.json
2022-07-21 15:37:03.302 - ApplicationConfig load finished: C:\Users\320148197\Documents\ShareX\ApplicationConfig.json
2022-07-21 15:37:03.319 - UploadersConfig load started: C:\Users\320148197\Documents\ShareX\UploadersConfig.json
2022-07-21 15:37:03.325 - MainForm init started.
2022-07-21 15:37:03.741 - UploadersConfig load finished: C:\Users\320148197\Documents\ShareX\UploadersConfig.json
2022-07-21 15:37:03.751 - HotkeysConfig load started: C:\Users\320148197\Documents\ShareX\HotkeysConfig.json
2022-07-21 15:37:04.244 - HotkeysConfig load finished: C:\Users\320148197\Documents\ShareX\HotkeysConfig.json
2022-07-21 15:37:06.251 - MainForm init finished.
2022-07-21 15:37:07.863 - Startup time: 10266 ms
2022-07-21 15:37:07.975 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2022-07-21 15:37:07.975 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2022-07-21 15:37:07.975 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2022-07-21 15:37:07.975 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2022-07-21 15:37:07.975 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2022-07-21 15:37:07.979 - HotkeyManager started.
2022-07-21 15:37:07.980 - WatchFolderManager started.
2022-07-21 17:23:51.698 - ShareX closing.
2022-07-21 17:23:51.709 - ApplicationConfig save started: C:\Users\320148197\Documents\ShareX\ApplicationConfig.json
2022-07-21 17:23:52.307 - ApplicationConfig save successful: C:\Users\320148197\Documents\ShareX\ApplicationConfig.json
2022-07-21 17:23:52.308 - UploadersConfig save started: C:\Users\320148197\Documents\ShareX\UploadersConfig.json
2022-07-21 17:23:52.437 - UploadersConfig save successful: C:\Users\320148197\Documents\ShareX\UploadersConfig.json
2022-07-21 17:23:52.437 - HotkeysConfig save started: C:\Users\320148197\Documents\ShareX\HotkeysConfig.json
2022-07-21 17:23:52.683 - HotkeysConfig save successful: C:\Users\320148197\Documents\ShareX\HotkeysConfig.json
2022-07-21 17:23:52.683 - ShareX closed.
2022-07-22 07:56:29.672 - ShareX starting.
2022-07-22 07:56:29.677 - Version: 14.0.1
2022-07-22 07:56:29.678 - Build: MicrosoftStore
2022-07-22 07:56:29.678 - Command line: "C:\Program Files\WindowsApps\19568ShareX.ShareX_14.0.1.0_x64__egrzcvs15399j\ShareX.exe" 
2022-07-22 07:56:29.678 - Personal path: C:\Users\320148197\Documents\ShareX
2022-07-22 07:56:29.678 - Operating system: Windows 10 Enterprise (64-bit)
2022-07-22 07:56:29.679 - Running as elevated process: False
2022-07-22 07:56:30.405 - Flags: SilentRun
2022-07-22 07:56:30.469 - ApplicationConfig load started: C:\Users\320148197\Documents\ShareX\ApplicationConfig.json
2022-07-22 07:56:34.597 - ApplicationConfig load finished: C:\Users\320148197\Documents\ShareX\ApplicationConfig.json
2022-07-22 07:56:34.609 - UploadersConfig load started: C:\Users\320148197\Documents\ShareX\UploadersConfig.json
2022-07-22 07:56:34.611 - MainForm init started.
2022-07-22 07:56:35.340 - UploadersConfig load finished: C:\Users\320148197\Documents\ShareX\UploadersConfig.json
2022-07-22 07:56:35.448 - HotkeysConfig load started: C:\Users\320148197\Documents\ShareX\HotkeysConfig.json
2022-07-22 07:56:36.314 - HotkeysConfig load finished: C:\Users\320148197\Documents\ShareX\HotkeysConfig.json
2022-07-22 07:56:36.937 - MainForm init finished.
2022-07-22 07:56:38.649 - Startup time: 9417 ms
2022-07-22 07:56:38.681 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2022-07-22 07:56:38.682 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2022-07-22 07:56:38.682 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2022-07-22 07:56:38.682 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2022-07-22 07:56:38.682 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2022-07-22 07:56:38.685 - HotkeyManager started.
2022-07-22 07:56:38.738 - WatchFolderManager started.
2022-07-22 13:41:47.814 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2022-07-22 13:41:47.829 - Executing: Capture region
2022-07-22 13:41:51.046 - Task in queue. Job: Job, Type: Image, Host: Imgur
2022-07-22 13:41:51.349 - Task status: Preparing
2022-07-22 13:41:51.378 - Image copied to clipboard.
2022-07-22 13:41:51.413 - Image saved to file: C:\Users\320148197\Documents\ShareX\Screenshots\2022-07\r9I0djWqqn.png
2022-07-22 13:41:51.425 - Upload started. File name: r9I0djWqqn.png, File path: C:\Users\320148197\Documents\ShareX\Screenshots\2022-07\r9I0djWqqn.png
2022-07-22 13:41:52.506 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 13:41:52.507 - Upload failed. Retrying upload.
2022-07-22 13:41:53.626 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 13:41:53.633 - Task failed. File name: r9I0djWqqn.png, Errors:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 16:01:58.945 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2022-07-22 16:01:58.946 - Executing: Capture region
2022-07-22 16:02:03.829 - Task in queue. Job: Job, Type: Image, Host: Imgur
2022-07-22 16:02:03.841 - Task status: Preparing
2022-07-22 16:02:03.877 - Image copied to clipboard.
2022-07-22 16:02:03.906 - Image saved to file: C:\Users\320148197\Documents\ShareX\Screenshots\2022-07\msedge_3FXoprjQ57.png
2022-07-22 16:02:03.926 - Upload started. File name: msedge_3FXoprjQ57.png, File path: C:\Users\320148197\Documents\ShareX\Screenshots\2022-07\msedge_3FXoprjQ57.png
2022-07-22 16:02:05.324 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 16:02:05.324 - Upload failed. Retrying upload.
2022-07-22 16:02:06.791 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 16:02:06.793 - Task failed. File name: msedge_3FXoprjQ57.png, Errors:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 16:02:51.365 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2022-07-22 16:02:51.365 - Executing: Capture region
2022-07-22 16:02:55.452 - Task in queue. Job: Job, Type: Image, Host: Imgur
2022-07-22 16:02:55.525 - Task status: Preparing
2022-07-22 16:02:55.580 - Image copied to clipboard.
2022-07-22 16:02:55.605 - Image saved to file: C:\Users\320148197\Documents\ShareX\Screenshots\2022-07\msedge_0mXRWCzjmL.png
2022-07-22 16:02:55.629 - Upload started. File name: msedge_0mXRWCzjmL.png, File path: C:\Users\320148197\Documents\ShareX\Screenshots\2022-07\msedge_0mXRWCzjmL.png
2022-07-22 16:02:55.721 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 16:02:55.721 - Upload failed. Retrying upload.
2022-07-22 16:02:56.795 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 16:02:56.798 - Task failed. File name: msedge_0mXRWCzjmL.png, Errors:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
2022-07-22 16:03:05.093 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2022-07-22 16:03:13.461 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2022-07-22 16:04:46.108 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2022-07-22 16:04:56.346 - File opened: C:\Users\320148197\Documents\ShareX\Logs\ShareX-Log-2022-07.txt
2022-07-22 16:04:59.522 - File opened: C:\Users\320148197\Documents\ShareX\Logs\ShareX-Log-2022-07.txt
2022-07-22 16:05:05.806 - File opened: C:\Users\320148197\Documents\ShareX\Logs\ShareX-Log-2022-07.txt
2022-07-22 16:07:04.518 - File opened: C:\Users\320148197\Documents\ShareX\Logs\ShareX-Log-2022-07.txt

**Comment by EdCaneda** [comment]
I encountered this several times.
