### ISSUE TITLE
Can't upload images.

### ISSUE THREAD

**Issue by Fudster** [ShareX/ShareX#640]
Message:
The remote server returned an error: (403) Forbidden.

Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
You need to re authorize your login.
