### ISSUE TITLE
ShareX Google Photos uploader issue

### ISSUE THREAD

**Issue by erbanku** [ShareX/ShareX#6432]
ShareX Google Photos uploader returns 401 error from time to time, I need to refresh from the uploader settings every time to fix this. This issue has existed for a long time and is a very annoying bug.

Upload errors:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/uploads

Status code:
(401) Unauthorized

Headers:
X-GUploader-UploadID: ADPycdseeGgf_47UMywCMp_afeSTz0pVftT_wpXbIu9Ru0yGTW-hh90-2-ZW3JDsKONWiYT100-va532aOk0nDcbrHgKeIaOO_HR
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 71
Content-Type: text/html; charset=UTF-8
Date: Sun, 07 Aug 2022 04:50:57 GMT
Server: UploadServer

Response text:
{
  "code": 16,
  "message": "Authentication session is not defined."
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(401) Unauthorized

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sun, 07 Aug 2022 04:50:57 GMT
Server: ESF
WWW-Authenticate: Bearer realm="https://accounts.google.com/", error="invalid_token"

Response text:
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/uploads

Status code:
(401) Unauthorized

Headers:
X-GUploader-UploadID: ADPycdv2P0XShyma7AA9EcaqumRu_pGcFrSh9MuIk7ev-obKbcI9t1sp0iH5XLjIb1E4XAjvSrM7mFCENHMUeAYQW6dmCHyD1VbO
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 71
Content-Type: text/html; charset=UTF-8
Date: Sun, 07 Aug 2022 04:50:58 GMT
Server: UploadServer

Response text:
{
  "code": 16,
  "message": "Authentication session is not defined."
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(401) Unauthorized

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sun, 07 Aug 2022 04:50:59 GMT
Server: ESF
WWW-Authenticate: Bearer realm="https://accounts.google.com/", error="invalid_token"

Response text:
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/uploads

Status code:
(401) Unauthorized

Headers:
X-GUploader-UploadID: ADPycdsn_nveU5PKbIT714wWXASbILIq-yaGVdGAyN5JvyWg_PO9z9vuNtWcQFcvqDP30g351WZ3UyeCnJD25RQG-z4yXerLbKbK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 71
Content-Type: text/html; charset=UTF-8
Date: Sun, 07 Aug 2022 04:51:00 GMT
Server: UploadServer

Response text:
{
  "code": 16,
  "message": "Authentication session is not defined."
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(401) Unauthorized

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sun, 07 Aug 2022 04:51:00 GMT
Server: ESF
WWW-Authenticate: Bearer realm="https://accounts.google.com/", error="invalid_token"

Response text:
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.GooglePhotos.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/uploads

Status code:
(401) Unauthorized

Headers:
X-GUploader-UploadID: ADPycdu0qWfnpBsCAq4OseXaQvyVMquAv1K5ULEvZWPSiqtS6OXyHC0BjMyChdL85PGxk_FBQ552UXiJZQtgmpT5aBUu7YzhG55Z
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 71
Content-Type: text/html; charset=UTF-8
Date: Sun, 07 Aug 2022 04:51:02 GMT
Server: UploadServer

Response text:
{
  "code": 16,
  "message": "Authentication session is not defined."
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

Error message:
The remote server returned an error: (401) Unauthorized.

Request URL:
https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?fields=newMediaItemResults(mediaItem%2fproductUrl)

Status code:
(401) Unauthorized

Headers:
Vary: X-Origin,Referer,Origin,Accept-Encoding
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Transfer-Encoding: chunked
Accept-Ranges: none
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sun, 07 Aug 2022 04:51:02 GMT
Server: ESF
WWW-Authenticate: Bearer realm="https://accounts.google.com/", error="invalid_token"

Response text:
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
```

Additional log file:
[ShareX-Log-2022-08-07.txt](https://github.com/ShareX/ShareX/files/9276205/ShareX-Log-2022-08-07.txt)

**Comment by vonDubenshire** [comment]
I do not have a complete answer, but I noticed the OAuth access token error messages and thought I'd dig into it a little to leave some notes for the developer(s).

> https://stackoverflow.com/questions/52066480/401-unauthorized-on-google-photos-api-with-api-key 
You need to obtain an OAuth AccessToken to add as an HTTP Header in your request. [Here's a breakdown of the process I've used that has worked](https://stackoverflow.com/questions/51616556/q-google-photos-library-api-i-dont-know-how-it-works-someone/51957412#51957412), with the caveat that it periodically gets 401 errors from the mediaItems requests. It seems that Google is throttling the requests and denies a few if they're coming too fast.

The link he provides goes here:

https://stackoverflow.com/questions/51616556/q-google-photos-library-api-i-dont-know-how-it-works-someone/51957412#51957412

He documents his experience and what worked, though in 2018.

I opened the OAuth 2.0 documentation on Google's site and saw it was last updated in August 2022, so that may have something to do with it.

https://developers.google.com/identity/protocols/oauth2/web-server

https://developers.google.com/identity/protocols/oauth2/native-app
