### ISSUE TITLE
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by themegabyte** [ShareX/ShareX#6438]
I am not sure if this is ShareX issue or a MinIO issue.

I just spun up a MiniIO docker server and tested it with mc.exe (there native windows client). And it seems to be working.

![image](https://user-images.githubusercontent.com/9980686/183533762-05e97ec5-b21f-4a89-9b6d-7957499308b6.png)

However, I cannot seem to figure out why I cannot upload using ShareX. Here are two errors I encountered while uploading files and images.

While uploading files and videos.

```
Error message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

Request URL:
http://myURL.com:9000/sharex/%20Pro%20licensing.xlsx

Stack trace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

Upload to Amazon S3 failed.
```

While uploading images:
```
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
http://myURL.com:9000/sharex/chrome_n1WzQL0oZF.png

Status code:
(403) Forbidden

Headers:
Content-Security-Policy: block-all-mixed-content
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin,Accept-Encoding
X-Amz-Request-Id: 17098301FCB7A465
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Accept-Ranges: bytes
Content-Length: 425
Content-Type: application/xml
Date: Mon, 08 Aug 2022 23:39:42 GMT
Server: MinIO

Response text:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>chrome_n1WzQL0oZF.png</Key><BucketName>sharex</BucketName><Resource>/sharex/chrome_n1WzQL0oZF.png</Resource><RequestId>17098301FCB7A465</RequestId><HostId>9cf2fe69-1fcd-41a3-9eeb-32215229a22b</HostId></Error>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

Upload to Amazon S3 failed.
```

My current S3 config looks like this on ShareX:

![image](https://user-images.githubusercontent.com/9980686/183533260-ff71737d-7824-445e-9d02-1a0be8c33c0b.png)

Can you please instruct me on how to enable more verbose logging so perhaps I can assist you better.

**Comment by themegabyte** [comment]
Adding some more information to this.

I was able to get some verbose logs from MINIO server:

Logs of a successful push via `mc cp`:

```log
mydomain.com:9000 [REQUEST s3.GetBucketLocation] [2022-08-09T03:40:42.037] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 GET /sharex/?location=
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 User-Agent: MinIO (windows; amd64) minio-go/v7.0.31 mc.exe/RELEASE.2022-08-05T08-01-28Z
mydomain.com:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
mydomain.com:9000 X-Amz-Date: 20220809T084041Z
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=99ee17c18ddc44e4af247a4d9a5478b6b61230d38c90eace4206a80d52bbb27a
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:42.040] [ Duration 3.182ms  Γåæ 77 B  Γåô 444 B ]
mydomain.com:9000 200 OK
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Length: 128
mydomain.com:9000 Server: MinIO
mydomain.com:9000 X-Amz-Request-Id: 1709A087A08DA0DE
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.HeadBucket] [2022-08-09T03:40:42.185] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 HEAD /sharex/
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 User-Agent: MinIO (windows; amd64) minio-go/v7.0.31 mc.exe/RELEASE.2022-08-05T08-01-28Z
mydomain.com:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
mydomain.com:9000 X-Amz-Date: 20220809T084041Z
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e24b8c0ab3abb5a3ea7e204efc6743fa92b530b380534f307b61cbb62e9c586e
mydomain.com:9000 
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:42.185] [ Duration 459┬╡s  Γåæ 77 B  Γåô 314 B ]
mydomain.com:9000 200 OK
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 Server: MinIO
mydomain.com:9000 X-Amz-Request-Id: 1709A087A95A8A32
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.HeadBucket] [2022-08-09T03:40:42.330] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 HEAD /sharex/
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 User-Agent: MinIO (windows; amd64) minio-go/v7.0.31 mc.exe/RELEASE.2022-08-05T08-01-28Z
mydomain.com:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
mydomain.com:9000 X-Amz-Date: 20220809T084041Z
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e24b8c0ab3abb5a3ea7e204efc6743fa92b530b380534f307b61cbb62e9c586e
mydomain.com:9000 
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:42.331] [ Duration 857┬╡s  Γåæ 77 B  Γåô 314 B ]
mydomain.com:9000 200 OK
mydomain.com:9000 Server: MinIO
mydomain.com:9000 X-Amz-Request-Id: 1709A087B2048734
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.GetBucketObjectLockConfig] [2022-08-09T03:40:42.477] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 GET /sharex/?object-lock=
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
mydomain.com:9000 X-Amz-Date: 20220809T084042Z
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1b84254df239f6bcebf5a59c226a6b4c4b93dd179cfa4366b86d6179898ae5e1
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 User-Agent: MinIO (windows; amd64) minio-go/v7.0.31 mc.exe/RELEASE.2022-08-05T08-01-28Z
mydomain.com:9000 
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:42.477] [ Duration 648┬╡s  Γåæ 77 B  Γåô 653 B ]
mydomain.com:9000 404 Not Found
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Content-Length: 330
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 Server: MinIO
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 X-Amz-Request-Id: 1709A087BAC4725C
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ObjectLockConfigurationNotFoundError</Code><Message>Object Lock configuration does not exist for this bucket</Message><BucketName>sharex</BucketName><Resource>/sharex/</Resource><RequestId>1709A087BAC4725C</RequestId><HostId>9cf2fe69-1fcd-41a3-9eeb-32215229a22b</HostId></Error>
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.HeadBucket] [2022-08-09T03:40:42.623] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 HEAD /sharex/
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 User-Agent: MinIO (windows; amd64) minio-go/v7.0.31 mc.exe/RELEASE.2022-08-05T08-01-28Z
mydomain.com:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
mydomain.com:9000 X-Amz-Date: 20220809T084042Z
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=546db50afa84743bb2e0302cf6f396cde0165e3ecc0401dec8817905a323c6f6
mydomain.com:9000 
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:42.624] [ Duration 665┬╡s  Γåæ 77 B  Γåô 314 B ]
mydomain.com:9000 200 OK
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Amz-Request-Id: 1709A087C383FEFA
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Server: MinIO
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.PutObject] [2022-08-09T03:40:42.775] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 PUT /sharex/world-cities.csv
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 Content-Type: text/csv
mydomain.com:9000 User-Agent: MinIO (windows; amd64) minio-go/v7.0.31 mc.exe/RELEASE.2022-08-05T08-01-28Z
mydomain.com:9000 X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
mydomain.com:9000 X-Amz-Date: 20220809T084042Z
mydomain.com:9000 X-Amz-Decoded-Content-Length: 8013
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=ede4732b13ac35716f7a91b022006bdad36f23cec1f79cfc4de6cb328c6fbe62
mydomain.com:9000 Content-Length: 8188
mydomain.com:9000 <BODY>
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:42.787] [ Duration 12.23ms  Γåæ 8.1 KiB  Γåô 325 B ]
mydomain.com:9000 200 OK
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Length: 0
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 ETag: "5ebe8db6a458c98b3770864a191a9ca7"
mydomain.com:9000 Server: MinIO
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Amz-Request-Id: 1709A087CC8BDC8F
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 <BODY>
mydomain.com:9000 

```

Log of ShareX pushing:

```log
mydomain.com:9000 [REQUEST s3.PutObject] [2022-08-09T03:40:46.927] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 PUT /sharex/powershell_5hhcvoJO0q.png
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 Connection: Keep-Alive
mydomain.com:9000 User-Agent: ShareX/14.1.0
mydomain.com:9000 X-Amz-Content-Sha256: e2a3864ac1566a9b3918e07d79b14ddf9fb5c5e5d0490ba16e1df3ea05804f83
mydomain.com:9000 X-Amz-Date: 20220809T084046Z
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=5a5a99263103e38922a0660bdbffb2d30a7d8426ec2476e6fec7ab7dfa93d01d
mydomain.com:9000 Content-Length: 8275
mydomain.com:9000 Content-Type: image/png
mydomain.com:9000 X-Amz-Storage-Class: STANDARD
mydomain.com:9000 <BODY>
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:46.928] [ Duration 758┬╡s  Γåæ 121 B  Γåô 756 B ]
mydomain.com:9000 403 Forbidden
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Server: MinIO
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 Content-Length: 433
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 X-Amz-Request-Id: 1709A088C40D4C9C
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>powershell_5hhcvoJO0q.png</Key><BucketName>sharex</BucketName><Resource>/sharex/powershell_5hhcvoJO0q.png</Resource><RequestId>1709A088C40D4C9C</RequestId><HostId>9cf2fe69-1fcd-41a3-9eeb-32215229a22b</HostId></Error>
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.PutObject] [2022-08-09T03:40:48.074] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 PUT /sharex/powershell_5hhcvoJO0q.png
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 X-Amz-Storage-Class: STANDARD
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=153c6063bc65af89c01023b0d258ecfd1fcf1c9bdfbb89f8fbfe2b15992836b1
mydomain.com:9000 Content-Length: 8275
mydomain.com:9000 Content-Type: image/png
mydomain.com:9000 User-Agent: ShareX/14.1.0
mydomain.com:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
mydomain.com:9000 X-Amz-Date: 20220809T084047Z
mydomain.com:9000 <BODY>
mydomain.com:9000 [RESPONSE] [2022-08-09T03:40:48.075] [ Duration 794┬╡s  Γåæ 110 B  Γåô 756 B ]
mydomain.com:9000 403 Forbidden
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Length: 433
mydomain.com:9000 X-Amz-Request-Id: 1709A0890860B95C
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 Server: MinIO
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>powershell_5hhcvoJO0q.png</Key><BucketName>sharex</BucketName><Resource>/sharex/powershell_5hhcvoJO0q.png</Resource><RequestId>1709A0890860B95C</RequestId><HostId>9cf2fe69-1fcd-41a3-9eeb-32215229a22b</HostId></Error>
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.PutObject] [2022-08-09T03:41:01.960] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 PUT /sharex/WINWORD_JZp1kuUwp6.mp4
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 Content-Type: video/mp4
mydomain.com:9000 User-Agent: ShareX/14.1.0
mydomain.com:9000 X-Amz-Content-Sha256: 3990be59fd0bc4329905755ef78f0a3a1516b33f79ac58f68d43e3a5b727503e
mydomain.com:9000 X-Amz-Date: 20220809T084101Z
mydomain.com:9000 X-Amz-Storage-Class: STANDARD
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=1738d7b61db5415b4b740fb5dbdd478287781b0c225513d3cf99652b193e31c5
mydomain.com:9000 Content-Length: 853079
mydomain.com:9000 <BODY>
mydomain.com:9000 [RESPONSE] [2022-08-09T03:41:01.961] [ Duration 760┬╡s  Γåæ 110 B  Γåô 750 B ]
mydomain.com:9000 403 Forbidden
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Amz-Request-Id: 1709A08C4411D29F
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Server: MinIO
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Content-Length: 427
mydomain.com:9000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>WINWORD_JZp1kuUwp6.mp4</Key><BucketName>sharex</BucketName><Resource>/sharex/WINWORD_JZp1kuUwp6.mp4</Resource><RequestId>1709A08C4411D29F</RequestId><HostId>9cf2fe69-1fcd-41a3-9eeb-32215229a22b</HostId></Error>
mydomain.com:9000 
mydomain.com:9000 [REQUEST s3.PutObject] [2022-08-09T03:41:03.761] [Client IP: 39.xx.xx.xx]
mydomain.com:9000 PUT /sharex/WINWORD_JZp1kuUwp6.mp4
mydomain.com:9000 Proto: HTTP/1.1
mydomain.com:9000 Host: mydomain.com:9000
mydomain.com:9000 X-Amz-Content-Sha256: fd3197a545fc8572adc839eb7c3486f6e346f475d73e14f612d877d738eafc71
mydomain.com:9000 X-Amz-Date: 20220809T084103Z
mydomain.com:9000 X-Amz-Storage-Class: STANDARD
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=34651b6a6f976b45e5ac42c2a38bdbe0907123a5ebb4d1caa2e2535eea9aa875
mydomain.com:9000 Content-Length: 853079
mydomain.com:9000 Content-Type: video/mp4
mydomain.com:9000 User-Agent: ShareX/14.1.0
mydomain.com:9000 <BODY>
mydomain.com:9000 [RESPONSE] [2022-08-09T03:41:03.762] [ Duration 1.221ms  Γåæ 110 B  Γåô 750 B ]
mydomain.com:9000 403 Forbidden
mydomain.com:9000 X-Xss-Protection: 1; mode=block
mydomain.com:9000 Content-Security-Policy: block-all-mixed-content
mydomain.com:9000 Vary: Origin,Accept-Encoding
mydomain.com:9000 X-Amz-Request-Id: 1709A08CAF6A52D0
mydomain.com:9000 Server: MinIO
mydomain.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
mydomain.com:9000 X-Content-Type-Options: nosniff
mydomain.com:9000 Accept-Ranges: bytes
mydomain.com:9000 Content-Length: 427
mydomain.com:9000 Content-Type: application/xml
mydomain.com:9000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>WINWORD_JZp1kuUwp6.mp4</Key><BucketName>sharex</BucketName><Resource>/sharex/WINWORD_JZp1kuUwp6.mp4</Resource><RequestId>1709A08CAF6A52D0</RequestId><HostId>9cf2fe69-1fcd-41a3-9eeb-32215229a22b</HostId></Error>
mydomain.com:9000 


```

**Comment by themegabyte** [comment]
Perhaps this could be the issue? I took snip of the headers that I saw were different. ShareX is signing it with "content-length" while the mc client is signing it with "host"

MC client
```log
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=ede4732b13ac35716f7a91b022006bdad36f23cec1f79cfc4de6cb328c6fbe62
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=5c52d4c0510afc1a278e84ee4e96faa7c3fff2c06a33f3fddb0bf1e9cd576428
```

Sharex

```log
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=5a5a99263103e38922a0660bdbffb2d30a7d8426ec2476e6fec7ab7dfa93d01d
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=153c6063bc65af89c01023b0d258ecfd1fcf1c9bdfbb89f8fbfe2b15992836b1
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=1738d7b61db5415b4b740fb5dbdd478287781b0c225513d3cf99652b193e31c5
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=34651b6a6f976b45e5ac42c2a38bdbe0907123a5ebb4d1caa2e2535eea9aa875
```

share x headers with signed payload off:
```log
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=404b460d4fec1f7bfb024ef2f5a222de1cbaa8355352eab613f206700cb47afd
mydomain.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=<credential>/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=0f0ad556c6daa716e94d3dd9494dae5ca1db6f9952928349e5a35882bba54bbe
```

**Comment by themegabyte** [comment]
Alright... I just used the play server (that MINIO provide as an example) and sharex smooothly uploaded it to it. Which means somethin is not alright with my server configuration.

Here's the trace log for that:

```play.min.io [REQUEST s3.PutObject] [2022-08-09T04:10:53.561] [Client IP: 39.xx.xx.xx]
play.min.io PUT /worldcieities/ShareX_6jnVAywLRZ.png
play.min.io Proto: HTTP/1.1
play.min.io Host: play.min.io
play.min.io Authorization: AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=7c521d30a2eb0303c15e1914ec40ac4d9b8c379a3128b41b9ba17984625f0760
play.min.io X-Forwarded-For: 39.xx.xx.xx
play.min.io X-Forwarded-Proto: https
play.min.io X-Amz-Date: 20220809T091052Z
play.min.io X-Amz-Storage-Class: STANDARD
play.min.io X-Real-Ip: 39.xx.xx.xx
play.min.io Content-Length: 6075
play.min.io Content-Type: image/png
play.min.io User-Agent: ShareX/14.1.0
play.min.io X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
play.min.io <BODY>
play.min.io [RESPONSE] [2022-08-09T04:10:53.576] [ Duration 15.262ms  Γåæ 6.1 KiB  Γåô 356 B ]
play.min.io 200 OK
play.min.io Vary: Origin,Accept-Encoding
play.min.io X-Content-Type-Options: nosniff
play.min.io X-Xss-Protection: 1; mode=block
play.min.io Accept-Ranges: bytes
play.min.io Content-Length: 0
play.min.io ETag: "9ca29b728f19c902b9100e66e976f5c6"
play.min.io X-Amz-Bucket-Region: us-east-1
play.min.io X-Amz-Request-Id: 1709A22D67D258FC
play.min.io Content-Security-Policy: block-all-mixed-content
play.min.io Server: MinIO
play.min.io Strict-Transport-Security: max-age=31536000; includeSubDomains
play.min.io <BODY>
play.min.io 

```
mp4 file.

```play.min.io [REQUEST s3.PutObject] [2022-08-09T04:18:03.493] [Client IP: 39.xx.xx.xx]
play.min.io PUT /worldcieities/ShareX_uqOnOCCJ7U.mp4
play.min.io Proto: HTTP/1.1
play.min.io Host: play.min.io
play.min.io X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
play.min.io X-Amz-Date: 20220809T091803Z
play.min.io X-Amz-Storage-Class: STANDARD
play.min.io X-Forwarded-For: 39.xx.xx.xx
play.min.io X-Forwarded-Proto: https
play.min.io X-Real-Ip: 39.xx.xx.xx
play.min.io Content-Length: 31661
play.min.io Content-Type: video/mp4
play.min.io User-Agent: ShareX/14.1.0
play.min.io Authorization: AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20220809/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=43e3b3dd7cad428617e64145a8428ab39ac936f33a411890a8507ce86cb803f1
play.min.io <BODY>
play.min.io [RESPONSE] [2022-08-09T04:18:03.538] [ Duration 45.165ms  Γåæ 31 KiB  Γåô 356 B ]
play.min.io 200 OK
play.min.io X-Amz-Request-Id: 1709A29181C39051
play.min.io X-Content-Type-Options: nosniff
play.min.io Content-Length: 0
play.min.io Content-Security-Policy: block-all-mixed-content
play.min.io Server: MinIO
play.min.io Strict-Transport-Security: max-age=31536000; includeSubDomains
play.min.io X-Xss-Protection: 1; mode=block
play.min.io Accept-Ranges: bytes
play.min.io ETag: "5c615f06644538d15ec26a50880446a4"
play.min.io Vary: Origin,Accept-Encoding
play.min.io X-Amz-Bucket-Region: us-east-1
play.min.io <BODY>
play.min.io 
```

I am going to put my server behind TLS and try again to see if ShareX works...

**Comment by themegabyte** [comment]
Does anyone here now how is this generated in ShareX!?

When I try upload it to my server with TLS, and all, basically the same configuration that `play.min.io` has, I get the below SHA256 hash, which is wrong.

`X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

When I upload to the `play.min.io` server, the SHA256 generated is correct:

`play.min.io X-Amz-Content-Sha256: d444f03ca34e579ea05dfca89dfa8d2b53ebd3d0bbfbbeba63fdce8423190aa0`

My file's SHA256 is below as I can see it on Windows: 
```
Name: ShareX_uqOnOCCJ7U.mp4
Size: 31661 bytes (30 KiB)
SHA256: D444F03CA34E579EA05DFCA89DFA8D2B53EBD3D0BBFBBEBA63FDCE8423190AA0
```

Its not making sense how shareX can generate two Hashes for the same file...

**Comment by themegabyte** [comment]
Alright I disabled, "Signed payload" and it worked finally...

Leaving my configuration here so that if any  of you into this, this might help.

Setup your Nginx Proxy like so: [https://docs.min.io/docs/setup-nginx-proxy-with-minio](url).

ShareX settings:

![image](https://user-images.githubusercontent.com/9980686/183639403-2611fdaf-cfef-463e-8008-88412186cc87.png)

The end point URL, must be the same as what you configured in Nginx.

Marking this as resolved.

**Comment by themegabyte** [comment]
FYI, it works without HTTP for me too now. OMG, I don't know what changed... I really don't know. Maybe I had to give this 10 hour sacrifice to the time gods? I will never know...
