### ISSUE TITLE
[DropBox sharing] The remote server returned an error: (409) Conflict

### ISSUE THREAD

**Issue by ujjwal-aryan** [ShareX/ShareX#6450]
**Images are uploaded but cannot get a share link**

```
Error message:
The remote server returned an error: (409) Conflict.

Request URL:
https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings

Status code:
(409) Conflict

Headers:
Content-Security-Policy: sandbox allow-forms allow-scripts
X-Content-Type-Options: nosniff
Accept-Encoding: identity,gzip
X-Dropbox-Response-Origin: far_remote
X-Dropbox-Request-Id: c464705525f24749ab85bec0d9629984
Content-Length: 71
Cache-Control: no-cache
Content-Type: application/json
Date: Tue, 16 Aug 2022 09:59:21 GMT
Server: envoy

Response text:
{"error_summary": "access_denied/", "error": {".tag": "access_denied"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)
```

**Comment by ujjwal-aryan** [comment]
Dont know if this is a fix or not but enabling share on the folder from dropbox fixed this issue.
