### ISSUE TITLE
bug: chrome extension -> ShareX with long image url causes System.IO.PathTooLongException

### ISSUE THREAD

**Issue by lrstanley** [ShareX/ShareX#6460]
Ran into an issue today when I started to utilize the ShareX chrome extension in combination with ShareX itself. In my case, I was right clicking an image in Google Photos, and was trying to push it to an S3 bucket with ShareX.

Received this error:

![System.IO.PathTooLongException](https://cdn.liam.sh/share/2022/08/u7fSb5IMoq.png)

The direct URL from Google photos (I've intentionally obfuscated some characters here and in the log output):
```
https://lh3.googleusercontent.com/os8v3QRMWMLNeYv4JQi3hIh3BFaiT_FlAV6WGDn2evCrKdTxx-Xw4jlAlwPpLQ2ZHxmPI6XQc-qV-zQF-8atc9oa7Goi5v1Yx43b2SwLYlDToSKDAa9sRLx-X936u6fzvcf7VsqWZLxpNOrNSjBnkek4NsCjihcIKESQBl1WYX4XfVpQxrsGbytTM3sBlG_kSIMH-nOE-3h54-Ki6qS2hLQefIGxv8ENiJW7zCGlpfiMgNovmxobwzlmfL3g3ztnYGEWh_r7ewuwI4XNuLYm4x4YtqqTCqbU28I0b1guK3ZibmTnC-FGJjhHGhFFJMHP34cFDsIm4e2lyvqF_hWQ9CYCK-pahsU66lWsAVOdgO8mNAediZzgPxjVS0clAVJ11Lv62Sj32RTxoyVYi1ZFu5mdPw-m5azfWBB5qhP7LrSgDEvzlS8RRDTZ3uIVU7asNUF9MzP2hpfmD4IYXcrbbkrlJLTi_yYcSyJa6Er22Dypdhxr74AxizZfOI3rb-RieCQ2G3Se79mGHoE3dPx9zisJ9L52DYmFxHVy-RrqR3sgCZ0FpvZMYLq2kDi0lDiSvSDs6ha5YHL-f_dXr5sommFrY6FqM_GejLQSf21b88zM-VWUiv3_PFoeYJS_RDRgh_nNToDvBOdWrRseqLJobDxvWZ0JUrG7cwggFlNPl8zrFAhxFqx41z_gYUZCo2n8gsBxHuDwdCMtQUuBdogc6zECwEnMwTmgXNHo76FCLfj63nkQwDItEVKoTbfAvcezUgnrHbCqW1YN5xlnpDN5TxPQOQZw3qkCvu0=s929-no?authuser=0
```

And ShareX logs:

```console
2022-08-22 00:05:31.040 - CommandLine: -NativeMessagingInput "C:\Users\me\AppData\Local\Temp\tmp9740.json"
2022-08-22 00:05:31.087 - Task in queue. Job: DownloadUpload, Type: File, Host: Amazon S3
2022-08-22 00:05:31.092 - Task status: Preparing
2022-08-22 00:05:31.094 - Task status: Preparing
2022-08-22 00:05:31.117 - Exception:
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NewNormalizePathLimitedChecks(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at ShareX.HelpersLib.FileHelpers.CreateDirectoryFromFilePath(String filePath)
   at ShareX.WorkerTask.DownloadFromURL(Boolean upload)
2022-08-22 00:12:44.023 - Task stopped. File name: os8v3QRMWMLNeYv4JQi3hIh3BFaiT_FlAV6WGDn2evCrKdTxx-Xw4jlAlwPpLQ2ZHxmPI6XQc-qV-zQF-8atc9oa7Goi5v1Yx43b2SwLYlDToSKDAa9sRLx-X936u6fzvcf7VsqWZLxpNOrNSjBnkek4NsCjihcIKESQBl1WYX4XfVpQxrsGbytTM3sBlG_kSIMH-nOE-3h54-Ki6qS2hLQefIGxv8ENiJW7zCGlpfiMgNovmxobwzlmfL3g3ztnYGEWh_r7ewuwI4XNuLYm4x4YtqqTCqbU28I0b1guK3ZibmTnC-FGJjhHGhFFJMHP34cFDsIm4e2lyvqF_hWQ9CYCK-pahsU66lWsAVOdgO8mNAediZzgPxjVS0clAVJ11Lv62Sj32RTxoyVYi1ZFu5mdPw-m5azfWBB5qhP7LrSgDEvzlS8RRDTZ3uIVU7asNUF9MzP2hpfmD4IYXcrbbkrlJLTi_yYcSyJa6Er22Dypdhxr74AxizZfOI3rb-RieCQ2G3Se79mGHoE3dPx9zisJ9L52DYmFxHVy-RrqR3sgCZ0FpvZMYLq2kDi0lDiSvSDs6ha5YHL-f_dXr5sommFrY6FqM_GejLQSf21b88zM-VWUiv3_PFoeYJS_RDRgh_nNToDvBOdWrRseqLJobDxvWZ0JUrG7cwggFlNPl8zrFAhxFqx41z_gYUZCo2n8gsBxHuDwdCMtQUuBdogc6zECwEnMwTmgXNHo76FCLfj63nkQwDItEVKoTbfAvcezUgnrHbCqW1YN5xlnpDN5TxPQOQZw3qkCvu0=s929-no
```

FWIW the difference in timestamps when it showed the `Task stopped` message, seems like it didn't show that in the log until I closed the error window.

**Comment by Jaex** [comment]
I need to get real file name from response headers instead of trying to grab it from url string.
