### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by SVaddula** [ShareX/ShareX#6536]
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at ShareX.HelpersLib.Extensions.CreateEmptyBitmap(Image img, Int32 widthOffset, Int32 heightOffset, PixelFormat pixelFormat)
   at ShareX.HelpersLib.ImageHelpers.AddShadow(Bitmap bmp, Single opacity, Int32 size, Single darkness, Color color, Point offset)
   at ShareX.ImageEffectsLib.Shadow.Apply(Bitmap bmp)
   at ShareX.ImageEffectsLib.ImageEffectPreset.ApplyEffects(Bitmap bmp)
   at ShareX.TaskHelpers.ApplyImageEffects(Bitmap bmp, TaskSettingsImage taskSettingsImage)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 14.1

**Comment by botatooo** [comment]
can we get system information?

**Comment by SVaddula** [comment]
Sure, what information would you need? Also could you tell me how to get that information.

**Comment by SVaddula** [comment]
> can we get system information?

Sure, what information would you need? Also could you tell me how to get that information.

**Comment by SVaddula** [comment]
Hello?

> can we get system information?
