### ISSUE TITLE
Seafile paths broken?

### ISSUE THREAD

**Issue by angelfor3v3r** [ShareX/ShareX#6564]
I just set up Seafile today and ShareX seems to fail if "Path:" is set to anything other than "/". Am I not understanding something here?

Theres a similar issue from a few years ago which is closed: https://github.com/ShareX/ShareX/issues/5094

ShareX 14.1 Portable
Windows 11 (22H2 - 22621.674)

```
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://[REDACTED]/seafhttp/upload-api/5ad5bf8e-4d6b-485f-90a2-3db469f0abd3

Status code:
(403) Forbidden

Headers:
Access-Control-Allow-Headers: x-requested-with, content-type, content-range, content-disposition, accept, origin, authorization
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Content-Length: 31
Content-Type: application/json; charset=utf-8
Date: Fri, 21 Oct 2022 14:23:23 GMT

Response text:
{"error": "Permission denied."}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by angelfor3v3r** [comment]
Sadly I’ve moved away from seafile so I don’t have anything to test with anymore.

**Comment by CoryRobertson** [comment]
This issue also happens with me as well
