### ISSUE TITLE
Imgur - Upload broke 

### ISSUE THREAD

**Issue by DidUknowiPwn** [ShareX/ShareX#657]
ShareX 9.9.0
Logged in to Imgur
Started occurring today
```
Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

**Comment by Jaex** [comment]
Problem in Imgur side.

**Comment by DidUknowiPwn** [comment]
Expected as much thanks though.
