### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kamekku14** [ShareX/ShareX#6608]
Got this error while opening the History window.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.HistoryLib.HistoryForm.pbThumbnail_MouseDown(Object sender, MouseEventArgs e)
   at System.Windows.Forms.MouseEventHandler.Invoke(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

ShareX 14.1

**Comment by StelioKontosXBL** [comment]
Is this reproducible? If so, could you provide a gif showing this happening?

Specifically looking for some clarification on when exactly "while opening" refers to...was the history window visible when the exception was thrown? If so, had you clicked anything in the history window?
