### ISSUE TITLE
System.IO.IO.Exception

### ISSUE THREAD

**Issue by madmax327** [ShareX/ShareX#6627]
I have reformated my PC and installed ShareX and I immediately get the below error
I am unable to see the program or edit settings.

 System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ShareX.Program.ReadPersonalPathConfig()
   at ShareX.Program.UpdatePersonalPath()
   at ShareX.Program.Main(String[] args)

ShareX 14.1

**Comment by StelioKontosXBL** [comment]
Most likely it's attempting to sync to a folder setup with cloud sync (One drive, Google Drive, Dropbox., etc...), that needs logged in again. Either...

- Login to whatever cloud storage service you use, and try again after,
- Verify that ShareX isn't running from that folder (this includes checking any dependencies such as FFmpeg aren't installed in that folder also), mentioned in #5401.
- Or missing registry key...see final comment in thread for #6493.

Duplicate of:
#6590
#6281
#5867
#5766
#5608

**Comment by anthonyn4** [comment]
Personally I fixed it by going into /Documents/ShareX, deleting the file PersonalPath.cfg, then opened ShareX with no issue.
