### ISSUE TITLE
Flickr auth doesn't work after updating Ukrainian translation

### ISSUE THREAD

**Issue by PerchunPak** [ShareX/ShareX#6637]
Just a click on `Connect...` button.

![image](https://user-images.githubusercontent.com/68118654/206725972-d1abc9f3-5a99-4484-8855-98f21d5ac6f4.png)

```
System.Exception: ConsumerKey or ConsumerSecret or ConsumerPrivateKey empty.
  at ShareX.UploadersLib.OAuthManager.GenerateQuery(String url, Dictionary'2 args, HttpMethod httpMethod, OAuthlnfo oauth, Dictionary'2& parameters)
  at ShareX.UploadersLib.Uploader.GetAuthorizationURL(String requestTokenURL, String authorizeURL, OAuthlnfo authlnfo, Dictionary'2 customParameters, HttpMethod httpMethod)
  at ShareX.UploadersLib.ImageUpIoaders.FIickrUpIoader.GetAuthorizationURLO
  at ShareX.UpIoadersLib.UploadersConfigForm.FIickrAuthOpenO
```

Version: Dev build on https://github.com/ShareX/ShareX/commit/4d6490136438e6086fe2a72576dfc1ccfbad2c03.

P.S. Verification code can be empty as well.

**Comment by PerchunPak** [comment]
Can't reproduce on 14.1.0 portable.

And can't reproduce with https://github.com/ShareX/ShareX/suites/9664126789/artifacts/462479523.

Reproduced with https://github.com/PerchunPak/ShareX/suites/9728177539/artifacts/466665625.

**Comment by PerchunPak** [comment]
Removing `+` on invariant strings didn't help.

**Comment by PerchunPak** [comment]
Forks miss API keys during the build
https://github.com/ShareX/ShareX/blob/develop/.github/workflows/build.yml#L53-L59
