### ISSUE TITLE
Imgur upload failed: (417) Internal expectation failed

### ISSUE THREAD

**Issue by issam-seghir** [ShareX/ShareX#6704]
Error When uploading a `image.gif `

```
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: keep-alive
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1245
X-Post-Rate-Limit-Reset: 3437
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
X-Served-By: cache-pmo2280024-PMO
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1674595524.116118,VS0,VE6784
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Tue, 24 Jan 2023 21:25:30 GMT
Server: cat factory 1.0

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by Shadowrs** [comment]
Same for me and im on VPN - maybe IP get rejected?
