### ISSUE TITLE
Pastebin: Bad API request, invalid api_paste_private

### ISSUE THREAD

**Issue by PerchunPak** [ShareX/ShareX#6729]
```
Error message:
The remote server returned an error: (422) Unprocessable Entity.

Request URL:
https://pastebin.com/api/api_post.php

Status code:
(422) Unprocessable Entity

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
CF-Cache-Status: DYNAMIC
CF-RAY: 79120878e95a4138-PRG
Content-Type: text/html; charset=UTF-8
Date: Sun, 29 Jan 2023 12:39:52 GMT
Server: cloudflare

Response text:
Bad API request, invalid api_paste_private

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)



System.ArgumentException: Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)
```
Fresh portable installation from getsharex.com (15.0.0, release date 2023-01-18) with chosen `Private (members only)` in Destination Settings -> Pastebin -> Privacy.

**Comment by PerchunPak** [comment]
Fixed by logging in the Pastebin account. ShareX should provide better message.
