### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by dullahan8** [ShareX/ShareX#6780]
When closing the Applications Settings window, I got this today. I'm not really sure where or how it's broken, or how to resolve it. I already tried reinstalling ShareX. Might be a settings issue or corrupted settings file?

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.MainForm.UpdateWorkflowsMenu()
   at ShareX.MainForm.tsbApplicationSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 15.0
```

**Comment by dullahan8** [comment]
Also just discovered the Hotkeys button doesn't work.

Noticed a previous issue with an identical title from months ago asked for a gif to help troubleshoot so here is one.
![ShareX_2023-02-25_22-57-49](https://user-images.githubusercontent.com/7637030/221396990-34c94803-b9e1-4906-bbe1-49baa50a8fb3.gif)

**Comment by dullahan8** [comment]
Noticed an item in the right-click context menu, "Disable Hotkeys". I tried clicking it but got this error again.

```System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.TaskHelpers.ToggleHotkeys(Boolean disableHotkeys)
   at ShareX.TaskHelpers.ToggleHotkeys()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 15.0```

I noticed all my previous hotkeys no longer function, but I'm not sure if that was because of the reinstall or because of the error.

**Comment by dullahan8** [comment]
Found the backups folder and replaced my ApplicationConfig.json and HotkeysConfig.json with copies from 1 week ago but it made no difference.

**Comment by teauxfu** [comment]
Hmm I haven't been able to reproduce this on Win10/v15 using the setup version from releases. What installer did you use? Anything interesting in the Debug > Debug log?

**Comment by dullahan8** [comment]
I used the installer downloaded from the releases page.

Weird, today it mysteriously fixed itself. Perhaps after several reboots or restarts of the application it managed to figure things out.

All the buttons on the GUI works. I can open the Hotkey settings. Mysteriously it said all the hotkeys are currently disabled so I clicked the dialogue to re-enable them all.

**Comment by dullahan8** [comment]
Closing as not reproducable.
