### ISSUE TITLE
FTP Upload Fails to Connect

### ISSUE THREAD

**Issue by badrhinogames** [ShareX/ShareX#679]
The login info is correct and ShareX can connect successfully to the FTP folder; however, whenever images are attempting to upload it fails every time. Clicking the "client" button in the FTP destination settings window brings up nothing in the folder which makes me wonder if it's connecting successfully. Here is the error that generates when images attempt to upload to FTP:

System.Net.FtpClient.FtpException: Failed to get the EPSV port from: Entering Passive Mode (74,208,55,155,219,103)
   at System.Net.FtpClient.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenDataStream(String command, Int64 restart)
   at System.Net.FtpClient.FtpClient.OpenWrite(String path, FtpDataType type)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
Did you tried changing IsActive setting?

**Comment by badrhinogames** [comment]
Thanks Jaex! Not sure how that got disabled.
