### ISSUE TITLE
File Upload not working

### ISSUE THREAD

**Issue by ryehamstrawberry** [ShareX/ShareX#6794]
Recently ShareX has stopped behaving nicely with my VPN and while uploads worked fine previously, the upload feature now produces the following error while VPN is enabled:
```
Error message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

Request URL:
https://api.imgur.com/3/upload

Stack trace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```
I've determined this must be a VPN service or local connectivity issue due to successful uploads when VPN is disabled, but I'm unsure why previously this was not an issue.
Any suggestions on how to troubleshoot and resolve failed uploads behind VPN would be appreciated.

---
ShareX v15.0 Portable

**Comment by ryehamstrawberry** [comment]
Note: this error occurs when "anonymous" user account is selected via ShareX. I'm unsure if using personal account credentials changes anything.

**Comment by The760** [comment]
Just wanted to comment and say that I am also having this issue when using a VPN. Have tried hopping between PIA and Mullvad. Works perfectly fine if I have the VPN off.
