### ISSUE TITLE
Bug in SSL connection

### ISSUE THREAD

**Issue by nordic** [ShareX/ShareX#681]
after trying upload picture to imgur.com 

Message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
It is not to do with ShareX. Probably you can upload now.

**Comment by hmksq** [comment]
I can reproduce by uploading images using HTTPS to a site with a valid certificate. But this error appears once-twice a day. If you get this error and click upload it will upload again and this type successfully.

For now I just set it to retry if the upload fails, it shouldn't have anymore problems.

```
Message:
The request was aborted: Could not create SSL/TLS secure channel.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```
