### ISSUE TITLE
Error message: The remote server returned an error: (409) Conflict.

### ISSUE THREAD

**Issue by Stati5tiker** [ShareX/ShareX#6818]
I have been getting this error today. I have kept all of my settings the same since 2022. I tried changing the Destination Settings for Dropbox. I also revoked and invoked access again, but the same issue persists. I can upload with other destinations like Google Drive.

If anyone knows how to approach this error, please let me know. 

Attempted:
- Changed settings around for destination settings for Dropbox.
- Revoked and invoked access.

Error message:
The remote server returned an error: (409) Conflict.

Request URL:
https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings

Status code:
(409) Conflict

Headers:
Content-Security-Policy: sandbox allow-forms allow-scripts
X-Content-Type-Options: nosniff
Accept-Encoding: identity,gzip
Vary: Accept-Encoding
X-Dropbox-Response-Origin: far_remote
X-Dropbox-Request-Id: 3a857630217841568c070f6808e61e42
Content-Length: 139
Cache-Control: no-cache
Content-Type: application/json
Date: Thu, 23 Mar 2023 03:19:06 GMT
Server: envoy

Response text:
{"error_summary": "settings_error/invalid_settings/.", "error": {".tag": "settings_error", "settings_error": {".tag": "invalid_settings"}}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

**Comment by Stati5tiker** [comment]
This has been resolved. On its own, unfortunately.

Just so you know, reinstalling the program did not work. I cleaned all files from all of C:\ that might include Documents and AppData (although I don't recall if there were any).

The problem was more than likely on Dropbox's end. I tested it today, and it works.
