### ISSUE TITLE
Uploads to Imgur fail after a few uploads

### ISSUE THREAD

**Issue by inVech** [ShareX/ShareX#683]
It then gives me this error;
Message:
The underlying connection was closed: An unexpected error occurred on a receive.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata) in M:\ShareX-9.9.0\ShareX.UploadersLib\Uploader.cs:line 344

**Comment by Jaex** [comment]
I don't think it is to do with ShareX.

**Comment by inVech** [comment]
I'm pretty sure it does, when I enabled retrying after fails to another host, I setup puush.me as the alternative, it uploaded there once, then gave the same error.

**Comment by inVech** [comment]
I'm pretty sure it does, when I enabled retrying after fails to another host, I setup puush.me as the alternative, it uploaded there once, then gave the same error.

**Comment by Jaex** [comment]
ShareX using same upload functions for years. Then how it worked before? I'm pretty sure it is to do with your computer.
