### ISSUE TITLE
upload image is impossible

### ISSUE THREAD

**Issue by mohamadArdestani** [ShareX/ShareX#6842]
Error message:
The underlying connection was closed: An unexpected error occurred on a send.

Request URL:
https://api.imgur.com/3/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by Aokromes** [comment]
works for me (TM)
https://i.imgur.com/Scpbqw1.png

**Comment by minhperry** [comment]
Imgur is removing anon uploads so this is going to fail soon
