### ISSUE TITLE
this is the data from the error message. 

### ISSUE THREAD

**Issue by DaveChu24** [ShareX/ShareX#6919]
System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ShareX.Program.ReadPersonalPathConfig()
   at ShareX.Program.UpdatePersonalPath()
   at ShareX.Program.Main(String[] args)

ShareX 15.0

This has been a handy program.  I enjoy using it and would like to continue using it when is is functional again.  I would appreciate a response and a solution.

**Comment by the-Arioch** [comment]
What might help

1. learn to use SysInternals Process Monitor, then trace ShareX start with it, see exactl Windows error and exact file path of it, this might give you enough of the clues to break out of the loop

2. total removal and clean-up of DotNet and then re-installation of it might help... or might totally ruing your Windows, too.
3. Actualy, this ususally is a very bad advise. OTOH i had about half-year of a mistewrious errors in some programs that in the end were caused by mis-configuration of DotNet 4.x and were fixed by ckean reinstall of it. Granted, i was doing it on Windows 7 that is per se perfectly fine without DotNet. I am, not sure Win10 would even let you log in if DotNet gets really removed...
