### ISSUE TITLE
SSH upload issue after latest update

### ISSUE THREAD

**Issue by chickenputty** [ShareX/ShareX#693]
When using SSH to upload a rectangular image capture:
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Renci.SshNet.Sftp.SubsystemSession.SendData(Byte[] data)
   at Renci.SshNet.Sftp.SftpSession.SendRequest(SftpRequest request)
   at Renci.SshNet.Sftp.SftpSession.RequestWrite(Byte[] handle, UInt64 offset, Byte[] data, EventWaitHandle wait, Action`1 writeCompleted)
   at Renci.SshNet.Sftp.SftpFileStream.FlushWriteBuffer()
   at Renci.SshNet.Sftp.SftpFileStream.Dispose(Boolean disposing)
   at Renci.SshNet.Sftp.SftpFileStream.Finalize()```

After it presents the error above ShareX crashes.

When clicking "Test" when setting up the FTP (SSH) it says "Connected!"

```2015-05-17 03:54:49.300 - ShareX 9.10.1 started
2015-05-17 03:54:49.300 - Operating system: Microsoft Windows NT 6.3.9600.0
2015-05-17 03:54:49.300 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2015-05-17 03:54:49.300 - Personal path: E:\Documents\ShareX
2015-05-17 03:54:49.302 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-05-17 03:54:49.307 - ApplicationConfig load started: E:\Documents\ShareX\ApplicationConfig.json
2015-05-17 03:54:49.858 - ApplicationConfig load finished: E:\Documents\ShareX\ApplicationConfig.json
2015-05-17 03:54:49.863 - UploadersConfig load started: E:\Documents\ShareX\UploadersConfig.json
2015-05-17 03:54:49.863 - MainForm init started
2015-05-17 03:54:50.076 - UploadersConfig load finished: E:\Documents\ShareX\UploadersConfig.json
2015-05-17 03:54:50.077 - HotkeysConfig load started: E:\Documents\ShareX\HotkeysConfig.json
2015-05-17 03:54:50.105 - HotkeysConfig load finished: E:\Documents\ShareX\HotkeysConfig.json
2015-05-17 03:54:50.254 - MainForm init finished
2015-05-17 03:54:50.303 - Startup time: 1045 ms
2015-05-17 03:54:50.306 - CommandLine: silent
2015-05-17 03:54:50.325 - Hotkey registered: Hotkey: Alt + X, Description: Capture rectangle region, Job: RectangleRegion
2015-05-17 03:54:50.326 - Hotkey registered: Hotkey: Page Up, Description: Clipboard upload, Job: ClipboardUpload
2015-05-17 03:54:50.326 - Hotkey registered: Hotkey: Alt + C, Description: Capture active window, Job: ActiveWindow
2015-05-17 03:54:50.326 - Hotkey registered: Hotkey: Alt + F, Description: Drag and drop upload, Job: DragDropUpload
2015-05-17 03:54:50.327 - HotkeyManager started
2015-05-17 03:54:50.329 - WatchFolderManager started
2015-05-17 03:55:50.824 - ApplicationConfig save started: E:\Documents\ShareX\ApplicationConfig.json
2015-05-17 03:55:51.042 - ApplicationConfig save successful: E:\Documents\ShareX\ApplicationConfig.json
2015-05-17 03:55:56.114 - Hotkey unregistered: Hotkey: Alt + X, Description: Capture rectangle region, Job: RectangleRegion
2015-05-17 03:55:56.114 - Hotkey unregistered: Hotkey: Page Up, Description: Clipboard upload, Job: ClipboardUpload
2015-05-17 03:55:56.115 - Hotkey unregistered: Hotkey: Alt + C, Description: Capture active window, Job: ActiveWindow
2015-05-17 03:55:56.115 - Hotkey unregistered: Hotkey: Alt + F, Description: Drag and drop upload, Job: DragDropUpload
2015-05-17 03:55:56.128 - ApplicationConfig save started: E:\Documents\ShareX\ApplicationConfig.json
2015-05-17 03:55:56.214 - ApplicationConfig save successful: E:\Documents\ShareX\ApplicationConfig.json
2015-05-17 03:55:56.214 - UploadersConfig save started: E:\Documents\ShareX\UploadersConfig.json
2015-05-17 03:55:56.306 - UploadersConfig save successful: E:\Documents\ShareX\UploadersConfig.json
2015-05-17 03:55:56.306 - HotkeysConfig save started: E:\Documents\ShareX\HotkeysConfig.json
2015-05-17 03:55:56.377 - HotkeysConfig save successful: E:\Documents\ShareX\HotkeysConfig.json
2015-05-17 03:55:56.380 - ShareX closing```

**Comment by Jaex** [comment]
SFTP codes was not changed for more than year so I'm not sure how it can be to do with new version. Also error happens inside SFTP library which can be to do with library itself.

**Comment by chickenputty** [comment]
I haven't touched anything besides for updating. The update did freeze at 23%, but I installed ShareX again from getsharex.com. Would there be a better way of making sure my installation isn't corrupt?

**Comment by Jaex** [comment]
I haven't touched ftp and sftp stuffs too because I'm not using FTP at all. So for years its codes staying mainly same and only ftp library changing if there is update. And I can't do anything about if problem to do with library. But for verify you can try installing previous version.

**Comment by chickenputty** [comment]
I've tried installing previous versions and it persists.

**Comment by Jaex** [comment]
You told it was working before and it persists in previous version that means nothing to do with ShareX.

**Comment by chickenputty** [comment]
My SSH was working properly before with around 7,000 successful uploads. After updating I was presented with the error above. It seems a little weird that it would be magically my fault after updating ShareX. Issue 687 seems to be very similar to mine too.

**Comment by Jaex** [comment]
Issue 687 can't be similar to yours because it is using separate library and that issue was opened in previous release. If problem to do with new version then how you can explain to me that in previous version it is still not working? Did you checked your ftp settings for are there anything wrong?

**Comment by chickenputty** [comment]
When I use the "Test" button on ShareX it tells me "Connected!". I assume this means my settings are correct?

**Comment by Jaex** [comment]
Your login settings correct.

**Comment by chickenputty** [comment]
When I install old versions of ShareX, does that also revert the libraries?

**Comment by Jaex** [comment]
For make sure you can first uninstall then install.

**Comment by chickenputty** [comment]
I uninstalled and installed the latest version and the issue persists. Is there something in AppData that needs to be cleared?

**Comment by Jaex** [comment]
ShareX only using "Documents\ShareX" unless you changed it.

**Comment by chickenputty** [comment]
I'll uninstall, delete that folder, install, and reconfigure my FTP tomorrow to see if that works.

**Comment by chickenputty** [comment]
The error was caused from my VPS having no available hard drive space for the upload. I've deleted a few things and now everything is working great.

Thanks for the help!
