### ISSUE TITLE
When I tried to update this happened

### ISSUE THREAD

**Issue by SkierEthan** [ShareX/ShareX#695]
System.MissingMethodException: Method not found: 'Boolean ShareX.HelpersLib.UpdateMessageBox.get_DontShow()'.
   at ShareX.MainForm.CheckUpdate()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by Jaex** [comment]
That means it is corrupt and you need to reinstall.
