### ISSUE TITLE
I got error when using rectangle region capture

### ISSUE THREAD

**Issue by ysys923** [ShareX/ShareX#698]
here's the log

2015-05-18 21:23:12.619 - ShareX 9.10.1 started
2015-05-18 21:23:12.627 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-05-18 21:23:12.627 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2015-05-18 21:23:12.627 - Personal path: C:\Users\Luca\Documents\ShareX
2015-05-18 21:23:12.627 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-05-18 21:23:12.630 - ApplicationConfig load started: C:\Users\Luca\Documents\ShareX\ApplicationConfig.json
2015-05-18 21:23:13.097 - ApplicationConfig load finished: C:\Users\Luca\Documents\ShareX\ApplicationConfig.json
2015-05-18 21:23:13.099 - UploadersConfig load started: C:\Users\Luca\Documents\ShareX\UploadersConfig.json
2015-05-18 21:23:13.102 - Language changed to: English (United States)
2015-05-18 21:23:13.102 - MainForm init started
2015-05-18 21:23:13.245 - UploadersConfig load finished: C:\Users\Luca\Documents\ShareX\UploadersConfig.json
2015-05-18 21:23:13.245 - HotkeysConfig load started: C:\Users\Luca\Documents\ShareX\HotkeysConfig.json
2015-05-18 21:23:13.261 - HotkeysConfig load finished: C:\Users\Luca\Documents\ShareX\HotkeysConfig.json
2015-05-18 21:23:13.384 - MainForm init finished
2015-05-18 21:23:13.423 - Startup time: 841 ms
2015-05-18 21:23:13.454 - Hotkey registered: Hotkey: Print Screen, Description: Capture active monitor, Job: ActiveMonitor
2015-05-18 21:23:13.454 - Hotkey registered: Hotkey: Pause, Description: Capture active window, Job: ActiveWindow
2015-05-18 21:23:13.454 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-05-18 21:23:13.455 - HotkeyManager started
2015-05-18 21:23:13.457 - WatchFolderManager started
2015-05-18 21:23:16.292 - Hotkey triggered: Hotkey: Ctrl + Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-05-18 21:23:16.316 - Unhandled exception:
System.ArgumentException: Font 'Verdana' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at ShareX.ScreenCaptureLib.Surface..ctor()
   at ShareX.ScreenCaptureLib.RectangleRegion..ctor()
   at ShareX.MainForm.CaptureRegion(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2015-05-18 21:23:22.876 - ShareX continue.

**Comment by Jaex** [comment]
"System.ArgumentException: Font 'Verdana' does not support style 'Regular'."

This means your Windows don't have this font or it is corrupt. So it is to do with your Windows because all Windows have this font by default normally.

**Comment by ysys923** [comment]
thank you I just fixed it
to get font file on my laptop

**Comment by Jaex** [comment]
How your Windows was missing that font? I thought all Windows have it.
