### ISSUE TITLE
The cloud file provider is not running.

### ISSUE THREAD

**Issue by MurasakiZerozaki** [ShareX/ShareX#6993]
I'm using portable ver, Win 11, OneDrive uninstalled. It is showing when I open "Application Settings". I already tried to install setup version, it just crashing on startup.

System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ShareX.Program.ReadPersonalPathConfig()
   at ShareX.ApplicationSettingsForm.UpdateControls()
   at ShareX.ApplicationSettingsForm..ctor()
   at ShareX.MainForm.tsbApplicationSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 15.0 Portable

**Comment by MurasakiZerozaki** [comment]
EDIT. I downloaded OneDrive and turned it off forever. Somehow 15.0 version is demanding on cloud sync even in a portable ver.

**Comment by carloswm85** [comment]
I had this same exception. For whatever reason, ShareX requires to have OneDrive running. It seems to be an unnercessary requirement. I'd just leave that configuration up to the user to make one ShareX is running.
