### ISSUE TITLE
Upload errors

### ISSUE THREAD

**Issue by InnocentSet** [ShareX/ShareX#704]
Keep getting this whenever I try and upload a screenshot (to Imgur)
Message:
The underlying connection was closed: An unexpected error occurred on a send.

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
Are you using bit defender?

**Comment by InnocentSet** [comment]
No, I'm using AVG and this problem only started happening approximately 2 hours ago. I'll have a look and see if I can add an exception :D
