### ISSUE TITLE
Upload time with FTP is extremely slower

### ISSUE THREAD

**Issue by SirNickParks** [ShareX/ShareX#706]
After updating to the latest version a day ago, I noticed a very large increase in upload time using FTP. Looked in the logs and found this new error?

    2015-05-23 21:24:14.093 - Unhandled exception:
    System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
       at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
       at ShareX.HelpersLib.DebugForm.btnLoadedAssemblies_Click(Object sender, EventArgs e)
        at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
        at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
        at System.Windows.Forms.Control.WndProc(Message& m)
        at System.Windows.Forms.ButtonBase.WndProc(Message& m)
        at System.Windows.Forms.Button.WndProc(Message& m)
        at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Here is the difference in times:
Before: 
2015-05-18 19:51:05.831 - Task completed. Filename: hRZWK.png, URL: http://nkp.us/hRZWK.png, Duration: 2527 ms

After: 
2015-05-23 21:24:15.176 - Task completed. Filename: LbiKJ.png, URL: http://nkp.us/LbiKJ.png, Duration: 13109 ms

**Comment by Jaex** [comment]
Nothing changed in FTP codes for years and for months in FTP library so it is not possible for latest version to have different behavior than previous version. That error was to do with Loaded assemblies button in debug window.
