### ISSUE TITLE
Capture not being sent to clipboard.

### ISSUE THREAD

**Issue by jetdzhet** [ShareX/ShareX#7089]
Since new Windows 11 update (KB5030310) and I think a Net Framework update too, every time I want a capture to be sent to clipboard, it doesn't happen.

> 2023-09-26 23:35:57.955 - Clipboard copy image failed.:
> System.Runtime.InteropServices.ExternalException (0x800401D0): Error en la operación solicitada del Portapapeles.
>    en System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
>    en System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
>    en ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
>    en ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
>    en ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img, String fileName)

This is what I get in the log. Anything I can do?

**Comment by dhtdht020** [comment]
Experiencing this issue too.
```
2023-09-29 00:12:12.340 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img, String fileName)
2023-09-29 00:12:12.340 - Image copied to clipboard.
```

This happens very inconsistently (have been able to reproduce only a few times, and usually does not happen again immediately after failing).

This could be an issue with the new Windows 11 update in general (wouldn't be surprised if it is) but I haven't encountered this with any other software yet.

**Comment by yevheniy-solovey-ms** [comment]
Same for me.

2023-10-03 11:40:20.670 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img, String fileName)

**Comment by jetdzhet** [comment]
Well, I've found kind of a workaround for now until this bug is fixed. 

I right-clicked the ShareX system tray icon and checked both of these options in "After capture tasks" (make sure to uncheck "Copy image to clipboard" btw)

![firefox_exZVXVH02m](https://github.com/ShareX/ShareX/assets/64153911/05447a7e-e613-4459-b3fa-10d57077db8e)

It doesn't copy right directly to the clipboard since it saves a file and then copies that file to the clipboard, but it is essentially the same behavior I look for.

**Comment by yevheniy-solovey-ms** [comment]
@jetdzhet, thanks for the workaround, but it does not fully fit my needs. I usually need to annotate the screenshots, so it adds unnecessary steps.

**Comment by pilanwu** [comment]
> @jetdzhet, thanks for the workaround, but it does not fully fit my needs. I usually need to annotate the screenshots, so it adds unnecessary steps.


I understand you can annotating first, then capture, then send to to clipbrd.
I always use region capture, annotating before caputure

**Comment by rafitamolin** [comment]
Still happening as of today, it's driving me crazy

```2024-08-14 16:46:59.054 - Clipboard copy image failed.:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at ShareX.HelpersLib.ClipboardHelpers.CopyData(IDataObject data, Boolean copy)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImageDefaultFillBackground(Image img, Color background)
   at ShareX.HelpersLib.ClipboardHelpers.CopyImage(Image img, String fileName)```
