### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by samsterpiece** [ShareX/ShareX#7141]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://api.imgur.com/3/upload

Status code:
(429) Too Many Requests

Headers:
Connection: keep-alive
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1194
X-Post-Rate-Limit-Reset: 2864
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 2000
X-Ratelimit-Userremaining: 2000
X-Ratelimit-Userreset: 3600
X-Served-By: cache-nyc-kteb1890037-NYC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1699639180.201862,VS0,VE83
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 139
Content-Type: application/vnd.imgur.v1+json
Date: Fri, 10 Nov 2023 17:59:40 GMT
Server: cat factory 1.0

Response text:
{"errors":[{"id":"legacy-api-6956b57996-thsfn/5EI5xXOsPK-742769","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (429) Too Many Requests.

Request URL:
https://api.imgur.com/3/upload

Status code:
(429) Too Many Requests

Headers:
Connection: keep-alive
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1193
X-Post-Rate-Limit-Reset: 2863
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 2000
X-Ratelimit-Userremaining: 2000
X-Ratelimit-Userreset: 3600
X-Served-By: cache-nyc-kteb1890037-NYC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1699639181.290818,VS0,VE65
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 139
Content-Type: application/vnd.imgur.v1+json
Date: Fri, 10 Nov 2023 17:59:41 GMT
Server: cat factory 1.0

Response text:
{"errors":[{"id":"legacy-api-6956b57996-thsfn/5EI5xXOsPK-742793","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by inson1** [comment]
https://github.com/ShareX/ShareX/issues/6884
