### ISSUE TITLE
Cloudflare R2

### ISSUE THREAD

**Issue by mrkhachaturov** [ShareX/ShareX#7154]
Followed this [guide ](https://getsharex.com/docs/cloudflare-r2)

When tryign to upload screenshot getting this error: Specified value has invalid CRLF characters.

Error message:
Specified value has invalid CRLF characters.
Parameter name: value

Request URL:
https://rkcloud.xxxxyyyaaayyyyy.r2.cloudflarestorage.com/screenshots/ShareX_nOvwGbkOZQ.png

Stack trace:
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.WebHeaderCollection.Add(String name, String value)
   at System.Collections.Specialized.NameValueCollection.Add(NameValueCollection c)
   at ShareX.UploadersLib.RequestHelpers.CreateWebRequest(HttpMethod method, String url, NameValueCollection headers, CookieCollection cookies, String contentType, Int64 contentLength)
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

Upload to Amazon S3 failed.

**Comment by CubityFirst** [comment]
What is the file naming pattern that you are using under Task Settings > Upload > File Naming?

**Comment by mrkhachaturov** [comment]
> What is the file naming pattern that you are using under Task Settings > Upload > File Naming?
It is set by default 

Name pattern for capture or clipboard upload:
%ra{10}

Name pattern for windows captur:
%pn_%ra{10}

**Comment by mrkhachaturov** [comment]
![ShareX_JyOHs2hKvl](https://github.com/ShareX/ShareX/assets/105451445/98c05b40-1b1f-4837-a6af-5ade230c32c2)

**Comment by mrkhachaturov** [comment]
![image](https://github.com/ShareX/ShareX/assets/105451445/3495289d-82aa-40f2-90ac-b642e01520a1)

**Comment by mrkhachaturov** [comment]
The problem was with the custom domain. 
The same domain I am using locally in my Active Directory. So the problem was with the DNS.
