### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Lurking00** [ShareX/ShareX#7167]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: keep-alive
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Served-By: cache-dfw-kdfw8210098-DFW
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1701233195.316096,VS0,VE5099
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 147
Content-Type: application/vnd.imgur.v1+json
Date: Wed, 29 Nov 2023 04:46:40 GMT
Server: cat factory 1.0

Response text:
{"errors":[{"id":"legacy-api-85d6878748-csclv/b4Dp3oAOhW-415646","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: keep-alive
Imgur-Media-Type: imgur.v1; param=full; format=json
X-Served-By: cache-dfw-kdfw8210098-DFW
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1701233201.422935,VS0,VE40
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 147
Content-Type: application/vnd.imgur.v1+json
Date: Wed, 29 Nov 2023 04:46:41 GMT
Server: cat factory 1.0

Response text:
{"errors":[{"id":"legacy-api-85d6878748-csclv/b4Dp3oAOhW-415695","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by inson1** [comment]
https://github.com/ShareX/ShareX/issues/7141
