### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by Qwontifus** [ShareX/ShareX#717]
System.ArgumentException: Font 'Verdana' does not support style 'Bold'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style)
   at ShareX.ScreenCaptureLib.Surface..ctor()
   at ShareX.ScreenCaptureLib.RectangleRegion..ctor()
   at ShareX.MainForm.CaptureRegion(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

**Comment by Jaex** [comment]
Check here: #698
