### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by slavoryback** [ShareX/ShareX#7174]
System.Exception: Unsupported request format: JSON
   at ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

System.Exception: Unsupported request format: JSON
   at ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

**Comment by Tomloyo** [comment]
Can you atleast add a screenshot
