### ISSUE TITLE
HELP (FIXED)

### ISSUE THREAD

**Issue by titsologgy** [ShareX/ShareX#718]
System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at ShareX.HelpersLib.TaskbarManager.get_TaskbarList()
   at ShareX.HelpersLib.TaskbarManager.SetProgressState(IntPtr hwnd, TaskbarProgressBarStatus state)
   at ShareX.HelpersLib.TaskbarManager.<>c__DisplayClass5.<SetProgressState>b__4()
   at ShareX.HelpersLib.Extensions.InvokeSafe(Control control, Action action)
   at ShareX.HelpersLib.TaskbarManager.SetProgressState(Form form, TaskbarProgressBarStatus state)
   at ShareX.UploadTask.Prepare()
   at ShareX.UploadTask.Start()
   at ShareX.TaskManager.StartTasks()
   at ShareX.TaskManager.Start(UploadTask task)
   at ShareX.UploadManager.RunImageTask(Image img, TaskSettings taskSettings)
   at ShareX.MainForm.AfterCapture(Image img, CaptureType captureType, TaskSettings taskSettings)
   at ShareX.MainForm.DoCaptureWork(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.MainForm.DoCapture(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.MainForm.CaptureRegion(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.MainForm.CaptureScreenshot(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.MainForm.tsmiRectangle_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by titsologgy** [comment]
i have this error every time i try to make a screenshot

**Comment by Jaex** [comment]
What is your operating system? Try disabling http://i.imgur.com/WNjBgJH.png for workaround.

**Comment by titsologgy** [comment]
thanks you very much !

**Comment by Jaex** [comment]
Nothing fixed. It is not supposed to give error and I asked you question.

**Comment by titsologgy** [comment]
i have windows 7
