### ISSUE TITLE
ecdsa keys are not supported

### ISSUE THREAD

**Issue by xPaw** [ShareX/ShareX#719]
```
System.NotSupportedException: Key 'EC' is not supported.
   at Renci.SshNet.PrivateKeyFile.Open(Stream privateKey, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at ShareX.UploadersLib.FileUploaders.SFTP.Connect()
   at ShareX.UploadersLib.FileUploaders.SFTP.UploadStream(Stream stream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.SFTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)
```

**Comment by Jaex** [comment]
I think you should report it to SFTP library project: https://sshnet.codeplex.com/
