### ISSUE TITLE
Access to the path 'C:\Program Files\ShareX\PersonalPath.cfg' is denied.

### ISSUE THREAD

**Issue by CompuRoot** [ShareX/ShareX#72]
Fresh install, then run as standard user.
I suggest to use %AppData% to store configuration files.

```
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\ShareX\PersonalPath.cfg' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at ShareX.Program.WritePersonalPathConfig(String path)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

**Comment by GriffReborn** [comment]
I'm with CompuRoot on this one. Portability is of no concern to me.  What is more important is that non-administrative users can use the software without hinderance.  It would be nice to be able to choose where the preferences are stored as with Notepad++, for example, where you get to choose during setup.

**Comment by Jaex** [comment]
You can already use notepad to change it.

**Comment by GriffReborn** [comment]
Can you explain that further please?  Thanks!

**Comment by McoreD** [comment]
ShareX should look for a PersonalPath.cfg in Personal Folder first
%LocalAppData% first and if it does not exist there it may look for
PersonalPath.cfg in its startup path. By having PersonalPath.cfg only in
Program Files, it prevents other non-administrator users from modifying it
when ShareX is installed in Program Files by another administrator. Same
logic goes for IndexerDefault.css - we shall not have editable files in
Program Files.
