### ISSUE TITLE
"ShareX - Failed to save settings" popup after updating to latest version.

### ISSUE THREAD

**Issue by whamer100** [ShareX/ShareX#7224]
I decided to update after not doing so for a few years (from version 13.3.1 Beta to 15.0.2.298 Dev), mostly since I just forgot, and now every time I do something I get a popup saying "ShareX - Failed to save settings" with the message "Unable to remove the file to be replaced".

**Comment by whamer100** [comment]
I just checked the debug log, and it says the following:

```
2024-01-19 17:04:59.544 - Exception:
System.IO.IOException: Unable to remove the file to be replaced.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalReplace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at ShareX.HelpersLib.SettingsBase`1.SaveInternal(String filePath)
2024-01-19 17:04:59.618 - ApplicationConfig save failed: C:\Users\whamm\Documents\ShareX\ApplicationConfig.json
```

**Comment by whamer100** [comment]
Upon further inspection, it looks like its happening with every json file, for some reason.

**Comment by whamer100** [comment]
Unfortunately it looks like updating actually just straight up caused some sort of corruption/amalgamation of two versions of the configuration files. Ended up just reinstalling and manually reconfiguring back to the state I was in before.
