### ISSUE TITLE
Streamable - Screen capture uploads mostly failing

### ISSUE THREAD

**Issue by Jacksaur** [ShareX/ShareX#7234]
Out of nowhere yesterday, ShareX has started failing to upload video captures to Streamable. Small, few second recordings seem to work. And I can drag the saved file of failed recordings and upload it manually to Streamable myself with no complaints from the service. Log of the error is here:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.CheckUploadFilters(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Stream data, String fileName, Int32 retry)

Error message:
The remote server returned an error: (413) Request Entity Too Large.

Request URL:
https://api.streamable.com/upload

Status code:
(413) Request Entity Too Large

Headers:
Connection: keep-alive
X-Served-By: cache-lhr7331-LHR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1706292648.657663,VS0,VE3922
Vary: x-session
Strict-Transport-Security: max-age=300
Accept-Ranges: bytes
Content-Length: 183
Content-Type: text/html
Date: Fri, 26 Jan 2024 18:10:51 GMT
Server: nginx/1.18.0
Via: 1.1 varnish

Response text:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

I have a full Streamable account, and ShareX is connected to it. I've checked the credentials and they are correct.

**Comment by it0na72** [comment]
Having the same issue here. Looks like this only started recently because everything worked fine a couple of days ago.

**Comment by MrPositivity** [comment]
Same issue here, File is not too large because if I drag and drop this same file in Steemable website it uploads without problem, so no clue what is happening

**Comment by itzParty** [comment]
I just started to have the same issue as well, I wonder whats going on..

**Comment by coldlik** [comment]
same ✋

**Comment by Jaex** [comment]
@lawlmart can you check please.

**Comment by Archov** [comment]
+1, same issue, I know for a fact there's no issues with my upload size because I have Streamable pro which has no file size limits.

**Comment by TwoTonShoe** [comment]
Same issue here too, just started happening this last week. Same as MrPositivity said.. file not too large can manually upload to streamable's website just fine. My file was 7mb while streamables Free plan (signed in) stats up to 10 minute clips and 250mb.

seems like an API issue.

**Comment by ompuco** [comment]
Have also been experiencing this as it's part of my usual workflow.

I understand that uploading isn't supported officially by Streamable's public API, so any changes on their end wouldn't be documented. I'm curious how difficult it'll be to fix this since it's definitely the thing I use ShareX for the most.

**Comment by Jacksaur** [comment]
Issues seem to have been fixed, seems it was an issue on Streamable's end.
Videos of up to 300mb have been uploading successfully for me.  
If no one else has any problems anymore, I'll close the issue.
