### ISSUE TITLE
the cloud file provider is not running

### ISSUE THREAD

**Issue by NaniDaFuck** [ShareX/ShareX#7246]
System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ShareX.Program.ReadPersonalPathConfig()
   at ShareX.Program.UpdatePersonalPath()
   at ShareX.Program.Main(String[] args)

ShareX 15.0

**Comment by glego** [comment]
The identical error persists following a clean installation of Windows 11 and linking my OneDrive account.

**Comment by glego** [comment]
Alright, the solution can be found in issue #6993; just start OneDrive...

**Comment by NaniDaFuck** [comment]
ty it works fine
