### ISSUE TITLE
Video uploading problem

### ISSUE THREAD

**Issue by westor7** [ShareX/ShareX#725]
Message:
The remote name could not be resolved: 'pomf.se'

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

Debug log: http://pastebin.com/z0n3Ghu0

**Comment by Jaex** [comment]
In your computer dns can't resolve that domain it can be to do with your computer/internet or domain itself so nothing to do with ShareX.
