### ISSUE TITLE
Memory Overflow Problem after updating to ShareX 16.0.1

### ISSUE THREAD

**Issue by DavidJoacaRo** [ShareX/ShareX#7329]
After updating to the latest version, a memory overflow can occur for unknown reasons. After restart of the app, and attempting to take a screenshot, the issue persists.

![2024-03-17_13-53-40_Taskmgr](https://github.com/ShareX/ShareX/assets/32200281/972437af-c360-4cf7-ba64-6aaff0124b73)

**Comment by DavidJoacaRo** [comment]
The Issue still occurs after a clean restart, and opening the GUI. Closing the GUI will still take RAM in the background.


![2024-03-17 21-34-04](https://github.com/ShareX/ShareX/assets/32200281/fc11116d-7a2a-4ac9-afb3-aeb87ce33a7e)

**Comment by DavidJoacaRo** [comment]
The log file seems to be generating a bit too much data.
![image](https://github.com/ShareX/ShareX/assets/32200281/cb97d90d-d697-4a66-b836-4f9394fa0ab6)

**Comment by DasDunkel** [comment]
Can't do much with a screenshot of the log file's size, we're gonna need more info, like what's being spammed into the log file.

**Comment by DavidJoacaRo** [comment]
I've tried restarting Windows and reinstall ShareX, but the log file gets bigger, it is now 7 GB.

**Comment by DasDunkel** [comment]
https://github.com/zarunbal/LogExpert

**Comment by DavidJoacaRo** [comment]
> https://github.com/zarunbal/LogExpert

![image](https://github.com/ShareX/ShareX/assets/32200281/9c8ff3ad-f930-4dab-a720-1f84d7ae60e7)

**Comment by DasDunkel** [comment]
Try closing ShareX completely, delete the large log file, then re-open ShareX briefly until it gets to something more reasonable like 500MB, then try viewing it

**Comment by DavidJoacaRo** [comment]
> Try closing ShareX completely, delete the large log file, then re-open ShareX briefly until it gets to something more reasonable like 500MB, then try viewing it

![image](https://github.com/ShareX/ShareX/assets/32200281/7789f888-ede5-45de-afe9-ef9f998d9ffa)

**Comment by DasDunkel** [comment]
Ah, windows defender might be blocking ShareX from accessing certain files;

Open the Windows Defender Security Center.
Browse to Virus & threat protection > Virus & threat protection settings > Manage Controlled folder access > Allow an app through Controlled folder access.
Press "Add an allowed app".
Browse to where ShareX is stored. (usually C:\Program Files (x86)\ShareX or C:\Program Files (x86)\Steam\steamapps\common\ShareX\ShareX)
Select ShareX.exe and press Open.
Approve the UAC prompt, if any.
Restart ShareX completely.

**Comment by DavidJoacaRo** [comment]
> Ah, windows defender might be blocking ShareX from accessing certain files;
> 
> Open the Windows Defender Security Center. Browse to Virus & threat protection > Virus & threat protection settings > Manage Controlled folder access > Allow an app through Controlled folder access. Press "Add an allowed app". Browse to where ShareX is stored. (usually C:\Program Files (x86)\ShareX or C:\Program Files (x86)\Steam\steamapps\common\ShareX\ShareX) Select ShareX.exe and press Open. Approve the UAC prompt, if any. Restart ShareX completely.

![image](https://github.com/ShareX/ShareX/assets/32200281/e30c80ed-2e85-4aaf-bbac-3adf8581254b)


I have done the steps you've said above and the issue persists.

**Comment by DavidJoacaRo** [comment]
> Do you have any other sort of antivirus? Or anything else that could be blocking ShareX's access to things? If yes, you may also need to add an exception for ShareX in them.
> 
> Is your OS up to date?
> 
> Does the issue persist if you downgrade to [V15](https://github.com/ShareX/ShareX/releases/tag/v15.0.0)?

I have tried completely disabling any firewall & antivirus, no fix.

I'm running Windows 10 Pro (Build 19045.4170)

The issue does not persist when downgrading to V15

**Comment by Jaex** [comment]
I fixed the memory related issue now which was caused by non stop trying to recreate named pipes on failure.

But I cannot fix that it is unable to create named pipes because something in your pc blocking/not allowing it.

So ShareX single instance support not gonna work in your pc if you can't find what is blocking it. Which is used for Windows Explorer or browser right click upload for example.

**Comment by zejjnt** [comment]
I have the same exact problem, and the pipe issue as well. ShareX spits an error about this about 45 times **every millisecond**.
I am using the dev build as instructed.
Relevant initial part of log;

`2024-03-27 14:17:15.651 - ShareX starting.
2024-03-27 14:17:15.652 - Version: 16.0.2.348 Dev
2024-03-27 14:17:15.653 - Build: Release
2024-03-27 14:17:15.653 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2024-03-27 14:17:15.653 - Personal path: C:\Users\timrag01\Documents\ShareX
2024-03-27 14:17:15.653 - Operating system: Windows 10 Pro (64-bit)
2024-03-27 14:17:15.654 - Running as elevated process: False
2024-03-27 14:17:15.675 - Exception:
System.IO.IOException: All pipe instances are busy.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeServerStream.Create(String fullPipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeAccessRights rights, SECURITY_ATTRIBUTES secAttrs)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
   at ShareX.HelpersLib.SingleInstanceManager.<ListenForConnectionsAsync>d__26.MoveNext()
2024-03-27 14:17:15.675 - Exception:
System.IO.IOException: All pipe instances are busy.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeServerStream.Create(String fullPipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeAccessRights rights, SECURITY_ATTRIBUTES secAttrs)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
   at ShareX.HelpersLib.SingleInstanceManager.<ListenForConnectionsAsync>d__26.MoveNext()
2024-03-27 14:17:15.675 - Exception:
System.IO.IOException: All pipe instances are busy.`

the remaining ~4 GB is just the IOException message repeated until everything again ran out of memory and I closed Sharex;

`2024-03-27 14:48:41.277 - Exception:
System.IO.IOException: All pipe instances are busy.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeServerStream.Create(String fullPipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeAccessRights rights, SECURITY_ATTRIBUTES secAttrs)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
   at ShareX.HelpersLib.SingleInstanceManager.<ListenForConnectionsAsync>d__26.MoveNext()
2024-03-27 15:05:44.844 - Hotkey unregistered: Hotkey: Ctrl + Shift + Print Screen, Description: Capture region, Job: RectangleRegion
2024-03-27 15:05:44.844 - Hotkey unregistered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2024-03-27 15:05:44.844 - Hotkey unregistered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2024-03-27 15:05:44.878 - ShareX closing.
2024-03-27 15:05:44.879 - ApplicationConfig save started: C:\Users\timrag01\Documents\ShareX\ApplicationConfig.json
2024-03-27 15:05:45.052 - ApplicationConfig save successful: C:\Users\timrag01\Documents\ShareX\ApplicationConfig.json
2024-03-27 15:05:45.052 - UploadersConfig save started: C:\Users\timrag01\Documents\ShareX\UploadersConfig.json
2024-03-27 15:05:45.191 - UploadersConfig save successful: C:\Users\timrag01\Documents\ShareX\UploadersConfig.json
2024-03-27 15:05:45.191 - HotkeysConfig save started: C:\Users\timrag01\Documents\ShareX\HotkeysConfig.json
2024-03-27 15:05:45.216 - HotkeysConfig save successful: C:\Users\timrag01\Documents\ShareX\HotkeysConfig.json
2024-03-27 15:05:45.216 - ShareX closed.
2024-03-27 15:54:27.224 - ShareX starting.`

Is there any way I can find what might be using said pipes?

**Comment by Jaex** [comment]
@zejjnt try latest dev build please, it should only output error once now.

**Comment by zejjnt** [comment]
> @zejjnt try latest dev build please, it should only output error once now.

So far so good! I'll keep testing from tuesday and onwards (after easter, it's the work laptop)
