### ISSUE TITLE
(Large) scrolling capture App crashed

### ISSUE THREAD

**Issue by WimSubzero** [ShareX/ShareX#7366]
Hi,

I tried to capture the folliwing web page : https://www.vkernel.ro/blog/clustering-active-directory-certificate-services-ad-cs

this resluted in 
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.HelpersLib.ImageHelpers.SavePNG(Image img, Stream stream, PNGBitDepth bitDepth)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   at ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 16.0.1

LOg file entry:

2024-03-28 18:08:06.010 - ShareX starting.
2024-03-28 18:08:06.010 - Version: 16.0.1
2024-03-28 18:08:06.010 - Build: Release
2024-03-28 18:08:06.011 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2024-03-28 18:08:06.011 - Personal path: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX
2024-03-28 18:08:06.012 - Operating system: Windows 10 Pro (64-bit)
2024-03-28 18:08:06.012 - Running as elevated process: False
2024-03-28 18:08:06.231 - ApplicationConfig load started: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\ApplicationConfig.json
2024-03-28 18:08:07.015 - ApplicationConfig load finished: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\ApplicationConfig.json
2024-03-28 18:08:07.021 - UploadersConfig load started: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\UploadersConfig.json
2024-03-28 18:08:07.029 - MainForm init started.
2024-03-28 18:08:07.287 - UploadersConfig load finished: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\UploadersConfig.json
2024-03-28 18:08:07.290 - HotkeysConfig load started: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\HotkeysConfig.json
2024-03-28 18:08:07.617 - HotkeysConfig load finished: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\HotkeysConfig.json
2024-03-28 18:08:07.660 - MainForm init finished.
2024-03-28 18:08:07.866 - Startup time: 1884 ms
2024-03-28 18:08:07.934 - Unable to register hotkey: Ctrl + Print Screen
2024-03-28 18:08:07.934 - Hotkey register failed: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2024-03-28 18:08:07.935 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2024-03-28 18:08:07.935 - Unable to register hotkey: Alt + Print Screen
2024-03-28 18:08:07.935 - Hotkey register failed: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2024-03-28 18:08:07.935 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2024-03-28 18:08:07.936 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2024-03-28 18:08:16.466 - HotkeyManager started.
2024-03-28 18:08:16.468 - WatchFolderManager started.
2024-03-28 18:11:10.821 - Task in queue. Job: Job, Type: Image, Host: 
2024-03-28 18:11:10.948 - Task status: Preparing
2024-03-28 18:11:11.966 - Image copied to clipboard.
2024-03-28 18:11:11.997 - Unhandled exception:
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.HelpersLib.ImageHelpers.SavePNG(Image img, Stream stream, PNGBitDepth bitDepth)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
   at ShareX.TaskHelpers.PrepareImage(Image img, TaskSettings taskSettings)
   at ShareX.WorkerTask.DoAfterCaptureJobs()
   at ShareX.WorkerTask.DoThreadJob()
   at ShareX.WorkerTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

ShareX 16.0.1
2024-03-28 18:11:22.197 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2024-03-28 18:13:11.308 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2024-03-28 18:16:18.806 - File opened: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\Logs\ShareX-Log-2024-03.txt
2024-03-28 18:16:57.347 - ShareX continue.
2024-03-28 18:17:35.775 - ShareX starting.
2024-03-28 18:17:35.775 - Version: 16.0.1
2024-03-28 18:17:35.775 - Build: Release
2024-03-28 18:17:35.776 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2024-03-28 18:17:35.776 - Personal path: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX
2024-03-28 18:17:35.777 - Operating system: Windows 10 Pro (64-bit)
2024-03-28 18:17:35.777 - Running as elevated process: False
2024-03-28 18:17:35.805 - ApplicationConfig load started: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\ApplicationConfig.json
2024-03-28 18:17:36.273 - ApplicationConfig load finished: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\ApplicationConfig.json
2024-03-28 18:17:36.278 - UploadersConfig load started: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\UploadersConfig.json
2024-03-28 18:17:36.286 - MainForm init started.
2024-03-28 18:17:36.385 - UploadersConfig load finished: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\UploadersConfig.json
2024-03-28 18:17:36.386 - HotkeysConfig load started: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\HotkeysConfig.json
2024-03-28 18:17:36.496 - HotkeysConfig load finished: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\HotkeysConfig.json
2024-03-28 18:17:36.715 - MainForm init finished.
2024-03-28 18:17:36.903 - Startup time: 1156 ms
2024-03-28 18:17:36.952 - Unable to register hotkey: Ctrl + Print Screen
2024-03-28 18:17:36.953 - Hotkey register failed: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2024-03-28 18:17:36.953 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2024-03-28 18:17:36.953 - Unable to register hotkey: Alt + Print Screen
2024-03-28 18:17:36.953 - Hotkey register failed: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2024-03-28 18:17:36.953 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2024-03-28 18:17:36.953 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
2024-03-28 18:17:39.283 - HotkeyManager started.
2024-03-28 18:17:39.284 - WatchFolderManager started.
2024-03-28 18:17:51.227 - Folder opened: C:\Users\WimMintiens\OneDrive - The Key 2 IT\Documents\ShareX\Screenshots\

**Comment by Jaex** [comment]
Looks like it is not possible to save that large images:
https://stackoverflow.com/questions/41876659/net-saving-very-large-images

But it must not crash ShareX, so I will fix that.

**Comment by mangkoran** [comment]
I still encounter this issue. The scrolling capture dimension is 1248 x 71280.

![image](https://github.com/user-attachments/assets/ea3ff604-9206-4010-8b0a-4837b0e81346)

Error log
```
2024-11-20 17:43:20.274 - Exception:
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ShareX.HelpersLib.ImageHelpers.SavePNG(Image img, Stream stream, PNGBitDepth bitDepth)
   at ShareX.TaskHelpers.SaveImageAsStream(Image img, EImageFormat imageFormat, PNGBitDepth pngBitDepth, Int32 jpegQuality, GIFQuality gifQuality)
2024-11-20 17:43:21.730 - Image saved to file: C:\Users\mangkoran\Documents\ShareX\Screenshots\2024-11\QVL6eecOFF.png
2024-11-20 17:43:21.861 - Task completed. File name: QVL6eecOFF.png, Duration: 2372 ms
```

Do note that the file is not created.
