### ISSUE TITLE
Could not send picture to imgur.com

### ISSUE THREAD

**Issue by Nosthertus** [ShareX/ShareX#743]
Error: log
Message:
```
The remote name could not be resolved: 'api.imgur.com'

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

i was selecting a rectangle frame to send.

**Comment by Jaex** [comment]
DNS server can't resolve imgur domain so it is completely not to do with ShareX.
