### ISSUE TITLE
attempting to upload to sharex

### ISSUE THREAD

**Issue by BigTizle** [ShareX/ShareX#7444]
Error message:
The remote server returned an error: (504) Gateway Timeout.

Request URL:
https://up.flickr.com/services/upload/

Status code:
(504) Gateway Time-out

Headers:
Connection: keep-alive
X-Cache: Error from cloudfront
X-Amz-Cf-Pop: JFK52-P2
X-Amz-Cf-Id: zBBt-uFEIzvAXi0YY4btUfyWHJn8zgBhdWCIjrMfgZFFu44m8-GpMQ==
Content-Length: 1033
Content-Type: text/html
Date: Mon, 13 May 2024 16:43:29 GMT
Server: CloudFront
Via: 1.1 11280d8f37ba4cb1d8f36f9f2a6e4c76.cloudfront.net (CloudFront)

Response text:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: zBBt-uFEIzvAXi0YY4btUfyWHJn8zgBhdWCIjrMfgZFFu44m8-GpMQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by MaxDesignFR** [comment]
I do also have this issue with `https://vgy.me/upload` for a recent while. Gif screen recordings, even small, tend to fail most times.

```
Error message:
Le serveur distant a retourné une erreur : (504) Dépassement du délai de la passerelle.

Request URL:
https://vgy.me/upload

Status code:
(504) Gateway Time-out

Headers:
Connection: keep-alive
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=bNyK4ox0FCOOnJRPIRyrmv7PhZh75tNmAfw6PZ6yv6xbSxPsIbDP32NkBys4KAPtza%2BpUNbXkBKLbjpd%2BADHXx9vf1vEES4bhVJjTHs0gM6SzqL2dKmTXyUe3hcIhn6NuwSWkeo%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Strict-Transport-Security: max-age=2592000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
Referrer-Policy: same-origin
CF-RAY: 883bb2e39bded357-CDG
alt-svc: h3=":443"; ma=86400
Content-Length: 15
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/plain; charset=UTF-8
Date: Tue, 14 May 2024 14:51:07 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Server: cloudflare

Response text:
error code: 504

Stack trace:
   à System.Net.HttpWebRequest.GetResponse()
   à ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
   ```
