### ISSUE TITLE
Cannot upload files on s-ul - 403 Forbidden - Generic server error

### ISSUE THREAD

**Issue by Skubers** [ShareX/ShareX#7489]
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://s-ul.eu/api/v1/upload

Status code:
(403) Forbidden

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Content-Type: application/json
Date: Mon, 10 Jun 2024 14:59:08 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Set-Cookie: s-ul=ru6vfftk67nmg84begncq8tk3d; expires=Mon, 10 Jun 2024 15:59:08 GMT; Max-Age=3600; path=/
Server: nginx/1.27.0

Response text:
{"success":false,"reason":"Generic server error, please contact support@s-ul.eu if this message persists. Error code: 110"}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
   
   [ShareX-Log-2024-06.txt](https://github.com/user-attachments/files/15775265/ShareX-Log-2024-06.txt)

**Comment by Skubers** [comment]
I did try refreshing my API key and it didn't work
