### ISSUE TITLE
Imgur upload broken?

### ISSUE THREAD

**Issue by Slind14** [ShareX/ShareX#749]
Hey,

since yesterday same time I'm getting this exception whenever I try to upload something

```
Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
```

I checked the authentication and it returns login success. There are also no imgur api issues reported: http://status.api.imgur.com/

**Comment by Jaex** [comment]
Not to do with ShareX.

**Comment by Slind14** [comment]
imgur server issue?

**Comment by Jaex** [comment]
Yes.
