### ISSUE TITLE
Error message: The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by VeinsWorld** [ShareX/ShareX#7515]
Error message:
The underlying connection was closed: An unexpected error occurred on a send.

Request URL:
https://guns.lol/api/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by L2K-CRASHOUT** [comment]
did u fix this?

**Comment by Port770** [comment]
nope

**Comment by Port770** [comment]
> did u fix this?

nope
