### ISSUE TITLE
WEBM to H264,MP4  or Others Conversion Error

### ISSUE THREAD

**Issue by aranjeevdev** [ShareX/ShareX#7521]
ShareX crashes with this Error on Window 11 Pro with the following Error when converting WEBM file to  H264 or other format.

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Value
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at ShareX.MediaLib.VideoConverterForm.Manager_EncodeProgressChanged(Single percentage)
   at ShareX.MediaLib.FFmpegCLIManager.UpdateEncodeProgress(String data)
   at ShareX.MediaLib.FFmpegCLIManager.FFmpeg_DataReceived(Object sender, DataReceivedEventArgs e)
   at ShareX.HelpersLib.ExternalCLIManager.cli_ErrorDataReceived(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

ShareX 16.1
![Error Screenshot 2024-07-08](https://github.com/ShareX/ShareX/assets/36615840/1b339de3-1d61-4868-90c9-c8125489ebb3)

**Comment by Jaex** [comment]
I cannot reproduce it:

![](https://jaex.getsharex.com/2024/07/ShareX_vtW8PJn4Pg.png)
