### ISSUE TITLE
The cloud file provider is not running. Windows 11

### ISSUE THREAD

**Issue by dboles99** [ShareX/ShareX#7522]
No matter what version I try to use, windows 11 produces an error as below.

System.IO.IOException: The cloud file provider is not running.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at ShareX.Program.ReadPersonalPathConfig()
   at ShareX.Program.UpdatePersonalPath()
   at ShareX.Program.Main(String[] args)

ShareX 16.1

**Comment by DrPPD-GH** [comment]
I got same error. It was resolved when I launched and logged into onedrive, and then ran shareex again.

**Comment by PaciFrisk-Dreemurr** [comment]
This error is also occurring in Windows 10 Home Edition. It seems to regain functionality when OneDrive is completely loaded in.
