### ISSUE TITLE
dont realy know the issue but here is error log

### ISSUE THREAD

**Issue by IXSENPA1XI** [ShareX/ShareX#7568]
X-Served-By: cache-chi-kigq8000120-CHI
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1723885944.570236,VS0,VE19265
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Frame-Options: DENY
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
Accept-Ranges: bytes
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Sat, 17 Aug 2024 09:12:42 GMT
Server: cat factory 1.0

Response text:
{"status":413,"success":false,"data":{"error":"file is over the size limit","request":"/3/upload","method":"POST"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by IXSENPA1XI** [comment]
occors when uploading

**Comment by L1Q** [comment]
it says it right there: "file is over the size limit"
