### ISSUE TITLE
arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by cblackbu** [ShareX/ShareX#7610]
Hi Guys,

I got this error on Windows 11 x64 23H2:
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Microsoft.Win32.SystemEvents.GetUserPreferenceCategory(Int32 msg, IntPtr wParam, IntPtr lParam)
   at Microsoft.Win32.SystemEvents.OnUserPreferenceChanging(Int32 msg, IntPtr wParam, IntPtr lParam)
   at Microsoft.Win32.SystemEvents.WindowProc(IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 16.1

**Comment by dustyshaw** [comment]
@cblackbu can you describe what steps you took for this issue to occur?

**Comment by cblackbu** [comment]
Hi Dusty,

I’m sorry I’m not sure exactly what I was doing.  I typically capture regions, edit the screenshots, add boxes, arrows, sometimes step #’s, and quotes.  In my mind I wasn’t doing anything I hadn’t done before without it crashing, but that doesn’t mean I didn’t try something in a new order.
