### ISSUE TITLE
File uploading on Mega not working

### ISSUE THREAD

**Issue by Sushubh** [ShareX/ShareX#762]
It used to work in the past. Connection is ok. Error: 

```
System.NotSupportedException: Stream must be fully read to obtain computed FileMac
   at CG.Web.MegaApiClient.MegaAesCtrStreamCrypter.get_MetaMac()
   at CG.Web.MegaApiClient.MegaApiClient.Upload(Stream stream, String name, INode parent)
   at ShareX.UploadersLib.FileUploaders.Mega.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

Message:
The remote name could not be resolved: 'gfs262n157.userstorage.mega.co.nz'

StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
```

**Comment by Scrxtchy** [comment]
Your end, fix your dns

https://mega.co.nz/#!RxRQHZpL!64vrPLDQ2BnNs3XzMwiGIm8Ca_kVClXPYDAKypaaf74

**Comment by Sushubh** [comment]
Right. Looks like it was either an ISP issue or Mega was having issues at the time. It works now. Thanks.

**Comment by Jaex** [comment]
Yes dns errors in your end.
