### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by shuzz22** [ShareX/ShareX#7658]
Error message:
The underlying connection was closed: An unexpected error occurred on a send.

Request URL:
https://kappa.lol/api/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
 
 
   what to do?

**Comment by evgenkotta** [comment]
Did you figure it out?
