### ISSUE TITLE
File Destination: Google Drive Error - 403 Forbidden (Missing scope: google.apps.drive.v3.DriveFiles.Create)

### ISSUE THREAD

**Issue by ronindesign** [ShareX/ShareX#7681]
After configuring Google Drive destination for file upload, when attempting to upload, a 403 Forbidden error is returned from the Google Drive API service.

It appears Google Drive API scope requirements may have changed and now there is a scope requirement to initially create a file before uploading it.

It would seem the current authorization scoped requested by the OAuth flow need to be updated to accommodate the missing scope:
`google.apps.drive.v3.DriveFiles.Create`

Google Drive API Service Error Response:
```json
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Insufficient Permission",
        "domain": "global",
        "reason": "insufficientPermissions"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.apps.drive.v3.DriveFiles.Create",
          "service": "drive.googleapis.com"
        }
      }
    ]
  }
}
```

Reproduce:
- Configure Google Drive file upload destination via OAuth using Google Account
- Debug > Test file upload

Result: Test file upload errors with `The remote server returned an error: (403) Forbidden.`

Debug Log:
```
2024-11-14 12:14:27.835 - Task failed. File name: Ql0vfz9z3l.png, Errors:
Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink,webContentLink&supportsAllDrives=true

Status code:
(403) Forbidden

Headers:
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
X-GUploader-UploadID: AHmUCY1bsrKnGAUsdZrnszXdBWg6JYVmVuZw0zVVHKF0Mqzy2pMlLBe2l-7HKR7PpQPQM3uXqLg
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Length: 623
Content-Type: application/json; charset=UTF-8
Date: Thu, 14 Nov 2024 20:14:27 GMT
Server: ESF
WWW-Authenticate: Bearer realm="https://accounts.google.com/", error="insufficient_scope", scope="https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive.appfolder https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/drive.resource"

Response text:
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Insufficient Permission",
        "domain": "global",
        "reason": "insufficientPermissions"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.apps.drive.v3.DriveFiles.Create",
          "service": "drive.googleapis.com"
        }
      }
    ]
  }
}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by ronindesign** [comment]
My mistake was failing to manually check the checkbox to allow Google Drive permissions when authorizing via the Google OAuth flow .
