### ISSUE TITLE
Dropbox upload error: "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server."

### ISSUE THREAD

**Issue by vavavr00m** [ShareX/ShareX#773]
Been uploading since  2015-07-07 19:43:28.850 Out of 99 files uploaded, only one file screwed up. The next parts after that were uploaded successfully.

2015-07-07 23:21:21.711 - Task status: Preparing
2015-07-07 23:21:21.810 - Upload started. Filename: xxx.part102.rar, Filepath: C:\Users\admin\Desktop\Filedrop\xxx.part102.rar
2015-07-07 23:24:05.291 - AddWebError(): Message:
The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)
2015-07-07 23:24:05.361 - Task failed. Filename: xxx.part102.rar, Errors:
Message:
The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.

**Comment by Jaex** [comment]
"closed by the server."

I don't think it is to do with ShareX.
