### ISSUE TITLE
Box.com upload failes: Refresh token has expired

### ISSUE THREAD

**Issue by Robinjoeh** [ShareX/ShareX#774]
When selecting and using Box.com as upload server, you must manually obtain an auth_token, as when it tries to use the refresh_token, it says it is expired already.. Check the log below.

Is it really needed to re-auth to Box.com every time you want to use ShareX (like once per day)?

2015-07-07 13:02:14.185 - ShareX 10.0 started
2015-07-07 13:02:14.186 - Operating system: Microsoft Windows NT 6.3.9600.0
2015-07-07 13:02:14.186 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2015-07-07 13:02:14.186 - Personal path: C:\Users\User\Documents\ShareX
2015-07-07 13:02:14.186 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-07-07 13:02:14.189 - ApplicationConfig load started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2015-07-07 13:02:14.833 - ApplicationConfig load finished: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2015-07-07 13:02:14.842 - UploadersConfig load started: C:\Users\User\Documents\ShareX\UploadersConfig.json
2015-07-07 13:02:14.853 - Language changed to: English (United States)
2015-07-07 13:02:14.853 - MainForm init started
2015-07-07 13:02:15.002 - UploadersConfig load finished: C:\Users\User\Documents\ShareX\UploadersConfig.json
2015-07-07 13:02:15.002 - HotkeysConfig load started: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2015-07-07 13:02:15.034 - HotkeysConfig load finished: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2015-07-07 13:02:15.204 - MainForm init finished
2015-07-07 13:02:15.242 - Startup time: 1119 ms
2015-07-07 13:02:15.243 - CommandLine: silent
2015-07-07 13:02:15.254 - Hotkey registered: Hotkey: Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-07-07 13:02:15.255 - HotkeyManager started
2015-07-07 13:02:15.257 - WatchFolderManager started
2015-07-07 17:06:42.317 - Hotkey triggered: Hotkey: Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-07-07 17:06:44.346 - Task in queue. Job: Job, Type: File, Host: Box
2015-07-07 17:06:44.355 - Task status: Preparing
2015-07-07 17:06:49.091 - Upload started. Filename: 2015-07-07_17-06-44.png
2015-07-07 17:06:50.583 - AddWebError(): Message:
The remote server returned an error: (400) Bad Request.

Response:
{"error":"invalid_grant","error_description":"Refresh token has expired"}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
2015-07-07 17:06:50.603 - Task failed. Filename: 2015-07-07_17-06-44.png, Errors:
Message:
The remote server returned an error: (400) Bad Request.

Response:
{"error":"invalid_grant","error_description":"Refresh token has expired"}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

Refresh access token failed.
2015-07-07 19:44:46.441 - Hotkey triggered: Hotkey: Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-07-07 21:33:43.580 - Hotkey triggered: Hotkey: Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-07-07 21:33:44.834 - Task in queue. Job: Job, Type: File, Host: Box
2015-07-07 21:33:44.834 - Task status: Preparing
2015-07-07 21:34:09.658 - Task completed. Filename: 2015-07-07_21-33-44.bmp, URL: , Duration: 24823 ms
2015-07-07 21:44:35.878 - Hotkey triggered: Hotkey: Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-07-07 22:43:57.201 - Hotkey triggered: Hotkey: Print Screen, Description: Capture rectangle region, Job: RectangleRegion
2015-07-07 22:43:58.008 - Task in queue. Job: Job, Type: File, Host: Box
2015-07-07 22:43:58.008 - Task status: Preparing
2015-07-07 22:43:59.137 - Upload started. Filename: 2015-07-07_22-43-58.png
2015-07-07 22:44:00.828 - AddWebError(): Message:
The remote server returned an error: (400) Bad Request.

Response:
{"error":"invalid_grant","error_description":"Invalid refresh token"}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)
2015-07-07 22:44:00.828 - Task failed. Filename: 2015-07-07_22-43-58.png, Errors:
Message:
The remote server returned an error: (400) Bad Request.

Response:
{"error":"invalid_grant","error_description":"Invalid refresh token"}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(String url, Stream dataStream, String boundary, String contentType, NameValueCollection headers, CookieCollection cookies, HttpMethod method)

Refresh access token failed.

**Comment by Jaex** [comment]
They made their authentication expire so if it is expired need to refresh it with refresh token. How it can be invalid refresh token no idea. I'm using Box now and it never tells invalid refresh token to me. I mean how the hell refresh token expires too. How am i supposed to program ShareX now? Majority of uploaders using same OAuth codes in ShareX and properly refresh so this problem even can be in their side.

**Comment by Jaex** [comment]
Hmm there is one more possibility, UploadersConfig saves when ShareX closing and when your pc shutdown ShareX could be unable to save because your Windows terminate it early. That way your new refresh tokens not saving and this problem happens. There is nothing I can do prevent Windows terminating ShareX early in this situation because normally it needed to wait until it close so I'm not sure how it happens for some people. I think some people have config to shutdown Windows faster which causing this.

**Comment by Robinjoeh** [comment]
Is there anything I can do on my end to fix this then? It is very annoying to auth to Box.com every day.... :( And wouldn't it be possible for you to save the refresh_token before Windows exits? (maybe after each file upload?)

**Comment by Jaex** [comment]
I was saving application settings when ShareX window minimize to tray maybe i should also save uploaders and hotkeys config too there. That way it would be more likely to get it saved.

**Comment by Robinjoeh** [comment]
If you can, that would be soooo awesome. I have been refreshing my auth now every day for a few weeks... Getting tired of it :)

Thanks for your quick answers and support.

When do you think it is solved?

**Comment by Jaex** [comment]
But it is not still permanent solution too. I mean if you don't minimize ShareX to tray after last token refreshing and if while shutdown if your Windows terminate ShareX before it can save settings then again same problem can happen.

**Comment by Robinjoeh** [comment]
Strange... Can the problem be that I'm using a SSD which turns the computer off very quickly?

**Comment by Jaex** [comment]
I'm using SSD too.

**Comment by Robinjoeh** [comment]
Ah, strange... But I do always minimize Sharex to tray, so that wouldnt be a problem - at least not for me. But why wouldn't it work to save the refresh_token after each upload instead? Wouldn't that be better? Then you won't have any issues to worry about when the application exits?

**Comment by Jaex** [comment]
I didn't wanted to save so frequently like if you are uploading very small many files it will save non stop every second.

**Comment by Robinjoeh** [comment]
Ah, I understand... Makes sense. But you can just check the upload queue, if it is empty = save refresh_token? That way, it would only be saved after the last upload if you choose to upload 100 files at once.

Or, if you can think of some manual fix for me, I would be more than happy to change some settings on my Windows or ShareX in order to fix this :)

Thanks again!

**Comment by Jaex** [comment]
Also people can do just captures without upload and do rapid captures like every second and because it is only single task it will try to save every second again.

**Comment by Robinjoeh** [comment]
Yes but  you wont need to update it if there is no upload made?

But no matter what, is there any rule or something I can add to Windows once it closes down? So that ShareX saves everything it has to save? That would probably be the fastest fix :)

**Comment by Jaex** [comment]
I still didn't figured out why save fails when Windows shut down in some people computer.

**Comment by Robinjoeh** [comment]
Ah, can I do something to help you out there maybe? I'd love to, it is a beautiful software that you have created. If I can contribute I'd love to.

**Comment by Jaex** [comment]
Maybe I should make issue #702 stay open and someone could have solution to it.

For now if you really want to make sure your settings save then you can close ShareX manually before shutdown.

I will also add minimize to tray save uploaders config too for increase chance your config get saved.

**Comment by Jaex** [comment]
Closing this issue because reopened other issue.
