### ISSUE TITLE
"Could not load file or assembly 'MegaApiClient'

### ISSUE THREAD

**Issue by ktdd** [ShareX/ShareX#776]
Can't access Destinations or Task settings, instantly get a popup with the following error message:

System.BadImageFormatException: Could not load file or assembly 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2'
   at ShareX.UploadersLib.UploadersConfig.IsValid(FileDestination destination)
   at ShareX.MainForm.EnableDisableToolStripMenuItems[T](ToolStripDropDownItem[] parents)
   at ShareX.MainForm.UpdateDestinationStates()
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownButton.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ktdd** [comment]
Uninstalling and cleaning registry finally worked, regular uninstall didn't. Closing this.
