### ISSUE TITLE
System.Net.FtpClient.FtpCommandException: Could not create socket.

### ISSUE THREAD

**Issue by pilovali** [ShareX/ShareX#791]
When I want to share a file or screenshot using FTP, I sometimes get this error:

System.Net.FtpClient.FtpCommandException: Could not create socket.
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadFile(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

After one or two retries it works fine.

**Comment by ElectronicWar** [comment]
This is a Windows system error. Sounds like a firewall or security software interfering with the FTP connection.

**Comment by pilovali** [comment]
Firewall disabled and no AV. It just fails once and when I retry it works.

**Comment by unixfox** [comment]
This error occur when the FTP server is inaccessible.

**Comment by Jaex** [comment]
I don't think this problem to do with ShareX.
