### ISSUE TITLE
OUT OF MEMORY EXCEPTION AFTER SCREENCAP!!! PLENTY OF MEMORY THO!!!!

### ISSUE THREAD

**Issue by asperkin** [ShareX/ShareX#794]
System.OutOfMemoryException: Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 8007000e Not enough storage is available to complete this operation. (Exception from HRESULT: 0x8007000E (E_OUTOFMEMORY)).
   at ShareX.HelpersLib.TaskbarManager.get_TaskbarList()
   at ShareX.HelpersLib.TaskbarManager.SetProgressState(IntPtr hwnd, TaskbarProgressBarStatus state)
   at ShareX.UploadTask.Prepare()
   at ShareX.UploadTask.Start()
   at ShareX.TaskManager.StartTasks()
   at ShareX.MainForm.AfterCapture(Image img, CaptureType captureType, TaskSettings taskSettings)
   at ShareX.MainForm.DoCaptureWork(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.MainForm.DoCapture(ScreenCaptureDelegate capture, CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.MainForm.CaptureRegion(CaptureType captureType, TaskSettings taskSettings, Boolean autoHideForm)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jaex** [comment]
Can you try running ShareX as admin.

**Comment by asperkin** [comment]
THAT WORKED!!! IT MUST BE RELATED TO THAT THEN! I AM THE ONLY USER AND AM ADMIN ON THIS COMP THO..

**Comment by Jaex** [comment]
Everybody using ShareX as non admin and still don't get this problem so something must be wrong in your computer not sure what but there is nothing I can fix about it. As a workaround you can disable its setting:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/dV9oUgYS3V.png)
