### ISSUE TITLE
Both color pickers are broken

### ISSUE THREAD

**Issue by Long-Horse** [ShareX/ShareX#825]
A window pops up and says this

`System.ArgumentOutOfRangeException: Parameter must be positive and < Width.
Parameter name: x
   at System.Drawing.Bitmap.GetPixel(Int32 x, Int32 y)
   at ShareX.ScreenCaptureLib.RectangleRegion.get_CurrentColor()
   at ShareX.TaskHelpers.SelectPointColor()
   at ShareX.ScreenColorPicker.btnPipette_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Jaex** [comment]
#788

**Comment by Long-Horse** [comment]
Um so how do I fix this? This error only happens on my first monitor and I am in v10.0

**Comment by Jaex** [comment]
Fixed version not released yet.

**Comment by Long-Horse** [comment]
Oh, I didn't catch that. I saw the commit and didn't realize you never pushed a new version. Any ETA?

**Comment by Jaex** [comment]
How am I supposed to have ETA.

**Comment by Long-Horse** [comment]
Well I don't know. The issue is fixed but not pushed out yet, correct? If not, then I'm not sure what that commit was in #788. Do you have any time you plan on pushing the update?

**Comment by Jaex** [comment]
I don't plan release dates.

**Comment by Long-Horse** [comment]
Oh so it's just when a bunch of bugs accumulate. Alright then, I'll just have to use the color picker on my other monitor for now. Thanks :)

**Comment by Jaex** [comment]
You could request me to compile release for you.

**Comment by Long-Horse** [comment]
Well, if you wouldn't mind, that'd be great!

**Comment by Jaex** [comment]
https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ShareX-10.1.0-setup.exe

**Comment by Long-Horse** [comment]
Thanks so much! Works great now
