### ISSUE TITLE
Screen Color Picker Returns #000000 or #FFFFFF or Error

### ISSUE THREAD

**Issue by Kyokou** [ShareX/ShareX#828]
Under the "Advanced" settings for "ScreenColorPIckerFormat" I have set it to $hex. The tool properly works when hovering over a color, trying to click to copy the value to the clip board returns #fff or #000 (I'm not sure what causes it to select one over the other).

When using the tool to copy values close to #FFFFFF (I only tested down to #FAFAFA) I get the following error:

```
System.ArgumentOutOfRangeException: Parameter must be positive and < Height.
Parameter name: y
   at System.Drawing.Bitmap.GetPixel(Int32 x, Int32 y)
   at ShareX.ScreenCaptureLib.RectangleRegion.get_CurrentColor()
   at ShareX.TaskHelpers.SelectPointColor()
   at ShareX.TaskHelpers.OpenScreenColorPicker(TaskSettings taskSettings)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

To clarify: This isn't an issue when using the "Color Picker" tool and then "Start Screen Color Picker". The above error only happens with the more recent "Screen Color Picker" tool.

**Comment by Jaex** [comment]
#825

**Comment by Kyokou** [comment]
10.1 fixed it! :) Thank you! (and shame on me for not thinking to check closed issues first)

Also absurdly fast response.....
