### ISSUE TITLE
Access denied when indexing folder

### ISSUE THREAD

**Issue by WebFreak001** [ShareX/ShareX#834]
Instead of throwing an exception and canceling the index folder task it would be useful to just have it marked red or something with a label "access denied"

```
System.UnauthorizedAccessException: Access to the path 'C:\inetpub\history' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.GetFolderInfo(String folderPath, Int32 level)
   at ShareX.IndexerLib.Indexer.Index(String folderPath)
   at ShareX.IndexerLib.IndexerHtml.Index(String folderPath)
   at ShareX.UploadManager.IndexFolder(String folderPath, TaskSettings taskSettings)
   at ShareX.UploadManager.IndexFolder(TaskSettings taskSettings)
   at ShareX.MainForm.tsmiIndexFolder_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Jaex** [comment]
I need to find path which I can reproduce this so I can test it.

**Comment by WebFreak001** [comment]
`C:\Windows\CSC` Or just generally index the Windows folder, there should be lots of files with no access
