### ISSUE TITLE
Not working on Windows 10.

### ISSUE THREAD

**Issue by Yandols** [ShareX/ShareX#837]
Hi, I have just upgraded to my pc to Windows 10 (Build 10240) and I noticed that ShareX apparently does not work for me anymore.

I got an error message while taking a screenshot, and the screenshot failed to save.
This is it's error message.
```
Could not create directory, check your path settings.

System.UnauthorizedAccessException: Access to the path 'C:\Users\User\Documents\ShareX\Screenshots\2015-08' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at ShareX.HelpersLib.Helpers.CreateDirectoryIfNotExist(String path, Boolean isFilePath)
```

And this is the error message I receive when exiting the application.
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\User\Documents\ShareX\Logs\ShareX-Log-2015-08.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   at ShareX.HelpersLib.Logger.SaveLog(String filepath)
   at ShareX.Program.Main(String[] args)
```

**Comment by Jaex** [comment]
ShareX works in Windows 10, we using W10 for long time. Your Windows not allows ShareX to access "C:\Users\User\Documents\ShareX\Screenshots\2015-08" this folder and therefore ShareX can't do anything about it. So it is about your Windows config and not bug in ShareX side.

**Comment by Jaex** [comment]
Check #884 for solution if you already not found it yourself.

**Comment by rliden** [comment]
> 
> 
> ShareX works in Windows 10, we using W10 for long time. Your Windows not allows ShareX to access "C:\Users\User\Documents\ShareX\Screenshots\2015-08" this folder and therefore ShareX can't do anything about it. So it is about your Windows config and not bug in ShareX side.

Right. It compiles and runs on your desktop so what's the problem? /smh

**Comment by triptych** [comment]
This helped me https://www.youtube.com/watch?v=i6yKG71YzwI
