### ISSUE TITLE
Color picker doesn't work with multiple monitors. 

### ISSUE THREAD

**Issue by dmxt** [ShareX/ShareX#838]
I have triple monitor setup. 

While using the color picker, the information output during the color picker is correct, but after clicking, it outputs incorrect color code, and I couldn't quite find a pattern for the incorrect color code. Most of time it spits out `#FFFFFF` however. This only works on left and middle (primary) monitor.

On right monitor, it spits out this error instead of color code, which you may find this useful:

```
System.ArgumentOutOfRangeException: Parameter must be positive and < Width.
Parameter name: x
   at System.Drawing.Bitmap.GetPixel(Int32 x, Int32 y)
   at ShareX.ScreenCaptureLib.RectangleRegion.get_CurrentColor()
   at ShareX.TaskHelpers.SelectPointColor()
   at ShareX.TaskHelpers.OpenScreenColorPicker(TaskSettings taskSettings)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I never had this problem with single monitor setup, so I feel it has something to do with multi-monitor setup.

**Comment by Jaex** [comment]
Hi, I already fixed this problem: #788, #825, #828
If you would like to test it I put download link for beta version in #ShareX IRC channel title.
