### ISSUE TITLE
Get Eror - Color Picker tool (dual monitor, Windows 10)

### ISSUE THREAD

**Issue by Inomoz** [ShareX/ShareX#841]
System.ArgumentOutOfRangeException: Parameter must be positive and < Width.
Parameter name: x
   at System.Drawing.Bitmap.GetPixel(Int32 x, Int32 y)
   at ShareX.ScreenCaptureLib.RectangleRegion.get_CurrentColor()
   at ShareX.TaskHelpers.SelectPointColor()
   at ShareX.TaskHelpers.OpenScreenColorPicker(TaskSettings taskSettings)
   at ShareX.MainForm.HandleHotkeys(HotkeySettings hotkeySetting)
   at ShareX.HotkeyManager.OnHotkeyTrigger(HotkeySettings hotkeySetting)
   at ShareX.HotkeyManager.hotkeyForm_HotkeyPress(UInt16 id, Keys key, Modifiers modifier)
   at ShareX.HotkeyForm.OnKeyPressed(UInt16 id, Keys key, Modifiers modifier)
   at ShareX.HotkeyForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Inomoz** [comment]
Tool* - Screen Color Picker

**Comment by Jaex** [comment]
#838, #788, #825, #828
