### ISSUE TITLE
Uploading from Clipboard System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by arleslie** [ShareX/ShareX#860]
When I select text (and copy it) and press Ctrl+Alt+6 (Upload From Clipboard) I received an IO exception.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Andrew Leslie\Documents\ShareX\Screenshots\2015-08\2015-08-03_13-18-34.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ShareX.UploadTask.DoTextJobs()
   at ShareX.UploadTask.DoThreadJob()
   at ShareX.UploadTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Jaex** [comment]
It is fixed #847
