### ISSUE TITLE
Imgur uploads instantly fail

### ISSUE THREAD

**Issue by RedReign** [ShareX/ShareX#866]
Whenever I take a screenshot of the current window, entire screen, or a cursor-specified area, I get this error:

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.RefreshAccessToken()
   at ShareX.UploadersLib.ImageUploaders.Imgur.CheckAuthorization()
   at ShareX.UploadersLib.ImageUploaders.Imgur.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadImage(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

I have no idea what's causing it, a few weeks ago imgur uploads were working fine.

**Comment by Jaex** [comment]
This happens when their website is down or in maintenance. And they sending not proper response to parse and can't show proper error therefore.

**Comment by SirWilli** [comment]
I get this errors too often. The main issue here is that it doesn't try to reupload it and if you don't save it locally too the screenshot is gone.
