### ISSUE TITLE
ShareX Errors every time it tries to start.

### ISSUE THREAD

**Issue by MichaelPriebe** [ShareX/ShareX#868]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at ShareX.TaskSettings..ctor()
   at ShareX.ApplicationConfig..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
   at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
   at ShareX.Program.LoadProgramSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)
```
Every time I try to start it, or every time it starts when windows starts.
The only way I can get it open is by re installing it, but it starts to error again after I restart my computer.

**Comment by plttn** [comment]
Also seeing this occur. Nothing in log file.

Win10x64

**Comment by plttn** [comment]
And reinstalling seems to have fixed it.

I'd suggest rebooting once after it breaks, reinstall then, and then reboot again, see if that works.

**Comment by Jaex** [comment]
This problem not to do with ShareX and according to users mainly happens because of corrupted file or .NET framework installation related issue. I'm not sure how when installing it can be corrupted too.
