### ISSUE TITLE
Could not load file or assembly 'MegaApiClient,

### ISSUE THREAD

**Issue by 5shekel** [ShareX/ShareX#879]
after update sharex didnt open, 
open manually and click 'destinations'.
![image](https://cloud.githubusercontent.com/assets/222526/9140781/375576ce-3d3c-11e5-899d-52ef22a0e5a0.png)
```
2015-08-07 19:36:46.667 - ShareX 10.1 started
2015-08-07 19:36:46.677 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-08-07 19:36:46.677 - Command line: "U:\foreverDesk\ShareX\ShareX.exe" -silent
2015-08-07 19:36:46.677 - Personal path: C:\Users\i7\Documents\ShareX
2015-08-07 19:36:46.679 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-08-07 19:36:46.692 - ApplicationConfig load started: C:\Users\i7\Documents\ShareX\ApplicationConfig.json
2015-08-07 19:36:47.978 - ApplicationConfig load finished: C:\Users\i7\Documents\ShareX\ApplicationConfig.json
2015-08-07 19:36:47.981 - UploadersConfig load started: C:\Users\i7\Documents\ShareX\UploadersConfig.json
2015-08-07 19:36:47.982 - MainForm init started
2015-08-07 19:36:48.093 - UploadersConfig load failed:
System.IO.FileLoadException: Could not load file or assembly 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at ShareX.HelpersLib.SettingsHelper.Load[T](Stream stream, SerializationType type)
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2015-08-07 19:36:48.093 - UploadersConfig load started: C:\Users\i7\Documents\ShareX\UploadersConfig.json.bak
2015-08-07 19:36:48.098 - UploadersConfig load failed:
System.IO.FileLoadException: Could not load file or assembly 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'MegaApiClient, Version=1.1.0.39, Culture=neutral, PublicKeyToken=0480d311efbeb4e2'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at ShareX.HelpersLib.SettingsHelper.Load[T](Stream stream, SerializationType type)
   at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)


```

**Comment by Jaex** [comment]
Did you tried reinstalling?

**Comment by 5shekel** [comment]
i didnt want to touch it, if you guys need something specific to know

**Comment by Jaex** [comment]
Reinstall it.

**Comment by 5shekel** [comment]
working after reinstall
