### ISSUE TITLE
the "Copy" file uploader is not working

### ISSUE THREAD

**Issue by EslaMx7** [ShareX/ShareX#880]
I checked the log and found : 
`2015-08-08 19:39:25.720 - CopyAuthOpen - Authorization URL is empty.`
this regarding the source code seems to be a problem with the application keys while getting the auth url from the service.

**Comment by Jaex** [comment]
I tried to authorize and upload both worked. So I'm unable to reproduce your problem.

**Comment by EslaMx7** [comment]
it worked for me on Windows 8.1 but on Windows 10 it takes no action when i click the authorize button even if run as admin.
any ideas where the problem might be ? or did you tested it on Windows 10 ?

**Comment by Jaex** [comment]
I tested on Windows 10.

**Comment by EslaMx7** [comment]
i checked the log again and found this : 
```
2015-08-09 09:18:47.415 - Exception:
System.TypeInitializationException: The type initializer for 'ShareX.UploadersLib.FileUploaders.Jira' threw an exception. ---> System.Security.Cryptography.CryptographicException: The specified network password is not correct.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at ShareX.UploadersLib.FileUploaders.Jira..cctor()
   --- End of inner exception stack trace ---
   at ShareX.UploadersLib.FileUploaders.Jira.get_PublicKey()
   at ShareX.UploadersLib.UploadersConfigForm.LoadSettings(UploadersConfig uploadersConfig)
2015-08-09 09:18:54.644 - CopyAuthOpen - Authorization URL is empty.
```

is this problem specific to me only ?

**Comment by Jaex** [comment]
Someone was reported it too and who implemented JIRA don't know why it happens.

**Comment by EslaMx7** [comment]
it works fine now.
