### ISSUE TITLE
ShareX won't start

### ISSUE THREAD

**Issue by ljllewellyn** [ShareX/ShareX#881]
Sorry if this isn't the right place to post, but the Report Bug button sent me here so I guess it is.

I'm getting the following error on startup (and any subsequent attempts to open ShareX):

    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly     'ShareX.ScreenCaptureLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
       at ShareX.TaskSettings..ctor()
       at ShareX.ApplicationConfig..ctor()
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
       at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance[T]()
       at ShareX.HelpersLib.SettingsHelper.Load[T](String path, SerializationType type, Boolean checkBackup)
       at ShareX.HelpersLib.SettingsBase`1.Load(String filePath)
       at ShareX.Program.LoadProgramSettings()
       at ShareX.Program.Run()
       at ShareX.Program.Main(String[] args)

I am running Windows 10 Pro 64-bit. I haven't tried reinstalling ShareX yet in case you wanted me to try a few things first to help debug the issue.

If you need any more system or configuration information then I'd be happy to post it here.

**Comment by Jaex** [comment]
#868

**Comment by Jaex** [comment]
I don't know how suddenly people keep getting corrupt installations.
