### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by RDF2050** [ShareX/ShareX#890]
Message:
The remote server returned an error: (503) Server Unavailable.

Response:
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
We don't have any servers so can't be to do with us.
