### ISSUE TITLE
Printscreen error 

### ISSUE THREAD

**Issue by loveandpower** [ShareX/ShareX#892]
Message:
The remote server returned an error: (405) Method Not Allowed.

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
Imgur API down.

**Comment by sebiqq** [comment]
Thanks.

**Comment by Jaex** [comment]
#891, #890, #749, #657, #533, #522, #426
