### ISSUE TITLE
Upload Error (Re-opening Issue #533)

### ISSUE THREAD

**Issue by Cyph3r** [ShareX/ShareX#895]
A continuation of unconfirmed closed case https://github.com/ShareX/ShareX/issues/533

Confirmed in Windows 10 with ShareX to imgur. Does not error on small images, but on larger ones, gives 405 error.

http://bit.ly/1IAkzsQ

Message:
The remote server returned an error: (405) Method Not Allowed.

Response:

405 Not Allowed

405 Not Allowed

nginx

StackTrace:
at System.Net.HttpWebRequest.GetResponse()
at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment]
#894, #893, #892, #891, #890
