### ISSUE TITLE
Upload from clipboard causes crash

### ISSUE THREAD

**Issue by athropods** [ShareX/ShareX#908]
Copying text to the clipboard and uploading will cause a crash. My settings were the same before the latest update and it worked fine then. First is the log from the error window, second is the output log. 

Here is the output from the error window 

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Angel's Tears\Documents\ShareX\Screenshots\2015-08\2015-08-14_22-00-01.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ShareX.UploadTask.DoTextJobs()
   at ShareX.UploadTask.DoThreadJob()
   at ShareX.UploadTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Here is the output log

2015-08-10 15:33:46.760 - ShareX 10.0 started
2015-08-10 15:33:46.765 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-08-10 15:33:46.765 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2015-08-10 15:33:46.765 - Personal path: C:\Users\Angel's Tears\Documents\ShareX
2015-08-10 15:33:46.765 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-08-10 15:33:46.768 - ApplicationConfig load started: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:33:47.255 - ApplicationConfig load finished: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:33:47.257 - MainForm init started
2015-08-10 15:33:47.258 - UploadersConfig load started: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:33:47.423 - UploadersConfig load finished: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:33:47.423 - HotkeysConfig load started: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:33:47.456 - HotkeysConfig load finished: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:33:47.556 - MainForm init finished
2015-08-10 15:33:47.602 - Startup time: 872 ms
2015-08-10 15:33:47.611 - Hotkey registered: Hotkey: Ctrl + Shift + 2, Description: Capture entire screen, Job: PrintScreen
2015-08-10 15:33:47.611 - Hotkey registered: Hotkey: Ctrl + Shift + 3, Description: Capture active window, Job: ActiveWindow
2015-08-10 15:33:47.611 - Hotkey registered: Hotkey: Ctrl + Shift + 4, Description: Capture rectangle region, Job: RectangleRegion
2015-08-10 15:33:47.611 - Hotkey registered: Hotkey: Ctrl + Shift + 5, Description: Screen recording, Job: ScreenRecorder
2015-08-10 15:33:47.611 - Hotkey registered: Hotkey: Ctrl + Shift + 6, Description: Text, Job: ClipboardUpload
2015-08-10 15:33:47.612 - HotkeyManager started
2015-08-10 15:33:47.613 - WatchFolderManager started
2015-08-10 15:34:05.994 - ApplicationConfig save started: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:06.165 - ApplicationConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:06.165 - UploadersConfig save started: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:06.242 - UploadersConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:06.242 - HotkeysConfig save started: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:06.314 - HotkeysConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:06.322 - ShareX closing
2015-08-10 15:34:10.014 - ShareX 10.1 started
2015-08-10 15:34:10.018 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-08-10 15:34:10.018 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2015-08-10 15:34:10.018 - Personal path: C:\Users\Angel's Tears\Documents\ShareX
2015-08-10 15:34:10.018 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-08-10 15:34:10.034 - ApplicationConfig load started: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:10.527 - ApplicationConfig load finished: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:10.529 - MainForm init started
2015-08-10 15:34:10.529 - UploadersConfig load started: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:10.704 - UploadersConfig load finished: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:10.704 - HotkeysConfig load started: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:10.738 - HotkeysConfig load finished: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:10.838 - MainForm init finished
2015-08-10 15:34:10.885 - Startup time: 894 ms
2015-08-10 15:34:10.894 - Hotkey registered: Hotkey: Ctrl + Shift + 2, Description: Capture entire screen, Job: PrintScreen
2015-08-10 15:34:10.894 - Hotkey registered: Hotkey: Ctrl + Shift + 3, Description: Capture active window, Job: ActiveWindow
2015-08-10 15:34:10.894 - Hotkey registered: Hotkey: Ctrl + Shift + 4, Description: Capture rectangle region, Job: RectangleRegion
2015-08-10 15:34:10.894 - Hotkey registered: Hotkey: Ctrl + Shift + 5, Description: Screen recording, Job: ScreenRecorder
2015-08-10 15:34:10.894 - Hotkey registered: Hotkey: Ctrl + Shift + 6, Description: Text, Job: ClipboardUpload
2015-08-10 15:34:10.895 - HotkeyManager started
2015-08-10 15:34:10.897 - WatchFolderManager started
2015-08-10 15:34:31.993 - ApplicationConfig save started: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:31.993 - HotkeysConfig save started: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:31.994 - UploadersConfig save started: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:32.117 - HotkeysConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:32.139 - UploadersConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:32.154 - ApplicationConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:33.465 - Hotkey unregistered: Hotkey: Ctrl + Shift + 2, Description: Capture entire screen, Job: PrintScreen
2015-08-10 15:34:33.465 - Hotkey unregistered: Hotkey: Ctrl + Shift + 3, Description: Capture active window, Job: ActiveWindow
2015-08-10 15:34:33.465 - Hotkey unregistered: Hotkey: Ctrl + Shift + 4, Description: Capture rectangle region, Job: RectangleRegion
2015-08-10 15:34:33.465 - Hotkey unregistered: Hotkey: Ctrl + Shift + 5, Description: Screen recording, Job: ScreenRecorder
2015-08-10 15:34:33.465 - Hotkey unregistered: Hotkey: Ctrl + Shift + 6, Description: Text, Job: ClipboardUpload
2015-08-10 15:34:33.483 - ApplicationConfig save started: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:33.588 - ApplicationConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\ApplicationConfig.json
2015-08-10 15:34:33.588 - UploadersConfig save started: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:33.662 - UploadersConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\UploadersConfig.json
2015-08-10 15:34:33.662 - HotkeysConfig save started: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:33.730 - HotkeysConfig save successful: C:\Users\Angel's Tears\Documents\ShareX\HotkeysConfig.json
2015-08-10 15:34:33.732 - ShareX closing

**Comment by Jaex** [comment]
#900, #847, #860, #870
