### ISSUE TITLE
Text upload can cause System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by uncajesse** [ShareX/ShareX#937]
To reproduce,

1. have this default setting
Task settings -> Advanced ->TestTaskSaveAsFile = True

2. use a sub-folder pattern
Application settings -> Paths

3. make sure the sub-folder that the text will be saved in does NOT exist yet

4. upload some text from a file or clipboard

5. (see below)

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[username]\Documents\ShareX\Screenshots\2015-08\2015-08-20_16-50-49.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ShareX.UploadTask.DoTextJobs()
   at ShareX.UploadTask.DoThreadJob()
   at ShareX.UploadTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Jaex** [comment]
#908, #900, #870, #860, #847

**Comment by uncajesse** [comment]
I should have searched closed issues for existing bug reports. Well it's the first bug I've run into after using this for sooo many years. Props for that Jaex. :)
