### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by Gensoo** [ShareX/ShareX#939]
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.ImageUploaders.Imgur.RefreshAccessToken()
   at ShareX.UploadersLib.ImageUploaders.Imgur.CheckAuthorization()
   at ShareX.UploadersLib.ImageUploaders.Imgur.Upload(Stream stream, String fileName)
   at ShareX.UploadTask.UploadImage(Stream stream, String fileName)
   at ShareX.UploadTask.DoUpload(Int32 retry)

**Comment by Jaex** [comment]
That means Imgur sent invalid response.
