### ISSUE TITLE
Unable to share text clipboard, exception triggered

### ISSUE THREAD

**Issue by archon810** [ShareX/ShareX#947]
Hi,

I'm getting an exception when trying to share the clipboard containing the contents of this gist: https://gist.github.com/archon810/8a31b798bbff430cdcab. When I press the key combo to upload it (which should post it to gist), I get the following, followed by a full ShareX (10.1) crash:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Archon810\Documents\ShareX\Screenshots\2015-08\2015-08-26_15-55-22.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ShareX.UploadTask.DoTextJobs()
   at ShareX.UploadTask.DoThreadJob()
   at ShareX.UploadTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Jaex** [comment]
#937, #908, #900, #870, #860, #847
