### ISSUE TITLE
Can't upload Clipboard Text selection to text uploader

### ISSUE THREAD

**Issue by Justin991q** [ShareX/ShareX#965]
Hello,

I tried to upload text from my clipboard to Github gist, but when I did that there pops up an error. I also tried to change the uploader to an other uploader. I have this issue for a hour now I don't have any troubles before. My friend have this problem aswell.

Error:
<pre>
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Justin\Pictures\Screens\2015-09\Pasted by Justin at 22;14;16 on 02-09-2015.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ShareX.UploadTask.DoTextJobs()
   at ShareX.UploadTask.DoThreadJob()
   at ShareX.UploadTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
</pre>

**Comment by Jaex** [comment]
It is fixed and will be released in 2 days.
