### ISSUE TITLE
Error screen recording (gif)

### ISSUE THREAD

**Issue by Samuell95** [ShareX/ShareX#982]
I try screen capture to gif but every time i get error.
Version of ShareX is: 10.2
```

************** Exception Text **************
System.InvalidOperationException: StandardIn has not been redirected.
   at System.Diagnostics.Process.get_StandardInput()
   at ShareX.HelpersLib.ExternalCLIManager.WriteInput(String input)
   at ShareX.ScreenRecordForm.StopRecording()
   at ShareX.ScreenRegionForm.OnStopRequested()
   at ShareX.ScreenRegionForm.btnStop_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ShareX
    Assembly Version: 10.2.0.0
    Win32 Version: 10.2.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ShareX.HelpersLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.HelpersLib.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ShareX.UploadersLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.UploadersLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Program%20Files/ShareX/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ShareX.ScreenCaptureLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.ScreenCaptureLib.DLL
----------------------------------------
ShareX.ImageEffectsLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.ImageEffectsLib.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
ShareX.IndexerLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.IndexerLib.DLL
----------------------------------------
ShareX.MediaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.MediaLib.DLL
----------------------------------------
ShareX.IRCLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ShareX/ShareX.IRCLib.DLL
----------------------------------------
MegaApiClient
    Assembly Version: 1.1.1.44
    Win32 Version: 1.1.1.44
    CodeBase: file:///C:/Program%20Files/ShareX/MegaApiClient.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Jaex** [comment]
I have no idea why you have this error because normally it is redirected.

**Comment by SharkWipf** [comment]
I'm having the same issue, both with gif and webm recording, I have some more details for you though.  
I'm running a dual 4K screen setup, if I try to record anywhere on my left screen or the first ~2/3rd of my right screen recording works fine.  
However, as soon as I try to record anywhere beyond ~2/3rd of my right screen, it'll do the countdown thingy and then it'll pop up an FFMpeg error:  
```
ffmpeg version N-74835-gbd6610c Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[gdigrab @ 0000000002f898a0] Capture area (2496,802),(2606,884) extends outside window area (-2560,0),(2560,1440)desktop: Input/output error
```
On clicking "Stop" or "Abort" it'll throw the same error dialog @Samuell95 has already mentioned.

**Comment by Jaex** [comment]
Then both of you have #923 this problem?

**Comment by SharkWipf** [comment]
Oh, seems like it. I did get that error before clicking the stop/abort button, it moves to the background while recording though. On pressing the stop/abort buttons it throws the other message then closes when you click close, so it might be that the others didn't see this message, but it was there.

**Comment by Jaex** [comment]
When I reproduce your error I don't get StandardIn error:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/09/TjmwqPi6bk.png)

**Comment by SharkWipf** [comment]
Ah huh, that's odd, not even when clicking stop? That's when it pops up for me.

**Comment by Jaex** [comment]
How you can stop something which is not started yet?

**Comment by SharkWipf** [comment]
Oh wait, I see. For me it doesn't show up until the countdown hits 0, after which it'll actually "pretend" to record. Do you maybe have the countdown disabled on your own setup?  
I'd record it for you but yeah...  
Anyway, I'll check the solution given in the other thread, I assume it'll work then. Thanks!

**Comment by Jaex** [comment]
Few days ago I made sure ui only show started and start timer when FFmpeg actually started recording that way when error happened my button still stayed Start instead of Stop so I couldn't even press Stop button when there is FFmpeg error window open.

**Comment by Samuell95** [comment]
I try it again an this console show up:
```
ffmpeg version N-68625-g1728659 Copyright (c) 2000-2014 the FFmpeg developers
  built on Dec 19 2014 22:13:35 with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 16.100 / 56. 16.100
  libavformat    56. 16.101 / 56. 16.101
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  4.100 /  5.  4.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[gdigrab @ 0000000004b0bd20] Capturing whole desktop as 506x490x32 at (597,334)
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1442080474.397557, bitrate: 39672 kb/s
    Stream #0:0: Video: bmp, bgra, 506x490, 39672 kb/s, 5 tbr, 1000k tbn, 5 tbc
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0000000004b2c500] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA4 LZCNT
[libx264 @ 0000000004b2c500] profile High 4:4:4 Predictive, level 2.2, 4:4:4 8-bit
[libx264 @ 0000000004b2c500] 264 - core 142 r2479 dd79a61 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=5 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'C:\Users\Samuel\Documents\ShareX\Screenshots\2015-09\2015-09-12_19-54-32.mp4':
  Metadata:
    encoder         : Lavf56.16.101
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 506x490, q=-1--1, 5 fps, 10240 tbn, 5 tbc
    Metadata:
      encoder         : Lavc56.16.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame=    3 fps=0.0 q=0.0 size=      96kB time=00:00:00.60 bitrate=1313.9kbits/s    
frame=    6 fps=6.0 q=0.0 size=      98kB time=00:00:01.20 bitrate= 666.7kbits/s    
frame=    8 fps=5.3 q=0.0 size=      99kB time=00:00:01.60 bitrate= 504.5kbits/s    
frame=    9 fps=5.7 q=0.0 Lsize=     100kB time=00:00:01.80 bitrate= 454.1kbits/s    
video:99kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.870810%
[libx264 @ 0000000004b2c500] frame I:1     Avg QP: 0.00  size: 96966
[libx264 @ 0000000004b2c500] frame P:8     Avg QP: 0.00  size:   474
[libx264 @ 0000000004b2c500] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0000000004b2c500] mb P  I16..4: 32.3%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip:67.7%
[libx264 @ 0000000004b2c500] coded y,u,v intra: 6.2% 5.9% 5.9% inter: 0.0% 0.0% 0.0%
[libx264 @ 0000000004b2c500] i16 v,h,dc,p: 87% 11%  2%  0%
[libx264 @ 0000000004b2c500] kb/s:447.80
ffmpeg version N-68625-g1728659 Copyright (c) 2000-2014 the FFmpeg developers
  built on Dec 19 2014 22:13:35 with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 16.100 / 56. 16.100
  libavformat    56. 16.101 / 56. 16.101
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  4.100 /  5.  4.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Samuel\Documents\ShareX\Screenshots\2015-09\2015-09-12_19-54-32.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.16.101
  Duration: 00:00:01.80, start: 0.000000, bitrate: 454 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 506x490, 450 kb/s, 5 fps, 5 tbr, 10240 tbn, 10 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[AVFilterGraph @ 0000000005055ec0] No such filter: 'palettegen'
Error opening filters!
```

**Comment by Jaex** [comment]
You need to upgrade your FFmpeg using download button again in FFmpeg window.

**Comment by Samuell95** [comment]
Where can find update button for FFmpeg?

**Comment by Jaex** [comment]
task settings, screen recorder, screen recording options, download

**Comment by Samuell95** [comment]
Thanks, its working ! :+1:
