### ISSUE TITLE
Error when opening destination settings

### ISSUE THREAD

**Issue by user6323** [ShareX/ShareX#985]
Hello. Recently i used version 9.10.1 .
I installed 10.2.0 and copy v9 config files over v10 config, and when i open the "Destination settings" window - i get error:

```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ListBox.set_SelectedIndex(Int32 value)
   at ShareX.UploadersLib.UploadersConfigForm.LoadSettings()
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

How to fix it?

**Comment by Jaex** [comment]
Check #974
