### ISSUE TITLE
ShareX - Error

### ISSUE THREAD

**Issue by Maggew** [ShareX/ShareX#994]
After I visit "Destination > Destination Settings this was the error I received. Maybe it has something to do with Imgur?

```
2015-09-15 10:31:34.421 - ShareX 10.1 started
2015-09-15 10:31:34.426 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-09-15 10:31:34.426 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2015-09-15 10:31:34.426 - Personal path: C:\Users\MAGGEW\Documents\ShareX
2015-09-15 10:31:34.427 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-09-15 10:31:34.430 - ApplicationConfig load started: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 10:31:34.430 - ApplicationConfig load started: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json.bak
2015-09-15 10:31:34.430 - ApplicationConfig not found. Loading new instance.
2015-09-15 10:31:34.673 - UploadersConfig load started: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 10:31:34.673 - UploadersConfig load started: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json.bak
2015-09-15 10:31:34.673 - UploadersConfig not found. Loading new instance.
2015-09-15 10:31:34.673 - MainForm init started
2015-09-15 10:31:34.688 - HotkeysConfig load started: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 10:31:34.688 - HotkeysConfig load started: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json.bak
2015-09-15 10:31:34.688 - HotkeysConfig not found. Loading new instance.
2015-09-15 10:31:35.136 - MainForm init finished
2015-09-15 10:31:35.204 - Startup time: 864 ms
2015-09-15 10:31:35.255 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2015-09-15 10:31:35.255 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2015-09-15 10:31:35.255 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2015-09-15 10:31:35.255 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2015-09-15 10:31:35.257 - HotkeyManager started
2015-09-15 10:31:35.260 - WatchFolderManager started
2015-09-15 10:31:43.099 - Hotkey unregistered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2015-09-15 10:31:43.099 - Hotkey unregistered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2015-09-15 10:31:43.099 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2015-09-15 10:31:43.099 - Hotkey unregistered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2015-09-15 10:31:43.125 - ApplicationConfig save started: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 10:31:43.406 - ApplicationConfig save successful: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 10:31:43.406 - UploadersConfig save started: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 10:31:43.540 - UploadersConfig save successful: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 10:31:43.540 - HotkeysConfig save started: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 10:31:43.628 - HotkeysConfig save successful: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 10:31:43.632 - ShareX closing
2015-09-15 18:00:20.484 - ShareX 10.2 started
2015-09-15 18:00:20.515 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-09-15 18:00:20.515 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2015-09-15 18:00:20.515 - Personal path: C:\Users\MAGGEW\Documents\ShareX
2015-09-15 18:00:20.515 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-09-15 18:00:20.515 - ApplicationConfig load started: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 18:00:22.337 - ApplicationConfig load finished: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 18:00:22.347 - MainForm init started
2015-09-15 18:00:22.347 - UploadersConfig load started: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 18:00:22.540 - UploadersConfig load finished: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 18:00:22.540 - HotkeysConfig load started: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 18:00:22.576 - HotkeysConfig load finished: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 18:00:22.959 - MainForm init finished
2015-09-15 18:00:23.039 - Startup time: 2716 ms
2015-09-15 18:00:23.039 - CommandLine: silent
2015-09-15 18:00:23.059 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2015-09-15 18:00:23.059 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2015-09-15 18:00:23.059 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2015-09-15 18:00:23.059 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2015-09-15 18:00:23.059 - HotkeyManager started
2015-09-15 18:00:23.069 - WatchFolderManager started
2015-09-15 18:00:23.099 - GitHub update check failed:
System.Net.WebException: The remote name could not be resolved: 'api.github.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()
2015-09-15 18:00:23.119 - XML update check failed:
System.Net.WebException: The remote name could not be resolved: 'getsharex.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at ShareX.HelpersLib.XMLUpdateChecker.CheckUpdate()
2015-09-15 20:00:23.328 - GitHub update check failed:
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()
2015-09-15 21:00:23.353 - GitHub update check failed:
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()
2015-09-15 22:00:23.357 - GitHub update check failed:
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()
2015-09-15 23:00:23.343 - GitHub update check failed:
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()
2015-09-15 23:26:24.379 - Hotkey unregistered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2015-09-15 23:26:24.380 - Hotkey unregistered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2015-09-15 23:26:24.380 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2015-09-15 23:26:24.380 - Hotkey unregistered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2015-09-15 23:26:24.408 - ApplicationConfig save started: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 23:26:24.643 - ApplicationConfig save successful: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 23:26:24.643 - UploadersConfig save started: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 23:26:24.720 - UploadersConfig save successful: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 23:26:24.720 - HotkeysConfig save started: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 23:26:24.824 - HotkeysConfig save successful: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 23:26:24.827 - ShareX closing
2015-09-15 23:38:01.665 - ShareX 10.2 started
2015-09-15 23:38:01.685 - Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-09-15 23:38:01.685 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2015-09-15 23:38:01.685 - Personal path: C:\Users\MAGGEW\Documents\ShareX
2015-09-15 23:38:01.685 - Git: https://github.com/ShareX/ShareX/tree/ffb8d351394653e32418ed7e5555982158ee0426
2015-09-15 23:38:01.695 - ApplicationConfig load started: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 23:38:02.997 - ApplicationConfig load finished: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-15 23:38:02.997 - MainForm init started
2015-09-15 23:38:02.997 - UploadersConfig load started: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 23:38:03.199 - UploadersConfig load finished: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-15 23:38:03.200 - HotkeysConfig load started: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 23:38:03.240 - HotkeysConfig load finished: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-15 23:38:03.756 - MainForm init finished
2015-09-15 23:38:03.839 - Startup time: 2273 ms
2015-09-15 23:38:03.840 - CommandLine: silent
2015-09-15 23:38:03.864 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2015-09-15 23:38:03.864 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2015-09-15 23:38:03.864 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2015-09-15 23:38:03.864 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2015-09-15 23:38:03.864 - HotkeyManager started
2015-09-15 23:38:03.864 - WatchFolderManager started
2015-09-15 23:38:03.924 - GitHub update check failed:
System.Net.WebException: The remote name could not be resolved: 'api.github.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ShareX.HelpersLib.GitHubUpdateChecker.GetReleases()
   at ShareX.HelpersLib.GitHubUpdateChecker.CheckUpdate()
2015-09-15 23:38:03.944 - XML update check failed:
System.Net.WebException: The remote name could not be resolved: 'getsharex.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at ShareX.HelpersLib.XMLUpdateChecker.CheckUpdate()
2015-09-16 00:27:47.026 - Hotkey unregistered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
2015-09-16 00:27:47.026 - Hotkey unregistered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2015-09-16 00:27:47.026 - Hotkey unregistered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2015-09-16 00:27:47.026 - Hotkey unregistered: Hotkey: Shift + Print Screen, Description: Screen recording, Job: ScreenRecorder
2015-09-16 00:27:47.057 - ApplicationConfig save started: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-16 00:27:47.311 - ApplicationConfig save successful: C:\Users\MAGGEW\Documents\ShareX\ApplicationConfig.json
2015-09-16 00:27:47.311 - UploadersConfig save started: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-16 00:27:47.407 - UploadersConfig save successful: C:\Users\MAGGEW\Documents\ShareX\UploadersConfig.json
2015-09-16 00:27:47.407 - HotkeysConfig save started: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-16 00:27:47.524 - HotkeysConfig save successful: C:\Users\MAGGEW\Documents\ShareX\HotkeysConfig.json
2015-09-16 00:27:47.529 - ShareX closing
```
![2015-09-17_01-47-34](https://cloud.githubusercontent.com/assets/1291364/9925988/418cff00-5cdf-11e5-83bf-816f8a4cff23.png)

**Comment by Jaex** [comment]
#974
